opfab/operatorfabric-core

- src/docs/asciidoc/reference_doc/users_management.adoc
Nothing in release notes as it is just for documentation.
> Add documentation for activity area feature (#2968)

- src/test/cypress/cypress/integration/ExternalDevicesConfiguration.spec.js
- ui/main/src/app/modules/externaldevicesconfiguration/editModal/externaldevicesconfiguration-modal.component.html
- ui/main/src/app/modules/externaldevicesconfiguration/editModal/externaldevicesconfiguration-modal.component.ts
-  Text : #3256 : Replace single filter with new multiselect component in external devices configuration screen
> Replace single filter with new multiselect component in external devices configuration screen (#3256)

- config/dev/nginx.conf.template
- config/docker/nginx.conf
Add millis in time
Add request time processing
Remove referrer
Task :  #3288 Change nginx log format
> Format nginx logs

- src/test/cypress/cypress/integration/1-RealTimeUsers.spec.js
- src/test/cypress/cypress/integration/Acknowledgment.spec.js
- src/test/cypress/cypress/integration/ActivityArea.spec.js
- src/test/cypress/cypress/integration/EntityAcknowledgment.spec.js
- src/test/cypress/cypress/integration/ResponseCard.spec.js
- src/test/cypress/cypress/integration/SessionEnded.spec.js
- src/test/cypress/cypress/integration/SoundNotification.spec.js
- src/test/cypress/cypress/integration/UserCard.spec.js
- src/test/cypress/cypress/support/commands.js
- ui/main/src/app/modules/usercard/usercard.component.html
- ui/main/src/app/modules/usercard/usercard.component.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
-  Text : #3183 :  Add an error message when a user without entity tries to send a card
> Add an error message when a user without entity tries to send a card (#3183)

- src/test/cypress/cypress/integration/Admin.spec.js
- ui/main/src/app/modules/admin/components/editmodal/groups/edit-group-modal.component.html
- ui/main/src/app/modules/admin/components/editmodal/groups/edit-group-modal.component.ts
-  Text : #3262 : Replace single filter with new multiselect component in group administration
> Replace single filter with new multiselect component in group administration (#3262)

- src/test/cypress/cypress/integration/1-RealTimeUsers.spec.js
- ui/main/src/app/modules/realtimeusers/realtimeusers.component.html
- ui/main/src/app/modules/realtimeusers/realtimeusers.component.scss
- ui/main/src/app/modules/realtimeusers/realtimeusers.component.ts
- ui/main/src/app/modules/realtimeusers/realtimeusers.module.ts
Fix #3221
-  Text : #3221 : Display all connected users per group on realtime users dashboard
> Display all connected users per group on realtime users dashboard (#3221)

- ui/main/src/app/modules/share/archives-logging-filters/archives-logging-filters.component.html
- ui/main/src/app/modules/share/archives-logging-filters/archives-logging-filters.component.scss
- ui/main/src/scss/styles.scss
> Archives/logging : adjustment for search button with admin mode

- ui/main/src/app/modules/usercard/usercard.component.ts
> Remove test code

- src/test/cypress/cypress/integration/UserCard.spec.js
> Avoid falky usercard test with childcard

- src/docs/asciidoc/reference_doc/template_description.adoc
- src/test/cypress/cypress/integration/BusinessMenu.spec.js
- src/test/cypress/cypress/integration/Calendar.spec.js
- src/test/cypress/cypress/integration/CardDetail.spec.js
- src/test/cypress/cypress/integration/Timeline.spec.js
- src/test/cypress/cypress/integration/UserCard.spec.js
- src/test/resources/bundles/cypress/template/kitchenSink.handlebars
- ui/main/src/app/modules/cards/cards.module.ts
- ui/main/src/app/modules/cards/components/detail/detail.component.html
- ui/main/src/app/modules/cards/components/detail/detail.component.ts
- ui/main/src/app/modules/share/spinner/spinner.component.scss
- ui/main/src/assets/js/templateGateway.js
-  Text : #3190 : Add the possibility to display a spinner in the card template
> Add the possibility to display a spinner in the card template (#3190)

- ui/main/src/app/modules/externaldevicesconfiguration/editModal/externaldevicesconfiguration-modal.component.html
- ui/main/src/app/modules/externaldevicesconfiguration/externaldevicesconfiguration.module.ts
Fix #3296
-  Text : #3296: Add new spinner in external device configuration
> Add new spinner in external device configuration (#3296)

- ui/main/src/app/modules/feedconfiguration/feedconfiguration.component.ts
Fix #3246 
-  Text : #3246 : Feed notification configuration : display problem if the user has no right for a process group
> Feed notification configuration : display problem if the user has no right for a process group (#3246)

- src/test/cypress/cypress/integration/ResponseCard.spec.js
- ui/main/src/app/modules/cards/cards.module.ts
- ui/main/src/app/modules/cards/components/detail/detail.component.html
- ui/main/src/app/modules/cards/components/detail/detail.component.ts
-  Text : #3260 : Replace single filter with new multiselect component in entity choice for response in detail card
> Replace single filter with new multiselect component in entity choice for response in detail card (#3260)

- config/dev/docker-compose.yml
- config/dev/nginx.conf.template
- config/docker/docker-compose.yml
- config/docker/nginx-cors-permissive.conf
- config/docker/nginx.conf
- config/docker/ui-config/ui-menu.json
- src/test/cypress/cypress/integration/BusinessMenu.spec.js
- src/test/cypress/cypress/integration/ExternalApp.spec.js
- src/test/externalWebAppExample/index.html
Fix  #3253
-  Text :  #3253 : Add an example for external web application for testing
> Add an example for external web application for testing (#3253)

- src/test/cypress/cypress/integration/CardDetail.spec.js
- ui/main/src/app/modules/cards/components/card-details/card-details.component.html
-  Text : #3295 : Add new spinner in card detail
> Add new spinner in card detail (#3295)

- src/test/cypress/cypress/integration/CardDetail.spec.js
- ui/main/src/app/modules/share/card-detail/card-detail.component.html
- ui/main/src/app/modules/share/card-detail/card-detail.component.ts
- ui/main/src/assets/js/templateGateway.js
-  Text : #3307 : Add the possibility to display a spinner in the archived cards
> Add the possibility to display a spinner in the archived cards (#3307)

- ui/main/src/app/modules/logging/logging.component.html
Fix #3297
-  Text : #3297 : Add new spinner for export in progress in logging component
> Add new spinner for export in progress in logging component (#3297)

- src/test/cypress/cypress/integration/Translation.spec.js
- ui/main/src/app/modules/settings/components/settings/list-setting/list-setting.component.html
- ui/main/src/app/modules/settings/components/settings/list-setting/list-setting.component.ts
- ui/main/src/app/modules/settings/settings.module.ts
In feature : #3255 Replace single filter with new multiselect component in settings
> Replace single filter with new multiselect component in settings (#3255)

- ui/main/src/app/modules/calendar/calendar.component.ts
- #3332 Bug in calendar when no daysOfWeek in recurrence
> Solve bug in calendar when no daysOfWeek in recurrence (#3332)

- src/test/cypress/cypress/integration/Translation.spec.js
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
> Add a point in our texts if it is a sentence (#3175)

- ui/main/src/app/modules/archives/archives.component.ts
- In release note : nothing to add
> Fix date in archive card footer (#3354)

- ui/main/src/app/modules/usercard/selectStateForm/usercard-select-state-form.component.ts
Nothing in release note as bugs were not present on previous release
> Correct bugs #3377 #3376

- src/test/cypress/cypress/integration/Archives.spec.js
- ui/main/src/app/modules/cards/cards.module.ts
- ui/main/src/app/modules/cards/components/detail/detail.component.html
- ui/main/src/app/modules/cards/components/detail/detail.component.scss
- ui/main/src/app/modules/cards/components/detail/detail.component.ts
- ui/main/src/app/modules/share/card-detail/card-detail.component.html
- ui/main/src/app/modules/share/card-detail/card-detail.component.ts
- ui/main/src/app/modules/share/card-detail/card-detail.module.ts
- ui/main/src/app/modules/share/template-rendering/template-rendering.component.html
- ui/main/src/app/modules/share/template-rendering/template-rendering.component.scss
- ui/main/src/app/modules/share/template-rendering/template-rendering.component.ts
- ui/main/src/app/modules/share/template-rendering/template-rendering.module.ts
- ui/main/src/app/modules/usercard/usercard.component.html
> Refacto : Externalize template rendering in a share component

- ui/main/src/app/modules/share/light-card/light-card.component.scss
-  Text : #3370 : Feed light card : words are cut in summary text
> Feed light card : words are cut in summary text (#3370)

- src/test/cypress/cypress/integration/CardDetail.spec.js
Fix #3359 
-  Text : #3359 : Add a cypress test for card detail footer
> Add a cypress test for card detail footer (#3359)

- ui/main/src/app/modules/admin/components/editmodal/groups/edit-group-modal.component.html
-  Text : #3355 : Group administration : bad display of TYPE single-select
> Group administration : bad display of TYPE single-select (#3355)

- ui/main/src/app/modules/share/archives-logging-filters/archives-logging-filters.component.html
-  Text : #3361 : Admin checkbox : mouseover text overflows the screen
> Admin checkbox : mouseover text overflows the screen (#3361)

- src/test/cypress/cypress/integration/Translation.spec.js
- ui/main/src/app/modules/feed/components/card-list/filters/feed-filter/feed-filter.component.html
- ui/main/src/scss/styles.scss
-  Text : #3172 : Checkboxes can be checked even outside the text
> Checkboxes can be checked even outside the text (#3172)

- build.gradle
- services/external-devices/build.gradle
- services/external-devices/src/main/java/org/opfab/externaldevices/controllers/ConfigurationsController.java
- services/external-devices/src/main/java/org/opfab/externaldevices/services/ConfigService.java
- services/external-devices/src/test/java/org/opfab/externaldevices/application/UnitTestApplication.java
- services/external-devices/src/test/java/org/opfab/externaldevices/services/ConfigServiceShould.java
- src/test/api/karate/externaldevices/deleteUserConfig.feature
- tools/spring/spring-oauth2-utilities/build.gradle
- tools/spring/spring-oauth2-utilities/src/main/java/org/opfab/springtools/configuration/oauth/FeignConfiguration.java
- tools/spring/spring-oauth2-utilities/src/main/java/org/opfab/springtools/configuration/oauth/UserServiceProxy.java
Fix #3306
-  In chapter :  Bug
-  Text : #3306 : Remove settings value playSoundOnExternalDevice when removing user link to external device
> Remove settings value playSoundOnExternalDevice when removing user link to external device (#3306)

- ui/main/src/app/modules/feed/components/card-list/filters/feed-filter/feed-filter.component.html
-  Text : #3368 : Feed : "Reset all filters" link is clickable on more than just the text
> Feed : "Reset all filters" link is clickable on more than just the text (#3368)

- ui/main/src/app/modules/usercard/usercard.component.html
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/nl.json
-  Text : #3350 : Spinner too small when we send a usercard
> Spinner too small when we send a usercard (#3350)

- ui/main/src/app/modules/share/multi-select/multi-select.component.ts
- ui/main/src/app/modules/usercard/selectStateForm/usercard-select-state-form.component.ts
> Improve multiselect component

- config/docker/ui-config/web-ui.json
- src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc
- src/docs/asciidoc/resources/migration_guide_to_3.10.adoc
- ui/main/src/app/modules/about/about.component.ts
Fix #3327
-  Text : #3327 : Move the about configuration away form settings in web-ui.json
> Move the about configuration away from settings in web-ui.json (#3327)

- src/test/cypress/cypress/integration/SoundNotification.spec.js
- ui/main/src/app/modules/core/application-loading/sound-activation/sound-activation.component.ts
- ui/main/src/app/services/sound-notification.service.ts
-  Text : #3422 Not using default sound settings defined in web-ui.json when user has no settings
> Solve bug: Not using default sound settings defined in web-ui.json when user has no settings (#3422)

- src/test/cypress/cypress/integration/UserCard.spec.js
- src/test/cypress/cypress/support/commands.js
- src/test/cypress/cypress/support/userCardCommands.js
Fix #3381 
-  Text : #3381 : Add cypress test for userCard service select
> Add cypress test for userCard service select (#3381)

- src/test/cypress/cypress/integration/Acknowledgment.spec.js
- ui/main/src/app/modules/cards/components/detail/detail.component.html
- ui/main/src/app/modules/cards/components/detail/detail.component.ts
- ui/main/src/app/modules/share/spinner/spinner.component.html
- ui/main/src/app/modules/share/spinner/spinner.component.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
-  Text : #3351 : Add spinner when click on "acknowledge and close"
> Add spinner when click on "acknowledge and close" (#3351)

- src/test/cypress/cypress/integration/UserCard.spec.js
- ui/main/src/app/modules/cards/components/detail/detail.component.html
- ui/main/src/app/modules/cards/components/detail/detail.component.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
-  Text : #3349 : Add a spinner when delete a card if slow network
> Add a spinner when delete a card if slow network (#3349)

- ui/main/src/app/modules/cards/components/detail/detail.component.html
-  Text : #3374 : Bad display of "Response closed" dutch version
> Bad display of "Response closed" dutch version (#3374)

- ui/main/src/app/modules/navbar/navbar.component.html
- ui/main/src/app/modules/navbar/navbar.component.ts
- ui/main/src/app/modules/navbar/navbar.module.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
-  In chapter : Features 
-  Text : #3347 : Add a spinner when logout is slow
> Add a spinner when logout is slow (#3347)

- services/businessconfig/src/main/java/org/opfab/businessconfig/controllers/BusinessconfigController.java
- services/businessconfig/src/test/java/org/opfab/businessconfig/controllers/BusinessconfigControllerForMonitoringShould.java
- services/businessconfig/src/test/java/org/opfab/businessconfig/controllers/BusinessconfigControllerWithWrongConfigurationShould.java
- services/businessconfig/src/test/java/org/opfab/businessconfig/services/ProcessesServiceShould.java
- services/cards-publication/src/test/java/org/opfab/cards/publication/controllers/CardControllerProcessAcknowledgementShould.java
- services/cards-publication/src/test/java/org/opfab/cards/publication/controllers/CardControllerProcessUserReadShould.java
- services/cards-publication/src/test/java/org/opfab/cards/publication/controllers/CardControllerShould.java
- services/cards-publication/src/test/java/org/opfab/cards/publication/controllers/CardControllerUserCardShould.java
- services/users/src/main/java/org/opfab/users/controllers/UsersController.java
- tools/generic/utilities/src/test/java/org/opfab/utilities/PathUtilsShould.java
- tools/spring/spring-test-utilities/src/main/java/org/opfab/springtools/configuration/test/WithMockOpFabUserSecurityContextFactory.java
> Cleaning useless 'Throws Exception'

- config/docker/ui-config/web-ui.json
- src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc
- src/docs/asciidoc/resources/migration_guide_to_3.10.adoc
- ui/main/src/app/modules/settings/components/settings/settings.component.html
- ui/main/src/app/modules/settings/components/settings/settings.component.ts
-  Text : #3328 : Settings screen configuration : move "settings.infos.hide" section to ''settingsScreen.hiddenSettings"
> Settings screen configuration : move "settings.infos.hide" section to ''settingsScreen.hiddenSettings" (#3328)

- services/cards-publication/src/test/java/org/opfab/cards/publication/services/CardPermissionControlServiceShould.java
- services/cards-publication/src/test/java/org/opfab/cards/publication/services/CardProcessServiceShould.java
> Cards-pub : Move java tests on cardPermissionControlService in a separate file

- ui/main/src/app/modules/core/application-loading/application-loading.component.html
- ui/main/src/app/modules/core/application-loading/application-loading.component.scss
- ui/main/src/app/modules/core/application-loading/application-loading.component.ts
Fix #3362 
-  Text :  #3362 : Spinner for loading opfab : use shared spinner component
> Use shared spinner component when loading opfab

- ui/main/src/app/modules/admin/components/editmodal/entities/edit-entity-modal.component.ts
- ui/main/src/app/modules/admin/components/editmodal/groups/edit-group-modal.component.ts
- ui/main/src/app/modules/admin/components/editmodal/perimeters/edit-perimeter-modal.component.ts
-  Text : #3466 : Group/entity/perimeter creation : some special characters in id field are not forbidden
> Group/entity/perimeter creation : some special characters in id field are not forbidden (#3466)

- src/test/cypress/cypress/integration/Monitoring.spec.js
- ui/main/src/scss/styles.scss
Nothing to add in the release note
> Enable sort by severity in the monitoring screen (#3444)

- ui/main/src/app/services/authentication/authentication.service.ts
Fix #3353 
-  Text : #3353 : Logout with slow network show "session expired" popup
> Logout with slow network show "session expired" popup (#3353)

- services/businessconfig/src/main/java/org/opfab/businessconfig/controllers/CustomExceptionHandler.java
- services/businessconfig/src/test/java/org/opfab/businessconfig/controllers/CustomExceptionHandlerShould.java
- services/external-devices/src/main/java/org/opfab/externaldevices/controllers/CustomExceptionHandler.java
- services/users/src/main/java/org/opfab/users/controllers/CustomExceptionHandler.java
- tools/spring/spring-utilities/src/main/java/org/opfab/springtools/OpfabCustomExceptionHandler.java
- tools/spring/spring-utilities/src/test/java/org/opfab/springtools/OpfabCustomExceptionHandlerShould.java
> Refactoring CustomExceptionHandler classes (#1938)

- src/docs/asciidoc/reference_doc/template_description.adoc
- src/test/externalWebAppExample/index.html
- ui/main/src/scss/styles.scss
- ui/main/src/shared/css/opfab-application.css
Fix #3405 
-  Text : #3405 : Add opfab button in shared css
> Add opfab button in shared css (#3405)

- src/docs/asciidoc/reference_doc/user_cards.adoc
- src/test/cypress/cypress/integration/UserCard.spec.js
- src/test/resources/bundles/conferenceAndITIncidentExample/template/usercard_conference.handlebars
- ui/main/src/app/modules/usercard/usercard.component.ts
Fix #3408 
-  Text : #3408 : User cards: Permit to add a list of recipients via the template & user choice
> User cards: Permit to add a list of recipients via the template & user choice (#3408)

- src/tooling/migration-opfab3/migration-opfab3.js
-  Text : #3471 : Migration script to opfab 3 : special characters not well translated
> Migration script to opfab 3 : special characters not well translated (#3471)

- ui/main/src/app/modules/activityarea/activityarea.component.ts
- ui/main/src/app/modules/admin/components/editmodal/entities/edit-entity-modal.component.ts
- ui/main/src/app/modules/admin/components/editmodal/groups/edit-group-modal.component.ts
- ui/main/src/app/modules/admin/components/editmodal/perimeters/edit-perimeter-modal.component.ts
- ui/main/src/app/modules/admin/components/editmodal/users/edit-user-modal.component.ts
- ui/main/src/app/modules/archives/archives.component.ts
- ui/main/src/app/modules/cards/components/detail/detail.component.ts
- ui/main/src/app/modules/core/application-loading/login/login.component.ts
- ui/main/src/app/modules/externaldevicesconfiguration/editModal/externaldevicesconfiguration-modal.component.ts
- ui/main/src/app/modules/feed/components/card-list/filters/feed-filter/feed-filter.component.ts
- ui/main/src/app/modules/feed/components/card-list/filters/feed-sort/feed-sort.component.ts
- ui/main/src/app/modules/feedconfiguration/feedconfiguration.component.ts
- ui/main/src/app/modules/logging/logging.component.ts
- ui/main/src/app/modules/monitoring/components/monitoring-filters/monitoring-filters.component.ts
- ui/main/src/app/modules/realtimeusers/realtimeusers.component.ts
- ui/main/src/app/modules/settings/components/settings/checkbox-setting/checkbox-setting.component.ts
- ui/main/src/app/modules/settings/components/settings/list-setting/list-setting.component.ts
- ui/main/src/app/modules/settings/components/settings/multi-settings/multi-settings.component.ts
- ui/main/src/app/modules/settings/components/settings/text-setting/text-setting.component.ts
- ui/main/src/app/modules/share/archives-logging-filters/archives-logging-filters.component.ts
- ui/main/src/app/modules/share/datetime-filter/datetime-filter.component.ts
- ui/main/src/app/modules/usercard/datesForm/usercard-dates-form.component.ts
- ui/main/src/app/modules/usercard/recipientForm/usercard-recipients-form.component.ts
- ui/main/src/app/modules/usercard/selectCardEmitterForm/usercard-select-card-emitter-form.component.ts
- ui/main/src/app/modules/usercard/selectStateForm/usercard-select-state-form.component.ts
- ui/main/src/app/modules/usercard/usercard.component.ts
- ui/main/src/app/services/user.service.ts
> Angular 14 : UntypedFormControl to strictly typed forms

- src/test/cypress/cypress/integration/UserCard.spec.js
- src/test/resources/bundles/conferenceAndITIncidentExample/template/conference.handlebars
- src/test/resources/bundles/conferenceAndITIncidentExample/template/usercard_conference.handlebars
-  Text : #3363 Add control in the conference user card creation/edition
> Add control in the conference user card creation/edition (#3363)

- src/test/cypress/cypress/integration/LoginPage.spec.js
- src/test/cypress/package-lock.json
- ui/main/src/app/modules/core/application-loading/application-loading.component.ts
- ui/main/src/app/services/i18n.service.ts
> Correct bug : Application does not take into account default locale config

- config/docker/ui-config/web-ui.json
- src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc
- ui/main/src/app/modules/feed/components/map/map.component.ts
- ui/main/src/app/modules/share/light-card/light-card.component.html
- ui/main/src/app/modules/share/light-card/light-card.component.ts
- ui/main/src/app/services/map.service.ts
- Added documentation about new config option "zoomToLocation"
- when hovering over a card with geo-info the map highlights the location
-  added a crosshair on the card list for cards that have geo information
-  clicking on the crosshair zooms (configurable using `feed.geomap.zoomToLocation`) to the location
> Added hover and zoom-to-card on the geomap function (#3452)

- ui/main/src/app/modules/feed/components/time-line/custom-timeline-chart/custom-timeline-chart.component.spec.ts
- ui/main/src/app/services/lightcards/filter.service.spec.ts
- ui/main/src/app/services/lightcards/filter.service.ts
- ui/main/src/app/services/lightcards/lightcards-feed-filter.service.ts
- ui/main/src/app/services/logs/remote-logger.service.ts
- ui/main/src/app/services/settings.service.ts
- ui/main/src/app/services/sound-notification.service.ts
> Add remote logs for debugging purpose (#3486)

- services/users/src/main/java/org/opfab/users/controllers/GroupsController.java
- services/users/src/main/java/org/opfab/users/controllers/UsersController.java
- services/users/src/test/java/org/opfab/users/controllers/UsersControllerShould.java
- src/test/api/karate/users/createUsers.feature
- src/test/api/karate/users/groups/deleteGroup.feature
- src/test/api/karate/users/groups/deleteUserFromGroup.feature
- ui/main/src/app/modules/admin/components/editmodal/users/edit-user-modal.component.ts
Fix #1328
Replace  PR #3478
-  Text : #1328 : Prevent the suppression of the administration group for the admin user
> Make sure the admin user is always in the ADMIN group (#1328)

- ui/main/src/app/modules/feed/components/pinned-cards/pinned-cards.component.html
Fix #3488
-  Text : #3488 : Fix pinned cards display for long titles
> Fix pinned cards display for long titles (#3488)

- ui/main/src/app/modules/share/light-card/light-card.component.html
> Reduce space between response and ack icons in feed (#3487)

- services/cards-consultation/src/main/java/org/opfab/cards/consultation/services/CardSubscriptionService.java
- services/users/src/main/java/org/opfab/users/controllers/EntitiesController.java
- services/users/src/main/java/org/opfab/users/controllers/GroupsController.java
- services/users/src/main/java/org/opfab/users/services/UserService.java
- services/users/src/main/java/org/opfab/users/services/UserServiceImp.java
- services/users/src/test/java/org/opfab/users/application/configuration/SpringRabbitMqConfiguration.java
- src/test/cypress/cypress/integration/1-RealTimeUsers.spec.js
- ui/main/src/app/modules/activityarea/activityarea.component.ts
- ui/main/src/app/modules/navbar/info/info.component.ts
- ui/main/src/app/store/actions/user.actions.ts
- ui/main/src/app/store/effects/user.effects.ts
Fix #3176 
-  Text : #3176 : Updates for users/entities/groups should be sent to components that need it
> Updates for users/entities/groups should be sent to components that need it (#3176)

- src/test/cypress/cypress/support/commands.js
> Test adaptation to avoid falky cypress test

- services/external-devices/src/main/java/org/opfab/externaldevices/controllers/ConfigurationsController.java
- services/external-devices/src/main/java/org/opfab/externaldevices/controllers/DevicesController.java
- services/external-devices/src/main/java/org/opfab/externaldevices/controllers/NotificationsController.java
- services/external-devices/src/main/java/org/opfab/externaldevices/drivers/ExternalDeviceException.java
- services/external-devices/src/main/java/org/opfab/externaldevices/services/ConfigService.java
- services/external-devices/src/main/java/org/opfab/externaldevices/services/DevicesService.java
- services/external-devices/src/test/java/org/opfab/externaldevices/services/DevicesServiceShould.java
- src/docs/asciidoc/reference_doc/external_devices_service.adoc
- src/test/resources/external-devices/connectDevice..sh
- src/test/resources/external-devices/createDevice.sh
- src/test/resources/external-devices/deleteDevice.sh
- src/test/resources/external-devices/disconnectDevice.sh
- src/test/resources/external-devices/testDevice.json
-  Text : Regularly try to reconnect disconnected external devices (#3299)
> Regularly try to reconnect disconnected devices (#3299)

- CICD/github/install.sh
> Set timezone to paris for CICD

- src/test/cypress/cypress/support/commands.js
> Adjust login test code to avoid falky cypress tests

- src/test/cypress/cypress/integration/EntityAcknowledgment.spec.js
- src/test/resources/bundles/cypress/template/kitchenSink.handlebars
> Avoid falky test in entityAcknowlegment cypress test

- src/test/cypress/cypress/integration/ActivityArea.spec.js
- src/test/cypress/cypress/integration/LoginPage.spec.js
> Adjust cypress tests when login to avoid falky test

- src/docs/asciidoc/reference_doc/users_management.adoc
> Add documentation for realtime groups and activity area screen (#3491)

- ui/main/src/app/modules/activityarea/activityarea.component.ts
- ui/main/src/app/modules/realtimeusers/realtimeusers.component.ts
-  Text : #3512 : Realtime screen bug when a connected user has no entity
> Realtime screen bug when a connected user has no entity (#3512)

- src/test/cypress/cypress/integration/SessionEnded.spec.js
- src/test/cypress/cypress/integration/SoundNotification.spec.js
- src/test/cypress/cypress/support/commands.js
- src/test/cypress/cypress/support/feedCommands.js
- src/test/cypress/cypress/support/opfabGeneralCommands.js
- src/test/cypress/cypress/support/settingsCommands.js
- src/test/cypress/cypress/support/soundCommands.js
> Avoid falky cypress tests on sound + refacto

- src/test/cypress/cypress/support/commands.js
> Improve activity area test commands to avoid falky tests

- ui/main/src/app/modules/settings/components/settings/base-setting/base-setting.directive.ts
- ui/main/src/app/modules/settings/components/settings/checkbox-setting/checkbox-setting.component.ts
- ui/main/src/app/modules/settings/components/settings/list-setting/list-setting.component.ts
- ui/main/src/app/modules/settings/components/settings/multi-settings/multi-settings.component.ts
- ui/main/src/app/modules/settings/components/settings/text-setting/text-setting.component.ts
> Add logs in settings to help diagnostic cypress falky tests

- ui/main/src/app/modules/activityarea/activityarea.component.ts
> Improvment in activity area to avoid falky cypress tests

- src/test/cypress/cypress/integration/Timeline.spec.js
- src/test/resources/cards/cypress/feed/chartLineWithCustomDate.json
> Improvment to avoid falky cypress test on timeline

- src/test/cypress/cypress/integration/Admin.spec.js
- ui/main/src/app/modules/admin/components/table/admin-table.directive.html
- ui/main/src/app/modules/admin/components/table/admin-table.directive.scss
- ui/main/src/app/modules/admin/components/table/admin-table.directive.ts
- ui/main/src/app/modules/admin/components/table/entities-table.component.ts
- ui/main/src/app/modules/admin/components/table/groups-table.component.ts
- ui/main/src/app/modules/admin/components/table/perimeters-table.component.ts
- ui/main/src/app/modules/admin/components/table/users-table.component.ts
- ui/main/src/app/services/cached-crud-service.ts
Fix #3503
-  Text : #3503 : Add export feature for admin screens
> Add export feature for admin screens (#3503)

- src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc
- ui/main/package-lock.json
- ui/main/package.json
- ui/main/src/app/modules/feed/components/map/map.component.ts
Signed-off-by: Gerben Danen <geppyz@gmail.com>
-  Text : #3450
> Add Graph to Map and added labels and translation (#3450)

- src/test/cypress/cypress/support/commands.js
- ui/main/src/app/store/effects/user.effects.ts
> Adjust activity area cypress tests

- CICD/github/install.sh
> Adjust CI/CD script

- src/test/cypress/cypress/integration/ResponseCard.spec.js
- src/test/cypress/cypress/support/commands.js
> Adjust response card cypress test

- src/test/cypress/cypress/integration/SoundNotification.spec.js
> Adujst sound cypress testing

- services/businessconfig/src/main/java/org/opfab/businessconfig/model/ProcessStatesData.java
- services/businessconfig/src/main/modeling/swagger.yaml
- src/docs/asciidoc/reference_doc/card_notification.adoc
- src/test/api/karate/businessconfig/getABusinessconfig.feature
- src/test/api/karate/businessconfig/resources/bundle_api_test_v2/config.json
- src/test/cypress/cypress/integration/Acknowledgment.spec.js
- src/test/resources/bundles/cypress/config.json
- src/test/resources/bundles/defaultProcess_V1/config.json
- ui/main/src/app/model/processes.model.ts
- ui/main/src/app/modules/cards/components/detail/detail.component.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
-  Text : #3545 : Add a possibility to not close card when user acknowledge
> Add a possibility to not close card when user acknowledge (#3545)

- src/test/cypress/cypress/integration/Admin.spec.js
- ui/main/src/app/modules/admin/components/editmodal/groups/edit-group-modal.component.html
- ui/main/src/app/modules/admin/components/editmodal/groups/edit-group-modal.component.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
Fix #3534
-  Text : #3534 : Administration screen : Add in groups popup the list of members
> Administration screen : Add in groups popup the list of members (#3534)

- services/businessconfig/src/main/java/org/opfab/businessconfig/model/ProcessStatesData.java
- services/businessconfig/src/main/modeling/swagger.yaml
- src/docs/asciidoc/reference_doc/user_cards.adoc
- src/test/api/karate/businessconfig/getABusinessconfig.feature
- src/test/api/karate/businessconfig/resources/bundle_api_test_v2/config.json
- src/test/cypress/cypress/integration/UserCard.spec.js
- src/test/resources/bundles/conferenceAndITIncidentExample/config.json
- src/test/resources/bundles/defaultProcess_V1/config.json
- src/test/resources/bundles/defaultProcess_V1/template/process.handlebars
- src/test/resources/cards/cypress/userCard/message.json
- ui/main/src/app/model/processes.model.ts
- ui/main/src/app/modules/cards/components/detail/detail.component.ts
Fix #3544 
-  Text : #3544 : Add the possibility to hide edit or delete card link
> Add the possibility to hide edit or delete card link (#3544)

- ui/main/src/app/modules/admin/admin.module.ts
- ui/main/src/app/modules/admin/components/cell-renderers/id-cell-renderer.component.html
- ui/main/src/app/modules/admin/components/cell-renderers/id-cell-renderer.component.ts
- ui/main/src/app/modules/admin/components/editmodal/groups/edit-group-modal.component.html
- ui/main/src/app/modules/admin/components/table/admin-table.directive.ts
- ui/main/src/app/modules/admin/components/table/entities-table.component.ts
- ui/main/src/app/modules/admin/components/table/groups-table.component.ts
- ui/main/src/app/modules/admin/components/table/perimeters-table.component.ts
- ui/main/src/app/modules/admin/components/table/users-table.component.ts
Fix #3562
-  Text : #3562: Admin screens: do not cut long values for ID column
> Admin screens: do not cut long values for ID column  (#3562)

- src/docs/asciidoc/reference_doc/template_description.adoc
- src/test/resources/bundles/conferenceAndITIncidentExample/template/incidentInProgress.handlebars
- src/test/resources/bundles/conferenceAndITIncidentExample/template/usercard_conference.handlebars
- src/test/resources/bundles/conferenceAndITIncidentExample/template/usercard_incidentInProgress.handlebars
- src/test/resources/bundles/defaultProcess_V1/template/chart-line.handlebars
- src/test/resources/bundles/defaultProcess_V1/template/chart.handlebars
- src/test/resources/bundles/defaultProcess_V1/template/process.handlebars
- src/test/resources/bundles/defaultProcess_V1/template/usercard_process.handlebars
- src/test/resources/bundles/messageOrQuestionExample/template/confirmation.handlebars
- src/test/resources/bundles/messageOrQuestionExample/template/question.handlebars
- src/test/resources/bundles/messageOrQuestionExample/template/usercard_confirmation.handlebars
- src/test/resources/bundles/messageOrQuestionExample/template/usercard_question.handlebars
- src/test/resources/bundles/taskExample/template/task.handlebars
- src/test/resources/bundles/taskExample/template/usercard_task.handlebars
> Improve templates code

- services/cards-publication/src/main/java/org/opfab/cards/publication/services/CardProcessingService.java
-  Text : #3589 Add logs when user ack/read/unack/unread
> Add logs when user ack/read/unack/unread (#3589)

- config/docker/ui-config/web-ui.json
- src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc
- src/docs/asciidoc/resources/migration_guide_to_3.10.adoc
- src/test/cypress/cypress/integration/FeedConfigurationTests.spec.js
- ui/main/package-lock.json
- ui/main/src/app/modules/feed/components/card-list/filters/feed-filter/feed-filter.component.html
- ui/main/src/app/modules/feed/components/card-list/filters/feed-filter/feed-filter.component.ts
- ui/main/src/app/modules/feed/components/card-list/filters/feed-sort/feed-sort.component.html
- ui/main/src/app/modules/feed/components/card-list/filters/feed-sort/feed-sort.component.ts
- ui/main/src/app/modules/feed/components/card-list/filters/filters.component.html
- ui/main/src/app/modules/feed/components/card-list/filters/filters.component.ts
Fix #3570
-  Text : #3570 : Set default feed filtering and sorting values in web-ui.json
> Set default feed filtering and sorting values in web-ui.json (#3570)

- src/docs/asciidoc/reference_doc/template_description.adoc
- src/test/resources/bundles/defaultProcess_V1/template/usercard_process.handlebars
- ui/main/src/assets/js/opfab.js
-  Text : #3595  Add methods for templates to set selected values and options list in multiselect component
> Add methods for templates to set selected values and options list in multiselect component (#3595)

- ui/main/src/app/modules/feed/feed.component.ts
-  Text : #3566 Add experimental hallway mod
To use it set users that are in this mode via  settings.userInHallwayMode  in web-ui.json
> Add experimental hallway mode (#3566)

- src/test/cypress/cypress/integration/Admin.spec.js
- ui/main/src/app/modules/admin/components/editmodal/entities/edit-entity-modal.component.html
- ui/main/src/app/modules/admin/components/editmodal/entities/edit-entity-modal.component.ts
- ui/main/src/app/modules/admin/components/editmodal/groups/edit-group-modal.component.html
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
Fix #3603 
-  Text : #3603 : Administration screen : Add in entity popup the list of members
> Administration screen : Add in entity popup the list of members (#3603)

- ui/main/src/app/modules/feed/components/card-list/filters/feed-filter/feed-filter.component.scss
-  Text : #3623 : Feed filters : red color for the icon
> Feed filters : red color for the icon (#3623)

- src/docs/asciidoc/resources/index.adoc
- ui/main/src/app/services/reminder/reminder.service.ts
> Improve reminder logs

- ui/main/src/app/modules/businessconfigparty/iframedisplay.component.scss
> Disable footer when using iFrame.

- src/test/externalWebAppExample/index.html
Fix #3619
-  Text : #3619 : Add margin-right and margin-left in external application example
> Add margin-right and margin-left in external application example (#3619)

- src/test/cypress/cypress/integration/CardDetail.spec.js
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
Fix #3621
-  Text : #3621 :  Archive card footer : "Deleted or updated" instead of "Deleted"
> Archive card footer : "Deleted or updated" instead of "Deleted" (#3621)

- ui/main/src/app/modules/archives/archives.component.html
- ui/main/src/app/modules/core/application-loading/app-loaded-in-another-tab/app-loaded-in-another-tab.component.html
- ui/main/src/app/modules/core/application-loading/application-loading.component.html
- ui/main/src/app/modules/core/connection-lost/connection-lost.component.html
- ui/main/src/app/modules/core/session-end/session-end.component.html
- ui/main/src/app/modules/share/spinner/spinner.component.html
Fix #3632
-  Text : #3632 : Correct invalid CSS style property
> Correct invalid CSS style property (#3632)

- src/docs/asciidoc/reference_doc/card_structure.adoc
- ui/main/src/app/modules/feed/components/map/map.component.ts
-  Text : Support for POLYGON geometry when using the geographical map, allowing cards to highlight a region on the map.
> Added support for POLYGON geometry (#3639)

- ui/main/src/app/modules/archives/archives.component.ts
Fix #3630 
-  Text : #3630 : Archives and Logging page: filter is applied on pagination change
> Archives and Logging page: filter is applied on pagination change (#3630)

- services/users/src/main/java/org/opfab/users/services/UserServiceImp.java
> Improve code for issue about non filterable notif (#3524)

- ui/main/src/app/modules/usercard/selectStateForm/usercard-select-state-form.component.ts
…
-  Text :  #3651 Correct bug : In usercard , sometimes template does not change when changing process
> Correct bug : In usercard , sometimes template does not change when changing process (#3651)

- services/cards-publication/src/main/java/org/opfab/cards/publication/services/CardTranslationService.java
- services/cards-publication/src/test/java/org/opfab/cards/publication/services/CardProcessServiceShould.java
- services/cards-publication/src/test/java/org/opfab/cards/publication/services/CardTranslationServiceShould.java
- src/test/api/karate/businessconfig/resources/bundle_api_test/i18n.json
- src/test/api/karate/businessconfig/resources/bundle_api_test_without_i18n_file/config.json
- src/test/api/karate/businessconfig/resources/bundle_api_test_without_i18n_file/css/style.css
- src/test/api/karate/businessconfig/resources/bundle_api_test_without_i18n_file/template/template.handlebars
- src/test/api/karate/businessconfig/resources/bundle_processDeleteUserCard/i18n.json
- src/test/api/karate/businessconfig/resources/bundle_process_1/i18n.json
- src/test/api/karate/businessconfig/resources/bundle_process_2/i18n.json
- src/test/api/karate/businessconfig/resources/packageBundles.sh
- src/test/api/karate/cardTests.txt
- src/test/api/karate/cards/getCardSubscription.feature
- src/test/api/karate/cards/postCardWithI18nUnexisting.feature
- tools/generic/utilities/src/main/java/org/opfab/utilities/I18nTranslation.java
- tools/spring/spring-test-utilities/src/main/java/org/opfab/springtools/configuration/test/I18nProcessesCacheTestApplication.java
- tools/spring/spring-test-utilities/src/main/java/org/opfab/springtools/configuration/test/ProcessesCacheTestApplication.java
To be merged after https://github.com/opfab/operatorfabric-core/pull/3451 because branch FE-3178 was created from branch FE-3234. Thanks.
-  Text : #3178 : Refuse cards if no translation file or no translation
> Refuse cards if no translation file or no translation (#3178)

- ui/main/src/app/modules/cards/components/detail/detail.component.html
-  Text : #3634 : Question cards : text not well aligned
> Question cards : text not well aligned (#3634)

- src/docs/asciidoc/reference_doc/template_description.adoc
- src/test/resources/bundles/messageOrQuestionExample/template/confirmation.handlebars
- ui/main/src/assets/js/opfab.js
Fix #3622 
-  Text : #3622 : Potential script injection in confirmation example
> Avoid potential script injection in confirmation example (#3622)

- src/test/cypress/cypress/integration/FeedTests.spec.js
- src/test/cypress/cypress/support/cardCommands.js
- src/test/cypress/cypress/support/feedCommands.js
Fix #3585
-  Text : #3585 : Add cypress test for sorting feature in feed
> Add cypress test for sorting feature in feed (#3585)

- ui/main/src/app/modules/cards/components/detail/detail.component.ts
Fix #3615 
-  Text : #3615 : Avoid vertical scroll bar in agenda detail card view
> Avoid vertical scroll bar in agenda detail card view (#3615)

- src/docs/asciidoc/reference_doc/template_description.adoc
- src/docs/asciidoc/resources/migration_guide_to_3.11.adoc
- src/test/resources/bundles/defaultProcess_V1/template/chart-line.handlebars
- src/test/resources/bundles/defaultProcess_V1/template/chart.handlebars
- ui/main/src/app/modules/share/template-rendering/template-rendering.component.ts
- ui/main/src/assets/js/templateGateway.js
-  Text : #3614 : Template input field reset when going in full screen or change day/night mode 
-   In chapter :  Features
-  Text : #3614 : Add Add onStyleChange() method to templateGateway
> Template input field reset when going in full screen or change day/night mode #3614

- src/docs/asciidoc/business_description.adoc
-  Text : Add information on the documentation regarding small resolution supported (#3626)
> Add information on the documentation regarding small resolution supported (#3626)

- .gitignore
> Adjust .gitignore file

- ui/main/src/app/modules/cards/components/detail/detail.component.ts
-  Text : #3672 : Acknowledgments lost when setting card in full screen mode
> Acknowledgments lost when setting card in full screen mode (#3672)

- ui/main/src/app/common/utilities.ts
- ui/main/src/app/modules/share/template-rendering/template-rendering.component.html
- ui/main/src/app/modules/share/template-rendering/template-rendering.component.ts
- ui/main/src/app/services/template-css.service.ts
- ui/main/src/app/store/effects/processes.effects.ts
Add a cache mechanism for css associated with templates
-  Text : 3628  Solve bug : In templates , with slow network, style is apply long after template processing
> Solve bug : In templates , with slow network, style is apply long after template processing (#3638)

- src/test/cypress/cypress/integration/FeedTests.spec.js
- src/test/cypress/cypress/support/feedCommands.js
Fix #3586 
-  Text : #3586 : Add cypress test for filter feature in feed
> Add cypress test for filter feature in feed (#3586)

- bin/load_environment_light.sh
> Upgrade node to lts version

- config/dev/users-dev.yml
- config/docker/users-docker.yml
- config/keycloak/export/dev-users-0.json
- src/docs/asciidoc/reference_doc/user_cards.adoc
- src/test/cypress/cypress/integration/Acknowledgment.spec.js
- src/test/cypress/cypress/integration/Admin.spec.js
- src/test/cypress/cypress/integration/ExternalDevicesConfiguration.spec.js
- src/test/cypress/cypress/integration/UserCard.spec.js
- src/test/resources/bundles/defaultProcess_V1/template/usercard_process.handlebars
- ui/main/src/app/modules/share/multi-select/multi-select.component.ts
- ui/main/src/app/modules/usercard/recipientForm/usercard-recipients-form.component.ts
- ui/main/src/assets/js/usercardTemplateGateway.js
Fix #3681
-  Text : #3681: Retrieve the list of recipients before sending a User Card
> Retrieve the list of recipients before sending a User Card (#3681)

- src/test/cypress/cypress/support/userCardCommands.js
> Update usercard process choice to be compatible with long list of process

- src/test/cypress/cypress/integration/Acknowledgment.spec.js
- src/test/cypress/cypress/integration/EntityAcknowledgment.spec.js
- src/test/cypress/cypress/integration/FeedTests.spec.js
- src/test/cypress/cypress/integration/Monitoring.spec.js
- src/test/cypress/cypress/integration/ResponseCard.spec.js
- src/test/cypress/cypress/integration/UserCard.spec.js
- src/test/cypress/cypress/support/cardCommands.js
> Add new cypress commands for card

- ui/main/src/app/modules/usercard/usercard.component.html
- ui/main/src/app/modules/usercard/usercard.component.ts
-  Text : #3723 Avoid flickering when editing user card
> Avoid flickering when editing user card (#3723)

- ui/main/src/app/modules/feed/components/pinned-cards/pinned-cards.component.ts
- ui/main/src/app/modules/feed/feed.component.html
- ui/main/src/app/modules/feed/feed.component.ts
Fix #2814
-  Text : #2814 : Show pinned cards also  on small screen view
> Show pinned cards also on small screen view  (#2814)

- src/test/cypress/cypress/integration/Acknowledgment.spec.js
- src/test/cypress/cypress/integration/CardDetail.spec.js
- ui/main/src/app/modules/cards/components/detail/detail.component.html
- ui/main/src/app/modules/cards/components/detail/detail.component.ts
Fix #3685
-  Text : #3685 : Show entities already acknowledged in card footer for user having more than one entities concerned
> Show entities already acknowledged in card footer for user having more than one entities concerned (#3685)

- config/docker/ui-config/web-ui.json
- src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc
- src/test/cypress/cypress/integration/Acknowledgment.spec.js
- src/test/cypress/cypress/integration/ActivityArea.spec.js
- src/test/cypress/cypress/integration/Archives.spec.js
- src/test/cypress/cypress/integration/Calendar.spec.js
- src/test/cypress/cypress/integration/FeedNotificationConfiguration.spec.js
- src/test/cypress/cypress/integration/Timeline.spec.js
- src/test/cypress/cypress/support/feedCommands.js
- ui/main/src/app/modules/archives/archives.component.html
- ui/main/src/app/modules/archives/archives.module.ts
- ui/main/src/app/modules/cards/cards.module.ts
- ui/main/src/app/modules/cards/components/detail/detail.component.html
- ui/main/src/app/modules/cards/components/detail/detail.component.ts
- ui/main/src/app/modules/share/light-card/light-card.component.html
- ui/main/src/app/modules/share/light-card/light-card.component.spec.ts
- ui/main/src/app/modules/share/light-card/light-card.module.ts
- ui/main/src/app/modules/share/pipes/opfab-title-case.pipe.ts
- ui/main/src/app/modules/share/pipes/pipes.module.ts
-  Text : #3447 
Note: for some reason, the space behind the card titles seemed to be removed. I adapted the test cases to accommodate this, but I'm not sure if this causes any issues for you. [
> Make card titles case configurable (#3447)

- services/cards-publication/src/main/java/org/opfab/cards/publication/services/CardProcessingService.java
- src/test/api/karate/cards/cardsWithTimespans.feature
- src/test/resources/bundles/taskExample/template/usercard_task.handlebars
-  Text : #3702 : Reminder feature : deal with time field when it is non filled
> Reminder feature : deal with time field when it is non filled (#3702)

- src/test/cypress/cypress/integration/Admin.spec.js
- src/test/cypress/cypress/integration/Archives.spec.js
- src/test/cypress/cypress/integration/FeedNotificationConfiguration.spec.js
- src/test/resources/bundles/bundle_api_test/config.json
- src/test/resources/bundles/bundle_api_test/css/style.css
- src/test/resources/bundles/bundle_api_test/i18n.json
- src/test/resources/bundles/bundle_api_test/template/template.handlebars
- src/test/resources/perimeters/createAllPerimeter.sh
- src/test/resources/perimeters/externalRecipent.json
Fix #3716
-  Text : #3716 : Error message when sending card message example
> Error message when sending card message example (#3716)

- src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc
- ui/main/src/app/modules/feed/components/map/map.component.ts
Signed-off-by: Gerben Danen <geppyz@gmail.com>
-  Text : #3525
> Add feature to customize backgroundlayer in map (#3525)

- ui/main/src/app/modules/core/application-loading/app-loaded-in-another-tab/app-loaded-in-another-tab.component.ts
- ui/main/src/app/services/card.service.ts
- ui/main/src/app/services/sound-notification.service.ts
- ui/main/src/app/store/effects/authentication.effects.spec.ts
- ui/main/src/app/store/effects/authentication.effects.ts
Nothing in release note as it is already present in release 3.10.2
> Correct bug : sound still active after user is disconnected (#3741)

- src/test/cypress/cypress/integration/UserCard.spec.js
> Fix 'Time' field for recurrence for cypress tests on usercard

- ui/main/src/app/modules/core/application-loading/application-loading.component.html
- ui/main/src/app/modules/core/application-loading/application-loading.component.ts
-  Text : #3738 : Add environment banner on the login screen
> Add environment banner on the login screen (#3738)

- ui/main/src/app/services/card.service.ts
- ui/main/src/app/store/effects/authentication.effects.ts
-  Text : #3750 Failed to delete subscription when logging out
> Correct bug : Failed to delete subscription when logging out (#3750)

- .gitignore
- config/dev/businessconfig-dev.yml
>  Move directory for bundles in dev mode

- bin/run_all.sh
- bin/waitForOpfabToStart.sh
> Make the output of waitForOpfabToStart.sh looks better

- client/businessconfig/src/main/java/org/opfab/businessconfig/model/ShowAcknowledgmentFooterEnum.java
- client/businessconfig/src/main/modeling/config.json
- services/businessconfig/src/main/java/org/opfab/businessconfig/model/ProcessStatesData.java
- services/businessconfig/src/main/modeling/swagger.yaml
- src/docs/asciidoc/reference_doc/card_notification.adoc
- src/test/api/karate/businessconfig/getABusinessconfig.feature
- src/test/api/karate/businessconfig/resources/bundle_api_test_v2/config.json
- src/test/cypress/cypress/integration/Acknowledgment.spec.js
- src/test/resources/bundles/conferenceAndITIncidentExample/config.json
- src/test/resources/bundles/defaultProcess_V1/config.json
- src/test/resources/bundles/messageOrQuestionExample/config.json
- src/test/resources/cards/cypress/ack/message7.json
- ui/main/src/app/model/processes.model.ts
- ui/main/src/app/modules/card/components/card-body/card-body.component.ts
- ui/main/src/app/services/processes.service.ts
- ui/main/src/app/services/user-permissions.service.ts
-  Text : #3751 : Permit to show acknowledgment footer to all users
> Permit to show acknowledgment footer to all users (#3751)

- services/cards-consultation/src/main/java/org/opfab/cards/consultation/configuration/mongo/RecurrenceReadConverter.java
- services/cards-consultation/src/main/java/org/opfab/cards/consultation/model/RecurrenceConsultationData.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/configuration/mongo/RecurrenceReadConverter.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/configuration/mongo/RecurrenceWriterConverter.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/model/RecurrencePublicationData.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/services/CardProcessingService.java
- services/cards-publication/src/main/modeling/swagger.yaml
- services/cards-publication/src/test/java/org/opfab/cards/publication/services/CardProcessServiceShould.java
- src/docs/asciidoc/reference_doc/card_notification.adoc
- src/test/api/karate/cards/cardsWithTimespans.feature
- src/test/resources/bundles/taskExample/template/task.handlebars
- src/test/resources/bundles/taskExample/template/usercard_task.handlebars
- ui/main/package-lock.json
- ui/main/package.json
- ui/main/src/app/model/card.model.ts
- ui/main/src/app/modules/calendar/calendar.component.ts
- ui/main/src/app/modules/calendar/calendar.module.ts
- ui/main/src/app/services/reminder/reminderUtils.spec.ts
- ui/main/src/app/services/reminder/reminderUtils.ts
-  Text : #3604 : Add months possibility for repeating reminder feature
> Add months possibility for repeating reminder feature (#3604)

- ui/main/src/app/modules/feedconfiguration/feedconfiguration.component.html
- ui/main/src/app/modules/feedconfiguration/feedconfiguration.component.ts
- ui/main/src/app/services/processes.service.ts
-  Text : #3781 : Make disabled checkboxes coherent in notification configuration screen
> Make disabled checkboxes coherent in notification configuration screen

- ui/main/src/app/modules/share/light-card/light-card.component.scss
> Improve display of multi-line card titles (#3805)

- ui/main/src/app/modules/calendar/calendar.component.ts
Nothing in release notes because the corresponding feature is not yet delivered.
> Bug in calendar in december for task with no months set (#3815)

- src/docs/asciidoc/resources/index.adoc
- src/docs/asciidoc/resources/migration_guide_to_3.10.adoc
- src/docs/asciidoc/resources/migration_guide_to_3.11.adoc
- src/docs/asciidoc/resources/migration_guide_to_3.6.adoc
- src/docs/asciidoc/resources/migration_guide_to_3.7.adoc
> Migration doc 3.11 is not reference in main documentation + errors in text (#3817)

- client/businessconfig/src/main/java/org/opfab/businessconfig/model/ShowAcknowledgmentFooterEnum.java
- services/businessconfig/src/main/modeling/swagger.yaml
- src/docs/asciidoc/reference_doc/card_notification.adoc
- src/test/api/karate/businessconfig/getABusinessconfig.feature
- src/test/api/karate/businessconfig/resources/bundle_api_test_v2/config.json
- src/test/cypress/cypress/integration/Acknowledgment.spec.js
- src/test/resources/bundles/defaultProcess_V1/config.json
- ui/main/src/app/model/processes.model.ts
- ui/main/src/app/modules/card/components/card-body/card-body.component.ts
- ui/main/src/app/services/user-permissions.service.ts
Nothing in release notes as the feature is not yet delivered.
> Change "OnlyForEntitiesAllowedToEdit" into "OnlyForUsersAllowedToEdit"

- ui/main/src/assets/i18n/en.json
> Typo errors in en.json file (#3827)

- ui/main/src/app/modules/share/multi-select/multi-select.component.ts
-  Text : #3826 Code injection in multiselect component
> Solve bug : Code injection in multiselect component (#3826)

- ui/main/src/app/services/sound-notification.service.ts
#3833 Define a minimum value for sound replayInterval
> Define a minimum value for sound replayInterval (#3833)

- ui/main/src/app/modules/admin/components/table/admin-table.directive.ts
-  Text : #3818 : Admin screens, dots after edit button
> Admin screens, dots after edit button (#3818)

- ui/main/src/app/modules/feed/components/pinned-cards/pinned-cards.component.ts
Fix #3824 
-  Text : #3824 : Pinned cards : error log in console with reduced view
> Pinned cards : error log in console with reduced view (#3824)

- src/test/cypress/cypress/integration/EntityAcknowledgment.spec.js
- ui/main/src/app/modules/card/components/card-ack/card-ack.component.ts
Fix #3752, #3731
-  Text : #3752, #3731 : Do not show unacknowledgment button when ack is at the entity level
> Do not show unacknowledgment button when ack is at the entity level (#3752, #3731)

- ui/main/src/app/modules/share/archives-logging-filters/archives-logging-filters.component.ts
-  Text : #3831 : Problem with "active from/to" and "publish from/to" dates in archives/logging screens
> Problem with "active from/to" and "publish from/to" dates in archives/logging screens (#3831)

- src/test/api/karate/cards/postCardWithProcessAndOrStateUnexisting.feature
> Avoid karate falky test with no process test

- src/test/api/karate/cards/postCardWithI18nUnexisting.feature
> Add a retry to avoid falky karate test with i18n test 

- src/test/cypress/cypress/integration/Admin.spec.js
> Correct admin cypress test to avoid falky test

- src/test/cypress/cypress/integration/ResponseCard.spec.js
> Adjust test for response card to avoid falky cypress test

- src/test/api/karate/cards/post1CardThenUpdateThenDelete.feature
- src/test/cypress/cypress/integration/ResponseCard.spec.js
> Avoid falky karate push card test 

- src/docs/asciidoc/community/index.adoc
> Doc adjustments

- ui/main/src/app/modules/externaldevicesconfiguration/table/externaldevicesconfiguration-directive.html
- ui/main/src/app/modules/externaldevicesconfiguration/table/externaldevicesconfiguration-directive.ts
-  Text : #3854 : Cannot add user external device config when slow network
> Cannot add user external device config when slow network (#3854)

- src/test/cypress/cypress/integration/Archives.spec.js
- ui/main/src/app/modules/archives/archives.component.html
- ui/main/src/app/modules/archives/archives.component.ts
- ui/main/src/app/modules/share/simplified-card-view/simplified-card-view.component.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
-  Text : #3776 : Add in archives footer card detail the entity recipients
> Add in archives footer card detail the entity recipients (#3776)

- src/test/cypress/cypress/integration/Translation.spec.js
> Correct falky translation test

- src/test/cypress/cypress/integration/ExternalDevicesConfiguration.spec.js
- ui/main/src/app/modules/externaldevicesconfiguration/table/externaldevicesconfiguration-directive.html
> avoid failed cypress tests on externaldevicesconfig screen

- config/docker/ui-config/web-ui.json
- src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc
- ui/main/src/app/modules/feed/components/card-list/card-list.component.html
- ui/main/src/app/modules/feed/components/card-list/filters/feed-search/feed-search.component.html
- ui/main/src/app/modules/feed/components/card-list/filters/feed-search/feed-search.component.scss
- ui/main/src/app/modules/feed/components/card-list/filters/feed-search/feed-search.component.ts
- ui/main/src/app/modules/feed/components/card-list/filters/feed-sort/feed-sort.component.ts
- ui/main/src/app/modules/feed/components/card-list/filters/filters.component.html
- ui/main/src/app/modules/feed/components/card-list/filters/filters.component.ts
- ui/main/src/app/modules/feed/feed.module.ts
- ui/main/src/app/services/lightcards/lightcards-feed-filter.service.ts
- ui/main/src/app/services/lightcards/search-service.ts
> Search filter in the Card Feed (#3768)

- config/docker/external-devices-docker.yml
- services/external-devices/src/main/java/org/opfab/externaldevices/drivers/ExternalDeviceDriverFactory.java
- services/external-devices/src/main/java/org/opfab/externaldevices/drivers/ModbusDriver.java
- services/external-devices/src/main/java/org/opfab/externaldevices/drivers/ModbusDriverFactory.java
- services/external-devices/src/main/java/org/opfab/externaldevices/services/DevicesService.java
- services/external-devices/src/test/java/org/opfab/externaldevices/drivers/ModbusDriverFactoryShould.java
- services/external-devices/src/test/java/org/opfab/externaldevices/drivers/ModbusDriverShould.java
- services/external-devices/src/test/java/org/opfab/externaldevices/services/DevicesServiceShould.java
- src/docs/asciidoc/deployment/configuration/configuration.adoc
Feature 
#3884 Add an option to have no keepAlive for connections to external devices
> Add an option to have no keepAlive for connections to external devices

- src/test/cypress/cypress/support/commands.js
- src/test/cypress/cypress/support/opfabCommands.js
> Correct invalid time in cypress test logs

- config/cypress/generateUIConfigForCypress.sh
- src/test/cypress/cypress/integration/CheckIfOpfabUrlIsAlreadyTaken.spec.js
- src/test/cypress/launchCypressUI.sh
> Remove check if url is used for cypress tests

- ui/main/src/app/modules/activityarea/activityarea.component.ts
> Avoid cypress falky test with activity area screen

- ui/main/src/app/modules/activityarea/activityarea.component.ts
> Avoid cypress falky test with activity area screen II

- CICD/github/build.sh
- build.gradle
> Correct deprecated sonar gradle plugin syntaxe

- src/test/cypress/cypress/integration/1-RealTimeUsers.spec.js
- ui/main/src/app/modules/activityarea/activityarea.component.ts
> Avoid cypress falky test with activity area screen III

- bin/load_environment_light.sh
- ui/main/package-lock.json
> Upgrade node to 18.12.1

- src/test/cypress/cypress/integration/ExternalDevicesConfiguration.spec.js
> Avoid cypress falky test in external devices configuration

- CICD/github/build.sh
> Add more memory for gradle in CI

- bin/load_environment_light.sh
- services/businessconfig/src/main/docker/Dockerfile
- services/cards-consultation/src/main/docker/Dockerfile
- services/cards-publication/src/main/docker/Dockerfile
- services/external-devices/src/main/docker/Dockerfile
- services/users/src/main/docker/Dockerfile
- src/docs/asciidoc/dev_env/requirements.adoc
- src/docs/asciidoc/resources/index.adoc
- src/docs/asciidoc/resources/migration_guide_to_3.12.adoc
- src/test/dummyModbusDevice/src/main/docker/Dockerfile
- src/test/externalApp/src/main/docker/Dockerfile
-  Text : #2105 Migrate to java 17
> Migrate to java 17 (#2105)

- src/docs/asciidoc/getting_started/index.adoc
> Correct english in getting started (#3952)

- services/cards-publication/src/main/java/org/opfab/cards/publication/services/CardProcessingService.java
No need to add to the release note
> Solved sonar issue (#3955)

- services/users/src/main/java/org/opfab/users/controllers/PerimetersController.java
- services/users/src/main/java/org/opfab/users/services/PerimetersService.java
- services/users/src/test/java/org/opfab/users/controllers/PerimetersControllerShould.java
- services/users/src/test/java/org/opfab/users/services/PerimetersServiceShould.java
- services/users/src/test/java/org/opfab/users/stubs/GroupRepositoryStub.java
- services/users/src/test/java/org/opfab/users/stubs/PerimeterRepositoryStub.java
- src/test/api/karate/users/perimeters/createPerimeters.feature
> Refacto user service : refaco perimeter

- services/cards-publication/src/main/java/org/opfab/cards/publication/model/CardPublicationData.java
Small correction of a boolean test
> Sonar cloud correction #3966

- services/users/src/main/java/org/opfab/users/configuration/oauth2/OAuth2UsersConfiguration.java
- tools/spring/spring-oauth2-utilities/src/main/java/org/opfab/springtools/configuration/oauth/jwt/JwtProperties.java
> Map the JWT custom name field to the family_name field (#3959)

- src/docs/asciidoc/dev_env/project_structure.adoc
> Adjust project structure documentation

- AUTHORS.txt
> Add Clement Bouvier as author

- ui/main/src/app/modules/archives/archives.component.ts
> Correct error in log

- config/dev/docker-compose.yml
- config/docker/docker-compose.yml
- config/docker/ui-config/web-ui.json
- config/keycloak/export/dev-realm.json
Signed-off-by: Gerben Danen <geppyz@gmail.com>
-  Text : #4002
> Upgraded keycloak and mongodb (#4002)

- client/users/src/main/java/org/opfab/users/model/PermissionEnum.java
- client/users/src/main/modeling/config.json
- services/users/src/main/java/org/opfab/users/model/GroupData.java
- services/users/src/main/modeling/swagger.yaml
- services/users/src/test/java/org/opfab/users/services/GroupsServiceShould.java
> Add permissions field to Group object (#4006)

- ui/main/src/app/modules/admin/components/table/admin-table.directive.ts
> Quick fix of a regression from the #3999 merge

- src/test/api/karate/users/groups/createGroups.feature
- src/test/api/karate/users/groups/getGroupDetails.feature
- src/test/api/karate/users/groups/getGroups.feature
> Modify Karate test for group permissions

- src/test/cypress/cypress/integration/Admin.spec.js
- ui/main/src/app/app.module.ts
- ui/main/src/app/modules/admin/components/table/admin-table.directive.ts
- ui/main/src/app/modules/admin/components/table/groups-table.component.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
> Added the permission column in the group table #4006

- services/users/src/main/java/org/opfab/users/model/CurrentUserWithPerimetersData.java
- services/users/src/main/java/org/opfab/users/services/CurrentUserWithPerimetersService.java
- services/users/src/main/modeling/swagger.yaml
- services/users/src/test/java/org/opfab/users/services/CurrentUserWithPerimetersServiceShould.java
> Add new field "permissions" in CurrentUserWithPerimters Object (#4006)

- src/test/cypress/cypress/integration/Acknowledgment.spec.js
- src/test/cypress/cypress/integration/EntityAcknowledgment.spec.js
- src/test/cypress/cypress/support/cardCommands.js
- ui/main/src/app/modules/card/components/card-ack/card-ack.component.html
- ui/main/src/app/modules/card/components/card-ack/card-ack.component.ts
> Refactoring card-ack component (#3862)

- config/dev/users-dev.yml
- config/docker/users-docker.yml
- services/cards-consultation/src/main/java/org/opfab/cards/consultation/repositories/ArchivedCardCustomRepositoryImpl.java
- services/cards-consultation/src/main/java/org/opfab/cards/consultation/repositories/UserUtilitiesCommonToCardRepository.java
- ui/main/src/app/model/permission.model.ts
- ui/main/src/app/model/user.model.ts
- ui/main/src/app/model/userWithPerimeters.model.ts
- ui/main/src/app/modules/share/archives-logging-filters/archives-logging-filters.component.ts
- ui/main/src/app/services/user.service.ts
> Use the new Permission for viewing all archives  (#4006)

- services/users/src/main/java/org/opfab/users/services/EntitiesService.java
- services/users/src/main/java/org/opfab/users/services/GroupsService.java
- services/users/src/main/java/org/opfab/users/services/NotificationService.java
- services/users/src/main/java/org/opfab/users/services/PerimetersService.java
- services/users/src/test/java/org/opfab/users/services/EntitiesServiceShould.java
- services/users/src/test/java/org/opfab/users/services/GroupsServiceShould.java
- services/users/src/test/java/org/opfab/users/services/PerimetersServiceShould.java
- services/users/src/test/java/org/opfab/users/services/UserSettingsServiceShould.java
- services/users/src/test/java/org/opfab/users/services/UsersServiceShould.java
> Refacto user service : add unit tests for notification of user updates + small corrections

- src/test/cypress/cypress/integration/Admin.spec.js
- ui/main/src/app/modules/admin/components/editmodal/groups/edit-group-modal.component.html
- ui/main/src/app/modules/admin/components/editmodal/groups/edit-group-modal.component.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
> Added the edit button and the cypress tests for permissions in the admin group table #4006

- config/dev/users-dev.yml
- config/docker/users-docker.yml
- config/keycloak/export/dev-users-0.json
- services/cards-publication/src/main/java/org/opfab/cards/publication/controllers/CardController.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/services/CardPermissionControlService.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/services/CardProcessingService.java
- services/cards-publication/src/test/java/org/opfab/cards/publication/services/CardProcessServiceShould.java
- ui/main/src/app/modules/card/components/card-ack/card-ack.component.ts
- ui/main/src/app/modules/card/components/card-actions/card-actions.component.ts
- ui/main/src/app/modules/card/components/card-reponse/card-response.component.ts
- ui/main/src/app/modules/usercard/usercard.component.ts
- ui/main/src/app/services/lightcards/lightcards-store.service.ts
> Use the new permission for READONLY users (#4006)

- src/test/cypress/cypress/integration/Admin.spec.js
- ui/main/src/app/modules/admin/components/editmodal/users/edit-user-modal.component.html
- ui/main/src/app/modules/admin/components/editmodal/users/edit-user-modal.component.ts
- ui/main/src/app/modules/admin/components/table/users-table.component.ts
> Removed the roles feature from the users admin table #4006

- services/businessconfig/src/test/java/org/opfab/businessconfig/controllers/BusinessconfigControllerForMonitoringShould.java
- services/businessconfig/src/test/java/org/opfab/businessconfig/controllers/GivenAdminUserBusinessconfigControllerShould.java
- services/cards-consultation/src/main/java/org/opfab/cards/consultation/repositories/ArchivedCardCustomRepositoryImpl.java
- services/cards-consultation/src/main/java/org/opfab/cards/consultation/repositories/UserUtilitiesCommonToCardRepository.java
- services/cards-consultation/src/test/java/org/opfab/cards/consultation/routes/MessageToSubscriptionsRoutesShould.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/services/CardPermissionControlService.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/services/CardProcessingService.java
- services/cards-publication/src/test/java/org/opfab/cards/publication/controllers/CardControllerShould.java
- services/users/src/main/java/org/opfab/users/configuration/oauth2/OAuth2UsersConfiguration.java
- tools/spring/spring-oauth2-utilities/src/main/java/org/opfab/springtools/configuration/oauth/OAuth2GenericConfiguration.java
- tools/spring/spring-oauth2-utilities/src/main/java/org/opfab/springtools/configuration/oauth/OAuth2JwtProcessingUtilities.java
- tools/spring/spring-test-utilities/src/main/java/org/opfab/springtools/configuration/test/OpFabUserDetails.java
- tools/spring/spring-test-utilities/src/main/java/org/opfab/springtools/configuration/test/WithMockOpFabUser.java
- tools/spring/spring-test-utilities/src/main/java/org/opfab/springtools/configuration/test/WithMockOpFabUserReactive.java
- tools/spring/spring-test-utilities/src/main/java/org/opfab/springtools/configuration/test/WithMockOpFabUserSecurityContextFactory.java
- tools/spring/spring-test-utilities/src/main/java/org/opfab/springtools/configuration/test/WithMockOpFabUserSecurityContextFactoryReactive.java
- ui/main/src/app/services/user.service.ts
> Use the new ADMIN permission for administrators (#4006)

- src/docs/asciidoc/reference_doc/users_management.adoc
> Updated the documentation #4006

- .gitignore
- config/dev/docker-compose.yml
- config/docker/docker-compose.yml
- src/test/resources/mongodump.sh
- src/test/resources/mongorestore.sh
-  Text : Added scripts to speed up the database resetting process during testing
> Added scripts to save and load a back up of the test config #4030

- src/test/cypress/cypress/integration/ResponseCard.spec.js
- ui/main/src/app/modules/card/components/card-reponse/card-response.component.html
- ui/main/src/app/modules/card/components/card-reponse/card-response.component.ts
> Disabled the pop up button if no entities are selected when responding to a card #3618

- ui/main/src/app/modules/businessconfigparty/iframedisplay.component.ts
> Fix for encoded urls in iframe (#3848)

- ui/main/src/app/business/services/date-time-formatter.service.ts
- ui/main/src/app/business/services/guid.service.ts
- ui/main/src/app/modules/archives/archives.component.ts
- ui/main/src/app/modules/card/components/card-footer-text/card-footer-text.component.ts
- ui/main/src/app/modules/feed/components/time-line/custom-timeline-chart/custom-timeline-chart.component.spec.ts
- ui/main/src/app/modules/feed/components/time-line/init-chart/init-chart.component.spec.ts
- ui/main/src/app/modules/logging/components/cell-renderers/time-cell-renderer.component.ts
- ui/main/src/app/modules/logging/logging.component.ts
- ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.ts
- ui/main/src/app/modules/navbar/info/info.component.ts
- ui/main/src/app/modules/share/light-card/light-card.component.spec.ts
- ui/main/src/app/modules/share/light-card/light-card.component.ts
- ui/main/src/app/modules/share/timeline-buttons/timeline-buttons.component.ts
- ui/main/src/app/modules/useractionlogs/components/useractionlogs-table/useractionlogs-table.component.ts
- ui/main/src/app/services/authentication/authentication.service.ts
- ui/main/src/app/services/card.service.ts
- ui/main/src/tests/helpers.ts
Move date-time-formatter and gui service in business/services repository
> Refacto UI : move some business services to the new business repository

- ui/main/src/app/modules/admin/components/confirmation-dialog/confirmation-dialog.component.html
- ui/main/src/app/modules/admin/components/confirmation-dialog/confirmation-dialog.component.ts
- ui/main/src/shared/css/opfab-application.css
> Change the default focus to Ok and removed the autofocus outline #4008

- ui/main/src/app/modules/share/simplified-card-view/simplified-card-view.component.html
- ui/main/src/app/modules/share/simplified-card-view/simplified-card-view.component.ts
Fix #3375 
-  Text : #3375 : Lock answer in archived cards detail
> Lock answer in archived cards detail (#3375)

- src/test/cypress/cypress/integration/CoreMenuConfigurationTests.spec.js
- ui/main/src/app/business/services/menu.service.ts
- ui/main/src/app/modules/navbar/navbar.component.ts
Fix #4063 
-  Text : #4063 : Do not show menu when user has not the good permission
> Do not show menu when user has not the good permission (#4063)

- services/cards-publication/src/main/java/org/opfab/cards/publication/services/CardProcessingService.java
- services/users/src/main/java/org/opfab/users/configuration/oauth2/OAuth2UsersConfiguration.java
- services/users/src/main/java/org/opfab/users/services/CurrentUserWithPerimetersService.java
- services/users/src/test/java/org/opfab/users/services/CurrentUserWithPerimetersServiceShould.java
- ui/main/src/app/services/user.service.ts
Nothing in release note , it is a complement to #4006
> Set permission ot admin when user member of admin group

- src/docs/asciidoc/reference_doc/template_description.adoc
- src/test/resources/bundles/taskAdvancedExample/template/taskAdvanced.handlebars
- src/test/resources/bundles/taskAdvancedExample/template/usercard_taskAdvanced.handlebars
- ui/main/src/app/modules/card/services/handlebars.service.spec.ts
- ui/main/src/app/modules/card/services/handlebars.service.ts
Nothing in release notes because this bug is not present in the actual release yet.
> Missing zero-padding for Task Advanced card (#4069)

- src/test/cypress/cypress/integration/GeoMap.spec.js
- src/test/resources/cards/cypress/geoMap/invalid_point_card1.json
- src/test/resources/cards/cypress/geoMap/invalid_polygon_card1.json
- src/test/resources/cards/cypress/geoMap/message1.json
- src/test/resources/cards/cypress/geoMap/point_card1.json
- src/test/resources/cards/cypress/geoMap/point_card2.json
- src/test/resources/cards/cypress/geoMap/point_card3.json
- src/test/resources/cards/cypress/geoMap/polygon_card1.json
-  In chapter :  Task
-  Text : #3137
> Add cypress tests for the geomap feature (#3137)

- ui/main/src/app/modules/feed/components/map/map.component.ts
> Geomap does not show circles on the map (#3988)

- src/test/resources/bundles/taskAdvancedExample/template/taskAdvanced.handlebars
> Task advanced user card: selecting december results in both january, february and december being selected (#4097)

- ui/main/src/app/modules/admin/components/editmodal/users/edit-user-modal.component.ts
-  Text : #4087 Solve bug : Admin users: field "authorizedIPAddresses" not taken into account
> Solve bug : Admin users: field "authorizedIPAddresses" not taken into account (#4087)

- services/users/src/main/java/org/opfab/users/services/EntitiesService.java
- services/users/src/main/java/org/opfab/users/services/GroupsService.java
- services/users/src/test/java/org/opfab/users/services/EntitiesServiceShould.java
- services/users/src/test/java/org/opfab/users/services/GroupsServiceShould.java
- src/test/api/karate/cards/deleteUserCard.feature
- src/test/api/karate/users/entities/createEntities.feature
- src/test/api/karate/users/groups/createGroups.feature
- src/test/api/karate/users/groups/deleteUserFromGroup.feature
- src/test/api/karate/users/groups/updateExistingGroup.feature
- ui/main/package-lock.json
- ui/main/src/app/modules/admin/components/editmodal/entities/edit-entity-modal.component.html
- ui/main/src/app/modules/admin/components/editmodal/entities/edit-entity-modal.component.ts
- ui/main/src/app/modules/admin/components/editmodal/groups/edit-group-modal.component.html
- ui/main/src/app/modules/admin/components/editmodal/groups/edit-group-modal.component.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
> Prevented entity name and group name duplication #1321

- ui/main/src/app/modules/core/application-loading/application-loading.component.ts
- ui/main/src/app/modules/navbar/navbar.component.html
- ui/main/src/app/modules/navbar/navbar.component.ts
- ui/main/src/app/services/global-style.service.ts
Fix #3819
-  Text : #3819 : Fix choose activity area on login does not take into account day mode
> Fix choose activity area on login does not take into account day mode (#3819)

- ui/main/src/app/modules/core/application-loading/application-loading.component.ts
- ui/main/src/app/store/actions/user.actions.ts
- ui/main/src/app/store/effects/user.effects.ts
> Refacto UI : remove use of ngrx for token synchro

- ui/main/src/app/modules/admin/components/editmodal/groups/edit-group-modal.component.ts
Fix #4088
-  Text : #4088 : Fix error in console log when creating a new group
> Fix error in console log when creating a new group (#4088)

- ui/main/src/app/modules/feed/components/card-list/filters/feed-search/feed-search.component.html
- ui/main/src/app/modules/feed/components/card-list/filters/feed-search/feed-search.component.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
Fix #4098 
-  Text : #4098 : Fix Feed search placeholder is not translated
> Fix Feed search placeholder is not translated (#4098)

- ui/main/src/app/modules/admin/components/table/admin-table.directive.ts
- ui/main/src/app/modules/externaldevicesconfiguration/table/externaldevicesconfiguration-directive.ts
- ui/main/src/assets/i18n/en.json
Fix #4091 
Fix #4093
I propose to add nothing in release notes
> Fix typos (#4091, #4093)

- ui/main/src/app/modules/feed/components/card-list/filters/feed-search/feed-search.component.scss
Fix #4101 
-  Text : #4101 : Fix spinner position when search in feed activated
> Fix spinner position when search in feed activated (#4101)

- ui/main/src/app/app.module.ts
- ui/main/src/app/business/server/acknowledge.server.ts
- ui/main/src/app/business/services/acknowledge.service.spec.ts
- ui/main/src/app/business/services/acknowledge.service.ts
- ui/main/src/app/modules/card/components/card-ack/card-ack.component.ts
- ui/main/src/app/modules/feed/components/card-list/card-list.component.ts
- ui/main/src/app/server/angularAcknowledgement.server.ts
- ui/main/src/app/services/reminder/reminder.service.ts
- ui/main/src/app/services/rrule-reminder/rrule-reminder.service.ts
> Refacto the acknowledgement service in the business code #4048

- ui/main/src/app/business/server/config.server.ts
- ui/main/src/app/business/services/i18n.service.ts
- ui/main/src/app/modules/core/application-loading/application-loading.component.ts
- ui/main/src/app/modules/share/light-card/light-card.component.spec.ts
- ui/main/src/app/server/angularConfig.server.ts
- ui/main/src/tests/mocks/configServer.mock.ts
> Refacto i18n service into business code #4053

- src/test/cypress/cypress/integration/UserCard.spec.js
- src/test/resources/bundles/defaultProcess_V1/config.json
- src/test/resources/bundles/messageOrQuestionExample/config.json
- ui/main/src/app/business/model/card.model.ts
- ui/main/src/app/modules/usercard/usercard.component.ts
-  Text : #3769 : when creating a usercard with no startDate , startDate is not well set
> Fix : when creating a usercard with no startDate , startDate is not well set (#3769)

- ui/main/src/app/modules/share/countdown/countdown.spec.ts
> Refacto countdown test to avoid falky test

- src/test/resources/bundles/conferenceAndITIncidentExample/template/usercard_incidentInProgress.handlebars
-  Text : #4156 : IT incident example card : "impacted services" not selected in edit mode
> IT incident example card : "impacted services" not selected in edit mode (#4156)

- src/test/cypress/cypress/integration/SoundNotification.spec.js
- ui/main/src/app/business/model/message.model.ts
- ui/main/src/app/modules/core/alert/alert.component.html
- ui/main/src/app/modules/core/alert/alert.component.scss
- ui/main/src/app/modules/core/alert/alert.component.ts
- ui/main/src/app/services/sound-notification.service.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
Fix #4134
-  Text : #4134 : Play sound and show alert when a new card is not visible in feed
> Play sound and show alert when a new card is not visible in feed (#4134)

- ui/main/src/app/app.module.ts
- ui/main/src/app/business/server/perimeters.server.ts
- ui/main/src/app/business/services/perimeters.service.ts
- ui/main/src/app/modules/admin/components/editmodal/groups/edit-group-modal.component.ts
- ui/main/src/app/modules/admin/components/editmodal/perimeters/edit-perimeter-modal.component.ts
- ui/main/src/app/modules/admin/services/sharing.service.ts
- ui/main/src/app/server/angularPerimeters.server.ts
> Refacto perimeter service into business code #4167

- ui/main/src/app/app.module.ts
- ui/main/src/app/business/server/groups.server.ts
- ui/main/src/app/business/services/application-update.service.ts
- ui/main/src/app/business/services/entities.service.ts
- ui/main/src/app/business/services/groups.service.ts
- ui/main/src/app/modules/activityarea/activityarea.component.ts
- ui/main/src/app/modules/admin/components/editmodal/groups/edit-group-modal.component.ts
- ui/main/src/app/modules/admin/components/editmodal/users/edit-user-modal.component.ts
- ui/main/src/app/modules/admin/components/table/admin-table.directive.ts
- ui/main/src/app/modules/admin/services/sharing.service.ts
- ui/main/src/app/modules/core/application-loading/application-loading.component.ts
- ui/main/src/app/modules/realtimeusers/realtimeusers.component.ts
- ui/main/src/app/server/angularEntities.server.ts
- ui/main/src/app/server/angularGroups.server.ts
> Refacto groups service into business code #4166

- src/docs/asciidoc/reference_doc/template_description.adoc
- ui/main/src/assets/js/opfab.js
-  Text : #4184 : Add a disable/enable method for multiselect component
> Add a disable/enable method for multiselect component (#4184)

- config/dev/common-dev.yml
- config/docker/common-docker.yml
- services/cards-consultation/src/main/java/org/opfab/cards/consultation/services/CardSubscriptionService.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/controllers/CardController.java
- services/users/src/main/java/org/opfab/users/controllers/UserActionLogsController.java
- src/docs/asciidoc/deployment/configuration/configuration.adoc
-  Text : #4181 : Add an option to deactivate user action log
> Add an option to deactivate user action log (#4181)

- ui/main/src/app/app.module.ts
- ui/main/src/app/business/server/adminprocess.server.ts
- ui/main/src/app/business/services/adminprocess.service.ts
- ui/main/src/app/business/services/entities.service.spec.ts
- ui/main/src/app/modules/admin/services/sharing.service.ts
- ui/main/src/app/server/angularAdminProcess.server.ts
> Refacto admin process services into business code #4168

- services/businessconfig/src/main/java/org/opfab/businessconfig/model/UserCardData.java
- services/businessconfig/src/main/modeling/swagger.yaml
- src/docs/asciidoc/resources/migration_guide_to_3.13.adoc
- src/test/api/karate/businessconfig/resources/bundle_api_test/config.json
- src/test/api/karate/businessconfig/resources/bundle_api_test_v2/config.json
- src/test/api/karate/businessconfig/resources/bundle_api_test_with_newState/config.json
- src/test/api/karate/businessconfig/resources/bundle_api_test_without_i18n_file/config.json
- src/test/resources/bundles/conferenceAndITIncidentExample/config.json
- src/test/resources/bundles/defaultProcess_V1/config.json
- src/test/resources/bundles/messageOrQuestionExample/config.json
- src/test/resources/bundles/taskAdvancedExample/config.json
- src/test/resources/bundles/taskExample/config.json
- ui/main/src/app/modules/usercard/usercard.component.ts
-  Text : #4159 : lttdVisible & expirationDateVisible set by default to false
> lttdVisible & expirationDateVisible set by default to false (#4159)

- src/test/cypress/cypress/integration/SoundNotification.spec.js
> Try to avoid falky test on sound notification

- services/businessconfig/src/main/modeling/swagger.yaml
- src/docs/asciidoc/reference_doc/card_notification.adoc
- src/test/cypress/cypress/integration/Acknowledgment.spec.js
- src/test/resources/bundles/conferenceAndITIncidentExample/config.json
- ui/main/src/app/business/model/processes.model.ts
- ui/main/src/app/business/services/user-permissions.service.ts
-  Text : #4185 Added the possibility to never show the acknowledgement footer
> Added the possibility to never show the acknowledgement footer #4185

- src/test/cypress/cypress/integration/UserActionLogs.spec.js
- ui/main/src/app/modules/archives/archives.component.html
- ui/main/src/app/modules/archives/archives.component.scss
- ui/main/src/app/modules/archives/archives.component.ts
- ui/main/src/app/modules/archives/archives.module.ts
- ui/main/src/app/modules/archives/components/archived-card-detail/archived-card-detail.component.html
- ui/main/src/app/modules/archives/components/archived-card-detail/archived-card-detail.component.scss
- ui/main/src/app/modules/archives/components/archived-card-detail/archived-card-detail.component.ts
- ui/main/src/app/modules/useractionlogs/components/useractionlogs-table/useractionlogs-table.component.html
- ui/main/src/app/modules/useractionlogs/components/useractionlogs-table/useractionlogs-table.component.ts
- ui/main/src/app/modules/useractionlogs/useractionlogs.module.ts
Fix #4105
-  Text : #4105 : Open corresponding archive card when clicking on card id in user action logs screen
> Open corresponding archive card when clicking on card id in user action logs screen (#4105)

- ui/main/src/app/services/lightcards/lightcards-feed-filter.service.ts
- ui/main/src/app/services/lightcards/search-service.ts
Fix #4203
I propose to add nothing in release note as the feature was not included in previous release
> Fix notification message not shown when new card is hidden by search filter (#4203)

- ui/main/src/app/modules/admin/components/editmodal/users/edit-user-modal.component.html
- ui/main/src/app/modules/admin/components/editmodal/users/edit-user-modal.component.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
-  Text : #1280 IP address format validator when adding or editing a user in the admin screen
> Added a front end IP address format check #1280

- src/test/api/karate/cards/fetchArchivedCardsWithParamsOrFilter.feature
Fix #4207
Nothing in release note :
> Solve pb with falky karate test in fetchArchivedCardsWithParamsOrFilter (#4207)

- src/test/cypress/cypress/integration/GeoMap.spec.js
- src/test/resources/cards/cypress/geoMap/point_same_location_card1.json
- src/test/resources/cards/cypress/geoMap/point_same_location_card2.json
- src/test/resources/cards/cypress/geoMap/point_same_location_card3.json
- ui/main/src/app/modules/feed/components/map/map.component.html
- ui/main/src/app/modules/feed/components/map/map.component.scss
- ui/main/src/app/modules/feed/components/map/map.component.ts
- ui/main/src/app/modules/share/light-card/light-card.component.html
- ui/main/src/app/modules/share/light-card/light-card.component.ts
> Show popup with list of cards on the geomap (#4126)

- ui/main/src/app/modules/realtimeusers/realtimeusers.component.html
Fix #4096
-  Text : #4096 : Real time screen : vertical scrollbar sometimes without any reason
> Fix Real time screen : vertical scrollbar sometimes without any reason (#4096)

- ui/main/src/app/business/services/card/selectedCard.service.ts
- ui/main/src/app/business/services/lightcards/lightcards-store.service.ts
- ui/main/src/app/modules/card/card.component.html
- ui/main/src/app/modules/card/card.component.ts
- ui/main/src/app/modules/card/components/card-actions/card-actions.component.ts
- ui/main/src/app/modules/card/components/card-body/card-body.component.ts
- ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.ts
- ui/main/src/app/modules/monitoring/monitoring.component.html
- ui/main/src/app/modules/monitoring/monitoring.component.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
Fix #4163 
-  Text : #4163 : Show deleted card message in detail view
> Show deleted card message in detail view (#4163)

- src/test/cypress/package-lock.json
- ui/main/src/app/business/model/processes.model.ts
- ui/main/src/app/business/services/acknowledge.service.spec.ts
- ui/main/src/app/business/services/acknowledge.service.ts
- ui/main/src/app/business/services/process-states-multi-select-options.service.ts
- ui/main/src/app/business/services/processes.service.ts
- ui/main/src/app/business/services/user-permissions.service.ts
- ui/main/src/app/modules/admin/components/cell-renderers/state-rights-cell-renderer.component.ts
- ui/main/src/app/modules/admin/components/editmodal/perimeters/edit-perimeter-modal.component.ts
- ui/main/src/app/modules/admin/components/table/perimeters-table.component.ts
- ui/main/src/app/modules/card/card.component.ts
- ui/main/src/app/modules/card/components/card-header/card-header.component.ts
- ui/main/src/app/modules/feed/components/pinned-cards/pinned-cards.component.ts
- ui/main/src/app/modules/feedconfiguration/feedconfiguration.component.ts
- ui/main/src/app/modules/logging/logging.component.ts
- ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.ts
- ui/main/src/app/modules/monitoring/monitoring.component.ts
- ui/main/src/app/modules/share/light-card/light-card.component.ts
- ui/main/src/app/modules/share/simplified-card-view/simplified-card-view.component.ts
- ui/main/src/app/modules/usercard/selectStateForm/usercard-select-state-form.component.ts
- ui/main/src/app/modules/usercard/usercard.component.ts
- ui/main/src/app/server/angularProcess.server.ts
- ui/main/src/tests/helpers.ts
> Correct mapping of process object

- src/test/cypress/cypress/integration/SoundNotification.spec.js
> Adjust cypress sound test to avoid false positives

- ui/main/src/app/modules/card/card.component.ts
> Fix deleted card message issue (#4242)

- ui/main/src/app/business/services/process-states-multi-select-options.service.ts
Nothing in release notes because the bug was not present in the previous release.
> Archives screen : Filtering by state does not work (#4254)

- src/test/cypress/cypress/integration/SoundNotification.spec.js
> Adjust cypress sound test

- src/test/cypress/cypress/integration/BusinessMenu.spec.js
- src/test/cypress/cypress/integration/Translation.spec.js
- ui/main/src/app/modules/navbar/navbar.component.html
- ui/main/src/app/modules/navbar/navbar.component.scss
- ui/main/src/app/modules/navbar/navbar.component.ts
- ui/main/src/scss/styles.scss
> Improve menu interaction (#4200)

- ui/main/src/app/modules/feed/components/time-line/custom-timeline-chart/custom-timeline-chart.component.html
- ui/main/src/app/modules/feed/components/time-line/custom-timeline-chart/custom-timeline-chart.component.scss
- ui/main/src/app/modules/feed/components/time-line/custom-timeline-chart/custom-timeline-chart.component.ts
> Scrollable card list in popup of timeline (#4251)

- src/test/cypress/cypress/integration/BusinessMenu.spec.js
> update for businessMenu cypress test failing

- src/test/cypress/cypress/integration/BusinessMenu.spec.js
> Fix business menu cypress test

- src/test/cypress/cypress/integration/UserCard.spec.js
- src/test/cypress/cypress/support/userCardCommands.js
> Fix usercard cypress test

- src/test/cypress/cypress/integration/UserCard.spec.js
- src/test/cypress/cypress/support/userCardCommands.js
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
> Clarify message about "authorized IP addresses" (#4246)

- src/test/cypress/cypress/integration/Timeline.spec.js
- ui/main/src/app/modules/feed/components/time-line/custom-timeline-chart/custom-timeline-chart.component.ts
-  Text : #4252 : Update the days' name in the X-axis of the timeline under the "month" setting
> Update the days' name in the X-axis of the timeline under the "month" setting. (#4252)

- tools/spring/spring-utilities/src/main/java/org/opfab/springtools/OpfabCustomExceptionHandler.java
> Do not print stack trace when api return code is 404 (#4235)

- ui/main/src/app/business/model/datetime-ngb.model.ts
> sonarcloud code smells : remove Nested Ternary Operation

- services/cards-consultation/src/main/java/org/opfab/cards/consultation/configuration/webflux/GlobalErrorAttributes.java
- services/cards-consultation/src/main/java/org/opfab/cards/consultation/configuration/webflux/GlobalErrorWebExceptionHandler.java
- services/cards-consultation/src/main/java/org/opfab/cards/consultation/configuration/webflux/IpAddressAuthorizationManager.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/services/CardTranslationService.java
- services/users/src/main/java/org/opfab/users/configuration/oauth2/WebSecurityChecks.java
- tools/spring/spring-oauth2-utilities/src/main/java/org/opfab/springtools/configuration/oauth/WebSecurityChecks.java
> sonarcloud code smells : Replace this instanceof check and cast with 'instanceof String string'

- ui/main/src/app/modules/feedconfiguration/feedconfiguration.component.ts
- ui/main/src/app/server/angularUser.server.ts
> Map json parsing #4270

- CICD/github/setOldMongoKeycloakVersions.sh
- config/docker/docker-compose.yml
- config/keycloak/export/dev-realm-keycloak12.json
> Correct CI test with old keycloak version (#4290)

- ui/main/src/app/business/common/utilities.ts
- ui/main/src/app/modules/share/archives-logging-filters/archives-logging-filters.component.ts
> Sorting strings doesn't take emojis into account anymore #4262

- src/test/cypress/cypress/integration/Archives.spec.js
- src/test/cypress/cypress/integration/UserCard.spec.js
- src/test/cypress/cypress/support/userCardCommands.js
- ui/main/src/app/modules/archives/components/archived-card-detail/archived-card-detail.component.html
- ui/main/src/app/modules/archives/components/archived-card-detail/archived-card-detail.component.scss
- ui/main/src/app/modules/archives/components/archived-card-detail/archived-card-detail.component.ts
- ui/main/src/app/modules/share/simplified-card-view/simplified-card-view.component.ts
- ui/main/src/app/modules/usercard/usercard.component.html
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
> Entities recipients for information : update archive card detail footer (#4264)

- services/cards-consultation/src/main/java/org/opfab/cards/consultation/configuration/mongo/RRuleReadConverter.java
- services/cards-consultation/src/main/java/org/opfab/cards/consultation/model/RRuleConsultationData.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/configuration/mongo/RRuleReadConverter.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/configuration/mongo/RRuleWriterConverter.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/model/RRulePublicationData.java
- services/cards-publication/src/main/modeling/swagger.yaml
- src/test/api/karate/cards/postCardWithRRuleRecurrence.feature
- ui/main/src/app/business/model/card.model.ts
- ui/main/src/app/modules/calendar/calendar.component.ts
Fix #4230 
-  Text : #4230 : Fix task duration not used in calendar
> Fix task duration not used in calendar (#4230)

- src/test/resources/bundles/taskAdvancedExample/template/taskAdvanced.handlebars
-  Text : #4248 : Task advanced example : modify ordinal numbers in the card detail
> Task advanced example : modify ordinal numbers in the card detail (#4248)

- services/cards-consultation/src/main/java/org/opfab/cards/consultation/repositories/ArchivedCardCustomRepositoryImpl.java
- src/docs/asciidoc/dev_env/token.adoc
- tools/spring/spring-oauth2-utilities/src/main/java/org/opfab/springtools/configuration/oauth/UserServiceCache.java
- tools/swagger-spring-generators/src/main/java/org/opfab/generators/OpfabClientGenerator.java
- tools/swagger-spring-generators/src/main/java/org/opfab/generators/OpfabSpringGenerator.java
- tools/user-action-tracing/src/main/java/org/opfab/useractiontracing/repositories/UserActionLogCustomRepositoryImpl.java
> solving some minor code smells

- config/dev/docker-compose.yml
- config/docker/docker-compose.yml
> Updated mongodb to 5.0.15 #4296

- src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc
- ui/main/src/app/modules/feed/components/map/map.component.ts
> Add GeoJSON layer capability to map (#4280)

- ui/main/src/app/modules/core/application-loading/application-loading.component.ts
Fix #4245
-  Text : #4245 : Fix browser stuck for user tryin to connect without authorized IP address
> Fix browser stuck for user tryin to connect without authorized IP address

- ui/main/src/app/business/services/sound-notification.service.ts
-  Text #4313 : Handle remind cards like other cards when hidden from filters
> Handle remind cards like other cards when hidden from filters (#4313)

- src/test/cypress/cypress/integration/Acknowledgment.spec.js
> Fix falky acknowledge cypress test

- config/dev/users-dev.yml
- services/cards-consultation/src/main/java/org/opfab/cards/consultation/repositories/CardCustomRepositoryImpl.java
- services/users/src/main/java/org/opfab/users/scheduledtask/DeleteExpiredLogsScheduler.java
- src/docs/asciidoc/deployment/configuration/configuration.adoc
- src/docs/asciidoc/reference_doc/users_management.adoc
- tools/user-action-tracing/src/main/java/org/opfab/useractiontracing/repositories/UserActionLogCustomRepository.java
- tools/user-action-tracing/src/main/java/org/opfab/useractiontracing/repositories/UserActionLogCustomRepositoryImpl.java
- tools/user-action-tracing/src/main/java/org/opfab/useractiontracing/services/UserActionLogService.java
-  Text : #4180 User action logs older than 61 days (default value) are deleted.
> Added a log cleaner #4180

- services/cards-publication/src/main/java/org/opfab/cards/publication/kafka/auth/AADWorkloadIdentityLoginCallbackHandler.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/kafka/auth/builder/TokenRequestBuilder.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/kafka/auth/builder/TokenRequestBuilderFactory.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/kafka/auth/dto/OAuthBearerTokenImpl.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/kafka/util/BeanUtil.java
- services/cards-publication/src/test/java/org/opfab/cards/publication/kafka/auth/AADWorkloadIdentityLoginCallbackHandlerShould.java
- services/cards-publication/src/test/java/org/opfab/cards/publication/kafka/auth/builder/TokenRequestBuilderFactoryShould.java
- services/cards-publication/src/test/java/org/opfab/cards/publication/kafka/auth/builder/TokenRequestBuilderShould.java
- services/cards-publication/src/test/java/org/opfab/cards/publication/kafka/auth/dto/OAuthBearerTokenImplShould.java
- src/docs/asciidoc/deployment/configuration/configuration.adoc
> Add SASL Oauth AAD capability for kafka (#4300)

- services/users/src/main/java/org/opfab/users/model/UserSettingsData.java
- services/users/src/main/modeling/swagger.yaml
- services/users/src/test/java/org/opfab/users/model/UserSettingsDataShould.java
- services/users/src/test/java/org/opfab/users/services/CurrentUserWithPerimetersServiceShould.java
- src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc
- ui/main/src/app/business/services/reminder/reminder.service.ts
- ui/main/src/app/business/services/rrule-reminder/rrule-reminder.service.ts
- ui/main/src/app/business/services/system-notification.service.ts
- ui/main/src/app/modules/core/application-loading/application-loading.component.ts
- ui/main/src/app/modules/settings/components/settings/settings.component.html
- ui/main/src/app/modules/settings/components/settings/settings.component.ts
- ui/main/src/app/modules/usercard/usercard.component.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
> Use operating system notifications (#3778)

- ui/main/src/app/authentication/auth.service.ts
- ui/main/src/app/router/router-navigation.service.ts
-  Text : #4336 Card with spaces in processInstanceId are not visible in card detail
> Solve isssue : Card with spaces in processInstanceId are not visible in card detail (#4336)

- ui/main/src/app/server/angularProcess.server.ts
-  Text : #4341 Card detail fail to process template for old bundle version
> Solve issue: Card detail fail to process template for old bundle version (#4341)

- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
> Added missing translations

- ui/main/src/app/business/services/system-notification.service.ts
> Add permission request for push notifications (#4340)

- src/test/cypress/cypress/integration/Admin.spec.js
> Correct falky cypress test on admin groups screen

- services/businessconfig/build.gradle
> Fix businessconfig dependencies

- services/users/src/main/java/org/opfab/users/services/UsersService.java
- services/users/src/test/java/org/opfab/users/services/UsersServiceShould.java
> Remove unnecessary message in eventbus

- src/test/cypress/cypress/integration/Admin.spec.js
- src/test/cypress/cypress/integration/Archives.spec.js
- src/test/cypress/cypress/integration/Logging.spec.js
- src/test/cypress/cypress/integration/Monitoring.spec.js
- src/test/cypress/cypress/scripts/cleanDownloadsDir.sh
- src/test/cypress/cypress/support/scriptCommands.js
Fix #4324 
I propose to add nothing in release notes
> Add a script to cleanup cypress download folder (#4324)

- services/cards-consultation/src/main/java/org/opfab/cards/consultation/services/CardRoutingUtilities.java
- services/cards-consultation/src/main/java/org/opfab/cards/consultation/services/CardSubscriptionService.java
- services/cards-consultation/src/test/java/org/opfab/cards/consultation/services/CardRoutingUtilitiesShould.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/services/CardNotificationService.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/services/CardProcessingService.java
> Opimize delete card message sending

- ui/main/src/app/modules/feed/components/map/map.component.html
- ui/main/src/app/modules/feed/components/map/map.component.scss
> Scrollable list in the geomap popup (#4344)

- config/docker/ui-config/web-ui.json
- src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc
- ui/main/src/app/modules/core/alert/alert.component.html
- ui/main/src/app/modules/core/alert/alert.component.scss
- ui/main/src/app/modules/core/alert/alert.component.ts
> Improve alert message for cards hidden by filter (#4367)

- ui/main/src/app/app.component.ts
- ui/main/src/app/business/services/sound-notification.service.ts
-  Text : #4373 Sound notification enhancement
> Sound notification enhancement (#4373)

- services/users/src/main/java/org/opfab/users/configuration/oauth2/OAuth2UsersConfiguration.java
- tools/spring/spring-oauth2-utilities/src/main/java/org/opfab/springtools/configuration/oauth/jwt/JwtProperties.java
-  Text : #4345 : First and last name for new user in keycloak are not set properly in opfab
> First and last name for new user in keycloak are not set properly in opfab (#4345)

- src/test/cypress/cypress/integration/Resilience.spec.js
> Resilience test : add more time for rabbitMQ to be fully reloaded

- services/businessconfig/src/main/java/org/opfab/businessconfig/services/ProcessesService.java
> Fixed the path of a delete function that was forgotten

- services/cards-publication/src/test/java/org/opfab/cards/publication/mocks/CardRepositoryMock.java
- services/cards-publication/src/test/java/org/opfab/cards/publication/services/CardProcessServiceShould.java
> Refacto delete test

- ui/main/src/app/modules/share/archives-logging-filters/archives-logging-filters.component.html
- ui/main/src/app/modules/share/archives-logging-filters/archives-logging-filters.component.ts
-  Text : #4349 : The "Process" drop-down list is not displayed when a user has no rights on any process
> The "Process" drop-down list is not displayed when a user has no rights on any process (#4349)

- config/dev/users-dev.yml
- config/docker/users-docker.yml
- config/keycloak/export/dev-users-0.json
- services/cards-consultation/src/main/java/org/opfab/cards/consultation/configuration/mongo/LightCardReadConverter.java
- services/cards-consultation/src/main/java/org/opfab/cards/consultation/repositories/CardCustomRepositoryImpl.java
- Nothing in release note as it is an update on already merged feature
> Read LigthCard entityRecipients, entityRecipientsForInformation and entitiesAcks fields from mongo (#4358)

- src/test/api/karate/cards/postCardWithProcessAndOrStateUnexisting.feature
> Add a retry to avoid falky karate test

- src/docs/asciidoc/community/index.adoc
see https://blog.alexdevero.com/truthy-falsy-values-in-javascript/
> Remove coding rule not recommanded anymore (sonarCloud)

- ui/main/src/app/modules/logging/components/logging-table/logging-table.component.ts
-  Text : #4399 Adjust column width in logging screen
> Adjust column width in logging screen (#4399)

- src/docs/asciidoc/community/index.adoc
- ui/main/src/app/modules/usercard/recipientForm/usercard-recipients-form.component.ts
- ui/main/src/app/modules/usercard/usercard.component.ts
> remove unecessary js guideline and correct concerned code

- src/docs/asciidoc/reference_doc/template_description.adoc
- src/test/cypress/cypress/integration/CardDetail.spec.js
- src/test/resources/bundles/cypress/template/kitchenSink.handlebars
- ui/main/src/app/modules/core/application-loading/application-loading.component.ts
- ui/main/src/assets/js/opfab.js
Fix #4410 
-  Text : #4410 : Add a js method for template to open a specific card in the feed
> Add a js method for template to open a specific card in the feed (#4410)

- ui/main/src/app/modules/feed/components/time-line/custom-timeline-chart/custom-timeline-chart.component.ts
-  Text : #4318 Unexpected error message on the console from the card feed tab
> Solve issue : Unexpected error message on the console from the card feed tab

- services/cards-consultation/src/main/java/org/opfab/cards/consultation/repositories/ArchivedCardCustomRepositoryImpl.java
> Log adjustment to avoid unecessary log in info mode

- ui/main/src/app/modules/dashboard/dashboard.component.html
- ui/main/src/app/modules/feed/components/time-line/custom-timeline-chart/custom-timeline-chart.component.html
- ui/main/src/app/modules/feed/components/time-line/custom-timeline-chart/custom-timeline-chart.component.ts
- ui/main/src/scss/styles.scss
Nothing in release note as it was not present in previous release
> Fix Timeline cards scrollbar in popover unusable (#4431)

- services/businessconfig/src/main/java/org/opfab/businessconfig/configuration/oauth2/WebSecurityConfiguration.java
- services/businessconfig/src/main/java/org/opfab/businessconfig/controllers/BusinessconfigController.java
- services/businessconfig/src/main/java/org/opfab/businessconfig/services/ProcessesService.java
- services/businessconfig/src/main/modeling/swagger.yaml
- src/test/api/karate/businessconfig/getBusinessData.feature
- src/test/resources/deleteAllBusinessData.sh
-  Text : #4408 Added an API method to delete all businessdata files
> Added an API method to delete all businessdata files #4408

- src/test/cypress/cypress/integration/ActivityArea.spec.js
- ui/main/src/app/business/view/activityarea/activitearea.view.spec.ts
- ui/main/src/app/business/view/activityarea/activityarea.view.ts
- ui/main/src/app/business/view/activityarea/activityareaPage.ts
- ui/main/src/app/modules/activityarea/activityarea.component.html
- ui/main/src/app/modules/activityarea/activityarea.component.ts
- ui/main/src/tests/mocks/entitiesServer.mock.ts
- ui/main/src/tests/mocks/settingsServer.mock.ts
- ui/main/src/tests/mocks/userServer.mock.ts
-  Text : #4439 Remove group column from activity area screen choice
> Remove group column from activity area screen + refacto

- services/cards-publication/src/main/java/org/opfab/cards/publication/controllers/CustomExceptionHandler.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/services/CardProcessingService.java
- services/cards-publication/src/test/java/org/opfab/cards/publication/services/CardProcessServiceShould.java
- tools/spring/spring-utilities/src/main/java/org/opfab/springtools/OpfabCustomExceptionHandler.java
-  Text :  #4459 Adjust log for card publication service.
> Adjust log for card publication service

- services/cards-publication/src/main/java/org/opfab/cards/publication/services/CardProcessingService.java
- services/cards-publication/src/test/java/org/opfab/cards/publication/services/CardProcessServiceShould.java
Fix #4339 
-  Text : #4339 :  Check forbidden characters in process and processInstanceId
> Check forbidden characters in process and processInstanceId (4339)

- build.gradle
- services/businessconfig/src/main/docker/Dockerfile
- services/cards-consultation/src/main/docker/Dockerfile
- services/cards-publication/src/main/docker/Dockerfile
- services/external-devices/build.gradle
- services/external-devices/src/main/docker/Dockerfile
- services/services.gradle
- services/users/src/main/docker/Dockerfile
- src/docs/asciidoc/dev_env/env_variables.adoc
- src/docs/asciidoc/dev_env/launch_dev.adoc
- src/docs/asciidoc/dev_env/requirements.adoc
- src/test/dummyModbusDevice/dummyModbusDevice.gradle
- src/test/externalApp/externalApp.gradle
- src/test/externalApp/src/main/docker/Dockerfile
- web-ui/src/main/docker/Dockerfile
- web-ui/web-ui.gradle
-  Text : #4486  Simplify proxy configuration for docker images build and improve documentation regarding proxy
> Simplify proxy configuration for docker images build and improve documentation regarding proxy

- services/businessconfig/src/main/java/org/opfab/businessconfig/model/UserCardData.java
- services/businessconfig/src/main/modeling/swagger.yaml
- src/docs/asciidoc/reference_doc/user_cards.adoc
- src/docs/asciidoc/resources/migration_guide_to_3.15.adoc
- src/test/api/karate/businessconfig/getABusinessconfig.feature
- src/test/api/karate/businessconfig/resources/bundle_api_test_v2/config.json
- src/test/cypress/cypress/integration/UserCard.spec.js
- src/test/resources/bundles/defaultProcess_V1/config.json
- ui/main/src/app/business/model/processes.model.ts
- ui/main/src/app/modules/usercard/recipientForm/usercard-recipients-form.component.ts
Fix #2731 
-  Text : #2731 : Remove deprecated use of recipientList in state definition
> Remove deprecated use of recipientList in state definition (#2731)

- services/cards-publication/src/main/java/org/opfab/cards/publication/services/CardProcessingService.java
> Check forbidden chars using String.contains() (#4339)

- services/businessconfig/src/main/java/org/opfab/businessconfig/model/EntitiesGroupsData.java
- services/businessconfig/src/main/modeling/swagger.yaml
- services/businessconfig/src/test/data/realtimescreens.json
- services/businessconfig/src/test/java/org/opfab/businessconfig/controllers/GivenAdminUserBusinessconfigControllerShould.java
- src/docs/asciidoc/reference_doc/users_management.adoc
- src/docs/asciidoc/resources/migration_guide_to_3.15.adoc
- src/test/api/karate/businessconfig/resources/realtimescreens1.json
- src/test/api/karate/businessconfig/resources/realtimescreens2.json
- src/test/api/karate/businessconfig/uploadAndGetRealTimeScreensFile.feature
- src/test/cypress/cypress/integration/1-RealTimeUsers.spec.js
- src/test/resources/realTimeScreens/realTimeScreens.json
- ui/main/src/app/business/model/real-time-screens.model.ts
- ui/main/src/app/modules/realtimeusers/realtimeusers.component.html
- ui/main/src/app/modules/realtimeusers/realtimeusers.component.ts
-  Text : #4435 : Remove use of groups in realtime screen
> Remove use of groups in realtime screen (#4435)

- src/test/cypress/cypress/integration/Timeline.spec.js
> Correct falky timeline test

- config/docker/ui-config/ui-menu.json
- src/docs/asciidoc/reference_doc/ui_customization.adoc
- src/docs/asciidoc/resources/index.adoc
- src/docs/asciidoc/resources/migration_guide_to_3.15.adoc
- src/docs/asciidoc/resources/migration_guide_to_4.0.adoc
- src/test/cypress/cypress/integration/CoreMenuConfigurationTests.spec.js
- src/test/resources/uiConfig/ui-menu-not-defined.json
- src/test/resources/uiConfig/ui-menu-not-visible-to-all.json
- src/test/resources/uiConfig/ui-menu-only-admin-group.json
- src/test/resources/uiConfig/ui-menu-visible-to-all.json
- src/test/resources/uiConfig/updateCoreMenu.sh
- ui/main/src/app/business/model/menu.model.ts
- ui/main/src/app/business/services/config.service.spec.ts
- ui/main/src/app/business/services/config.service.ts
- ui/main/src/app/business/services/menu.service.ts
- ui/main/src/app/modules/core/application-loading/application-loading.component.ts
- ui/main/src/app/modules/navbar/menus/menu-link/menu-link.component.html
- ui/main/src/app/modules/navbar/menus/menu-link/menu-link.component.ts
- ui/main/src/app/modules/navbar/navbar.component.html
- ui/main/src/app/modules/navbar/navbar.component.ts
- ui/main/src/tests/helpers.ts
-  Text : #4442 : Add a more customizable navigation bar menu
> Add a more customizable navbar menu (#4442)

- ui/main/src/app/modules/navbar/menus/menu-link/menu-link.component.html
- ui/main/src/app/modules/navbar/menus/menu-link/menu-link.component.scss
- ui/main/src/app/modules/navbar/menus/menu-link/menu-link.component.ts
- ui/main/src/app/modules/navbar/navbar.component.html
- ui/main/src/app/modules/navbar/navbar.component.ts
> Sort the core menus in the order of the ui-menu.json conf file (#4505)

- src/test/cypress/cypress/integration/Timeline.spec.js
- ui/main/src/app/modules/feed/components/time-line/custom-timeline-chart/custom-timeline-chart.component.html
> Adjust timeline cypress test to avoid falky tests

- src/docs/asciidoc/deployment/index.adoc
- src/test/resources/logs/getLogs.sh
- src/test/resources/logs/setLogs.sh
-  Text : #4454:  Add scripts to change log level on services
> Add scripts to change log level on services (#4454)

- services/businessconfig/src/main/java/org/opfab/businessconfig/configuration/json/BusinessconfigModule.java
- services/businessconfig/src/main/java/org/opfab/businessconfig/model/EntitiesTreeData.java
- services/businessconfig/src/main/java/org/opfab/businessconfig/model/UserCardData.java
- services/businessconfig/src/main/modeling/swagger.yaml
- src/docs/asciidoc/reference_doc/user_cards.adoc
- src/test/cypress/cypress/integration/UserCard.spec.js
- src/test/resources/bundles/defaultProcess_V1/config.json
- ui/main/src/app/business/model/processes.model.ts
- ui/main/src/app/business/services/entities.service.ts
- ui/main/src/app/modules/usercard/recipientForm/usercard-recipients-form.component.ts
- ui/main/src/app/modules/usercard/selectStateForm/usercard-select-state-form.component.ts
- ui/main/src/app/modules/usercard/usercard.component.ts
Fix #4494
-  Text : #4494: Add possibility to restrict the list of entities for sending card (#4494)
> Restrict the list of entities for sending card (#4494)

- services/businessconfig/src/main/java/org/opfab/businessconfig/model/ProcessStatesData.java
- services/businessconfig/src/main/modeling/swagger.yaml
- src/docs/asciidoc/reference_doc/user_cards.adoc
- src/test/api/karate/businessconfig/getABusinessconfig.feature
- src/test/api/karate/businessconfig/resources/bundle_api_test_v2/config.json
- src/test/cypress/cypress/integration/UserCard.spec.js
- src/test/cypress/cypress/support/cardCommands.js
- src/test/cypress/cypress/support/feedCommands.js
- src/test/cypress/cypress/support/userCardCommands.js
- src/test/resources/bundles/conferenceAndITIncidentExample/config.json
- ui/main/src/app/business/model/processes.model.ts
- ui/main/src/app/business/services/user.service.ts
- ui/main/src/app/modules/card/components/card-actions/card-actions.component.html
- ui/main/src/app/modules/card/components/card-actions/card-actions.component.scss
- ui/main/src/app/modules/card/components/card-actions/card-actions.component.ts
- ui/main/src/app/modules/usercard/selectStateForm/usercard-select-state-form.component.ts
- ui/main/src/app/modules/usercard/usercard.component.html
- ui/main/src/app/modules/usercard/usercard.component.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
- ui/main/src/assets/images/icons/create-copy.svg
-  Text : #4448 : Create usercard as a copy
> Create usercard as a copy (#4448)

- ui/main/src/app/modules/feed/components/map/map.component.ts
Nothing in release note (Bug was not present in previous release)
> Solve issue : geomap does not switch to day/night mode (#4529)

- src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc
> update for typos

- ui/main/src/app/modules/useractionlogs/useractionlogs.component.html
> User action logs screen : adjust space between fields and message (#4535)

- ui/main/src/app/modules/admin/components/table/admin-table.directive.html
> Adjust design in processes management screen (#4544)

- ui/main/src/app/modules/dashboard/dashboard.component.ts
> Exception in console when switching from dashboard to feed screen (#4550)

- ui/main/src/app/business/view/dashboard/dashboard.view.ts
> Remove debug logs in dashboard.view.ts (#4551)

- src/docs/asciidoc/reference_doc/card_structure.adoc
> Correct documentation regarding uid of card (#4532)

- src/docs/asciidoc/reference_doc/card_examples.adoc
> Documentation refers to a non-existent process (#4538)

- ui/main/src/app/modules/dashboard/dashboard.component.html
> Dashboard : add a message if the user has no process/state (#4546)

- ui/main/src/app/business/store/router.store.ts
- ui/main/src/app/modules/card/components/card-actions/card-actions.component.ts
- ui/main/src/app/modules/dashboard/dashboard.component.ts
-  Text : #4542 : Dashboard : unexpected redirection to the feed after editing and updating a card
> Dashboard : unexpected redirection to the feed after editing and updating a card (#4542)

- build.gradle
- node-services/cards-external-diffusion/src/domain/server-side/opfabServicesInterface.ts
- node-services/cards-external-diffusion/tests/opfabservicesInterface.test.ts
> Add code coverage in sonarCloud for cards-diffusion service (#4520)

- services/users/src/main/java/org/opfab/users/model/UserSettingsData.java
- services/users/src/main/modeling/swagger.yaml
- services/users/src/test/java/org/opfab/users/model/UserSettingsDataShould.java
- services/users/src/test/java/org/opfab/users/services/CurrentUserWithPerimetersServiceShould.java
- services/users/src/test/java/org/opfab/users/services/UserSettingsServiceShould.java
- src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc
- src/test/api/karate/users/patchUserSettings.feature
- ui/main/src/app/modules/settings/components/settings/settings.component.html
- ui/main/src/app/modules/settings/components/settings/text-setting/text-setting.component.html
-  Text : #4547 : Remove description field in user settings
> Remove description field in user settings (#4547)

- src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc
- src/test/cypress/cypress/integration/Timeline.spec.js
- src/test/resources/send6TestCards.sh
- ui/main/src/app/server/angularOpfabEventStream.server.ts
> Miscellaneous fixes

- services/cards-consultation/src/main/java/org/opfab/cards/consultation/services/CardRoutingUtilities.java
- services/cards-consultation/src/test/java/org/opfab/cards/consultation/services/CardRoutingUtilitiesShould.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/model/CardOperationData.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/model/CardPublicationData.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/services/CardNotificationService.java
> Remove userRecipientsIds, groupRecipientsIds and entityRecipientsIds from CardOperation class

- config/docker/ui-config/web-ui.json
- src/docs/asciidoc/deployment/configuration/configuration.adoc
- src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc
- src/test/cypress/cypress/integration/UserCard.spec.js
- ui/main/src/app/modules/usercard/usercard.component.html
- ui/main/src/app/modules/usercard/usercard.component.ts
-  Text : #4447 Added connection status circle next to entities in card preview
> Added connection circles for entities in card preview #4447

- build.gradle
- node-services/cards-external-diffusion/build.gradle
> Fix sonar coverage settings (#FE-4520)

- node-services/cards-external-diffusion/build.gradle
- node-services/cards-external-diffusion/docker/Dockerfile
> Fix docker task for cards-external-diffusion

- build.gradle
> Fix sonar lcov files path (#4520)

- ui/main/src/app/modules/share/archives-logging-filters/archives-logging-filters.component.ts
- ui/main/src/app/modules/useractionlogs/components/useractionlogs-filters/useractionlogs-filters.component.ts
Fix #FE-4536
-  Text : #FE-4536 : Fix datepicker reset
> Fix datepicker reset (#FE-4536)

- services/cards-consultation/src/main/java/org/opfab/cards/consultation/repositories/CardCustomRepositoryImpl.java
- services/cards-consultation/src/main/java/org/opfab/cards/consultation/repositories/UserUtilitiesCommonToCardRepository.java
- services/cards-consultation/src/main/java/org/opfab/cards/consultation/services/CardRoutingUtilities.java
- services/cards-consultation/src/test/java/org/opfab/cards/consultation/services/CardRoutingUtilitiesShould.java
- src/docs/asciidoc/reference_doc/user_cards.adoc
- src/test/cypress/cypress/support/userCardCommands.js
- ui/main/src/app/business/model/card.model.ts
- ui/main/src/app/business/services/card.service.ts
- ui/main/src/app/business/services/lightcards/lightcards-store.service.ts
- ui/main/src/app/modules/usercard/usercard.component.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
-  Text : #4573 :  See card sent by your entities
> See card sent by your entities (#4573)

- services/businessconfig/src/main/java/org/opfab/businessconfig/services/ProcessesService.java
- src/test/api/karate/businessconfig/resources/bundle_api_test_with_forbidden_processId/config.json
- src/test/api/karate/businessconfig/resources/bundle_api_test_with_forbidden_processId/css/style.css
- src/test/api/karate/businessconfig/resources/bundle_api_test_with_forbidden_processId/i18n.json
- src/test/api/karate/businessconfig/resources/bundle_api_test_with_forbidden_processId/template/template.handlebars
- src/test/api/karate/businessconfig/resources/packageBundles.sh
- src/test/api/karate/businessconfig/uploadBundle.feature
-  Text : #4525 : Control the process id in config.json files
> Control the process id in config.json files (#4525)

- ui/main/src/assets/i18n/en.json
> Changed an abbreviation for the complete word

- ui/main/src/app/business/services/grouped-cards.service.ts
- ui/main/src/app/modules/share/light-card/grouped-card-list/grouped-card-list.component.html
- ui/main/src/app/modules/share/light-card/grouped-card-list/grouped-card-list.component.ts
-  Text : #3629 : Optimize grouping feed feature when a lot of cards are present
> Grouped cards improvement when too many cards (#3629)

- src/test/api/karate/cards/cards.feature
- src/test/api/karate/cards/userCards.feature
- src/test/externalApp/src/main/java/org/opfab/externalapp/service/ExternalAppServiceImpl.java
> Refactor test with external application (#4541)

- ui/main/src/app/modules/card/components/card-body/card-body.component.ts
-  Text : #4537 Removed scrollbar and fullscreen button from dashboard cards
> Removed scrollbar and fullscreen button from dashboard cards #4537

- ui/main/src/app/business/services/acknowledge.service.ts
- ui/main/src/app/modules/card/components/card-ack/card-ack.component.ts
- ui/main/src/app/modules/feed/components/card-list/card-list.component.ts
> Refacto to avoid acknowlegde  service to depend from lightcard store service

- src/test/resources/bundles/messageOrQuestionExample/config.json
- ui/main/src/app/modules/card/components/card-body/card-body.component.ts
-  Text : #4608 Fixed the showDetailCardHeader condition
> Fixed the showDetailCardHeader test #4608

- ui/main/src/app/modules/share/timeline-buttons/timeline-buttons.component.html
-  Text : #4533 Fixed the date format when 'Day' is selected on the timeline while hidden
> Changed the format of date when 'Day' is selected on the timeline while hidden #4533

- services/businessconfig/src/main/java/org/opfab/businessconfig/controllers/BusinessconfigController.java
- tools/generic/utilities/src/main/java/org/opfab/utilities/StringUtils.java
- tools/generic/utilities/src/test/java/org/opfab/utilities/StringUtilsShould.java
-  Text : #4636 : Sanitize inputs in business config service
> Sanitize inputs in business config service (#4636)

- ui/main/src/app/modules/usercard/usercard.component.ts
> Solve sonar issue Prefer using nullish coalescing operator (#4650)

- ui/main/src/app/business/services/card/handlebars.service.spec.ts
- ui/main/src/app/business/services/card/handlebars.service.ts
- ui/main/src/app/business/services/lightcards/grouped-cards.service.ts
- ui/main/src/app/modules/archives/components/archived-card-detail/archived-card-detail.component.ts
> Solve sonar issues regarding string sort function (#4635)

- ui/main/src/app/business/services/cached-crud-service.ts
- ui/main/src/app/business/services/global-style.service.ts
- ui/main/src/app/business/view/activityarea/activityarea.view.ts
- ui/main/src/app/modules/feed/components/map/map.component.ts
- ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.ts
- ui/main/src/app/modules/usercard/usercard.component.ts
> Solves sonar issues regarding optional chain expression (#4656)

- ui/main/src/app/modules/admin/components/editmodal/users/edit-user-modal.component.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
-  Text : #4640 : Do not authorize space in login and minimum length 2 characters
> Do not authorize space in login (#4640)

- src/test/cypress/cypress/integration/Timeline.spec.js
> Add a retry in cypress timeline test to avoid falky test

- ui/main/src/app/business/model/datetime-ngb.model.ts
> Solve sonar issue useless assignment (#4670)

- ui/main/src/app/authentication/auth-handler.ts
> Solve sonar issue Do not use Error to declare a variable (#4674)

- ui/main/src/app/modules/admin/components/table/admin-table.directive.ts
- ui/main/src/app/modules/archives/archives.component.ts
- ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.ts
> Solve sonar issues Unexpected constant binary expression (#4673)

- src/test/cypress/cypress/integration/BusinessMenu.spec.js
> Add a retry to solve falky test with business menu

- config/docker/docker-compose.yml
- config/docker/node-services.json
- node-services/cards-external-diffusion/config/default-docker.json
- node-services/cards-external-diffusion/config/default.json
- node-services/cards-reminder/config/default-docker.json
- node-services/cards-reminder/config/default.json
- src/docs/asciidoc/deployment/port_table.adoc
- src/test/api/karate/cards-external-diffusion/cardsExternalDiffusion.feature
Fix #4663
I propose to add nothing in release notes as this service it was not in previous releas
> Change port table for cards-reminder and cards-external-diffusion (#4663)

- ui/main/src/app/business/server/businessData.server.ts
- ui/main/src/app/business/services/businessconfig/businessdata.service.ts
- ui/main/src/app/modules/admin/admin-routing.module.ts
- ui/main/src/app/modules/admin/admin.component.html
- ui/main/src/app/modules/admin/admin.module.ts
- ui/main/src/app/modules/admin/components/cell-renderers/action-cell-renderer.component.html
- ui/main/src/app/modules/admin/components/cell-renderers/action-cell-renderer.component.ts
- ui/main/src/app/modules/admin/components/confirmation-dialog/confirmation-dialog.component.html
- ui/main/src/app/modules/admin/components/table/admin-table.directive.html
- ui/main/src/app/modules/admin/components/table/admin-table.directive.scss
- ui/main/src/app/modules/admin/components/table/admin-table.directive.ts
- ui/main/src/app/modules/admin/components/table/businessData-table.component.ts
- ui/main/src/app/modules/admin/components/table/entities-table.component.ts
- ui/main/src/app/modules/admin/components/table/groups-table.component.ts
- ui/main/src/app/modules/admin/components/table/perimeters-table.component.ts
- ui/main/src/app/modules/admin/components/table/users-table.component.ts
- ui/main/src/app/modules/admin/services/sharing.service.ts
- ui/main/src/app/server/angularBusinessData.server.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
-  Text : #4620 Added Business Data Management Table in the administration tab
> Added Business Data Management Table #4620

- node-services/cards-external-diffusion/jest.config.js
- node-services/cards-reminder/jest.config.js
> Adjust node services test coverage

- src/test/cypress/cypress/integration/Acknowledgment.spec.js
- src/test/cypress/cypress/integration/Admin.spec.js
- src/test/cypress/cypress/integration/Archives.spec.js
- src/test/cypress/cypress/integration/Logging.spec.js
- src/test/cypress/cypress/integration/ResponseCard.spec.js
- src/test/cypress/cypress/integration/Translation.spec.js
- src/test/cypress/cypress/integration/UserActionLogs.spec.js
- src/test/cypress/cypress/integration/UserCard.spec.js
- ui/main/package-lock.json
- ui/main/package.json
> Upgrade virtual-select to version 1.0.39

- ui/main/src/app/business/services/acknowledge.service.spec.ts
> Add some unit test in acknowledge.service.spec.ts (#4645)

- services/users/src/main/java/org/opfab/users/configuration/oauth2/OAuth2UsersConfiguration.java
- services/users/src/main/java/org/opfab/users/model/UserData.java
- services/users/src/main/modeling/swagger.yaml
- services/users/src/test/java/org/opfab/users/services/EntitiesServiceShould.java
- services/users/src/test/java/org/opfab/users/services/GroupsServiceShould.java
- services/users/src/test/java/org/opfab/users/services/PerimetersServiceShould.java
- services/users/src/test/java/org/opfab/users/services/UsersServiceShould.java
- src/test/api/karate/users/createUsers.feature
- src/test/api/karate/users/updateExistingUser.feature
- src/test/cypress/cypress/integration/Admin.spec.js
- tools/spring/spring-test-utilities/src/main/java/org/opfab/springtools/configuration/test/WithMockOpFabUser.java
- tools/spring/spring-test-utilities/src/main/java/org/opfab/springtools/configuration/test/WithMockOpFabUserReactive.java
- ui/main/src/app/business/model/user.model.ts
- ui/main/src/app/business/services/acknowledge.service.spec.ts
- ui/main/src/app/business/view/activityarea/activityarea.view.spec.ts
- ui/main/src/app/modules/admin/components/editmodal/users/edit-user-modal.component.html
- ui/main/src/app/modules/admin/components/editmodal/users/edit-user-modal.component.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
-  Text : #4641 When adding or editing a user, it's possible to see, add or edit a comment about the user
> Added a comment attribute to users #4641

- web-ui/src/main/docker/Dockerfile
> Remove unused package in web-ui alpine for security reasons

- .github/workflows/anchore-analysis.yml
> Adjust anchor security tool configuration

- src/test/resources/bundles/taskExample/template/usercard_task.handlebars
> Adjust date on task usercard for cypress test

- config/docker/node-services.json
- node-services/cards-external-diffusion/config/default-docker.json
- node-services/cards-external-diffusion/config/default.json
- node-services/cards-external-diffusion/src/cardsExternalDiffusion.ts
- node-services/cards-external-diffusion/src/domain/application/cardsDiffusionControl.ts
- node-services/cards-external-diffusion/src/domain/client-side/cardsExternalDiffusionService.ts
- node-services/cards-external-diffusion/src/domain/server-side/cardsExternalDiffusionOpfabServicesInterface.ts
- node-services/cards-external-diffusion/tests/cardsDiffusionControl.test.ts
- node-services/cards-external-diffusion/tests/opfabservicesInterface.test.ts
- node-services/cards-reminder/src/cardsReminder.ts
- node-services/cards-reminder/src/domain/application/cardsReminderControl.ts
- node-services/cards-reminder/src/domain/client-side/cardsRemiderService.ts
- node-services/cards-reminder/src/domain/server-side/cardsReminderOpfabServicesInterface.ts
- node-services/common/src/common/client-side/authenticationService.ts
- node-services/common/src/common/server-side/opfabServicesInterface.ts
- node-services/supervisor/config/default-docker.json
- node-services/supervisor/config/default.json
- node-services/supervisor/src/connectionSupervisor.ts
- node-services/supervisor/src/domain/application/acknowledgmentChecker.ts
- node-services/supervisor/src/domain/application/connectionChecker.ts
- node-services/supervisor/src/domain/client-side/supervisorService.ts
- node-services/supervisor/tests/acknowledgementChecker.test.ts
- node-services/supervisor/tests/connectionChecker.test.ts
- node-services/supervisor/tests/opfabservicesInterface.test.ts
- src/test/api/karate/cards-external-diffusion/cardsExternalDiffusion.feature
Fix #4450
-  Text : #4450 : check user permission when posting a new config for supervisor and cards-external-diffusion services
> Check user permission when posting a new config for supervisor and cards-external-diffusion services (#4450)

- src/test/cypress/cypress/integration/UserCard.spec.js
> Avoid falky cypress test on usercard

- config/docker/node-services.json
- node-services/cards-external-diffusion/config/default-docker.json
- node-services/cards-external-diffusion/config/default.json
- node-services/cards-external-diffusion/src/domain/application/cardsDiffusionControl.ts
- node-services/cards-external-diffusion/src/domain/client-side/cardsExternalDiffusionService.ts
- node-services/cards-external-diffusion/src/domain/server-side/cardsExternalDiffusionOpfabServicesInterface.ts
- node-services/cards-external-diffusion/tests/cardsDiffusionControl.test.ts
Fix #4783 
Nothing in release note :
> Card diffusion service : add opfabUrlInMailContent as config parameter (#4783)

- .github/workflows/anchore-analysis.yml
> Launch anchor analysis during the night

- bin/load_environment_light.sh
> Adjust java version

- ui/main/src/app/business/buildInTemplates/message/messageUserCardTemplateView.spec.ts
- ui/main/src/app/business/buildInTemplates/question/card/questionCardTemplateView.spec.ts
- ui/main/src/app/business/buildInTemplates/question/usercard/questionUserCardTemplateView.spec.ts
> Remove fdescribe

- .github/workflows/main.yml
- .github/workflows/verify_copyright.yml
- CICD/github/licenceHeaderCheck.sh
> Check copyright header on each push (#4739)

- node-services/cards-reminder/tests/rruleReminderUtils.test.ts
> Avoid warning regarding date format on build

- services/cards-publication/src/main/java/org/opfab/cards/publication/configuration/Services.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/ratelimiter/CardSendingLimiter.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/ratelimiter/CustomClock.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/ratelimiter/DefaultClock.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/services/CardProcessingService.java
- services/cards-publication/src/test/java/org/opfab/cards/publication/ratelimiter/CardSendingLimiterShould.java
- services/cards-publication/src/test/java/org/opfab/cards/publication/ratelimiter/TestClock.java
- services/cards-publication/src/test/java/org/opfab/cards/publication/services/CardProcessServiceShould.java
- src/docs/asciidoc/deployment/configuration/configuration.adoc
- src/docs/asciidoc/deployment/index.adoc
> Rate limiter for card sending (#4329)

- services/businessconfig/src/main/java/org/opfab/businessconfig/configuration/oauth2/WebSecurityConfiguration.java
- services/businessconfig/src/test/java/org/opfab/businessconfig/application/WebSecurityConfiguration.java
- services/cards-consultation/src/main/java/org/opfab/cards/consultation/configuration/webflux/WebSecurityConfiguration.java
- services/cards-consultation/src/test/java/org/opfab/cards/consultation/application/configuration/WebSecurityConfiguration.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/configuration/oauth2/WebSecurityConfiguration.java
- services/external-devices/src/main/java/org/opfab/externaldevices/configuration/oauth2/WebSecurityConfiguration.java
- services/users/src/main/java/org/opfab/users/configuration/oauth2/WebSecurityConfiguration.java
- src/test/externalApp/src/main/java/org/opfab/externalapp/config/WebSecurityConfiguration.java
> Remove use of deprecated methods of HttpSecurity (#4765)

- services/cards-publication/src/main/java/org/opfab/cards/publication/model/ArchivedCardPublicationData.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/model/CardPublicationData.java
… (#4689)
-  Text : #4689 : Add a mongoDB index for field parentCardId (in cards and in archives)
> Add a mongoDB index for field parentCardId (in cards and in archives) (#4689)

- ui/main/src/app/modules/navbar/info/info.component.html
- ui/main/src/app/modules/navbar/info/info.component.ts
> Add a tooltip to show user connected entities (#4776)

- node-services/cards-external-diffusion/package-lock.json
- node-services/cards-external-diffusion/package.json
- node-services/cards-reminder/package-lock.json
- node-services/cards-reminder/package.json
- node-services/common/package-lock.json
- node-services/common/package.json
- node-services/common/src/common/server-side/eventBus.ts
- node-services/supervisor/package-lock.json
- node-services/supervisor/package.json
> Update dependency amqp-connection-manager to v4.1.14

- services/cards-consultation/src/main/java/org/opfab/cards/consultation/configuration/webflux/WebSecurityConfiguration.java
- services/users/src/main/java/org/opfab/users/configuration/oauth2/WebSecurityConfiguration.java
> Remove use of deprecated methods of HttpSecurity (#4837)

- config/docker/node-services.json
- node-services/supervisor/config/default-docker.json
- node-services/supervisor/config/default.json
- node-services/supervisor/src/domain/application/acknowledgmentChecker.ts
- node-services/supervisor/src/domain/client-side/configDTO.ts
- node-services/supervisor/src/domain/client-side/configService.ts
- node-services/supervisor/src/domain/client-side/supervisorService.ts
- node-services/supervisor/tests/acknowledgementChecker.test.ts
- src/docs/asciidoc/deployment/configuration/configuration.adoc
> typo errors in acknowledgment field names in node services

- ui/main/src/app/modules/admin/components/cell-renderers/state-rights-cell-renderer.component.html
- ui/main/src/app/modules/card/components/card-header/card-header.component.html
- ui/main/src/app/modules/feed/components/card-list/filters/filters.component.html
- ui/main/src/app/modules/monitoring/components/cell-renderers/answer-cell-renderer.component.html
- ui/main/src/app/modules/monitoring/monitoring.component.html
- ui/main/src/app/modules/navbar/info/info.component.html
- ui/main/src/app/modules/navbar/navbar.component.html
- ui/main/src/app/modules/share/archives-logging-filters/archives-logging-filters.component.html
- ui/main/src/app/modules/share/countdown/countdown.component.html
- ui/main/src/app/modules/share/light-card/light-card.component.html
- ui/main/src/app/modules/share/timeline-buttons/timeline-buttons.component.html
- ui/main/src/scss/styles.scss
> Tool tips does not always appear on top right (agenda / usercard ...) (#4830)

- src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc
> delete of 'sendCardsByEmail' and 'email' fields of web-ui doc

- ui/main/src/app/server/angularConfig.server.ts
> Fix ui locale loading in dev mode

- config/dev/cards-consultation-dev.yml
- services/cards-consultation/src/main/java/org/opfab/cards/consultation/services/CardSubscriptionService.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/configuration/Services.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/configuration/oauth2/WebSecurityConfiguration.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/kafka/consumer/CardCommandConsumerListener.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/kafka/producer/ResponseCardProducer.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/scheduledtasks/DeleteExpiredCardScheduler.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/services/CardTranslationService.java
- services/cards-publication/src/main/resources/application.yml
- services/cards-publication/src/test/java/org/opfab/cards/publication/kafka/integration/SendKafkaCardShould.java
- services/cards-publication/src/test/resources/application-kafka.yml
- services/cards-publication/src/test/resources/application.yml
- services/users/src/main/java/org/opfab/users/scheduledtask/DeleteExpiredLogsScheduler.java
- src/docs/asciidoc/deployment/configuration/configuration.adoc
- src/docs/asciidoc/dev_env/kafka.adoc
- src/docs/asciidoc/reference_doc/response_cards.adoc
- src/docs/asciidoc/reference_doc/users_management.adoc
- src/docs/asciidoc/resources/migration_guide_to_4.0.adoc
-  Text : #4819 : Normalize configuration parameters for back services
> Normalize configuration parameters for back services (#4819)

- src/test/api/karate/cards/postCardWithI18nUnexisting.feature
- src/test/api/karate/cards/postCardWithProcessAndOrStateUnexisting.feature
- src/test/cypress/cypress/integration/BusinessMenu.spec.js
- src/test/cypress/cypress/integration/Timeline.spec.js
- src/test/cypress/cypress/integration/UserCard.spec.js
> fixed typos

- client/client.gradle
- services/services.gradle
- tools/tools.gradle
> Solve gradle deprecated feature (#4818)

- node-services/cards-reminder/tests/cardsReminderControl.test.ts
> Increase code coverage for cards-reminder (#4708)

- services/businessconfig/src/main/docker/Dockerfile
- services/cards-consultation/src/main/docker/Dockerfile
- services/cards-publication/src/main/docker/Dockerfile
- services/external-devices/src/main/docker/Dockerfile
- services/users/src/main/docker/Dockerfile
> Create a default config directory in java docker services

- src/test/cypress/cypress/integration/BusinessMenu.spec.js
- src/test/cypress/cypress/integration/CoreMenuConfigurationTests.spec.js
- src/test/cypress/cypress/support/opfabGeneralCommands.js
> Add a cypress test for change password (#4836)

- ui/main/package-lock.json
- ui/main/package.json
Why this PR : 
https://stackoverflow.com/questions/76101101/xlsx-package-vulnerabilities-found-but-there-is-no-newer-package
https://git.sheetjs.com/sheetjs/sheetjs/issues/2667
https://cdn.sheetjs.com/
> library xlsx not published anymore on npmjs

- ui/main/src/app/modules/navbar/navbar.component.html
- ui/main/src/app/modules/navbar/navbar.component.ts
-  Text : #4706 : Opfab menu - permit to mix opfab menu and custom menu
> Opfab menu - permit to mix opfab menu and custom menu (#4706)

- services/cards-consultation/src/main/java/org/opfab/cards/consultation/repositories/ArchivedCardCustomRepositoryImpl.java
- src/test/cypress/cypress/integration/ActivityArea.spec.js
- src/test/cypress/cypress/integration/Archives.spec.js
- ui/main/src/app/modules/archives/archives.component.html
- ui/main/src/app/modules/archives/archives.component.scss
- ui/main/src/app/modules/archives/archives.component.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
-  Text : #4368 In archives view / export : removed field business period, added fields publisher, entity recipients and process
> add in archives view/export new field (#4368)

- ui/main/src/app/modules/archives/components/archived-card-detail/archived-card-detail.component.html
- ui/main/src/app/modules/archives/components/archived-card-detail/archived-card-detail.component.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
> Add business period in card footer for archives detail card (#4884)

- node-services/cards-reminder/package-lock.json
- node-services/cards-reminder/package.json
> Add saslprep dependency to fix mongodb driver warning

- node-services/cards-external-diffusion/src/domain/client-side/cardsExternalDiffusionService.ts
- node-services/cards-reminder/src/domain/client-side/cardsRemiderService.ts
- node-services/supervisor/src/domain/client-side/supervisorService.ts
> Do not stop node services on exception (#4891)

- config/docker/node-services.yml
- node-services/cards-external-diffusion/src/domain/application/cardsDiffusionControl.ts
- node-services/cards-external-diffusion/tests/opfabservicesInterface.test.ts
- node-services/common/src/common/server-side/opfabServicesInterface.ts
- node-services/supervisor/config/default-docker.yml
- node-services/supervisor/config/default.yml
- node-services/supervisor/src/domain/application/connectionChecker.ts
- node-services/supervisor/src/domain/client-side/configDTO.ts
- node-services/supervisor/src/domain/client-side/configService.ts
- node-services/supervisor/src/domain/client-side/supervisorService.ts
- node-services/supervisor/tests/connectionChecker.test.ts
- node-services/supervisor/tests/opfabservicesInterface.test.ts
> Supervisor : consider user if member of specific groups (#4901)

- services/users/src/main/java/org/opfab/users/services/UsersService.java
> Solve potential null exception (Ref audit : CID:22984)

- src/docs/asciidoc/reference_doc/card_structure.adoc
> Correct wrong parameter name in ui configuration documentation

- src/test/cypress/cypress/integration/GroupCards.spec.js
- src/test/resources/cards/cypress/group/message4.json
- ui/main/src/app/modules/share/light-card/light-card.component.html
- ui/main/src/app/modules/share/light-card/light-card.component.ts
> Grouped cards : blue arrow should not be displayed if only one card ? (#4632)

- src/test/resources/bundles/defaultProcess_V1/template/usercard_process.handlebars
- ui/main/src/app/modules/usercard/usercard.component.ts
-  Text : #4948 : Permit to send geo information from a user card
> Permit to send geo information from a user card (#4948)

- services/users/src/main/java/org/opfab/users/services/UsersService.java
> Solve potential null exception (Ref audit : CID:22990)

- services/businessconfig/src/main/java/org/opfab/businessconfig/services/ProcessesService.java
> Solve potential null exception (Ref audit : CID:16660)

- services/businessconfig/src/main/java/org/opfab/businessconfig/controllers/BusinessconfigController.java
> Solve potential null exception (Ref audit : CID:27923)

- src/docs/asciidoc/reference_doc/response_cards.adoc
- src/test/cypress/cypress/integration/ResponseCard.spec.js
- src/test/resources/bundles/messageOrQuestionExample/template/confirmation.handlebars
- src/test/resources/bundles/messageOrQuestionExample/template/usercard_confirmation.handlebars
- ui/main/src/app/modules/card/components/card-reponse/card-response.component.ts
- ui/main/src/app/modules/usercard/usercard.component.ts
Fix #4794
-  Text : #4794 :  Add the possibility to set the publisher of the card via getUserResponse
> Add the possibility to set the publisher of the card via getUserResponse (#4794)

- config/dev/common-dev.yml
- config/dev/docker-compose.yml
- src/test/externalApp/src/main/docker/Dockerfile
> Fix dev mode configuration

- tools/generic/utilities/src/main/java/org/opfab/utilities/eventbus/rabbit/RabbitEventBus.java
> Solve hardcoded credentials in Java source code  (Ref audit : CID:29177)

- node-services/cards-reminder/config/default.yml
> Correct error in card reminder service configuration

- src/tooling/migration-rrule-recurrence/package-lock.json
- src/tooling/migration-rrule-recurrence/package.json
> CVE-2021-32050 (Medium) detected in mongodb-4.1.3.tgz (#4968)

- src/docs/asciidoc/reference_doc/user_cards.adoc
- ui/main/src/app/modules/usercard/usercard.component.ts
> Update in documentation the field list that can be set for usercard (4951)

- tools/spring/spring-oauth2-utilities/src/main/java/org/opfab/springtools/configuration/oauth/OpFabJwtAuthenticationToken.java
> Solve incorrect definition of Serializable class (Ref audit : CID:16634)

- services/cards-consultation/src/main/java/org/opfab/cards/consultation/services/CardRoutingUtilities.java
> Solve potential null pointer exception (Ref audit : CID:31171)

- node-services/cards-external-diffusion/src/domain/application/cardRoutingUtilities.ts
- node-services/cards-external-diffusion/tests/cardRoutingUtilities.test.ts
- node-services/cards-external-diffusion/tests/cardsDiffusionControl.test.ts
- services/users/src/main/java/org/opfab/users/model/CurrentUserWithPerimetersData.java
- services/users/src/main/java/org/opfab/users/model/UserSettingsData.java
- services/users/src/main/java/org/opfab/users/services/CurrentUserWithPerimetersService.java
- services/users/src/main/java/org/opfab/users/services/UserSettingsService.java
- services/users/src/main/modeling/swagger.yaml
- services/users/src/test/java/org/opfab/users/services/CurrentUserWithPerimetersServiceShould.java
- services/users/src/test/java/org/opfab/users/services/UserSettingsServiceShould.java
- src/docs/asciidoc/architecture/index.adoc
- src/docs/asciidoc/reference_doc/mail_notification.adoc
- src/test/api/karate/cards-external-diffusion/cardsExternalDiffusion.feature
- src/test/cypress/cypress/integration/FeedNotificationConfiguration.spec.js
- src/test/cypress/cypress/integration/FeedTests.spec.js
- src/test/cypress/cypress/support/feedCommands.js
- ui/main/src/app/business/model/userWithPerimeters.model.ts
- ui/main/src/app/modules/feedconfiguration/feedconfiguration.component.html
- ui/main/src/app/modules/feedconfiguration/feedconfiguration.component.scss
- ui/main/src/app/modules/feedconfiguration/feedconfiguration.component.ts
- ui/main/src/app/server/angularUser.server.ts
- ui/main/src/assets/images/icons/envelope-regular.svg
-  Text : #4712 : Set the possibility for the user to choose which process/state he wants to receive by email
> Set the possibility for the user to choose which process/state he wants to receive by email (#4712)

- services/users/src/main/java/org/opfab/users/configuration/oauth2/WebSecurityConfiguration.java
- src/test/api/karate/users/entities/getEntityDetails.feature
It avoids supervisor service to have admin right to access opfab Anyway all users have access to the list of entities with all details so in practice it does not give users access to new datas
> Authorize access to GET entity for all users

- config/docker/node-services.yml
- node-services/cards-external-diffusion/config/default-docker.yml
- node-services/cards-external-diffusion/config/default.yml
- node-services/cards-external-diffusion/src/cardsExternalDiffusion.ts
- node-services/cards-reminder/config/default-docker.yml
- node-services/cards-reminder/config/default.yml
- node-services/cards-reminder/src/cardsReminder.ts
- node-services/common/src/common/server-side/logger.ts
- node-services/supervisor/config/default-docker.yml
- node-services/supervisor/config/default.yml
- node-services/supervisor/src/connectionSupervisor.ts
- src/docs/asciidoc/deployment/configuration/configuration.adoc
> Add operatorfabric prefix to all params in node services configuration (#4942)

- tools/generic/utilities/src/main/java/org/opfab/utilities/PathUtils.java
- tools/generic/utilities/src/test/java/org/opfab/utilities/PathUtilsShould.java
> Solve Filesystem path, filename, or URI manipulation   (Ref audit : CID:22597)

- node-services/common/src/common/server-side/logger.ts
- services/businessconfig/src/main/resources/application.yml
- services/cards-consultation/src/main/resources/application.yml
- services/cards-publication/src/main/resources/application.yml
- services/external-devices/src/main/resources/application.yml
-  Text : #4984 Prevent log injection
> Prevent log injection

- services/cards-publication/src/main/java/org/opfab/cards/publication/kafka/auth/AADWorkloadIdentityLoginCallbackHandler.java
> Solve potential null pointer exception (Ref audit : CID:29174)

- tools/spring/spring-utilities/src/main/java/org/opfab/springtools/json/InstantDeserializer.java
> Solve potential null exception (Ref audit : CID:16669)

- services/users/src/main/java/org/opfab/users/configuration/oauth2/OAuth2UsersConfiguration.java
> Solve information exposure to log file  (Ref audit : CID:22504)

- services/businessconfig/src/main/java/org/opfab/businessconfig/model/RealTimeScreenData.java
- services/businessconfig/src/main/modeling/swagger.yaml
- src/test/api/karate/businessconfig/resources/realtimescreens1.json
- src/test/api/karate/businessconfig/uploadAndGetRealTimeScreensFile.feature
- ui/main/src/app/business/model/real-time-screens.model.ts
- ui/main/src/app/business/view/realtimeusers/realtimePage.ts
- ui/main/src/app/business/view/realtimeusers/realtimeusers.view.spec.ts
- ui/main/src/app/business/view/realtimeusers/realtimeusers.view.ts
- ui/main/src/app/modules/realtimeusers/realtimeusers.component.html
- ui/main/src/app/modules/realtimeusers/realtimeusers.component.ts
- ui/main/src/tests/mocks/configServer.mock.ts
> Realtime screen : only show users member of specific groups (#4900)

- services/cards-publication/src/main/java/org/opfab/cards/publication/services/CardProcessingService.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/services/CardValidationService.java
> Externalize code regarding json validation from CardProcessingService (#3733)

- src/test/cypress/cypress/integration/BusinessMenu.spec.js
- ui/main/src/app/modules/navbar/menus/menu-link/menu-link.component.html
- ui/main/src/app/modules/navbar/menus/menu-link/menu-link.component.ts
Fix #4946
-  Text : #4946 :  Fix External application theme when opened in new tab
> Fix External application theme when opened in new tab (#4946)

- services/cards-publication/src/main/java/org/opfab/cards/publication/kafka/CardObjectMapper.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/kafka/card/CardCommandFactory.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/kafka/command/BaseCommandHandler.java
- services/cards-publication/src/test/java/org/opfab/cards/publication/kafka/card/CardCommandFactoryShould.java
- services/cards-publication/src/test/java/org/opfab/cards/publication/kafka/command/BaseCommandHandlerShould.java
- services/cards-publication/src/test/java/org/opfab/cards/publication/kafka/command/CreateCardCommandHandlerShould.java
- services/cards-publication/src/test/java/org/opfab/cards/publication/kafka/command/DeleteCardCommandHandlerShould.java
- services/cards-publication/src/test/java/org/opfab/cards/publication/kafka/command/UpdateCardCommandHandlerShould.java
> Simplify code regarding jackson mapper for kafka

- node-services/cards-external-diffusion/src/domain/application/cardRoutingUtilities.ts
- node-services/cards-external-diffusion/src/domain/application/cardsDiffusionControl.ts
- node-services/cards-external-diffusion/src/domain/server-side/cardsExternalDiffusionOpfabServicesInterface.ts
- node-services/cards-external-diffusion/tests/cardRoutingUtilities.test.ts
- node-services/cards-external-diffusion/tests/cardsDiffusionControl.test.ts
- services/users/src/main/java/org/opfab/users/configuration/oauth2/WebSecurityConfiguration.java
- services/users/src/main/java/org/opfab/users/controllers/UserWithPerimetersController.java
- services/users/src/main/java/org/opfab/users/mongo/repositories/MongoUserRepository.java
- services/users/src/main/java/org/opfab/users/mongo/repositories/UserRepositoryImpl.java
- services/users/src/main/java/org/opfab/users/repositories/UserRepository.java
- services/users/src/main/java/org/opfab/users/services/CurrentUserWithPerimetersService.java
- services/users/src/main/java/org/opfab/users/services/UsersService.java
- services/users/src/main/modeling/swagger.yaml
- services/users/src/test/java/org/opfab/users/services/CurrentUserWithPerimetersServiceShould.java
- services/users/src/test/java/org/opfab/users/stubs/UserRepositoryStub.java
> Fix mail sending for cards sent to parent entity (#4962)

- services/cards-publication/src/main/java/org/opfab/cards/publication/kafka/auth/AADWorkloadIdentityLoginCallbackHandler.java
> Solve Information exposure to log file (Ref audit : CID:29140)

- node-services/cards-external-diffusion/src/domain/application/cardsDiffusionControl.ts
- services/cards-consultation/src/main/java/org/opfab/cards/consultation/configuration/mongo/LightCardReadConverter.java
- services/cards-consultation/src/main/java/org/opfab/cards/consultation/model/LightCardConsultationData.java
- services/cards-consultation/src/main/java/org/opfab/cards/consultation/repositories/CardCustomRepositoryImpl.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/model/LightCardPublicationData.java
- services/cards-publication/src/main/modeling/swagger.yaml
- src/test/api/karate/cards/cardsUserRead.feature
> Cards-external-diffusion should not send mail when card has been read by user (#5014)

- ui/main/src/app/business/services/opfabAPI.service.ts
- ui/main/src/app/business/view/externalAppIframe/externalAppIFrame.view.spec.ts
- ui/main/src/app/business/view/externalAppIframe/externalAppIFrame.view.ts
- ui/main/src/app/modules/navbar/menus/menu-link/menu-link.component.ts
-  Text : #4568 Solve issue regarding usage of / in business menu urls
> Solve issue regarding usage of / in business menu urls (#4568)

- ui/main/src/app/modules/feed/components/pinned-cards/pinned-cards.component.ts
-  Text : #4696  automaticPinWhenAcknowledged error in browserconsole
> Solve issue : automaticPinWhenAcknowledged error in browserconsole (#4696)

- src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc
- src/docs/asciidoc/resources/migration_guide_to_4.0.adoc
- ui/main/src/app/authentication/auth-handler.ts
- ui/main/src/app/authentication/auth.service.ts
- ui/main/src/app/authentication/code-authentication-handler.ts
- ui/main/src/app/authentication/implicit-authentication-handler.ts
- ui/main/src/app/authentication/none-authentication-handler.ts
- ui/main/src/app/authentication/password-authentication-handler.ts
- ui/main/src/app/business/services/logs/remote-logger.service.ts
- ui/main/src/app/business/store/current-user.store.ts
- ui/main/src/app/modules/core/session-end/session-end.component.ts
- ui/main/src/app/server/angularRemoteLogger.server.ts
-  Text : #5030 Close eventStream when session is really expired
> Close eventStream when session is really expired

- src/docs/asciidoc/getting_started/index.adoc
> Adjust getting started documentation

- config/docker/nginx.conf
- src/docs/asciidoc/resources/migration_guide_to_4.0.adoc
-  Text : #5074 Add gzip compression for businessConfig services responses
> Add gzip compression for businessConfig services responses

- node-services/cards-external-diffusion/src/domain/client-side/cardsExternalDiffusionService.ts
> Solve sonar issue : Promise returned in function argument where a void return was expected.

- build.gradle
> Sonar configuration

- node-services/cards-external-diffusion/src/cardsExternalDiffusion.ts
- node-services/cards-reminder/src/cardsReminder.ts
> Avoid losing users update in case of stop/start of services (#5076)

- ui/main/src/app/modules/useractionlogs/components/useractionlogs-table/useractionlogs-table.component.ts
Fix #5068
-  Text :  #5068  : Fix bug when accessing a deleted archived card via user actions log screen
> Fix bug when accessing a deleted archived card via user actions log screen (#5068)

- config/docker/cards-external-diffusion.yml
- config/docker/cards-reminder.yml
- config/docker/common.yml
- config/docker/docker-compose.yml
- config/docker/supervisor.yml
- node-services/cards-external-diffusion/config/default-docker.yml
- node-services/cards-external-diffusion/docker/Dockerfile
- node-services/cards-reminder/config/default-docker.yml
- node-services/cards-reminder/docker/Dockerfile
- node-services/common/src/common/server-side/logger.ts
- node-services/supervisor/config/default-docker.yml
- node-services/supervisor/docker/Dockerfile
- src/docs/asciidoc/deployment/configuration/configuration.adoc
- src/docs/asciidoc/resources/migration_guide_to_4.0.adoc
> Create individual config files for nodes services 

- config/docker/docker-compose.yml
- src/docs/asciidoc/deployment/configuration/configuration.adoc
> Add example config to secure rabbitMQ

- src/docs/asciidoc/deployment/configuration/configuration.adoc
- src/docs/asciidoc/resources/migration_guide_to_4.0.adoc
> Adjust documentation regarding authToken configuration

- ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.ts
> Default export does not work for monitoring screen (#5127)

- ui/main/src/app/business/buildInTemplates/question/usercard/questionUserCardTemplateView.spec.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
> No translation for error in build-in template question (#5109)

- src/docs/asciidoc/resources/migration_guide_to_4.0.adoc
> Add rate limiter in migration guide

- config/keycloak/export/dev-users-0.json
> Correct error in user config in keycloak

- ui/main/src/app/business/buildInTemplates/message-or-question-list/usercard/message-or-question-listUserCardTemplateView.ts
> Removed html tags from the usercard of message-or-question list #5114

- config/docker/common.yml
> Adjust common config file to avoid confusion with comments

- ui/main/src/app/business/buildInTemplates/message-or-question-list/usercard/message-or-question-listUserCardTemplate.ts
> Prevented message persistence for message-or-question list #5123

- ui/main/src/app/business/buildInTemplates/message-or-question-list/usercard/message-or-question-listUserCardTemplate.ts
-  Text : #5113 Set a default title value for message-or-question list when editing from another state
> Set a default title value for message-or-question list when editing from another state #5113

- node-services/cards-reminder/src/domain/application/cardsReminderControl.ts
- node-services/cards-reminder/src/domain/application/reminderService.ts
- node-services/cards-reminder/src/domain/application/rruleReminderService.ts
- node-services/cards-reminder/src/domain/client-side/cardsRemiderService.ts
> Avoid cards reminder service crash (#5105)

- ui/main/src/app/business/buildInTemplates/message-or-question-list/card/message-or-question-listCardTemplate.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
> Added a missing translation

- node-services/cards-external-diffusion/tests/cardsDiffusionControl.test.ts
> Correct issue in unit test

- node-services/cards-reminder/src/cardsReminder.ts
- node-services/cards-reminder/src/domain/client-side/cardsRemiderService.ts
- node-services/cards-reminder/src/domain/server-side/remindDatabaseService.ts
> Add a retry mechanism for cards-diffusion connection to mongoDB

- src/test/resources/bundles/messageOrQuestionExample/config.json
- src/test/resources/businessData/message-and-question-list
- ui/main/src/app/business/buildInTemplates/message-or-question-list/usercard/message-or-question-listUserCardTemplate.ts
- ui/main/src/app/business/buildInTemplates/message-or-question-list/usercard/message-or-question-listUserCardTemplateView.ts
-  Text : #5058 Added recipients for information in message or question list
> Added recipients for information in message or question list #5058

- ui/main/src/app/modules/archives/archives.component.ts
Fix #5129 
-  Text : #5129 : Avoid never ending spinner if a request to archives fails
> Avoid never ending spinner if a request to archives fails (#5129)

- config/docker/nginx.conf
- src/docs/asciidoc/resources/index.adoc
- src/docs/asciidoc/resources/migration_guide_to_4.1.adoc
-  Text : #5144 Avoid latency when receiving cards
> Avoid latency when receiving cards (#5144)

- src/test/cypress/cypress/integration/ResponseCard.spec.js
- src/test/resources/cards/defaultProcess/question.json
- src/test/resources/cards/defaultProcess/questionWithKeepChildCards.json
Publisher error in  src/test/resources/cards/defaultProcess/questionWithKeepChildCards.json , the card was refused 
> Correct issue in cypress response card test

- src/test/cypress/cypress/integration/Archives.spec.js
- src/test/cypress/cypress/integration/ResponseCard.spec.js
- src/test/cypress/cypress/integration/UserActionLogs.spec.js
- src/test/cypress/cypress/integration/UserCard.spec.js
- src/test/cypress/cypress/support/archivesAndLoggingCommands.js
- src/test/cypress/cypress/support/opfabGeneralCommands.js
- src/test/cypress/cypress/support/userCardCommands.js
> Refactored the handling of multiselect components in cypress tests #5044

- ui/main/src/app/authentication/auth.service.ts
- ui/main/src/app/business/services/notifications/sound-notification.service.ts
- ui/main/src/app/business/services/session-manager.service.ts
- ui/main/src/app/modules/core/application-loading/account-already-used/account-already-used.component.ts
- ui/main/src/app/modules/core/session-end/session-end.component.ts
- ui/main/src/app/modules/navbar/navbar.component.ts
> Refacto session management

- node-services/cards-external-diffusion/src/cardsExternalDiffusion.ts
- node-services/cards-reminder/src/cardsReminder.ts
- node-services/supervisor/src/connectionSupervisor.ts
- src/docs/asciidoc/deployment/index.adoc
- src/test/api/karate/cards-external-diffusion/cardsExternalDiffusion.feature
- src/test/api/karate/cards-reminder/cardsReminder.feature
- src/test/api/karate/supervisor/supervisor.feature
Fix  #5029
-  Text : #5029 : Add healthcheck endpoint for node services
> Add healthcheck endpoint for node services (#5029)

- src/test/cypress/cypress/integration/FeedNotificationConfiguration.spec.js
- src/test/cypress/cypress/support/opfabGeneralCommands.js
- src/test/cypress/cypress/support/settingsCommands.js
> New cypress tests for the possibility for the user to choose which process/state he wants to receive by email (#4881)

- src/docs/asciidoc/resources/migration_guide_to_4.0.adoc
> update migration doc for opfab 4.0.0

- ui/main/src/shared/css/opfab-application.css
Fix #5115
-  Text : #5115 : Remove border in opfab table
> Remove border in opfab table (#5115)

- ui/main/src/app/business/buildInTemplates/task/usercard/taskUserCardTemplate.ts
- ui/main/src/app/business/buildInTemplates/task/usercard/taskUserCardTemplateView.ts
> Solve issue with task build in template

- CICD/github/setOldMongoKeycloakVersions.sh
- config/docker/ui-config/web-ui.json
- src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc
- src/docs/asciidoc/resources/migration_guide_to_3.10.adoc
- src/docs/asciidoc/resources/migration_guide_to_3.9.adoc
> keycloack => keycloak

- src/test/resources/cards/defaultProcess/contingencies.json
- src/test/resources/cards/defaultProcess/question.json
-  Text : #5117 Added coordinates to some example cards for richer view on the map
> Added coordinates to some examples #5117

- client/client.gradle
> Solve gradle issue with publish task

- ui/main/src/app/modules/feed/components/pinned-cards/pinned-cards.component.html
- ui/main/src/app/modules/feed/components/pinned-cards/pinned-cards.component.ts
- ui/main/src/app/modules/feed/feed.component.html
- ui/main/src/app/modules/feed/feed.component.ts
Fix #5102
-  Text : #5102 : Avoid truncated pinned cards
> Avoid truncated pinned cards (#5102)

- ui/main/src/app/modules/card/components/card-body/card-body.component.html
- ui/main/src/app/modules/card/components/card-body/card-body.component.ts
Fix #5101
-  Text : #5101 : Fix Automatic full screen mode for card detail in feed when filters visible
> Fix Automatic full screen mode for card detail in feed when filters visible (#5101)

- ui/main/src/app/modules/usercard/usercard.component.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
-  Text : #5112 : Question usercard : it should be impossible to set a lttd anterior to the current date
> Question usercard : it should be impossible to set a lttd anterior to the current date (#5112)

- ui/main/src/app/modules/core/application-loading/application-loading.component.ts
> Use native feature to change title instead of angular service

- ui/main/src/app/modules/feed/components/map/map.component.ts
> Prevented query of canvas outside of expected scope #5120

- bin/waitForOpfabToStart.sh
- config/dev/nginx.conf.template
- config/docker/nginx-cors-permissive.conf
- config/docker/nginx.conf
- services/businessconfig/src/main/resources/application.yml
- src/docs/asciidoc/reference_doc/business_data.adoc
- src/docs/asciidoc/resources/migration_guide_to_4.1.adoc
-  Text : #5177 Updated the file size limit of uploads to 100 MB
> Updated the file size limit of uploads to 100 MB #5177

- services/cards-publication/src/main/java/org/opfab/cards/publication/services/CardProcessingService.java
> The rate limiter now affects the representative of a card if there is one #5100

- ui/main/src/app/business/services/services-config.ts
- ui/main/src/app/modules/core/application-loading/application-loading.component.ts
> Isolate service loading from angular code (First step)

- ui/main/src/app/app.module.ts
- ui/main/src/app/business/services/services-config.ts
- ui/main/src/app/business/services/translation/i18n.service.ts
- ui/main/src/app/modules/core/application-loading/application-loading.component.ts
- ui/main/src/app/modules/share/light-card/light-card.component.spec.ts
> Refacto I18NService

- ui/main/src/app/business/services/businessconfig/adminprocess.service.ts
- ui/main/src/app/business/services/businessconfig/businessdata.service.ts
- ui/main/src/app/business/services/crud-service.ts
- ui/main/src/app/business/services/error-service.ts
- ui/main/src/app/business/services/notifications/external-devices.service.ts
- ui/main/src/app/business/services/users/entities.service.ts
- ui/main/src/app/business/services/users/groups.service.ts
- ui/main/src/app/business/services/users/perimeters.service.ts
- ui/main/src/app/business/services/users/user.service.ts
> Refacto UI service error management

- ui/main/src/app/business/services/global-style.service.ts
- ui/main/src/app/business/services/users/user-preference.service.ts
- ui/main/src/app/business/view/externalAppIframe/externalAppIFrame.view.spec.ts
- ui/main/src/app/modules/archives/archives.component.ts
- ui/main/src/app/modules/feed/components/card-list/card-list.component.ts
- ui/main/src/app/modules/feed/components/card-list/filters/feed-filter/feed-filter.component.ts
- ui/main/src/app/modules/feed/components/card-list/filters/feed-sort/feed-sort.component.ts
- ui/main/src/app/modules/realtimeusers/realtimeusers.component.ts
- ui/main/src/app/modules/share/archives-logging-filters/archives-logging-filters.component.ts
- ui/main/src/app/modules/share/timeline-buttons/timeline-buttons.component.ts
> Set user preference service as static

- src/docs/asciidoc/reference_doc/ui_api.adoc
> Doc adjustment

- node-services/cards-reminder/config/default.yml
- node-services/cards-reminder/src/domain/application/cardsReminderControl.ts
- node-services/cards-reminder/src/domain/client-side/cardsRemiderService.ts
- node-services/cards-reminder/src/domain/server-side/remindDatabaseService.ts
-  Text : #5260 Card reminder crashes in certains circumstances when keycloak slow to start
> Sove issue : Card reminder crashes in certains circumstances when keycloak slow to start (#5260)

- ui/main/src/app/business/services/grouped-cards.service.spec.ts
- ui/main/src/app/business/services/grouped-cards.service.ts
- ui/main/src/karma.conf.js
-  Text : Do not group cards together that have no tags
> Bugfix. Do not group cards together that have no tags

- src/test/cypress/cypress/integration/Acknowledgment.spec.js
- src/test/cypress/cypress/integration/UserActionLogs.spec.js
- src/test/cypress/cypress/integration/UserCard.spec.js
- src/test/resources/bundles/defaultProcess_V1/template/usercard_message.handlebars
> Message usercard : space characters added at the beginning/end of the field (#5119)

- src/docs/asciidoc/reference_doc/monitoring.adoc
> Add documentation for Monitoring Process screen (#5263)

- bin/load_environment_light.sh
- gradle.properties
- services/businessconfig/build.gradle
- services/businessconfig/src/main/docker/Dockerfile
- services/cards-consultation/build.gradle
- services/cards-consultation/src/main/docker/Dockerfile
- services/cards-publication/build.gradle
- services/cards-publication/src/main/docker/Dockerfile
- services/external-devices/build.gradle
- services/external-devices/src/main/docker/Dockerfile
- services/users/build.gradle
- services/users/src/main/docker/Dockerfile
- src/test/dummyModbusDevice/src/main/docker/Dockerfile
- src/test/externalApp/src/main/docker/Dockerfile
> 3.15.x Upgrade dependencies and patch snakeyaml

- src/docs/asciidoc/reference_doc/archives.adoc
> Add documentation for permission VIEW_ALL_ARCHIVED_CARDS_FOR_USER_PERIMETERS (#5266)

- bin/load_environment_light.sh
- gradle.properties
- services/businessconfig/src/main/docker/Dockerfile
- services/cards-consultation/src/main/docker/Dockerfile
- services/cards-publication/src/main/docker/Dockerfile
- services/external-devices/src/main/docker/Dockerfile
- services/users/src/main/docker/Dockerfile
- src/test/dummyModbusDevice/src/main/docker/Dockerfile
- src/test/externalApp/src/main/docker/Dockerfile
> Upgrade dependencies and patch snakeyaml

- SECURITY.md
- src/docs/asciidoc/CICD/release_process.adoc
> Update supported versions

- ui/main/src/app/modules/logging/logging.component.html
- ui/main/src/app/modules/logging/logging.component.ts
- ui/main/src/app/modules/processmonitoring/processmonitoring.component.html
- ui/main/src/app/modules/processmonitoring/processmonitoring.component.ts
- ui/main/src/app/modules/share/archives-logging-filters/archives-logging-filters.component.ts
> Process monitoring screen: take into account filter only when clicking search button (#5265)

- ui/main/src/app/business/buildInTemplates/message-or-question-list/usercard/message-or-question-listUserCardTemplateView.ts
- ui/main/src/app/business/services/user-permissions.service.ts
- ui/main/src/app/modules/card/components/card-body/card-body.component.html
- ui/main/src/app/modules/card/components/card-body/card-body.component.ts
- ui/main/src/app/modules/card/components/card-header/card-header.component.ts
- ui/main/src/app/modules/card/components/card-reponse/card-response.component.ts
-  Text : #5145 Activity areas can't ignore "emittingEntityAllowedToRespond" anymore
> Activity areas can't ignore emittingEntityAllowedToRespond anymore #FE-5145

- build.gradle
- gradle.properties
- services/businessconfig/build.gradle
- services/cards-consultation/build.gradle
- services/cards-publication/build.gradle
- services/external-devices/build.gradle
- services/users/build.gradle
-  Text : Upgrades dependencies to mitigate security vulnerabilities
> 3.15.x Upgrade dependencies (Avro, BouncyCastle, Guava, Snappy)

- .gitignore
- bin/dependencies/generateDependencyReport.sh
- bin/dependencies/searchForDependency.sh
- src/docs/asciidoc/dev_env/dependency.adoc
- src/docs/asciidoc/dev_env/index.adoc
-  Text : #5319 Add scripts to help dependency analysis
> Add scripts to help dependency analysis

- build.gradle
- services/businessconfig/build.gradle
- services/cards-consultation/build.gradle
- services/cards-publication/build.gradle
- services/external-devices/build.gradle
- services/users/build.gradle
Apply the same update as in 3.15 release 
> Dependency security udpate

- ui/main/src/app/modules/processmonitoring/components/processmonitoring-table/processmonitoring-table.component.ts
- ui/main/src/app/modules/processmonitoring/processmonitoring.component.ts
> update for solving bug on column size on processMonitoring screen (#4697)

- ui/main/src/app/business/buildInTemplates/message-or-question-list/usercard/message-or-question-listUserCardTemplateView.ts
> Build in template message or question list : response button shall not be visible for messages (#5332)

- SECURITY.md
> Update supported version

- build.gradle
- gradle.properties
- services/services.gradle
- tools/spring/build.gradle
- tools/tools.gradle
> Clean gradle configuration

- services/businessconfig/src/main/java/org/opfab/businessconfig/model/EntitiesGroupsData.java
- services/businessconfig/src/main/java/org/opfab/businessconfig/model/MonitoringData.java
- services/businessconfig/src/main/java/org/opfab/businessconfig/model/MonitoringExportData.java
- services/businessconfig/src/main/java/org/opfab/businessconfig/model/MonitoringExportFieldData.java
- services/businessconfig/src/main/java/org/opfab/businessconfig/model/ProcessData.java
- services/businessconfig/src/main/java/org/opfab/businessconfig/model/ProcessGroupData.java
- services/businessconfig/src/main/java/org/opfab/businessconfig/model/ProcessGroupsData.java
- services/businessconfig/src/main/java/org/opfab/businessconfig/model/RealTimeScreensData.java
- services/cards-consultation/src/main/java/org/opfab/cards/consultation/configuration/webflux/ArchivedCardRoutesConfig.java
- services/cards-consultation/src/main/java/org/opfab/cards/consultation/configuration/webflux/CardRoutesConfig.java
- services/cards-consultation/src/main/java/org/opfab/cards/consultation/configuration/webflux/CardSubscriptionRoutesConfig.java
- services/cards-consultation/src/main/java/org/opfab/cards/consultation/configuration/webflux/ConnectedRecipientsPreviewRoutesConfig.java
- services/cards-consultation/src/main/java/org/opfab/cards/consultation/configuration/webflux/ConnectionRoutesConfig.java
- services/cards-consultation/src/main/java/org/opfab/cards/consultation/configuration/webflux/MessageToSubscriptionsRoutesConfig.java
- services/cards-consultation/src/main/java/org/opfab/cards/consultation/services/CardRoutingUtilities.java
- services/cards-consultation/src/main/java/org/opfab/cards/consultation/services/ConnectedRecipientsPreviewService.java
- services/cards-consultation/src/test/java/org/opfab/cards/consultation/routes/MessageToSubscriptionsRoutesShould.java
- services/cards-publication/src/main/modeling/swagger.yaml
- src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc
- ui/main/src/app/business/server/card.server.ts
- ui/main/src/app/business/services/card/card.service.ts
- ui/main/src/app/modules/usercard/usercard.component.ts
- ui/main/src/app/server/angularCard.server.ts
-  Text : #5108  Preview of users connected takes notification configuration into account
> Preview of users connected takes notification configuration into account #5108

- node-services/cards-reminder/src/domain/application/reminderService.ts
> Cards reminder : Add more information on error log

- ui/main/src/app/business/buildInTemplates/task/usercard/taskUserCardTemplate.ts
> Task advanced : see how to use "event delegation" to improve performance (#5309)

- src/test/cypress/cypress/integration/BuildInTemplates.spec.js
- src/test/cypress/cypress/integration/TaskAdvanced.spec.js
- ui/main/src/app/business/buildInTemplates/task/usercard/taskUserCardTemplate.ts
> Add cypress tests for advanced task (#5264)

- ui/main/src/app/business/services/acknowledge.service.spec.ts
- ui/main/src/app/business/services/acknowledge.service.ts
- ui/main/src/app/business/services/user-permissions.service.ts
- ui/main/src/app/business/view/dashboard/dashboard.view.spec.ts
- ui/main/src/app/modules/card/components/card-ack/card-ack.component.ts
- ui/main/src/app/modules/card/components/card-actions/card-actions.component.ts
- ui/main/src/app/modules/card/components/card-body/card-body.component.ts
- ui/main/src/app/modules/card/components/card-reponse/card-response.component.ts
- ui/main/src/app/modules/usercard/usercard.component.ts
> Implement UserPermissionsService with static methods

- ui/main/src/app/business/view/dashboard/dashboard.view.spec.ts
> Correct sonarLint warning and solve potential falky test

- src/docs/asciidoc/dev_env/index.adoc
- src/docs/asciidoc/dev_env/node-services.adoc
- src/docs/asciidoc/dev_env/project_structure.adoc
> Add dev documentation for node services

- src/docs/asciidoc/reference_doc/template_description.adoc
- src/test/cypress/cypress/integration/Acknowledgment.spec.js
- src/test/cypress/cypress/integration/Calendar.spec.js
- src/test/cypress/cypress/integration/UserActionLogs.spec.js
- src/test/cypress/cypress/integration/UserCard.spec.js
- src/test/resources/bundles/defaultProcess_V1/css/style.css
- src/test/resources/bundles/defaultProcess_V1/template/chart.handlebars
- src/test/resources/bundles/defaultProcess_V1/template/template.handlebars
- src/test/resources/bundles/defaultProcess_V1/template/usercard_message.handlebars
- src/test/resources/cards/cypress/userCard/message.json
- src/test/resources/cards/defaultProcess/message.json
- ui/main/angular.json
- ui/main/package-lock.json
- ui/main/package.json
- ui/main/src/app/business/services/services-config.ts
- ui/main/src/app/business/services/translation/i18n.service.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
- ui/main/src/assets/js/opfab.js
- ui/main/src/scss/styles.scss
- ui/main/src/shared/css/opfab-application.css
Fix #4437 
-  Text : #4437 : Add a rich text editor for usercard
> Add a rich text editor for usercard (#4437)

- src/docs/asciidoc/deployment/index.adoc
> Adjust documentation for monitoring opfab

- node-services/cards-reminder/src/domain/client-side/cardsReminderService.ts
- node-services/cards-reminder/tests/cardsReminderService.test.ts
> Solve issue  Card reminder looses some occurences after reset (#5386)

- src/docs/asciidoc/deployment/configuration/security_configuration.adoc
> Correct documentation regarding security configuration (#5376)

- ui/main/src/app/business/services/acknowledge.service.spec.ts
- ui/main/src/app/business/services/acknowledge.service.ts
- ui/main/src/app/business/services/card/card.service.ts
- ui/main/src/app/business/services/lightcards/lightcards-store.service.ts
- ui/main/src/app/business/services/services-config.ts
- ui/main/src/app/business/view/activityarea/activityarea.view.spec.ts
- ui/main/src/app/business/view/dashboard/dashboard.view.spec.ts
- ui/main/src/app/modules/card/components/card-ack/card-ack.component.ts
- ui/main/src/app/modules/core/application-loading/application-loading.component.ts
- ui/main/src/app/modules/feed/components/card-list/card-list.component.ts
> Implement AcknowledgmentService with static methods

- ui/main/src/app/business/services/date-time-formatter.service.ts
- ui/main/src/app/business/services/services-config.ts
- ui/main/src/app/modules/archives/archives.component.ts
- ui/main/src/app/modules/archives/components/archived-card-detail/archived-card-detail.component.ts
- ui/main/src/app/modules/card/components/card-footer-text/card-footer-text.component.ts
- ui/main/src/app/modules/feed/components/map/map.component.ts
- ui/main/src/app/modules/feed/components/time-line/custom-timeline-chart/custom-timeline-chart.component.spec.ts
- ui/main/src/app/modules/feed/components/time-line/init-chart/init-chart.component.spec.ts
- ui/main/src/app/modules/logging/components/cell-renderers/time-cell-renderer.component.ts
- ui/main/src/app/modules/logging/logging.component.ts
- ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.ts
- ui/main/src/app/modules/navbar/info/info.component.ts
- ui/main/src/app/modules/processmonitoring/components/cell-renderers/time-cell-renderer.component.ts
- ui/main/src/app/modules/processmonitoring/processmonitoring.component.ts
- ui/main/src/app/modules/share/light-card/light-card.component.spec.ts
- ui/main/src/app/modules/share/light-card/light-card.component.ts
- ui/main/src/app/modules/share/timeline-buttons/timeline-buttons.component.ts
> Refacto date time formatter

- ui/main/src/app/business/buildInTemplates/message-or-question-list/usercard/message-or-question-listUserCardTemplate.ts
> Fixed the message-or-question-list message selection #5389

- src/docs/asciidoc/reference_doc/mail_notification.adoc
> (Copilot) Refactor Email Notifications documentation for clarity and conciseness

- ui/main/src/app/modules/feed/components/time-line/custom-timeline-chart/custom-timeline-chart.component.ts
> (Copilot) Solve sonar issue typescript:S6836

- ui/main/src/app/business/view/core/about/about.view.spec.ts
> (Copilot) Refactor test setup in about.view.spec.ts for improved readability and maintainability

- ui/main/src/app/business/view/dashboard/dashboard.view.spec.ts
> Adjust dashboard unit tests to avoid falky tests

- ui/main/src/app/business/services/admin/crud-processes-service.ts
- ui/main/src/app/business/services/businessconfig/adminprocess.service.ts
- ui/main/src/app/business/services/services-config.ts
- ui/main/src/app/modules/admin/services/sharing.service.ts
- ui/main/src/app/modules/core/application-loading/application-loading.component.ts
> Refacto admin process

- ui/main/src/app/modules/feed/components/time-line/custom-timeline-chart/custom-timeline-chart.component.ts
> (Copilot) Refactor timeline code to solve sonar complexity issue

- services/users/src/test/java/org/opfab/users/model/UserSettingsDataShould.java
> (Copilot) Solve sonar issue with UserSettingsData tests

- src/docs/asciidoc/reference_doc/ui_api.adoc
- src/docs/asciidoc/resources/migration_guide_to_4.1.adoc
- src/test/cypress/cypress/integration/CardDetail.spec.js
- src/test/resources/bundles/cypress/template/kitchenSink.handlebars
- src/test/resources/bundles/messageOrQuestionExample/template/confirmation.handlebars
- src/test/resources/cards/sendCard.sh
- ui/main/src/app/business/services/opfabAPI.service.ts
- ui/main/src/app/modules/card/components/card-body/card-body.component.ts
- ui/main/src/assets/js/templateGateway.js
- ui/main/src/assets/js/usercardTemplateGateway.js
- ui/main/src/tests/mocks/opfabApi.mock.ts
-  Text : #5312 The API now allows to call all the entities the user can answer on behalf of
> The API now allows to call all the entities the user can answer on behalf of #5312

- ui/main/src/app/business/common/utilities.ts
>  (Copilot) Code improvment in utilities

- ui/main/src/app/modules/core/application-loading/application-loading.component.ts
> (Copilot) Improve settings loading

- ui/main/src/app/business/services/admin/crud-business-data.service.ts
- ui/main/src/app/business/services/businessconfig/businessdata.service.ts
- ui/main/src/app/business/services/events/application-update.service.ts
- ui/main/src/app/business/services/opfabAPI.service.ts
- ui/main/src/app/business/services/services-config.ts
- ui/main/src/app/modules/admin/components/table/admin-table.directive.ts
- ui/main/src/app/modules/admin/services/sharing.service.ts
- ui/main/src/app/modules/core/application-loading/application-loading.component.ts
> Refacto business data

- services/users/src/main/java/org/opfab/users/configuration/DataInitComponent.java
> (Copilot) Correct sonar issues in DataInitComponent

- services/cards-publication/src/main/java/org/opfab/cards/publication/services/CardValidationService.java
> (Copilot) Solve sonar issue java:S5376

- ui/main/src/app/business/common/utilities.spec.ts
> (Copilot) Add unit test for ui utilities

- ui/main/src/app/business/services/card/card.service.ts
- ui/main/src/app/business/services/card/selectedCardLoader.service.ts
- ui/main/src/app/business/services/services-config.ts
- ui/main/src/app/modules/archives/archives.component.ts
- ui/main/src/app/modules/card/components/card-actions/card-actions.component.ts
- ui/main/src/app/modules/card/components/card-body/card-body.component.ts
- ui/main/src/app/modules/card/components/card-reponse/card-response.component.ts
- ui/main/src/app/modules/core/application-loading/application-loading.component.ts
- ui/main/src/app/modules/logging/logging.component.ts
- ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.ts
- ui/main/src/app/modules/processmonitoring/processmonitoring.component.ts
- ui/main/src/app/modules/useractionlogs/components/useractionlogs-table/useractionlogs-table.component.ts
- ui/main/src/app/modules/usercard/usercard.component.ts
> Refacto card service

- src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc
> Added documentation on hidden settings #5426

- services/cards-publication/src/main/modeling/swagger.yaml
> Documentation for remote logs #5300

- src/test/cypress/cypress/integration/Acknowledgment.spec.js
- src/test/cypress/cypress/integration/UserCard.spec.js
- ui/main/src/app/business/buildInTemplates/message/messageCardTemplate.ts
- ui/main/src/app/business/buildInTemplates/message/messageUserCardTemplate.ts
- ui/main/src/app/business/buildInTemplates/message/messageUserCardTemplateView.spec.ts
- ui/main/src/app/business/buildInTemplates/message/messageUserCardTemplateView.ts
Fix #5375
-  Text : #5375 : Use rich text editor in message build in templates
> Use rich text editor in message build in templates (#5375)

- build.gradle
- gradle.properties
- services/cards-publication/build.gradle
> Opfab not building with commons-text version 1.11.0 (#5350)

- ui/main/src/app/app.component.ts
- ui/main/src/app/business/services/card/selectedCard.service.ts
- ui/main/src/app/business/services/card/selectedCardLoader.service.ts
- ui/main/src/app/business/services/lightcards/lightcards-store.service.ts
- ui/main/src/app/business/services/services-config.ts
- ui/main/src/app/business/view/activityarea/activityarea.view.spec.ts
- ui/main/src/app/business/view/dashboard/dashboard.view.spec.ts
- ui/main/src/app/modules/calendar/calendar.component.ts
- ui/main/src/app/modules/card/card.component.ts
- ui/main/src/app/modules/card/components/card-body/card-body.component.ts
- ui/main/src/app/modules/dashboard/dashboard.component.ts
- ui/main/src/app/modules/feed/feed.component.ts
- ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.ts
- ui/main/src/app/modules/monitoring/monitoring.component.ts
- ui/main/src/app/modules/processmonitoring/components/processmonitoring-table/processmonitoring-table.component.ts
- ui/main/src/app/modules/processmonitoring/processmonitoring.component.ts
- ui/main/src/app/router/router-navigation.service.ts
> Refacto selected card

- node-services/cards-external-diffusion/package.json
- node-services/cards-reminder/package.json
- node-services/common/package.json
- node-services/common/src/common/server-side/jwtTokenUtils.ts
- node-services/supervisor/package.json
- ui/main/package.json
- ui/main/src/app/authentication/auth-handler.ts
> Opfab not building with jwtdecode v4.0 (#5373)

- tools/spring/spring-oauth2-utilities/src/main/java/org/opfab/springtools/configuration/oauth/OpFabJwtAuthenticationToken.java
> Solve serializable class with no version (Ref audit : CID 32646)

- node-services/common/src/common/server-side/logger.ts
- services/businessconfig/src/main/resources/application.yml
- services/cards-consultation/src/main/resources/application.yml
- services/cards-publication/src/main/resources/application.yml
- services/external-devices/src/main/resources/application.yml
- services/users/src/main/resources/application.yml
> Improve log injection prevention mechanism

- ui/main/src/app/business/services/logs/remote-logger.service.ts
> (Copilot) Remote log improvment

- src/docs/asciidoc/CICD/release_process.adoc
- src/docs/asciidoc/community/workflow.adoc
> Integrate release candidates in release process documentation

- ui/main/src/app/modules/core/application-loading/application-loading.component.ts
> Remove unnecessary loading of supervised entities

- src/test/cypress/cypress/support/settingsCommands.js
> Adjust settings cypress function to avoid falky tests

- ui/main/src/app/business/buildInTemplates/task/usercard/taskUserCardTemplate.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
-  Text : #5497 : Task advanced : two error messages not translated
> Task advanced : error message not translated (#5497)

- src/docs/asciidoc/reference_doc/template_description.adoc
- src/test/resources/bundles/defaultProcess_V1/template/template.handlebars
- ui/main/src/assets/js/opfab.js
> Fix usage of double quotation mark in rich text editor (#5498)

- ui/main/src/app/modules/admin/components/editmodal/supervised-entities/edit-supervised-entity-modal.component.ts
- ui/main/src/app/modules/admin/components/table/supervised-entities-table.component.ts
Nothing in release note as it is a new feature
> Fix bug when adding / udpating supervisor config (#5484)

- src/test/cypress/cypress/integration/TaskAdvanced.spec.js
- ui/main/src/app/business/buildInTemplates/task/usercard/taskUserCardTemplate.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
-  Text : #5490 : Task advanced : make impossible a card without any month/weekday selected
> Task advanced : make impossible a card without any month/weekday selected (#5490)

- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
Fix #5486 
-  Text : #5486 : Fix admin screen missing translations
> Fix admin screen missing translations (#5486)

- ui/main/src/app/modules/admin/components/cell-renderers/array-cell-renderer.component.ts
- ui/main/src/app/modules/admin/components/cell-renderers/entity-name-cell-renderer.component.ts
> Remove useless log in array-cell-renderer (#5500)

- services/cards-consultation/src/main/java/org/opfab/cards/consultation/repositories/CardCustomRepositoryImpl.java
> Remove useless logs in cards-consultation (#5501)

- CICD/github/build.sh
- build.gradle
- ui/main/package-lock.json
- ui/main/package.json
- ui/main/src/karma.conf.js
> Add ui test coverage

- src/docs/asciidoc/CICD/release_process.adoc
> Adjust doc for release candidate process

- src/test/cypress/cypress/integration/TaskAdvanced.spec.js
> Adjust cypress test to avoid falky test with task advanced

- src/docs/asciidoc/deployment/index.adoc
> Update documentation of restricted operations (#5178)

- ui/main/src/app/business/services/card/handlebars.service.spec.ts
- ui/main/src/app/business/services/card/handlebars.service.ts
- ui/main/src/app/business/services/events/application-update.service.ts
- ui/main/src/app/business/services/services-config.ts
- ui/main/src/app/modules/share/template-rendering/template-rendering.component.ts
- ui/main/src/app/modules/usercard/usercard.component.ts
> Implement Handlebars service with statics methods

- ui/main/src/app/business/services/lightcards/grouped-cards.service.spec.ts
- ui/main/src/app/business/services/lightcards/grouped-cards.service.ts
- ui/main/src/app/business/services/lightcards/lightcards-feed-filter.service.ts
- ui/main/src/app/business/view/dashboard/dashboard.view.spec.ts
- ui/main/src/app/modules/feed/components/card-list/card-list.component.ts
- ui/main/src/app/modules/share/light-card/light-card.component.ts
> Implement GroupedCardsServices with static methods

- client/users/src/main/java/org/opfab/users/model/RolesEnum.java
- client/users/src/main/modeling/config.json
- services/users/src/main/java/org/opfab/users/model/EntityData.java
- services/users/src/main/modeling/swagger.yaml
- services/users/src/test/java/org/opfab/users/services/EntitiesServiceShould.java
- ui/main/src/app/business/model/entity.model.ts
- ui/main/src/app/business/model/roles.model.ts
- ui/main/src/app/business/services/acknowledge.service.spec.ts
- ui/main/src/app/business/services/users/entities.service.spec.ts
- ui/main/src/app/business/view/activityarea/activityarea.view.spec.ts
- ui/main/src/app/business/view/realtimeusers/realtimeusers.view.spec.ts
- ui/main/src/app/modules/admin/admin.module.ts
- ui/main/src/app/modules/admin/components/cell-renderers/role-cell-renderer.component.html
- ui/main/src/app/modules/admin/components/cell-renderers/role-cell-renderer.component.scss
- ui/main/src/app/modules/admin/components/cell-renderers/role-cell-renderer.component.ts
- ui/main/src/app/modules/admin/components/editmodal/entities/edit-entity-modal.component.html
- ui/main/src/app/modules/admin/components/editmodal/entities/edit-entity-modal.component.ts
- ui/main/src/app/modules/admin/components/table/admin-table.directive.ts
- ui/main/src/app/modules/admin/components/table/entities-table.component.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
- ui/main/src/assets/js/opfab.js
> Added Roles to the admin screen #5424

- gradle.properties
> Upgrade Spring Boot to 3.1.6

- src/test/cypress/cypress/integration/TaskAdvanced.spec.js
- ui/main/src/app/business/buildInTemplates/task/card/taskCardTemplateView.spec.ts
- ui/main/src/app/business/buildInTemplates/task/card/taskCardTemplateView.ts
> Task advanced : a last comma that should not be displayed (#5496)

- ui/main/src/app/modules/processmonitoring/components/processmonitoring-table/processmonitoring-table.component.ts
> Add space between severity color and first column in monitoring processus (#5473)

- ui/main/src/app/modules/archives/archives.component.scss
- ui/main/src/app/modules/feed/components/card-list/filters/feed-filter-and-sort-icons/feed-filter-and-sort-icons.component.scss
- ui/main/src/app/modules/feed/components/card-list/filters/feed-search/feed-search.component.scss
- ui/main/src/scss/styles.scss
- ui/main/src/shared/js/opfab-application.js
Fix #5499
-  Text : #5499 : Fix navbar hovering style in day mode
> Fix navbar hovering style in day mode (#5499)

- ui/main/src/app/modules/settings/components/settings/base-setting/base-setting.directive.ts
- ui/main/src/app/modules/settings/components/settings/list-setting/list-setting.component.ts
> Avoid patching settings on component init

- src/test/cypress/cypress/integration/UserCard.spec.js
- ui/main/src/app/modules/usercard/usercard.component.html
-  Text : #5448 : Use badge to show entity recipients for user card preview
> Use badge to show entity recipients for user card preview (#5448)

- ui/main/src/app/business/view/dashboard/dashboard.view.spec.ts
- ui/main/src/app/business/view/dashboard/dashboard.view.ts
- ui/main/src/app/modules/dashboard/dashboard.component.ts
> Avoid memory leak and flaky ui test in dashboard

- ui/main/src/app/business/buildInTemplates/question/card/questionCardTemplate.ts
- ui/main/src/app/business/buildInTemplates/question/card/questionCardTemplateView.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
-  Text : #5462 : In question card build in template add date column for responses
> In question card build in template add date column for responses (#5462)

- bin/load_environment_light.sh
- node-services/cards-external-diffusion/docker/Dockerfile
- node-services/cards-reminder/docker/Dockerfile
- node-services/supervisor/docker/Dockerfile
> Use LTS node version in dev and docker environment (#5559)

- src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc
> Documentation : sort ui param list by alphabetical order (#5552)

- services/cards-publication/src/main/java/org/opfab/cards/publication/mongo/CardRepositoryImpl.java
- src/test/api/karate/cards/cardsReminder.feature
- src/test/resources/bundles/taskAdvancedExample/config.json
-  In chapter :   Bugs
-  Text : #5555  Reminder shall remove ack at the entity level
> Reminder shall remove ack at the entity level (#5555)

- ui/main/src/app/modules/admin/admin-routing.module.ts
- ui/main/src/app/modules/externaldevicesconfiguration/externaldevicesconfiguration-routing.module.ts
Fix #5474
-  Text : #5474 : Prevent non admin users from accessing the admin screen through the URL
> Prevent non admin users from accessing the admin screen through the URL (#5474)

- services/cards-consultation/src/test/java/org/opfab/cards/consultation/TestUtilities.java
- services/cards-publication/src/main/modeling/swagger.yaml
- src/test/api/karate/cards/cardsWithTimespans.feature
- src/test/api/karate/cards/postCardWithRRuleRecurrence.feature
-  Text : #5483 : Recurrent card : add a control in the code to forbid negative number for "minutes to remind before task"
> Recurrent card : add a control in the code to forbid negative number for "minutes to remind before task" (#5483)

- ui/main/src/app/business/services/notifications/external-devices.service.ts
- ui/main/src/app/business/services/notifications/sound-notification.service.ts
- ui/main/src/app/business/services/services-config.ts
- ui/main/src/app/modules/core/application-loading/application-loading.component.ts
- ui/main/src/app/modules/externaldevicesconfiguration/editModal/externaldevicesconfiguration-modal.component.ts
- ui/main/src/app/modules/externaldevicesconfiguration/table/devices.table.component.ts
- ui/main/src/app/modules/externaldevicesconfiguration/table/externaldevicesconfiguration-directive.ts
- ui/main/src/app/modules/externaldevicesconfiguration/table/users.table.component.ts
- ui/main/src/app/modules/settings/components/settings/settings.component.ts
> Implement ExternalDevicesService with static methods

- node-services/cards-external-diffusion/config/default-docker.yml
- node-services/cards-external-diffusion/config/default.yml
- node-services/cards-external-diffusion/src/domain/application/cardsDiffusionControl.ts
- node-services/cards-external-diffusion/src/domain/application/cardsDiffusionRateLimiter.ts
- node-services/cards-external-diffusion/src/domain/client-side/cardsExternalDiffusionService.ts
- node-services/cards-external-diffusion/src/domain/client-side/configDTO.ts
- node-services/cards-external-diffusion/tests/cardsDiffusionControl.test.ts
- node-services/cards-external-diffusion/tests/cardsDiffusionRateLimiter.test.ts
- src/docs/asciidoc/deployment/configuration/configuration.adoc
Fix #5428
-  Text : #5428 : Add a rate limiter for mail sending per destination address
> Add a rate limiter for mail sending per destination address (#5428)

- node-services/cards-external-diffusion/config/default-docker.yml
- node-services/cards-external-diffusion/config/default.yml
- node-services/cards-external-diffusion/package-lock.json
- node-services/cards-external-diffusion/package.json
- node-services/cards-external-diffusion/src/cardsExternalDiffusion.ts
- node-services/cards-external-diffusion/src/domain/application/cardsDiffusionControl.ts
- node-services/cards-external-diffusion/src/domain/client-side/cardsExternalDiffusionService.ts
- node-services/cards-external-diffusion/src/domain/server-side/cardsExternaDiffusionDatabaseService.ts
- node-services/cards-external-diffusion/tests/cardsDiffusionControl.test.ts
Fix #5589
-  Text : #5589 : Card external diffusion : store in mongoDB mails already sent
> Card external diffusion : store in mongoDB mails already sent (#5589)

- src/docs/asciidoc/reference_doc/build-in_templates.adoc
- src/test/resources/businessData/message-and-question-list
- ui/main/src/app/business/buildInTemplates/message-or-question-list/usercard/message-or-question-listUserCardTemplateView.spec.ts
- ui/main/src/app/business/buildInTemplates/message-or-question-list/usercard/message-or-question-listUserCardTemplateView.ts
Fix #5595
-  Text : #5595 : Message or question list template - Add option in config file to choose severity
> Message or question list template - Add option in config file to choose severity (#5595)

- ui/main/src/app/business/services/lightcards/lightcards-feed-filter.service.ts
- ui/main/src/app/business/services/lightcards/lightcards-store.service.ts
- ui/main/src/app/business/services/notifications/sound-notification.service.ts
- ui/main/src/app/business/services/notifications/system-notification.service.ts
- ui/main/src/app/business/view/activityarea/activityarea.view.spec.ts
- ui/main/src/app/business/view/activityarea/activityarea.view.ts
- ui/main/src/app/business/view/dashboard/dashboard.view.spec.ts
- ui/main/src/app/business/view/dashboard/dashboard.view.ts
- ui/main/src/app/business/view/timeline/timeline.view.spec.ts
- ui/main/src/app/modules/activityarea/activityarea.component.ts
- ui/main/src/app/modules/calendar/calendar.component.ts
- ui/main/src/app/modules/card/components/card-ack/card-ack.component.ts
- ui/main/src/app/modules/card/components/card-acks-footer/card-acks-footer.component.ts
- ui/main/src/app/modules/card/components/card-body/card-body.component.ts
- ui/main/src/app/modules/card/components/card-footer-text/card-footer-text.component.ts
- ui/main/src/app/modules/core/application-loading/application-loading.component.ts
- ui/main/src/app/modules/dashboard/dashboard.component.ts
- ui/main/src/app/modules/feed/components/card-list/card-list.component.ts
- ui/main/src/app/modules/feed/components/card-list/filters/filters.component.ts
- ui/main/src/app/modules/feed/components/pinned-cards/pinned-cards.component.ts
- ui/main/src/app/modules/feedconfiguration/feedconfiguration.component.ts
- ui/main/src/app/modules/monitoring/components/cell-renderers/responses-cell-renderer.component.ts
- ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.ts
- ui/main/src/app/modules/monitoring/monitoring.component.ts
> Implement LightCardStoreService as statics methods

- ui/main/src/app/business/services/events/application-events.service.ts
- ui/main/src/app/business/services/events/application-update.service.ts
- ui/main/src/app/modules/navbar/info/info.component.ts
> Implement application-events service with statics methods (#5609)

- ui/main/src/app/business/services/card/template-css.service.ts
- ui/main/src/app/business/services/events/application-update.service.ts
- ui/main/src/app/business/services/services-config.ts
- ui/main/src/app/modules/core/application-loading/application-loading.component.ts
- ui/main/src/app/modules/share/template-rendering/template-rendering.component.ts
> Implement template-css services with statics methods (#5610)

- ui/main/src/app/business/services/services-config.ts
- ui/main/src/app/business/services/users/settings.service.ts
- ui/main/src/app/business/view/activityarea/activityarea.view.spec.ts
- ui/main/src/app/business/view/activityarea/activityarea.view.ts
- ui/main/src/app/modules/activityarea/activityarea.component.ts
- ui/main/src/app/modules/core/application-loading/application-loading.component.ts
- ui/main/src/app/modules/feedconfiguration/feedconfiguration.component.ts
- ui/main/src/app/modules/settings/components/settings/base-setting/base-setting.directive.ts
- ui/main/src/app/modules/settings/components/settings/checkbox-setting/checkbox-setting.component.ts
- ui/main/src/app/modules/settings/components/settings/list-setting/list-setting.component.ts
- ui/main/src/app/modules/settings/components/settings/multi-settings/multi-settings.component.ts
- ui/main/src/app/modules/settings/components/settings/text-setting/text-setting.component.ts
> Implement settings services with statics methods (#5626)

- src/tooling/migration-opfab3/Dockerfile
> Update node for migration script to avoid security issues

- services/businessconfig/src/main/docker/Dockerfile
- services/cards-consultation/src/main/docker/Dockerfile
- services/cards-publication/src/main/docker/Dockerfile
- services/external-devices/src/main/docker/Dockerfile
- services/users/src/main/docker/Dockerfile
- src/test/externalApp/src/main/docker/Dockerfile
- web-ui/src/main/docker/Dockerfile
> Remove unneed curl in dockers to avoid CVS-2023-23914

- services/cards-publication/src/test/java/org/opfab/cards/publication/kafka/integration/SendKafkaCardShould.java
> Add more retries to kafka test to avoid flaky tests

- ui/main/src/tests/helpers.ts
> Remove dead code in test helper

- services/cards-consultation/src/test/java/org/opfab/cards/consultation/services/CardRoutingUtilitiesShould.java
> Avoid using spring for test CardRoutingUtilitiesShould

- src/docs/asciidoc/community/index.adoc
> Add code guidelines + remove old mailing lists in documentation

- ui/main/src/app/authentication/auth.service.ts
- ui/main/src/app/authentication/implicit-authentication-handler.ts
- ui/main/src/app/business/common/utilities.ts
- ui/main/src/app/business/services/businessconfig/processes.service.ts
- ui/main/src/app/business/services/config.service.ts
- ui/main/src/app/business/services/logs/logger.service.ts
- ui/main/src/app/business/services/notifications/sound-notification.service.ts
- ui/main/src/app/business/services/translation/i18n.service.ts
- ui/main/src/app/business/services/user-permissions.service.ts
- ui/main/src/app/business/services/users/entities.service.ts
- ui/main/src/app/business/services/users/groups.service.ts
- ui/main/src/app/business/services/users/perimeters.service.ts
- ui/main/src/app/business/services/users/supervised-entities.service.ts
- ui/main/src/app/business/services/users/user.service.ts
- ui/main/src/app/business/store/lightcards/lightcards-store.ts
- ui/main/src/app/business/view/realtimeusers/realtimeusers.view.ts
- ui/main/src/app/modules/admin/components/cell-renderers/state-rights-cell-renderer.component.ts
- ui/main/src/app/modules/card/card.component.ts
- ui/main/src/app/modules/card/components/card-actions/card-actions.component.ts
- ui/main/src/app/modules/core/application-loading/application-loading.component.ts
- ui/main/src/app/modules/feed/components/map/map.component.ts
- ui/main/src/app/modules/feed/feed.component.ts
- ui/main/src/app/modules/feedconfiguration/feedconfiguration.component.ts
- ui/main/src/app/modules/share/simplified-card-view/simplified-card-view.component.ts
- ui/main/src/app/modules/usercard/selectStateForm/usercard-select-state-form.component.ts
- ui/main/src/app/modules/usercard/usercard.component.ts
- ui/main/src/app/server/angularOpfabEventStream.server.ts
> UI : Add Log level option and replace console.log calls with logger service calls 

- ui/main/src/assets/i18n/fr.json
-  Text : #5502 : Business data management tab : missing accents for french version
> Business data management tab : missing accents for french version (#5502)

- ui/main/src/app/business/services/map.service.ts
- ui/main/src/app/modules/feed/components/map/map.component.ts
- ui/main/src/app/modules/share/light-card/light-card.component.ts
> Set map service as static (#5660)

- ui/main/src/app/business/services/opfabAPI.service.ts
- ui/main/src/app/business/services/services-config.ts
- ui/main/src/app/modules/card/components/card-body/card-body.component.ts
- ui/main/src/app/modules/card/components/card-reponse/card-response.component.ts
- ui/main/src/app/modules/core/application-loading/application-loading.component.ts
- ui/main/src/app/modules/share/simplified-card-view/simplified-card-view.component.ts
- ui/main/src/app/modules/share/template-rendering/template-rendering.component.ts
- ui/main/src/app/modules/usercard/recipientForm/usercard-recipients-form.component.ts
- ui/main/src/app/modules/usercard/usercard.component.ts
> Implement opfabAPI service with statics methods (#5627)

- services/cards-consultation/src/test/java/org/opfab/cards/consultation/TestUtilities.java
- services/services.gradle
> Remove use of random in unit test for back (#5653)

- ui/main/src/app/modules/share/light-card/light-card.component.html
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
-  Text : #5488 : Add a tooltip for icon to zoom on geo map
> Add a tooltip for icon to zoom on geo map (#5488)

- ui/main/src/app/business/services/acknowledge.service.spec.ts
- ui/main/src/app/business/services/card/handlebars.service.spec.ts
- ui/main/src/app/business/services/lightcards/grouped-cards.service.spec.ts
- ui/main/src/app/business/services/reminder/reminderUtils.spec.ts
- ui/main/src/app/business/services/rrule-reminder/rrule-reminderUtils.spec.ts
- ui/main/src/app/business/store/lightcards/lightcards-filter.spec.ts
- ui/main/src/app/business/store/lightcards/lightcards-sorter.spec.ts
- ui/main/src/app/business/view/activityarea/activityarea.view.spec.ts
- ui/main/src/app/business/view/dashboard/dashboard.view.spec.ts
- ui/main/src/app/business/view/timeline/circles.spec.ts
- ui/main/src/tests/helpers.ts
> Remove use of random in UI unit test (#5656)

- gradle/wrapper/gradle-wrapper.properties
- node-services/cards-external-diffusion/build.gradle
- node-services/cards-reminder/build.gradle
- node-services/supervisor/build.gradle
> Update dependency gradle to v8.5 (#5625)

- tools/spring/spring-oauth2-utilities/src/main/java/org/opfab/springtools/configuration/oauth/OAuth2GenericConfiguration.java
> Solve issue with fetchCurrentUserPerimeterWithPerimeter (#5655)

- src/docs/asciidoc/reference_doc/build-in_templates.adoc
- src/test/cypress/cypress/integration/BuildInTemplates.spec.js
- src/test/resources/businessData/message-and-question-list
- ui/main/src/app/business/buildInTemplates/message-or-question-list/usercard/message-or-question-listUserCardTemplate.ts
- ui/main/src/app/business/buildInTemplates/message-or-question-list/usercard/message-or-question-listUserCardTemplateView.spec.ts
- ui/main/src/app/business/buildInTemplates/message-or-question-list/usercard/message-or-question-listUserCardTemplateView.ts
Fix #5596
-  Text : #5596 : Message or question list template - Add option in config file to choose entity publisher list
> Message or question list template - Add option in config file to choose entity publisher list (#5596)

- src/test/api/karate/businessconfig/resources/bundle_supervisor/template/acknowledgement.handlebars
- src/test/resources/bundles/conferenceAndITIncidentExample/template/usercard_incidentInProgress.handlebars
- src/test/resources/bundles/defaultProcess_V1/template/chart-line.handlebars
- src/test/resources/bundles/defaultProcess_V1/template/usercard_message.handlebars
- src/test/resources/bundles/defaultProcess_V1/template/usercard_process.handlebars
- src/test/resources/bundles/messageOrQuestionExample/template/confirmation.handlebars
- src/test/resources/bundles/messageOrQuestionExample/template/usercard_confirmation.handlebars
- src/test/resources/bundles/supervisor/template/acknowledgement.handlebars
- src/test/resources/bundles/taskExample/template/usercard_task.handlebars
Maybe you prefer to wait before merging ? For testing maybe...
> Replace deprecated methods "templateGateway/usercardTemplateGateway" in bundles with new methods (#5697)

- ui/main/src/app/modules/card/components/card-reponse/card-response.component.ts
Nothing in release note 4.2.0 as it will be in a new release 4.1.1
> Solve issue :  Response card not received in real time if user entity is only sender of the card (#5714)

- config/docker/users.yml
- services/users/src/main/java/org/opfab/users/model/EntityData.java
- services/users/src/main/modeling/swagger.yaml
- services/users/src/test/java/org/opfab/users/services/EntitiesServiceShould.java
- src/docs/asciidoc/reference_doc/ui_api.adoc
- src/docs/asciidoc/resources/migration_guide_to_4.2.adoc
- src/test/api/karate/users/entities/createEntities.feature
- src/test/cypress/cypress/integration/Admin.spec.js
- src/test/cypress/cypress/integration/CardDetail.spec.js
- src/test/cypress/cypress/integration/CardDetailDepracted.spec.js
- src/test/resources/bundles/cypress/template/kitchenSink.handlebars
- src/test/resources/bundles/cypress/template/kitchenSinkDeprecated.handlebars
- ui/main/src/app/business/model/entity.model.ts
- ui/main/src/app/business/services/acknowledge.service.spec.ts
- ui/main/src/app/business/services/users/entities.service.spec.ts
- ui/main/src/app/business/services/users/entities.service.ts
- ui/main/src/app/business/view/activityarea/activityarea.view.spec.ts
- ui/main/src/app/business/view/activityarea/activityarea.view.ts
- ui/main/src/app/business/view/realtimeusers/realtimeusers.view.spec.ts
- ui/main/src/app/business/view/useractionlogs/userActionLogs.view.spec.ts
- ui/main/src/app/modules/admin/components/editmodal/entities/edit-entity-modal.component.html
- ui/main/src/app/modules/admin/components/editmodal/entities/edit-entity-modal.component.ts
- ui/main/src/app/modules/card/components/card-ack/card-ack.component.ts
- ui/main/src/app/modules/card/components/card-acks-footer/card-acks-footer.component.ts
- ui/main/src/app/modules/core/application-loading/activityarea-choice-after-login/activityarea-choice-after-login.component.ts
- ui/main/src/app/modules/feed/components/card-list/card-list.component.ts
- ui/main/src/app/modules/navbar/info/info.component.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
-  Text : #5614 Removed entityNotAllowedToSendCard attribute
> Removed entityNotAllowedToSendCard attribute #5614

- client/users/src/main/java/org/opfab/users/model/RolesEnum.java
- config/docker/users.yml
- services/users/src/main/java/org/opfab/users/model/EntityData.java
- services/users/src/main/modeling/swagger.yaml
- services/users/src/test/java/org/opfab/users/services/EntitiesServiceShould.java
- src/test/cypress/cypress/integration/Admin.spec.js
- src/test/cypress/cypress/integration/CardDetail.spec.js
- ui/main/src/app/business/model/roles.model.ts
- ui/main/src/app/business/view/activityarea/activityarea.view.spec.ts
- ui/main/src/app/business/view/activityarea/activityarea.view.ts
- ui/main/src/app/modules/core/application-loading/activityarea-choice-after-login/activityarea-choice-after-login.component.ts
- ui/main/src/app/modules/navbar/info/info.component.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
-  Text : #5707 Added the ACTIVITY_AREA role
> Added the ACTIVITY_AREA role #5707

- src/test/cypress/cypress/integration/Admin.spec.js
> Fixed admin.spec exports

- src/test/cypress/cypress/integration/TaskAdvanced.spec.js
- src/test/resources/bundles/taskAdvancedExample/i18n.json
- ui/main/src/app/business/buildInTemplates/task/card/taskCardTemplateView.spec.ts
- ui/main/src/app/business/buildInTemplates/task/card/taskCardTemplateView.ts
- ui/main/src/app/business/buildInTemplates/task/usercard/TaskUserCardTemplateView.spec.ts
- ui/main/src/app/business/buildInTemplates/task/usercard/taskUserCardTemplate.ts
- ui/main/src/app/business/buildInTemplates/task/usercard/taskUserCardTemplateView.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
-  Text : #5722 : Add "task title" field in task advanced build in template
> Add "task title" field in task advanced build in template (#5722)

- src/test/api/karate/businessconfig/resources/emptyRealtimescreens.json
- src/test/api/karate/businessconfig/uploadAndGetRealTimeScreensFile.feature
> Fixed config of businessconfig karate test

- services/businessconfig/src/main/java/org/opfab/businessconfig/model/ProcessStatesData.java
- services/businessconfig/src/main/modeling/swagger.yaml
- src/test/api/karate/businessconfig/getABusinessconfig.feature
- src/test/api/karate/businessconfig/getBusinessconfigTemplate.feature
- src/test/api/karate/businessconfig/resources/bundle_api_test/config.json
- src/test/api/karate/businessconfig/resources/bundle_api_test_v2/config.json
- src/test/api/karate/launchAllBusinessconfig.sh
-  Text : #5727 Added the email template as a config property
> Added the email template as a config property #5727

- .gitignore
- src/docs/asciidoc/resources/migration_guide_to_4.2.adoc
- src/tooling/migration-entity-roles/Dockerfile
- src/tooling/migration-entity-roles/docker-compose.yml
- src/tooling/migration-entity-roles/launchMigration.sh
- src/tooling/migration-entity-roles/migration-entity-roles-entrypoint.sh
- src/tooling/migration-entity-roles/migration-entity-roles.js
- src/tooling/migration-entity-roles/package-lock.json
- src/tooling/migration-entity-roles/package.json
-  Text : #5615 Added a migration script for entity roles
> Added a migration script for entity roles #5615

- src/test/cypress/cypress/integration/ResponseCard.spec.js
> Add a cypress test for new feature PROPAGATE_READ_ACK_TO_PARENT_CARD (#5735)

- services/businessconfig/build.gradle
- services/businessconfig/src/main/java/org/opfab/businessconfig/controllers/BusinessconfigController.java
Remove inheritance form generated swagger interface and modify method signatures to declare API mapping
> Remove swagger controller generation for businessconfig service

- src/test/cypress/cypress/integration/1-RealTimeUsers.spec.js
- ui/main/src/app/modules/activityarea/activityarea.component.html
- ui/main/src/app/modules/realtimeusers/realtimeusers.component.html
-  Text : #5598 : Change color for realtime screen and activity area screen for connected/disconnected circles
> Change color for realtime screen and activity area screen for connected/disconnected circles (#5598)

- ui/main/src/app/business/services/acknowledge.service.ts
- ui/main/src/app/modules/card/components/card-ack/card-ack.component.ts
Fix FE-5728
-  Text : FE-5728 : Fix isAcknowledgmentAllowed() method
> Fix isAcknowledgmentAllowed() method (FE-5728)

- settings.gradle
- src/docs/asciidoc/dev_env/gatling.adoc
- src/docs/asciidoc/dev_env/index.adoc
- src/test/gatling/gatlingTests.gradle
- src/test/gatling/src/gatling/java/org/opfab/sse/SseTest.java
To launch the test run : 
`./gradlew clean  gatlingRun-org.opfab.sse.SseTest`
Fix #5069 
-  Text : #5069 : Load test on SSE connection
> Load test on SSE connection (#5069)

- src/test/cypress/cypress/integration/UserCard.spec.js
- src/test/resources/bundles/messageOrQuestionExample/i18n.json
- ui/main/src/app/business/buildInTemplates/message/messageUserCardTemplate.ts
- ui/main/src/app/business/buildInTemplates/message/messageUserCardTemplateView.spec.ts
- ui/main/src/app/business/buildInTemplates/message/messageUserCardTemplateView.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
-  Text : #5748 : Message buildin template : add a field "title of the message"
> Message buildin template : add a field "title of the message" (#5748)

- bin/load_environment_light.sh
- node-services/cards-external-diffusion/docker/Dockerfile
- node-services/cards-external-diffusion/package-lock.json
- node-services/cards-external-diffusion/package.json
- node-services/cards-reminder/docker/Dockerfile
- node-services/cards-reminder/package-lock.json
- node-services/cards-reminder/package.json
- node-services/common/package-lock.json
- node-services/common/package.json
- node-services/supervisor/docker/Dockerfile
- node-services/supervisor/package-lock.json
- node-services/supervisor/package.json
- src/tooling/migration-entity-roles/Dockerfile
- src/tooling/migration-opfab3/Dockerfile
-  In chapter :  Dependencies upgrade
-  Text : Node.js 20.11.0
> Upgrade node to 20.11.0

- services/cards-publication/build.gradle
> Solve security issue with old version of common compress in cards-publication build

- bin/dependencies/generateDependencyReport.sh
- node-services/cards-external-diffusion/build.gradle
- node-services/cards-reminder/build.gradle
- node-services/common/build.gradle
- node-services/supervisor/build.gradle
- ui/main/build.gradle
> Use 'npm ci' instead of 'npm install' to ensure consistent dependencies

- src/test/cypress/cypress/integration/BuildInTemplates.spec.js
- ui/main/src/app/business/buildInTemplates/message-or-question-list/card/message-or-question-listCardTemplate.ts
- ui/main/src/app/business/buildInTemplates/message-or-question-list/card/message-or-question-listCardTemplateView.spec.ts
- ui/main/src/app/business/buildInTemplates/message-or-question-list/card/message-or-question-listCardTemplateView.ts
- ui/main/src/app/business/buildInTemplates/message-or-question-list/usercard/message-or-question-listUserCardTemplate.ts
- ui/main/src/app/business/buildInTemplates/message-or-question-list/usercard/message-or-question-listUserCardTemplateView.spec.ts
- ui/main/src/app/business/buildInTemplates/message-or-question-list/usercard/message-or-question-listUserCardTemplateView.ts
- ui/main/src/app/business/buildInTemplates/message/messageCardTemplate.ts
- ui/main/src/app/business/buildInTemplates/message/messageUserCardTemplateView.ts
- ui/main/src/assets/js/opfab.js
Fix #5737
-  Text : #5737 : Add rich text editor in message or question list build in template
> Add rich text editor in message or question list build in template (#5737)

- ui/main/src/app/app.module.ts
- ui/main/src/app/modules/devtools/richtext/richtext.component.html
- ui/main/src/app/modules/devtools/richtext/richtext.component.ts
- ui/main/src/app/modules/devtools/richtext/richtext.module.ts
- ui/main/src/app/router/app-routing.module.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
Fix #5777 
I wonder if we should add to release note as it is an hidden feature
> Add a helper page to deal with delta quills format (#5777)

- node-services/cards-external-diffusion/config/default-docker.yml
- node-services/cards-external-diffusion/config/default.yml
- node-services/cards-external-diffusion/package-lock.json
- node-services/cards-external-diffusion/package.json
- node-services/cards-external-diffusion/src/cardsExternalDiffusion.ts
- node-services/cards-external-diffusion/src/domain/application/cardsDiffusionControl.ts
- node-services/cards-external-diffusion/tests/cardsDiffusionControl.test.ts
- node-services/common/src/common/server-side/opfabServicesInterface.ts
- src/test/resources/bundles/defaultProcess_V1/config.json
- src/test/resources/bundles/defaultProcess_V1/template/contingencies.handlebars
- src/test/resources/bundles/defaultProcess_V1/template/contingenciesMail.handlebars
-  Text : #5729 Added content of the cards to the mail body
> Added content of the cards to the mail #5729

- src/docs/asciidoc/reference_doc/build-in_templates.adoc
- src/test/resources/bundles/messageOrQuestionExample/i18n.json
- src/test/resources/businessData/message-and-question-list
- ui/main/src/app/business/buildInTemplates/message-or-question-list/usercard/message-or-question-listUserCardTemplate.ts
- ui/main/src/app/business/buildInTemplates/message-or-question-list/usercard/message-or-question-listUserCardTemplateView.spec.ts
- ui/main/src/app/business/buildInTemplates/message-or-question-list/usercard/message-or-question-listUserCardTemplateView.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
-  Text : #5736 : Add the summary as an option in the buildin template of "message or question list" usercard
> Add the summary as an option in the buildin template of "message or question list" usercard (#5736)

- services/cards-publication/build.gradle
- services/cards-publication/src/main/modeling/swagger.yaml
> Remove swagger generation of controller for cards-publication service (#5759)

- src/test/cypress/cypress/integration/ActivityArea.spec.js
- ui/main/src/app/modules/activityarea/activityarea.component.html
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
Fix #5491 
-  Text : #5491 :  Activity area: show a message when user has no activity area
> Activity area: show a message when user has no activity area (#5491)

- config/dev/common-dev.yml
- config/docker/common.yml
- node-services/cards-external-diffusion/config/default.yml
- node-services/cards-reminder/config/default.yml
- node-services/supervisor/config/default.yml
- services/cards-publication/src/main/java/org/opfab/cards/publication/controllers/CardController.java
not in release note as it will be introduce in a previous release
> Solve issue : JWT Login claim parameter is not take into account for read and unack (#5799)

- src/test/externalWebAppExample/index.html
- ui/main/src/app/business/services/global-style.service.ts
- ui/main/src/app/business/view/navbar/navbarMenu.view.spec.ts
- ui/main/src/app/business/view/navbar/navbarMenu_OnMenuClick.view.spec.ts
- ui/main/src/shared/css/opfab-application.css
- ui/main/src/shared/js/opfab-application.js
> Refactoring night/day mode style management (#5790)

- node-services/cards-external-diffusion/build.gradle
- node-services/cards-external-diffusion/docker/Dockerfile
- node-services/cards-reminder/build.gradle
- node-services/cards-reminder/docker/Dockerfile
- node-services/supervisor/build.gradle
- node-services/supervisor/docker/Dockerfile
> Optimize node services docker build

- src/docs/asciidoc/resources/migration_guide_to_4.2.adoc
- src/tooling/migration-entity-roles/cleanMongoAfterMigration.sh
- src/tooling/migration-entity-roles/launchMigration.sh
- src/tooling/migration-entity-roles/migration-entity-roles.js
> Update entity role migration script to add a final clean (#5749)

- ui/main/src/app/modules/usercard/usercard.component.ts
> Minor adjustment in usercard component to prevent errors

- services/businessconfig/src/main/java/lombok.config
- services/businessconfig/src/main/java/org/opfab/businessconfig/controllers/BusinessconfigController.java
- services/businessconfig/src/main/java/org/opfab/businessconfig/model/EntitiesTree.java
- services/businessconfig/src/main/java/org/opfab/businessconfig/model/I18n.java
- services/businessconfig/src/main/java/org/opfab/businessconfig/model/Monitoring.java
- services/businessconfig/src/main/java/org/opfab/businessconfig/model/MonitoringExport.java
- services/businessconfig/src/main/java/org/opfab/businessconfig/model/MonitoringExportField.java
- services/businessconfig/src/main/java/org/opfab/businessconfig/model/Process.java
- services/businessconfig/src/main/java/org/opfab/businessconfig/model/ProcessGroup.java
- services/businessconfig/src/main/java/org/opfab/businessconfig/model/ProcessGroups.java
- services/businessconfig/src/main/java/org/opfab/businessconfig/model/ProcessStates.java
- services/businessconfig/src/main/java/org/opfab/businessconfig/model/ProcessUiVisibility.java
- services/businessconfig/src/main/java/org/opfab/businessconfig/model/RealTimeScreen.java
- services/businessconfig/src/main/java/org/opfab/businessconfig/model/RealTimeScreens.java
- services/businessconfig/src/main/java/org/opfab/businessconfig/model/ResourceTypeEnum.java
- services/businessconfig/src/main/java/org/opfab/businessconfig/model/Response.java
- services/businessconfig/src/main/java/org/opfab/businessconfig/model/ScreenColumn.java
- services/businessconfig/src/main/java/org/opfab/businessconfig/model/UserCard.java
- services/businessconfig/src/main/java/org/opfab/businessconfig/services/ProcessesService.java
- services/businessconfig/src/test/java/org/opfab/businessconfig/controllers/BusinessconfigControllerForMonitoringShould.java
- services/businessconfig/src/test/java/org/opfab/businessconfig/services/ProcessesServiceShould.java
> Remove lombok from business config service

- node-services/cards-external-diffusion/src/cardsExternalDiffusion.ts
- node-services/cards-external-diffusion/src/domain/application/cardsDiffusionControl.ts
- node-services/cards-external-diffusion/src/domain/client-side/cardsExternalDiffusionService.ts
- node-services/cards-external-diffusion/src/domain/server-side/BusinessConfigOpfabServicesInterface.ts
- node-services/cards-external-diffusion/tests/cardsDiffusionControl.test.ts
- node-services/common/src/common/server-side/opfabServicesInterface.ts
- tools/generic/utilities/src/main/java/org/opfab/utilities/eventbus/rabbit/RabbitEventBus.java
> Added cache to email content #5787

- src/docs/asciidoc/community/workflow.adoc
> Modifiy branch naming convention

- node-services/cards-external-diffusion/src/domain/server-side/BusinessConfigOpfabServicesInterface.ts
- node-services/cards-external-diffusion/src/domain/server-side/handlebarsHelpers.ts
- node-services/cards-external-diffusion/tests/cardsDiffusionControl.test.ts
- src/test/resources/bundles/defaultProcess_V1/template/contingencies.handlebars
- src/test/resources/bundles/defaultProcess_V1/template/contingenciesMail.handlebars
- ui/main/src/app/business/services/card/handlebars.service.ts
- ui/main/src/app/business/services/card/handlebarsHelper.ts
-  Text : #5731 Added handlerBars helpers to node service for sending mails
> Added handlerBars helpers to node service (#5731)

- ui/main/src/app/business/services/card/handlebars.service.ts
> Fixed the subscription to locale in handlebar

- src/docs/asciidoc/reference_doc/mail_notification.adoc
> Completed email documentation (#5830)

- node-services/cards-reminder/build.gradle
> Fix bug when building cards-reminder with a proxy for internet access

- ui/main/.eslintrc.json
- ui/main/angular.json
- ui/main/build.gradle
- ui/main/src/app/modules/admin/components/table/admin-table.directive.ts
- ui/main/src/app/modules/admin/components/table/businessData-table.component.ts
- ui/main/src/app/modules/admin/components/table/entities-table.component.ts
- ui/main/src/app/modules/admin/components/table/groups-table.component.ts
- ui/main/src/app/modules/admin/components/table/perimeters-table.component.ts
- ui/main/src/app/modules/admin/components/table/processes-table.component.ts
- ui/main/src/app/modules/admin/components/table/supervised-entities-table.component.ts
- ui/main/src/app/modules/admin/components/table/users-table.component.ts
- ui/main/src/app/modules/archives/archives.component.html
- ui/main/src/app/modules/feed/components/card-list/filters/feed-filter/feed-filter.component.html
- ui/main/src/app/modules/logging/logging.component.html
- ui/main/src/app/modules/processmonitoring/processmonitoring.component.html
- ui/main/src/app/modules/share/archives-logging-filters/archives-logging-filters.component.html
- ui/main/src/app/modules/share/archives-logging-filters/archives-logging-filters.component.ts
- ui/main/src/app/modules/share/datetime-filter/datetime-filter.component.ts
- ui/main/src/app/modules/usercard/datesForm/usercard-dates-form.component.html
- ui/main/src/assets/js/opfab.js
- ui/main/src/tests/mocks/opfabApi.mock.ts
> Add eslint in build process and correct eslint issues

- config/docker/ui-config/web-ui.json
- config/docker/users.yml
> Removed dead code

- src/test/api/karate/businessconfig/resources/bundle_api_test/config.json
- src/test/api/karate/businessconfig/resources/bundle_api_test/template/email_template.handlebars
- src/test/api/karate/cards-external-diffusion/cardsExternalDiffusion.feature
> Added karate test for mail content (#5828)

- client/cards/src/main/java/org/opfab/cards/model/CardOperationTypeEnum.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/controllers/CardController.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/model/CardOperationTypeEnum.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/mongo/CardRepositoryImpl.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/repositories/CardRepository.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/services/CardNotificationService.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/services/CardProcessingService.java
- services/cards-publication/src/main/modeling/swagger.yaml
- services/cards-publication/src/test/java/org/opfab/cards/publication/mocks/CardRepositoryMock.java
- src/test/api/karate/cards/cardsUserAcks.feature
- src/test/cypress/cypress/integration/Acknowledgment.spec.js
- src/test/cypress/cypress/integration/EntityAcknowledgment.spec.js
- ui/main/src/app/business/model/card-operation.model.ts
- ui/main/src/app/business/server/acknowledge.server.ts
- ui/main/src/app/business/services/acknowledge.service.ts
- ui/main/src/app/business/store/lightcards/lightcards-store.ts
- ui/main/src/app/modules/card/components/card-ack/card-ack.component.ts
- ui/main/src/app/modules/card/components/card-acks-footer/card-acks-footer.component.ts
- ui/main/src/app/modules/card/components/card-footer-text/card-footer-text.component.ts
- ui/main/src/app/server/angularAcknowledgement.server.ts
Fix #5049 
-  Text : #5049 : Implement cancel ack at the entity level
> Implement cancel ack at the entity level (#5049)

- ui/main/src/app/business/store/lightcards/lightcards-store.ts
- ui/main/src/app/modules/card/components/card-ack/card-ack.component.ts
> Fix eslint issues

- src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc
- src/docs/asciidoc/resources/migration_guide_to_4.2.adoc
- ui/main/src/app/business/model/feed-filter.model.ts
- ui/main/src/app/business/store/lightcards/lightcards-filter.spec.ts
- ui/main/src/app/business/store/lightcards/lightcards-filter.ts
- ui/main/src/app/modules/feed/components/card-list/card-list.component.html
- ui/main/src/app/modules/feed/components/card-list/card-list.component.ts
- ui/main/src/app/modules/feed/components/card-list/filters/feed-filter/feed-filter.component.html
- ui/main/src/app/modules/feed/components/card-list/filters/feed-filter/feed-filter.component.ts
- ui/main/src/app/modules/feed/feed.module.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
Fix #5815
-  Text : #5815 : Add a filter by process in feed filter screen
> Add a filter by process in feed filter screen (#5815)

- src/test/cypress/cypress/integration/FeedTests.spec.js
- src/test/cypress/cypress/support/feedCommands.js
> Add a cypress test for filter by process in feed filter screen (#5816)

- src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc
- ui/main/src/app/modules/feed/components/map/map.component.ts
-  Text : #5784 : Geomap pop up : option to show summary
> Geomap pop up : option to show summary (#5784)

- config/docker/ui-config/web-ui.json
- src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc
- ui/main/src/app/modules/feed/components/map/map.component.ts
-  Text : #5844 : Geographical map: visualize which Polygon representing a line on the geo-map belongs to which card in the card list
> Geographical map: visualize which Polygon representing a line on the geo-map belongs to which card in the card list (#5844)

- config/docker/ui-config/web-ui.json
- src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc
- src/docs/asciidoc/resources/migration_guide_to_4.2.adoc
- ui/main/src/app/business/services/process-states-multi-select-options.service.ts
- ui/main/src/app/business/store/lightcards/lightcards-filter.spec.ts
- ui/main/src/app/business/store/lightcards/lightcards-filter.ts
- ui/main/src/app/modules/feed/components/card-list/card-list.component.html
- ui/main/src/app/modules/feed/components/card-list/card-list.component.ts
- ui/main/src/app/modules/feed/components/card-list/filters/feed-filter/feed-filter.component.html
- ui/main/src/app/modules/feed/components/card-list/filters/feed-filter/feed-filter.component.ts
Fix #5817 
-  Text : #5817 : Add a filter by state in feed filter screen
> Add a filter by state in feed filter screen (#5817)

- src/test/cypress/cypress/integration/FeedTests.spec.js
- src/test/cypress/cypress/support/feedCommands.js
> Add a cypress test for filter by state in feed filter screen (#5818)

- ui/main/src/app/modules/dashboard/dashboard.component.html
- ui/main/src/app/modules/dashboard/dashboard.component.scss
- ui/main/src/app/modules/dashboard/dashboard.component.ts
- ui/main/src/app/modules/feed/components/card-list/card-list.component.html
- ui/main/src/app/modules/feed/components/card-list/card-list.component.ts
- ui/main/src/app/modules/feed/components/card-list/filters/feed-filter/feed-filter.component.ts
- ui/main/src/app/modules/feed/feed.component.html
- ui/main/src/app/modules/feed/feed.component.ts
Fix #5819
-  Text : #5819 : Add link from Dashboard to Feed setting process/state filters
> Add link from Dashboard to Feed setting process/state filters (#5819)

- src/test/cypress/cypress/integration/Dashboard.spec.js
> Add a cypress test for redirection to feed from dashboard (#5820)

- ui/main/src/app/modules/processmonitoring/components/processmonitoring-table/processmonitoring-table.component.ts
> Monitoring processus screen : fix problem related to upgrade of ag-grid (#5881)

- node-services/cards-external-diffusion/src/domain/application/cardsDiffusionControl.ts
- node-services/cards-external-diffusion/tests/cardsDiffusionControl.test.ts
> Fixed URL string for emails (#5890)

- ui/main/src/app/modules/core/about/about.component.html
- ui/main/src/app/modules/navbar/navbar.component.html
> Fixed missing logo (#5887)

- ui/main/src/app/modules/share/light-card/light-card.component.ts
> Fix card detail open after redirection from dashboard (#FE-5896)

- ui/main/src/app/modules/admin/components/table/admin-table.directive.scss
- ui/main/src/app/modules/admin/components/table/admin-table.directive.ts
- ui/main/src/app/modules/admin/components/table/supervised-entities-table.component.ts
- ui/main/src/app/modules/admin/components/table/users-table.component.ts
> Added max width to the columns in admin table (#5893)

- services/cards-consultation/src/main/java/org/opfab/cards/consultation/model/LightCard.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/model/LightCard.java
> Fix Ligthcard rRule serialization (#5892)

- node-services/cards-external-diffusion/src/domain/application/cardsDiffusionControl.ts
- node-services/cards-external-diffusion/tests/cardsDiffusionControl.test.ts
> Solve issue Mail notif : the text associated to the link is truncated  in the mail body (#5905)

- node-services/cards-external-diffusion/src/domain/client-side/configService.ts
> Fix send mail rate limiter configuration (#5897)

- ui/main/src/app/modules/processmonitoring/processmonitoring.component.ts
> Monitoring processus: reset does not remove cards filtering (#5886)

- node-services/common/.eslintrc.json
- node-services/common/.prettierrc.json
- node-services/common/build.gradle
- node-services/common/package-lock.json
- node-services/common/package.json
- node-services/common/src/common/server-side/authorizationService.ts
- node-services/common/src/common/server-side/eventBus.ts
- node-services/common/src/common/server-side/eventListener.ts
- node-services/common/src/common/server-side/getResponse.ts
- node-services/common/src/common/server-side/jwtTokenUtils.ts
- node-services/common/src/common/server-side/logger.ts
- node-services/common/src/common/server-side/opfabServicesInterface.ts
- node-services/common/tsconfig.json
> Add eslint/prettier for common node services code

- ui/main/build.gradle
- web-ui/web-ui.gradle
> Optimize gradle cache for ui

- src/test/api/karate/cards/getCardSubscription.feature
Fix #5917 
Nothing in  release note
> Check rRule card field on cards subscription (#5917)

- client/users/src/main/java/org/opfab/users/model/PermissionEnum.java
- client/users/src/main/java/org/opfab/users/model/RolesEnum.java
- services/users/src/main/java/org/opfab/users/model/PermissionEnum.java
- services/users/src/main/java/org/opfab/users/model/RolesEnum.java
Fix #5872 
Refactored PermissionEnum an not RightsEnum
Nothing In release note
> Refactoring enum objects in users service (#5872)

- src/docs/asciidoc/resources/migration_guide_to_4.1.adoc
> Fixed markdown syntax

- services/businessconfig/src/main/java/org/opfab/businessconfig/controllers/BusinessconfigController.java
- services/businessconfig/src/main/java/org/opfab/businessconfig/services/ProcessesService.java
- tools/generic/utilities/src/main/java/org/opfab/utilities/PathUtils.java
- Consolidated all security controls into processesServices.
- Added javadoc in PathUtils to alert developers about potential path traversal vulnerabilities.
> Minor code adjustments for improved path traversal security control  in opfab 

- node-services/cards-external-diffusion/src/domain/application/cardsDiffusionControl.ts
- node-services/cards-external-diffusion/tests/cardsDiffusionControl.test.ts
Fix #5921 
-  Text : #5921 : Do not try again to send mail for user rate limited
> Do not retry to send mail for user rate limited (#5921)

- node-services/cards-external-diffusion/src/cardsExternalDiffusion.ts
- node-services/cards-external-diffusion/tests/cardsDiffusionControl.test.ts
- node-services/cards-external-diffusion/tests/configService.test.ts
- node-services/cards-external-diffusion/tests/opfabservicesInterface.test.ts
- node-services/cards-reminder/src/cardsReminder.ts
- node-services/cards-reminder/tests/cardsReminderControl.test.ts
- node-services/cards-reminder/tests/cardsReminderService.test.ts
- node-services/common/src/common/server-side/logger.ts
- node-services/supervisor/src/supervisor.ts
- node-services/supervisor/src/tests/acknowledgementChecker.test.ts
- node-services/supervisor/src/tests/configService.test.ts
- node-services/supervisor/src/tests/connectionChecker.test.ts
- node-services/supervisor/src/tests/opfabservicesInterface.test.ts
- src/docs/asciidoc/deployment/index.adoc
- src/test/resources/logs/getLogsNodeService.sh
- src/test/resources/logs/setLogs.sh
- src/test/resources/logs/setLogsNodeService.sh
Fix #5869 
-  Text : #5869 : Add logLevel endpoint for node services
> Add logLevel endpoint for node services (#5869)

- node-services/supervisor/package.json
- node-services/supervisor/src/domain/application/acknowledgmentChecker.ts
- node-services/supervisor/src/domain/application/card.ts
- node-services/supervisor/src/domain/application/connectionChecker.ts
- node-services/supervisor/src/supervisor.ts
> Adjust eslint config for supervisor

- services/users/src/main/java/org/opfab/users/model/Group.java
- services/users/src/main/java/org/opfab/users/services/GroupsService.java
- services/users/src/main/modeling/swagger.yaml
- src/test/cypress/cypress/integration/Admin.spec.js
- ui/main/src/app/modules/admin/components/editmodal/groups/edit-group-modal.component.html
- ui/main/src/app/modules/admin/components/editmodal/groups/edit-group-modal.component.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
Fix #5870
-  Text : #5870 : Add the possibility to manage user group membership in the group creation/modification screen
> Add the possibility to manage user group membership in the group creation/modification screen (#5870)

- ui/main/.eslintrc.json
- ui/main/package-lock.json
- ui/main/package.json
> Add eslint rules to avoid focus test in ui code

- node-services/cards-external-diffusion/src/domain/application/cardsDiffusionControl.ts
- node-services/cards-external-diffusion/src/domain/server-side/cardsExternaDiffusionDatabaseService.ts
- node-services/cards-external-diffusion/tests/cardsDiffusionControl.test.ts
- src/test/api/karate/cards-external-diffusion/cardsExternalDiffusion.feature
- src/test/resources/cards/defaultProcess/message.json
> Mail service checks cards with mongo

- config/docker/ui-config/web-ui.json
- src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc
- src/test/cypress/cypress/integration/LoginPage.spec.js
- src/test/cypress/cypress/integration/Logout.spec.js
- ui/main/src/app/authentication/auth.service.ts
- ui/main/src/app/business/server/application-router.ts
- ui/main/src/app/business/services/router.service.ts
- ui/main/src/app/business/services/services-config.ts
- ui/main/src/app/router/app-routing.module.ts
- ui/main/src/app/services/angularRouterService.ts
- ui/main/src/tests/mocks/applicationRouter.mock.ts
Do not set hardcoded default value for entry page, use instead defaultEntryPage value in web-ui.json
Add a cypress test to check the feature
-  In chapter :  Features  
-  Text : #5612 Add an option to set the defaut opfab entry page
> Add an option to set the default opfab entry page (#5612)

- ui/main/src/app/modules/realtimeusers/realtimeusers.component.html
> Solve issue with realtime user screen title (#5970)

- client/users/src/main/java/org/opfab/users/model/RightsEnum.java
- services/cards-consultation/src/main/java/org/opfab/cards/consultation/repositories/UserUtilitiesCommonToCardRepository.java
- services/cards-consultation/src/main/java/org/opfab/cards/consultation/services/CardRoutingUtilities.java
- services/cards-consultation/src/test/java/org/opfab/cards/consultation/controllers/CardOperationsControllerShould.java
- services/cards-consultation/src/test/java/org/opfab/cards/consultation/repositories/ArchivedCardRepositoryShould.java
- services/cards-consultation/src/test/java/org/opfab/cards/consultation/repositories/CardRepositoryShould.java
- services/cards-consultation/src/test/java/org/opfab/cards/consultation/services/CardRoutingUtilitiesShould.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/services/CardPermissionControlService.java
- services/cards-publication/src/test/java/org/opfab/cards/publication/services/CardPermissionControlServiceShould.java
- services/cards-publication/src/test/java/org/opfab/cards/publication/services/CardProcessServiceShould.java
- services/users/src/main/java/org/opfab/users/model/CurrentUserWithPerimeters.java
- services/users/src/main/java/org/opfab/users/model/RightsEnum.java
- services/users/src/test/java/org/opfab/users/model/CurrentUserWithPerimetersDataShould.java
- services/users/src/test/java/org/opfab/users/services/GroupsServiceShould.java
- services/users/src/test/java/org/opfab/users/services/PerimetersServiceShould.java
- services/users/src/test/java/org/opfab/users/services/UserSettingsServiceShould.java
- services/users/src/test/java/org/opfab/users/services/UsersServiceShould.java
- tools/spring/spring-mongo-utilities/src/main/java/org/opfab/springtools/configuration/mongo/MongoConfiguration.java
- tools/spring/spring-test-utilities/src/main/java/org/opfab/springtools/configuration/test/OpFabUserDetails.java
> Solve issue : rights enum shall not be in uppercase in database (#5973)

- ui/main/src/app/modules/admin/admin-routing.module.ts
Fix #5938 
-  Text : #5938 : Fix admin screen reload error
> Fix admin screen reload error (#5938)

- gradle.properties
- In release note https://github.com/opfab/release-notes/blob/master/release_notes.4.2.0-RC.2  and in release note https://github.com/opfab/release-notes/blob/master/release_notes.4.2.0.md
-  In chapter :  Dependencies upgrade
-  Text : 
-  org.apache.commons:commons-compress  v1.26.0
-  spring boot  v3.2.3
> Update common-compress and spring boot

- ui/main/src/app/modules/admin/admin-routing.module.ts
> Revert Fix admin screen reload error (#5938)

- ui/main/src/app/business/services/businessconfig/processes.service.ts
- ui/main/src/app/business/view/processmonitoring/processmonitoring.view.spec.ts
- ui/main/src/app/business/view/processmonitoring/processmonitoring.view.ts
- ui/main/src/app/business/view/processmonitoring/processmonitoringPage.ts
- ui/main/src/app/modules/processmonitoring/processmonitoring.component.html
- ui/main/src/app/modules/processmonitoring/processmonitoring.component.scss
- ui/main/src/app/modules/processmonitoring/processmonitoring.component.ts
- ui/main/src/app/modules/processmonitoring/processmonitoring.module.ts
> Refacto process monitoring - first step

- node-services/cards-reminder/build.gradle
> Enforce eslint/prettier on cards-reminder service

- src/docs/asciidoc/community/workflow.adoc
> Adjust documentation for reviewer

- src/tooling/migration-entity-roles/migration-entity-roles.js
> Fix to the entity roles migration script

- ui/main/src/app/modules/activityarea/activityarea.component.html
-  Text : #6010 Fixed the Activity Area checkbox offset
> Fixed the Activity Area checkbox offset (#6010)

- src/test/cypress/cypress/integration/FeedNotificationConfiguration.spec.js
- ui/main/src/app/modules/feedconfiguration/feedconfiguration-routing.module.ts
- ui/main/src/app/modules/feedconfiguration/feedconfiguration.component.html
- ui/main/src/app/modules/feedconfiguration/feedconfiguration.component.scss
- ui/main/src/app/modules/feedconfiguration/feedconfiguration.component.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
Fix #5948 
-  Text : #5948 : Propose to save when exiting notification configuration screen
> Propose to save when exiting notification configuration screen (#5948)

- src/test/cypress/cypress/integration/1-RealTimeUsers.spec.js
- ui/main/src/app/business/view/realtimeusers/realtimeusers.view.spec.ts
- ui/main/src/app/business/view/realtimeusers/realtimeusers.view.ts
-  Text : #6014 Sorted the entities in real time screen and set the clusters' titles to uppercase
> Sorted the entities in real time screen and set the clusters' titles to uppercase (#6014)

- ui/main/src/app/modules/activityarea/activityarea.component.html
> Activity area tick

- ui/main/src/app/modules/admin/components/editmodal/users/edit-user-modal.component.ts
> Ignore false positive sonar security rexgexp issue in edit user modal

- ui/main/src/app/modules/admin/components/editmodal/users/edit-user-modal.component.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
> Fixed typo in IP address regex

- node-services/cards-external-diffusion/Dockerfile
- node-services/cards-reminder/Dockerfile
- node-services/supervisor/Dockerfile
- rabbitmq/Dockerfile
- services/businessconfig/Dockerfile
- services/cards-consultation/Dockerfile
- services/cards-publication/Dockerfile
- services/external-devices/Dockerfile
- services/users/Dockerfile
- src/test/dummyModbusDevice/Dockerfile
- src/test/externalApp/Dockerfile
- src/tooling/migration-entity-roles/Dockerfile
- src/tooling/migration-opfab3/Dockerfile
- ui/main/Dockerfile
> Add sha1 reference for docker images (Security)

- .github/workflows/verify_copyright.yml
> Adjust github copyright workflow permission

- src/docs/asciidoc/security/index.adoc
> Add documentation regarding cyber security

- CICD/github/setOldMongoVersion.sh
> Set old supported version of mongo to 4.4

- src/test/cypress/cypress/integration/ExternalDevicesConfiguration.spec.js
- ui/main/src/app/business/model/external-devices.model.ts
- ui/main/src/app/business/server/external-devices.server.ts
- ui/main/src/app/business/services/notifications/external-devices.service.ts
- ui/main/src/app/modules/externaldevicesconfiguration/editModal/externaldevices-modal.component.html
- ui/main/src/app/modules/externaldevicesconfiguration/editModal/externaldevices-modal.component.ts
- ui/main/src/app/modules/externaldevicesconfiguration/editModal/externaldevicesconfiguration-modal.component.html
- ui/main/src/app/modules/externaldevicesconfiguration/editModal/externaldevicesconfiguration-modal.component.scss
- ui/main/src/app/modules/externaldevicesconfiguration/editModal/externaldevicesconfiguration-modal.component.ts
- ui/main/src/app/modules/externaldevicesconfiguration/externaldevicesconfiguration.module.ts
- ui/main/src/app/modules/externaldevicesconfiguration/table/devices.table.component.ts
- ui/main/src/app/modules/externaldevicesconfiguration/table/externaldevices-directive.html
- ui/main/src/app/modules/externaldevicesconfiguration/table/externaldevicesconfiguration-directive.ts
- ui/main/src/app/server/angularExternalDevices.server.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
Fix #5949 
-  Text : #5949 : Allow to add new external devices from UI
> Allow to add new external devices from UI (#5949)

- .github/workflows/main.yml
Nothing in release note 
For more information : https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#understanding-the-risk-of-script-injections
> Adjust workflow to avoid script injection

- .github/workflows/testWithOldMongo.yml
> Secure TestWithOldMongo workflow

- .github/workflows/main.yml
> Remove unnecessary token in env for build step in main workflow

- ui/main/src/app/business/view/activityarea/activityarea.view.spec.ts
- ui/main/src/app/business/view/activityarea/activityarea.view.ts
-  Text : #6067 : Do not exclude current user connected on activity area screen
> Do not exclude current user connected on activity area screen (#6067)

- src/tooling/migration-entity-roles/package.json
> Update mongo dependency for migration-rrule-recurrence script (#6034) - Release 4.2

- services/businessconfig/src/main/java/org/opfab/businessconfig/services/ProcessesService.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/configuration/SecurityFilterConfiguration.java
> Add security comments in code

- src/docs/asciidoc/docs/single_page_doc.adoc
> Add security doc in single page documentation

- src/tooling/migration-entity-roles/package-lock.json
- src/tooling/migration-entity-roles/package.json
> Updated mongo for entity migration script (#6033)

- src/test/cypress/cypress/integration/UserActionLogs.spec.js
- ui/main/src/app/business/view/useractionlogs/userActionLogs.view.ts
- ui/main/src/app/modules/useractionlogs/useractionlogs.component.html
- ui/main/src/app/modules/useractionlogs/useractionlogs.component.scss
- ui/main/src/app/modules/useractionlogs/useractionlogs.component.ts
-  Text : #6032 : Add an export button for "user action logs" screen
> Add an export button for "user action logs" screen (#6032)

- ui/main/src/app/business/view/navbar/navbarMenu.view.ts
- ui/main/src/app/modules/admin/admin-routing.module.ts
- ui/main/src/app/modules/admin/components/table/admin-table.directive.html
- ui/main/src/app/modules/admin/components/table/admin-table.directive.ts
> Refacto admin page access control in UI (#6025)

- services/users/src/main/java/org/opfab/users/model/Group.java
- services/users/src/main/modeling/swagger.yaml
- services/users/src/test/java/org/opfab/users/services/GroupsServiceShould.java
- src/test/api/karate/users/groups/createGroups.feature
- src/test/api/karate/users/groups/getGroupDetails.feature
- src/test/api/karate/users/groups/getGroups.feature
- src/test/cypress/cypress/integration/Admin.spec.js
- ui/main/src/app/business/model/group.model.ts
- ui/main/src/app/business/services/users/groups.service.ts
- ui/main/src/app/modules/admin/components/editmodal/groups/edit-group-modal.component.html
- ui/main/src/app/modules/admin/components/editmodal/groups/edit-group-modal.component.ts
- ui/main/src/app/modules/admin/components/table/groups-table.component.ts
Fix #6079
- In release notes :
-  Text : #6079: Remove legacy field reatime in group object
> Remove legacy field realtime in group object (#6079)
