opfab/operatorfabric-core

- src/docs/asciidoc/start/index.adoc
Signed-off-by: Damien JEANDEMANGE <damien.jeandemange@rte-france.com>
*Does this PR already have an issue describing the problem ?* _NO_
*What kind of change does this PR introduce?* _doc update_
*What is the current behavior?* _Cannot push card in the GettingStarted tutorial_
*What is the new behavior (if this is a feature change)?* _Card JSON example is now usable in the GettingStarted tutorial_
*Does this PR introduce a breaking change?* _NO_
> fixed invalid JSON example in the 'Getting Started' page

- ui/main/src/app/modules/cards/components/card/card.component.html
- ui/main/src/app/modules/cards/components/card/card.component.spec.ts
- ui/main/src/app/modules/cards/components/card/card.component.ts
- ui/main/src/app/modules/feed/components/card-list/card-list.component.ts
- ui/main/src/app/store/actions/card.actions.ts
- ui/main/src/app/store/effects/card-operation.effects.spec.ts
- ui/main/src/app/store/reducers/card.reducer.spec.ts
- ui/main/src/app/store/reducers/card.reducer.ts
- ui/main/src/app/store/selectors/card.selectors.spec.ts
- ui/main/src/app/store/selectors/card.selectors.ts
- ui/main/src/app/store/states/card.state.ts
For each card in the feed:
If the card has been consulted once then the action buttons should appear 
If the card hasn't been opened yet  then the actions buttons remain hidden
See ticket OC-474
> [OC-474] Hide and display action buttons

- bin/load_environment_light.sh
Anyone who wants to clone for the first time the projet faces this java version not available by running the command “source ./bin/load_environment_light.sh”.
The java version needs to be updated. 
The version 8.0.212-zulu is not in the sdkman list anymore, the newest version is 8.0.222-zulu.
> [OC-500] Updating Java version from 8.0.212-zulu to 8.0.222-zulu

- ui/main/src/app/components/navbar/menus/menu-link/menu-link.component.html
Implementing the solution propsed by Wavestone (adding rel="noopener noreferrer" to links)
> [OC-584] Secure web page opening mechanism

- ui/main/src/assets/styles/style.css
A font-family or font css property should have at least one default value for old browsers
> [OC-561] Fixing the Quality gate

- ui/main/src/app/store/states/feed.state.spec.ts
- ui/main/src/app/store/states/feed.state.ts
Order cards in feed with publishDate in desc order instead of asc order (the first ordering is still severity)
> OC-632 Order feed with publishDate in desc order

- services/infra/config/src/main/docker/volume/dev-configurations/web-ui.yml
- services/infra/config/src/main/docker/volume/docker-configurations/web-ui.yml
- services/web/web-ui/src/docs/asciidoc/configuration.adoc
- ui/main/src/app/modules/settings/components/settings/settings.component.html
- ui/main/src/app/modules/settings/components/settings/settings.component.ts
In user settings all fields there should be maskable.
In that case for eg, developer can choose which fields he wants to present to the user in its user settings.
For let's co the only two fields necessary to display are "Language" and "Timezone".
The rest should be hidden.
> [OC-581] In user settings, all fields there should be maskable

- .travis.yml
Tested on branch: Sonar is still run for branch
> [OC-700] Skip sonar for external PRs

- src/docs/asciidoc/release_notes/1.1.0.RELEASE.adoc
- ui/main/src/app/store/selectors/settings.x.config.selectors.spec.ts
- ui/main/src/app/store/selectors/settings.x.config.selectors.ts
This fixes the fact that in the case of a boolean property the settingOrConfig selector didn't discriminate between a "false" value for settings and no value at all.
So if the property was set to true in config and to false in the settings, it would return true instead of false as expected.
I added tests with a boolean property, no changes to documentation needed (just added it to the release notes).
PS: I deleted function selectMergedSettings as it wasn't used anywhere except in its own test.
> [OC-783] Fix settingsOrConfig selector behaviour for booleans

- services/core/users/src/main/java/org/lfenergy/operatorfabric/users/model/UserSettingsData.java
- services/core/users/src/main/modeling/swagger.yaml
- services/core/users/src/test/java/org/lfenergy/operatorfabric/users/model/UserSettingsDataShould.java
- services/web/web-ui/src/docs/asciidoc/configuration.adoc
- src/docs/asciidoc/release_notes/1.1.0.RELEASE.adoc
- ui/main/src/app/modules/settings/components/settings/checkbox-setting/checkbox-setting.component.html
- ui/main/src/app/modules/settings/components/settings/checkbox-setting/checkbox-setting.component.scss
- ui/main/src/app/modules/settings/components/settings/checkbox-setting/checkbox-setting.component.spec.ts
- ui/main/src/app/modules/settings/components/settings/checkbox-setting/checkbox-setting.component.ts
- ui/main/src/app/modules/settings/components/settings/settings.component.html
- ui/main/src/app/modules/settings/components/settings/settings.component.spec.ts
- ui/main/src/app/modules/settings/components/settings/settings.component.ts
- ui/main/src/app/modules/settings/settings.module.ts
- ui/main/src/app/services/sound-notification.service.spec.ts
- ui/main/src/app/services/sound-notification.service.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
I decided to have four separate settings rather than a list because it made the checkbox component more reusable.
Note: I had to change the names of the configuration properties due to settings constraints.
> [OC-773] Making sound notifications manageable in settings

- services/core/actions/src/main/docker/Dockerfile
The bootstrap.yml file is no longer needed for Actions since it doesn't rely on the Config service anymore, so it should be removed from the Dockerfile otherwise the image can't be built.
> [OC-814] removing bootstrap file copy in Action Dockerfile

- build.gradle
- services/core/actions/src/main/docker/Dockerfile
- services/core/actions/src/main/resources/application-docker.yml
- services/infra/client-gateway/src/main/resources/bootstrap.yml
- services/infra/registry/build.gradle
- services/services.gradle
- src/main/docker/deploy/docker-compose.yml
- Specifying container names in deploy docker-compose so Actions service can refer to the containers in its properties defining where to reach other services (users etc.)
- Adding Spring Cloud Retry dependency back for registry (without it, registry startup fails) -> created OC-833 to investigate
- Adding application-docker.yml file for action service defining config when running in docker mode
Tested that everything worked ok for actions by using the fake third server (launched from modified deploy docker compose so it was on the same network as the other containers).
Other issues created to investigate weird logs / inconsistent behaviour between run_all mode and docker mode: 
- OC-823
- OC-827
- OC-829
- OC-833
> [OC-814] Fixing deploy docker

- .travis.yml
The workaround is to remove the two dependencies that cause the wrong version of typescript to be picked up by Sonar right before running sonar-scanner.
> [OC-865] Adding workaround until Sonar bug is fixed

- services/infra/config/src/main/docker/volume/docker-configurations/client-gateway.yml
Enables usage of `ng serve` with docker deploy configuration.
> configures cors for all routes for docker run-time

- src/docs/asciidoc/reference_doc/users_service.adoc
RELEASE NOTE 
Task : 
[OC-924] Correct OpFab doc dead link in Entities section
[OC-924]: https://opfab.atlassian.net/browse/OC-924
> [OC-924]  OpFab doc  dead link in Entities section

- config/dev/ngnix.conf
- config/docker/default-web-dev.conf
- config/docker/ngnix.conf
Leaves SSE open for one year by setting the `proxy_timeout` for `cardSubscription` to 365 days(the 1y configuration doesn't work).
> sets timeout for SSE to 1 year

- services/core/thirds/src/main/java/org/lfenergy/operatorfabric/thirds/model/ProcessData.java
- services/core/thirds/src/main/java/org/lfenergy/operatorfabric/thirds/model/ProcessStatesData.java
- src/docs/asciidoc/architecture/index.adoc
- src/docs/asciidoc/deployment/configuration/configuration.adoc
- src/docs/asciidoc/deployment/index.adoc
- src/docs/asciidoc/dev_env/launch_dev.adoc
- src/docs/asciidoc/dev_env/requirements.adoc
- src/docs/asciidoc/getting_started/index.adoc
- src/docs/asciidoc/getting_started/troubleshooting.adoc
- src/docs/asciidoc/reference_doc/archives.adoc
- src/docs/asciidoc/reference_doc/bundle_technical_overview.adoc
- src/docs/asciidoc/reference_doc/card_examples.adoc
- src/docs/asciidoc/reference_doc/card_structure.adoc
- src/docs/asciidoc/reference_doc/process_definition.adoc
- src/docs/asciidoc/reference_doc/thirds_service.adoc
- src/docs/asciidoc/resources/index.adoc
- src/docs/asciidoc/resources/migration_guide.adoc
- ui/main/src/app/modules/cards/components/card/card.component.ts
- ui/main/src/app/modules/cards/components/detail/detail.component.ts
- ui/main/src/app/modules/cards/services/handlebars.service.spec.ts
Documentation update accompanying OC-979.
2 files are left to update, signalled by a "TODO OC-979" comment, but we have to decide whether we want to keep them or not.
> OC-979 Documentation update

- services/core/cards-consultation/src/test/java/org/lfenergy/operatorfabric/cards/consultation/TestUtilities.java
- services/core/cards-consultation/src/test/java/org/lfenergy/operatorfabric/cards/consultation/controllers/CardOperationsControllerShould.java
- services/core/cards-consultation/src/test/java/org/lfenergy/operatorfabric/cards/consultation/repositories/CardRepositoryShould.java
- services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/model/CardPublicationData.java
- services/core/cards-publication/src/test/java/org/lfenergy/operatorfabric/cards/publication/controllers/CardControllerShouldBase.java
- services/core/cards-publication/src/test/java/org/lfenergy/operatorfabric/cards/publication/services/CardProcessServiceShould.java
- src/docs/asciidoc/reference_doc/card_structure.adoc
- src/docs/asciidoc/resources/migration_guide.adoc
- src/test/api/karate/cards/cards.feature
- src/test/api/karate/cards/cardsUserAcks.feature
- src/test/api/karate/cards/delete3BigCards.feature
- src/test/api/karate/cards/deleteCardFor3Users.feature
- src/test/api/karate/cards/fetchArchivedCard.feature
- src/test/api/karate/cards/post1BigCards.feature
- src/test/api/karate/cards/post1CardThenUpdateThenDelete.feature
- src/test/api/karate/cards/post2CardsGroupRouting.feature
- src/test/api/karate/cards/postCardFor3Users.feature
- src/test/api/karate/cards/userAcknowledgmentUpdateCheck.feature
- src/test/api/karate/users/perimeters/postCardRoutingPerimeters.feature
- src/test/utils/karate/cards/delete6CardsSeverity.feature
- src/test/utils/karate/cards/post6CardsSeverity.feature
- src/test/utils/karate/operatorfabric-getting-started/message_delete.feature
RELEASE NOTE :
[OC-981]Change way of creating card id . The id of the card is now build as process.processInstanceId and not anymore publisherID_process.
[OC-981]: https://opfab.atlassian.net/browse/OC-981
> [OC-981] Change way of creating card id

- build.gradle
- src/docs/asciidoc/CICD/release_process.adoc
- src/docs/asciidoc/dev_env/index.adoc
Tested by generating documentation locally and comparing using Git, no changes to output files.
No mention necessary in release notes I think.
> [OC-992] Fixing doc generation warnings

- services/core/businessconfig/src/main/docker/volume/businessconfig-storage/TEST/1/config.json
- services/core/businessconfig/src/main/docker/volume/businessconfig-storage/TEST/1/i18n/en.json
- services/core/businessconfig/src/main/docker/volume/businessconfig-storage/TEST/1/i18n/fr.json
- services/core/businessconfig/src/main/docker/volume/businessconfig-storage/TEST/config.json
- services/core/businessconfig/src/main/java/org/lfenergy/operatorfabric/businessconfig/model/ProcessData.java
- services/core/businessconfig/src/main/java/org/lfenergy/operatorfabric/businessconfig/model/ProcessStatesData.java
- services/core/businessconfig/src/main/modeling/swagger.yaml
- services/core/businessconfig/src/test/data/bundles/second/2.0/config.json
- services/core/businessconfig/src/test/data/bundles/second/2.1/config.json
- services/core/businessconfig/src/test/java/org/lfenergy/operatorfabric/businessconfig/controllers/GivenAdminUserThirdControllerShould.java
- src/docs/asciidoc/resources/migration_guide.adoc
- src/test/api/karate/businessconfig/resources/bundle_api_test/i18n/en.json
- src/test/api/karate/businessconfig/resources/bundle_api_test/i18n/fr.json
- src/test/utils/karate/businessconfig/resources/bundle_defaultProcess/config.json
- ui/main/src/app/model/processes.model.ts
- ui/main/src/app/modules/monitoring/monitoring.component.ts
Instead of using i18n objects in the config.json of the bundles
to represent  the name of the processes (json field "name" in the bundle)
and the name of states (json field "name" in the state definition)
, use  a string representing the i18 key .
RELEASE NOTE : nothing to add as this objects was not existing in previous release
> [OC-1066] Remove use of 18n key object

- src/docs/asciidoc/reference_doc/ui_customization.adoc
- ui/main/src/app/modules/businessconfigparty/iframedisplay.component.ts
When opening an external app in an iframe from the menu ,
the night/day mode (or style) is passed in the request
via a param in the GET Request .
Release note :
Features :
[OC-1098] When opening an external app in an iframe from business menu ,the night/day mode (or style) is passed in the request  via a param in the GET Request . When the user switch the mode, the iframe is reloaded.
[OC-1098]: https://opfab.atlassian.net/browse/OC-1098
> [OC-1098] Add day/night mode information in requests

- client/cards/src/main/java/org/lfenergy/operatorfabric/cards/model/PublisherTypeEnum.java
- client/cards/src/main/modeling/config.json
- services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/configuration/mongo/LightCardReadConverter.java
- services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/model/ArchivedCardConsultationData.java
- services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/model/CardConsultationData.java
- services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/model/LightCardConsultationData.java
- services/core/cards-consultation/src/test/java/org/lfenergy/operatorfabric/cards/consultation/TestUtilities.java
- services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/controllers/CardController.java
- services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/model/ArchivedCardPublicationData.java
- services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/model/CardPublicationData.java
- services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/model/LightCardPublicationData.java
- services/core/cards-publication/src/main/modeling/swagger.yaml
- services/core/cards-publication/src/test/java/org/lfenergy/operatorfabric/cards/publication/services/CardProcessServiceShould.java
- src/test/api/karate/cards/cards.feature
- src/test/api/karate/cards/userCards.feature
- ui/main/src/app/model/light-card.model.ts
- ui/main/src/app/modules/logging/logging.component.ts
- ui/main/src/app/services/card.service.ts
Tasks:
- [OC-1118] adds publisher type to cards and sets it to `SYSTEM` when user card end point called ;
- [OC-1119] displays `entity` as sender in `logging page` for `SYSTEM` publisher type.
[OC-1118]: https://opfab.atlassian.net/browse/OC-1118
[OC-1119]: https://opfab.atlassian.net/browse/OC-1119
> [OC-1118] displayes entity as sender in logging page

- services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/repositories/CardCustomRepositoryImpl.java
- ui/main/src/app/services/card.service.ts
Each time we change period of visibility on UI, we get all the card
of the period from the back even if we already have downloaded
previously this period. To avoid that we now memorize the period
already loaded and load only new period from the back
Release note :
Tasks: 
[OC-1155] Optimize loading card from the UI
[OC-1155]: https://opfab.atlassian.net/browse/OC-1155
> [OC-1155] Optimize loading card from the UI

- ui/main/src/app/components/share/datetime-filter/datetime-filter.component.html
Release note :
BUG: 
[OC-1175] Correct bug in datePicker : after opening the calendar, when clicking outside, the calendar shall disappear
[OC-1175]: https://opfab.atlassian.net/browse/OC-1175
> [OC-1175] Correct bug in datePicker

- config/dev/cards-publication-dev.yml
- config/docker/cards-publication-docker.yml
- services/core/businessconfig/src/main/java/org/lfenergy/operatorfabric/businessconfig/model/ResponseData.java
- services/core/businessconfig/src/main/modeling/swagger.yaml
- services/core/businessconfig/src/test/data/bundles/second/2.0/config.json
- services/core/businessconfig/src/test/data/bundles/second/2.1/config.json
- services/core/businessconfig/src/test/java/org/lfenergy/operatorfabric/businessconfig/services/ProcessesServiceShould.java
- src/docs/asciidoc/reference_doc/response_cards.adoc
- src/test/api/karate/businessconfig/getResponseBusinessconfig.feature
- src/test/api/karate/businessconfig/resources/bundle_test_action/config.json
- src/test/api/karate/launchAllBusinessconfig.sh
- ui/main/src/app/model/processes.model.ts
- ui/main/src/app/modules/cards/components/detail/detail.component.ts
[OC-1187](https://opfab.atlassian.net/browse/OC-1187) : Set the external recipient in the business process definition. You can find more information in the documentation : https://opfab.github.io/documentation/current/reference_doc/#_configure_the_response_in_config_json
> [OC-1187] Set the external recipient in the business process definition

- services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/model/ArchivedCardConsultationData.java
- services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/model/CardConsultationData.java
- services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/model/ArchivedCardPublicationData.java
- services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/model/CardPublicationData.java
- services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/model/LightCardPublicationData.java
- services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/services/CardProcessingService.java
- services/core/cards-publication/src/main/modeling/swagger.yaml
- src/docs/asciidoc/reference_doc/response_cards.adoc
- src/test/api/karate/cards/userCards.feature
[[OC-1190](https://opfab.atlassian.net/browse/OC-1190)] Add an option in card to keep child card. You can find more information in the documentation : https://opfab.github.io/documentation/current/reference_doc/#_send_a_question_card
> [OC-1190] Add an option in card to keep child card

- config/dev/web-ui.json
- config/docker/web-ui.json
- ui/main/src/app/modules/feed/components/time-line/init-chart/init-chart.component.ts
BUG 
[OC-1226] When the timeline is hide by the user, dates displayed shall take
into account the date format configured in web-ui.json. It applies
only for the mode TR and 7D
[OC-1226]: https://opfab.atlassian.net/browse/OC-1226
> [OC-1226] Correct bug in date format when timeline is hidden

- build.gradle
- config/monitoring/prometheus.yml
- config/monitoring/startPrometheus.sh
- config/monitoring/stopPrometheus.sh
- services/core/businessconfig/src/main/java/org/lfenergy/operatorfabric/businessconfig/configuration/oauth2/WebSecurityConfiguration.java
- services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/configuration/webflux/WebSecurityConfiguration.java
- services/core/users/src/main/java/org/lfenergy/operatorfabric/users/configuration/oauth2/WebSecurityConfiguration.java
- services/services.gradle
- src/docs/asciidoc/deployment/index.adoc
- src/test/api/karate/admin/getPrometheusMonitoring.feature
- src/test/api/karate/buildAndLaunchAll.sh
- src/test/api/karate/karate-config.js
- src/test/api/karate/launchAllAdmin.sh
Release note:
Features:
[OC-1233] Add prometheus monitoring endpoint (see documenation https://opfab.github.io/documentation/current/deployment/#_monitoring) 
[OC-1233]: https://opfab.atlassian.net/browse/OC-1233
> [OC-1233] Add prometheus monitoring endpoint

- services/core/users/src/main/java/org/lfenergy/operatorfabric/users/controllers/CustomExceptionHandler.java
[OC-1248](https://opfab.atlassian.net/browse/OC-1248) : Users service : do not trace the stack trace exception, only the message
> [OC-1248] Users service : do not trace the stack trace exception, only the message

- client/cards/src/main/avro/card.avsc
- client/cards/src/main/avro/cardCommand.avsc
- services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/kafka/card/CardCommandFactory.java
- services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/kafka/command/BaseCommandHandler.java
- services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/kafka/command/CreateCardCommandHandler.java
- services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/kafka/command/DeleteCardCommandHandler.java
- services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/kafka/command/UpdateCardCommandHandler.java
- services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/kafka/producer/ResponseCardProducer.java
- services/core/cards-publication/src/test/java/org/lfenergy/operatorfabric/cards/publication/kafka/card/CardCommandFactoryShould.java
- services/core/cards-publication/src/test/java/org/lfenergy/operatorfabric/cards/publication/kafka/command/BaseCommandHandlerShould.java
- services/core/cards-publication/src/test/java/org/lfenergy/operatorfabric/cards/publication/kafka/producer/KafkaAvroWithoutRegistrySerializerShould.java
- services/core/cards-publication/src/test/java/org/lfenergy/operatorfabric/cards/publication/kafka/producer/ResponseCardProducerShould.java
- src/docs/asciidoc/dev_env/kafka.adoc
[OC-1247]. Moved process and processInstanceId from CardCommand to Card in the AVRO schema. Now Card is a 100% match to the REST API Card. All that is left in CardCommand are properties present in the REST method (like POST, DELETE, UPDATE) that are not available on Kafka
[OC-1247]: https://opfab.atlassian.net/browse/OC-1247
> [OC-1247] Changes to Kafka AVRO scheme for clearity

- src/docs/asciidoc/reference_doc/process_definition.adoc
Frederic, I propose for release notes : 
Documentation :
[OC-1139] Add in documentation : describe notion of processes groups
[OC-1139]: https://opfab.atlassian.net/browse/OC-1139
> [OC-1139] Add in documentation : describe notion of processes groups

- services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/kafka/command/DeleteCardCommandHandler.java
- services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/services/CardProcessingService.java
- services/core/cards-publication/src/test/java/org/lfenergy/operatorfabric/cards/publication/kafka/command/DeleteCardCommandHandlerShould.java
- services/core/cards-publication/src/test/java/org/lfenergy/operatorfabric/cards/publication/services/CardProcessServiceShould.java
[OC-1278] - Delete card without id, but based on process and processInstanceId
Added a new method to delete a card that doesn't need to have its id set. If the id is not set, the id is re-calculated based on the process and processInstanceId. This functionality is needed by Kafka to be able to delete a card.
[OC-1278]: https://opfab.atlassian.net/browse/OC-1278
> Delete card without id, but based on process and processInstanceId

- services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/controllers/CardOperationsController.java
- services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/repositories/CardCustomRepositoryImpl.java
- services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/services/CardSubscription.java
- services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/services/CardSubscriptionService.java
- services/core/cards-consultation/src/test/java/org/lfenergy/operatorfabric/cards/consultation/controllers/CardOperationsControllerShould.java
- services/core/cards-consultation/src/test/java/org/lfenergy/operatorfabric/cards/consultation/services/CardSubscriptionServiceShould.java
- services/core/users/src/main/java/org/lfenergy/operatorfabric/users/controllers/UsersController.java
- tools/spring/spring-oauth2-utilities/build.gradle
- tools/spring/spring-oauth2-utilities/src/test/java/org/lfenergy/operatorfabric/springtools/configuration/oauth/UserServiceCacheShould.java
- tools/spring/spring-oauth2-utilities/src/test/java/org/lfenergy/operatorfabric/springtools/configuration/oauth/jwt/groups/GroupsUtilsShould.java
- tools/spring/spring-oauth2-utilities/src/test/java/org/lfenergy/operatorfabric/springtools/configuration/oauth/jwt/groups/GroupsUtilsWithApplicationFileConfigShould.java
- tools/spring/spring-test-utilities/src/main/java/org/lfenergy/operatorfabric/springtools/configuration/test/UserServiceCacheTestApplication.java
- ui/main/src/app/modules/feedconfiguration/feedconfiguration.component.ts
- ui/main/src/app/services/card.service.ts
This PR concernes [OC-1219](https://opfab.atlassian.net/browse/OC-1219) : Use notification filters to filter the feed of the user
**!! Warning !!** : the unit test receiveCards() in cards-consultation is desactived because it fails everytime with this modification.
> OC-1219 : Use notification filters to filter the feed of the user

- services/services.gradle
- src/docs/asciidoc/community/workflow.adoc
- src/test/externalApp/externalApp.gradle
- web-ui/web-ui.gradle
[OC-824](https://opfab.atlassian.net/browse/OC-824) : dockerTagSnapshot task shouldn't tag latest as well
> [OC-824] dockerTagSnapshot task shouldn't tag latest as well

- ui/main/src/app/services/card.service.ts
[OC-1301](https://opfab.atlassian.net/browse/OC-1301) : Logging - TIME OF ACTION shall be publish date and not start date
> [OC-1301] Logging - TIME OF ACTION shall be publish date and not start date

- src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/i18n/fr.json
- ui/main/src/app/model/line-of-monitoring-result.model.ts
- ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.html
- ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.scss
- ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.ts
- ui/main/src/app/modules/monitoring/monitoring.component.ts
Add a "-"  between start and end date in business date
First column color is severity color (like archives and logging)
Color of the state text is color of the state in config.json
Feature:
[OC-1341] Monitoring screen adjustement
[OC-1341]: https://opfab.atlassian.net/browse/OC-1341
> [OC-1341] Monitoring screen adjustement

- src/test/utils/karate/businessconfig/resources/bundle_defaultProcess/i18n/fr.json
- src/test/utils/karate/businessconfig/resources/bundle_defaultProcess_V0.1/i18n/fr.json
- ui/main/src/app/modules/cards/components/detail/detail.component.scss
- ui/main/src/app/modules/monitoring/components/monitoring-filters/monitoring-filters.component.html
- ui/main/src/app/modules/monitoring/components/monitoring-filters/monitoring-filters.component.scss
- ui/main/src/app/modules/monitoring/components/monitoring-filters/monitoring-filters.component.ts
- ui/main/src/app/modules/share/datetime-filter/datetime-filter.component.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
* No need to make default value configurable like hide/show timeline, by default filters are shown.
* Show/hide value is stored in local storage.
* The "summary" shown when the filters are hidden displays the values from the last sent query (which matches the results that are being displayed)
Meaning that if I send a query filtering on process "Test1", then change to "Test2" (without submitting the query), when I hide the filters the "summary" will display Test1. It might sometimes be confusing for the user but this way at least the filter summary is consistent with the results.
* I didn't do the white/bold style on the summary values (as described in Invision) because it wasn't the case for the existing text displayed when the timeline is hidden, I think we should either do it for both …
> [OC-1322] Add link to hide filter in monitoring screen

- ui/main/src/app/modules/cards/components/detail/detail.component.html
- ui/main/src/app/modules/cards/components/detail/detail.component.scss
- ui/main/src/app/modules/share/countdown/countdown.component.scss
I put "font-size:small" for lttd-icon for having the same value with lttd-text.
I also put "height" and "width": 13px for opfab-icon-help for having the same value than the text next to it, displaying the answers.
I think, this way, everything is aligned vertically, and I find it more harmonious, don't hesitate to tell me if you have remarks.
> [OC-1386] Card header style ajustement

- ui/main/src/app/modules/archives/archives.component.ts
BUG - Archives
Making another search after reseting filters, the old result appear quickly before the results of the new query is displayed
> [OC-1418] Solve bug when querying archives

- ui/main/src/app/modules/admin/admin.component.ts
- ui/main/src/app/modules/admin/components/editmodal/groups-entities/edit-entity-group-modal.component.ts
- ui/main/src/app/modules/admin/components/editmodal/groups-entities/edit-group-modal.component.html
- ui/main/src/app/modules/admin/components/editmodal/users/edit-user-modal.component.html
- ui/main/src/app/modules/admin/components/editmodal/users/edit-user-modal.component.ts
- ui/main/src/app/modules/admin/components/table/action-cell-renderer.component.html
- ui/main/src/app/modules/admin/components/table/action-cell-renderer.component.ts
- ui/main/src/app/modules/admin/components/table/admin-table.component.ts
Gradle launches the ui build with a production flag with triggered the AOT compilation mode, which enforces stricter rules.
In particular: https://angular.io/guide/aot-compiler#public-symbols
This commit fixes these errors, and OC-1437 will make AOT the default so ng build behaves the same as Gradle build.
> [OC-1191_fix] Fix errors detected in production mode

- ui/main/angular.json
Note : PR [OC-1191_fix] should be merged first otherwise this won't build.
I don't know if it's worth mentioning in the release notes?
> [OC-1437] Make AOT compilation the default for ng build

- ui/main/src/app/store/effects/authentication.effects.ts
To test , use  : PASSWORD mode in web-ui and set a small access token lifespan in keycloak 
BUG :
When using PASSWORD flow, once the token is expired the user isn't notified
> [OC-890] When using PASSWORD flow, once the token is expired notify the user

- ui/main/src/app/modules/navbar/navbar.component.html
- ui/main/src/app/modules/navbar/navbar.component.ts
I looked it up and Angular offers ways to deal with the issue of a variable that is not initialized yet when the template is being rendered, but it's mostly if there is something "clever" to do while the data is being prepared (show a placeholder, a little "loading" icon, etc.)...
But it's not the case here, this time is very short, and if the currentPath has not been initialized yet we just won't add the "active" style to any item in the navbar. To do that I felt the easiest way was to add an initialization of the currentPath in the constructor.
I don't think it's worth mentioning in the release notes.
> [OC-1455] Fix undefined currentPath error in console

- ui/main/src/app/modules/share/countdown/countdown.component.ts
The countdown counter disappears for 1 second when changing timeline period choosing a broader period that triggers the reload of cards list.
Release notes:
[OC-1489] Fix bug on delayed display of countdown counter 
[OC-1489]: https://opfab.atlassian.net/browse/OC-1489
> [OC-1489] Fix bug on delayed display of countdown counter

- src/docs/asciidoc/reference_doc/template_description.adoc
- src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/template/en/incidentInProgress.handlebars
- src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/template/en/usercard_incidentInProgress.handlebars
- src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/template/fr/incidentInProgress.handlebars
- src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/template/fr/usercard_incidentInProgress.handlebars
- ui/main/src/app/modules/cards/components/detail/detail.component.ts
- ui/main/src/app/modules/cards/services/handlebars.service.spec.ts
- ui/main/src/app/modules/cards/services/handlebars.service.ts
- ui/main/src/app/services/app.service.ts
There were several issues:
- The fact that the existing card detail remained present in the background when the edition modal was open, which led to conflicts for the template functions referencing elements by id. => solved by closing the detail before opening the edition modal and re-opening it afterwards.
- When editing the card, all impacts where checked regardless of the actual card content because an element with "checked=false" will still render as checked, the checked attribute needs to be absent for the checkbox to be unchecked. => created a custom handlebar helper for that.
The rest of the changes are just fixes for tslint warnings.
In the release notes, under bug:
[OC-1497] Fixing issue with card edition and IT incident example
[OC-1497]: …
> [OC-1497] Fixing issue with card edition and IT incident example

- services/core/cards-consultation/src/main/docker/Dockerfile
- services/core/cards-publication/src/main/docker/Dockerfile
Tested it with the Getting Started by changing the value for checkPerimeterForResponseCard and making sure it was taken into account.
To test, make sure to rebuild your snapshot images locally.
In the release notes under Bugs:
[OC-1526] Fixes configuration in cards-consultation and cards-publication docker images
+
2.1.0.RELEASE images for these two services did not take custom configuration passed through docker-compose into account properly
[OC-1526]: https://opfab.atlassian.net/browse/OC-1526
> [OC-1526] Fixes configuration in cards-consult and card-pub docker images

- config/dev/users-dev.yml
- config/docker/users-docker.yml
- services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/services/processors/impl/UserCardProcessorImpl.java
- services/core/cards-publication/src/test/java/org/lfenergy/operatorfabric/cards/publication/services/CardProcessServiceShould.java
- services/core/users/src/main/java/org/lfenergy/operatorfabric/users/model/EntityData.java
- services/core/users/src/main/modeling/swagger.yaml
- services/core/users/src/test/java/org/lfenergy/operatorfabric/users/configuration/ObjectMapperShould.java
- src/docs/asciidoc/reference_doc/users_management.adoc
- src/test/api/karate/cards/deleteUserCard.feature
- src/test/api/karate/cards/userCards.feature
- src/test/api/karate/users/entities/createEntities.feature
- ui/main/angular.json
- ui/main/src/app/model/entity.model.ts
- ui/main/src/app/modules/admin/components/editmodal/entities/edit-entity-modal.component.html
- ui/main/src/app/modules/admin/components/editmodal/entities/edit-entity-modal.component.ts
- ui/main/src/app/modules/admin/components/table/entities-table.component.ts
- ui/main/src/app/modules/cards/components/detail/detail.component.ts
- ui/main/src/app/modules/usercard/usercard.component.ts
- ui/main/src/app/services/entities.service.spec.ts
- ui/main/src/app/services/entities.service.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
Release notes:
In Features:
[OC-1257] Set groups of entities compatible with response card. Added "entityAllowedToSendCard "boolean field to Entity.
NOTE: If an Entity has entityAllowedToSendCard=false and has child entities, than child entities will be checked recursively 
[OC-1257]: https://opfab.atlassian.net/browse/OC-1257
> [OC-1257] Set groups of entities compatible with reponse card 

- README.adoc
- config/dev/nginx.conf.template
- config/docker/nginx-cors-permissive.conf
- config/docker/nginx.conf
- src/docs/asciidoc/deployment/configuration/security_configuration.adoc
- src/docs/asciidoc/dev_env/launch_dev.adoc
- src/docs/asciidoc/dev_env/troubleshooting.adoc
- src/docs/asciidoc/dev_env/ui.adoc
Release note 
Task :
[OC-1555] Permit to access opfab directly from localhost:2002 without /ui/
[OC-1555]: https://opfab.atlassian.net/browse/OC-1555
> [OC-1555] Permit to access opfab directly from localhost:2002 without /ui/

- config/dev/docker-compose.yml
- config/docker/docker-compose.yml
This branch upgrades the MongoDB docker image from 4.1.1-xenial to 4.4.4-bionic and upgrades the Keycloak docker image from 6.0.1 to 12.0.2 and adds a configuration parameter to support the 'upload_scripts' feature in Keycloak 12.
> [OC-1473] Upgrade MongoDB and Keycloak docker images.

- ui/main/src/app/modules/share/timeline-buttons/timeline-buttons.component.scss
Release note :
BUG 
[OC-1563] Bug Chrome  - Timeline domain list on two lines sometimes
[OC-1563]: https://opfab.atlassian.net/browse/OC-1563
> [OC-1563] Bug Chrome  - Timeline domain list on two lines sometimes

- src/main/docker/java-config-docker-entrypoint.sh
Moved JAVA_OPTIONS environment parameter in docker-entrypoint shell script. In the old position it was placed behind the -jar parameter. This caused java to skip the JAVA_OPTIONS and ignore the optional extra settings.
Signed-off-by: Gerben Danen <gerben.danen@alliander.com>
> [OC-1540] Bug fix in JAVA_OPTIONS in docker-entrypoint script

- .travis.yml
- CICD/travis/check_version.sh
- CICD/travis/upload_doc.sh
- src/docs/asciidoc/CICD/pipeline_conf.adoc
- src/docs/asciidoc/CICD/release_process.adoc
- src/docs/asciidoc/community/workflow.adoc
It changes a few things on the CICD worflow (see doc), especially the use of the ci_latest hook, but I don't think it's necessary to highlight these changes on the release notes as it won't affect users?
In the release notes under "Tasks":
[OC-1554] Adapting CICD for hotfixes
[OC-1554]: https://opfab.atlassian.net/browse/OC-1554
> [OC-1554] Adapting CICD for hotfixes

- build.gradle
- client/client.gradle
Executing "gradle generateSwaggerUI" generates API documentation, with the usual format. Generated files are visible in build directory, for example, here : 
operatorfabric-core/services/core/businessconfig/build/docs/api/index.html
I propose to add nothing in release_notes ?
[OC-1522 ](https://opfab.atlassian.net/browse/OC-1522): Is SpringFox dependency still used ?
> [OC-1522] Is SpringFox dependency still used?

- ui/main/src/app/services/config.service.ts
[OC-1598](https://opfab.atlassian.net/browse/OC-1598) : ConfigService.getConfigValue() : function always returns the fallback if the variable is a boolean set to false (in web-ui.json)
> [OC-1598] ConfigService.getConfigValue() : function always returns the fallback if the variable is a boolean set to false (in web-ui.json)

- ui/main/src/app/modules/cards/components/card-details/card-details.component.ts
OC-1481 : When card references an existing process but for a state that doesn't exist, an error should be thrown
> [OC-1481] When card references an existing process but for a state that doesn't exist, an error should be thrown

- ui/main/package.json
Tasks: 
[OC-1605] Stop angular building for IE11
[OC-1605]: https://opfab.atlassian.net/browse/OC-1605
> [OC-1605] Stop angular building for IE11

- ui/main/src/assets/i18n/en.json
[OC-1608](https://opfab.atlassian.net/browse/OC-1608) : Timeline buttons : replace "7 Day" by "7 Days"
> [OC-1608] Timeline buttons : replace "7 Day" by "7 Days"

- src/docs/asciidoc/resources/migration_guide_to_2.3.adoc
> [OC-1631] Documentation : Error on title "Migration Guide from release 2.2.2 to release 2.3.0"

- .gitignore
- src/test/cypress/package-lock.json
- ui/main/package-lock.json
The [new version of the gradle plugin](https://github.com/opfab/operatorfabric-core/pull/888) used to build the ui relies on npm ci (for reproductibility) rather than npm install.
For it to work, the package-lock.json needs to be committed (this is also coherent with having pinned our dependencies in the package.json).
In release notes, under tasks:
[OC-1630] Adding package-lock.json to git for npm ci
+
NOTE: From now on, if you want to build the ui
* If you have changed anything in the package.json, use `npm install` to install/update the dependency and update the package-lock.json accordingly
* If you just want to reproduce the current state of the ui, use `npm ci`: it will clear node_modules and install dependencies using the versions stated in package-lock.json, ensuring that what …
> [OC-1630] Adding package-lock.json to git for npm ci

- ui/main/src/app/services/perimeters.service.ts
Release notes
[OC-1621] Admin UI - When deleting a Perimeter remove it also from cache
[OC-1621]: https://opfab.atlassian.net/browse/OC-1621
> [OC-1621] Admin UI - When deleting a Perimeter remove it also from cache

- ui/main/package-lock.json
- ui/main/package.json
- ui/main/src/polyfills.ts
Tested on 4200 on Firefox and Chrome, nothing looked off.
ng test & build ok.
In the release notes, under tasks :
[OC-1611] Remove core-js dependency
[OC-1611]: https://opfab.atlassian.net/browse/OC-1611
> [OC-1611] Remove core-js dependency

- ui/main/src/polyfills.ts
This fixes the error message reported by @quinarygio:
```
Error: It looks like your application or one of its dependencies is using i18n.
Angular 9 introduced a global `$localize()` function that needs to be loaded.
Please run `ng add @angular/localize` from the Angular CLI.
(For non-CLI projects, add `import '@angular/localize/init';` to your `polyfills.ts` file.
For server-side rendering applications add the import to your `main.server.ts` file.)
```
I checked that I didn't remove any other import by mistake as part of removing the core-js dependency (OC-1611)
> [OC-1611] Adding localize back to polyfills file

- ui/main/src/app/services/card.service.ts
Added isAuthModeNone check to getSecurityHeader function. This fixes an issue while using authorization mode 'NONE' in combination with the checking of perimeters in the Cards Publication backend. The CardService has two functions that call the getSecurityHeader function. This causes the Authorization header to be overwritten, thereby causing the Cards Publication backend to not allow the user to publish a card. Bonus fix: added a space to a logger in the CardService to format the text the same as the other loggers.
Signed-off-by: Gerben Danen <gerben.danen@alliander.com>
> [OC-1585] Authorization mode 'NONE' fix with CardService and Perimeters.

- renovate.json
The default config excluded any dependencies under "test" so Karate and Cypress were not kept up to date by Renovate.
> [OC-1647] Update Renovate config to handle Karate and Cypress

- ui/main/package-lock.json
- ui/main/package.json
- Remove unused ngx-countdown and npm-audit-html
- Move zone.js and ngrx/store-devtools in dev dependencies only 
> [OC-1645] Npm package cleaning

- services/core/users/src/main/java/org/opfab/users/controllers/GroupsController.java
Release notes
[OC-1634] When changing perimeter attach to a group it is not propagate to the card-publication service
[OC-1634]: https://opfab.atlassian.net/browse/OC-1634
> [OC-1634] When changing perimeter attach to a group it is not propagate to the card-publication service

- ui/main/src/app/modules/cards/components/detail/detail.component.ts
- ui/main/src/app/modules/feed/components/card-list/card-list.component.ts
- ui/main/src/app/services/acknowledge.service.spec.ts
- ui/main/src/app/services/acknowledge.service.ts
- ui/main/src/app/services/action.service.ts
- ui/main/src/app/services/card.service.ts
- ui/main/src/app/services/entities.service.ts
- ui/main/src/app/services/reminder/reminder.service.ts
- ui/main/src/tests/helpers.ts
- ui/main/src/tests/mocks/entities.service.mock.ts
The branch OC-1604_B replace OC-1604 for the ticket, so the PR for the previous branch has been closed whitout being merged and we will merge this PR for the ticket.
Explanations about the work done : 
In the acknowledge.service.ts file, I only left functions directly related to the ack (even when they are not strictly speaking requests).
And I created a new file, action.service.ts, which contains functions allowing to know if the user has the right to answer or not.
And I propose to make another ticket to do a refacto consisting of using this new action service, in the Detail component (OC-1659).
OC-1604 : Acknowledge all cards : manage states with acknowledgmentAllowed set to "OnlyWhenResponseDisabledForUser"
> OC-1604 : Acknowledge all cards : manage states with acknowledgmentAllowed set to "OnlyWhenResponseDisabledForUser"

- ui/main/src/app/modules/cards/components/detail/detail.component.ts
Release notes
[OC-1654] After an update of a question card, the entities that have already answered shall be orange in card header
Note: the entities will be marked in green only  when they answer to the updated version of card
[OC-1654]: https://opfab.atlassian.net/browse/OC-1654
> [OC-1654] After an update of a question card, the entities that have already answered shall be orange in card header

- config/dev/web-ui.json
- config/docker/web-ui.json
- src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc
- ui/main/src/app/modules/feedconfiguration/feedconfiguration.component.html
- ui/main/src/app/modules/feedconfiguration/feedconfiguration.component.ts
- ui/main/src/app/modules/monitoring/components/monitoring-filters/monitoring-filters.component.html
- ui/main/src/app/modules/monitoring/components/monitoring-filters/monitoring-filters.component.ts
- ui/main/src/app/modules/share/archives-logging-filters/archives-logging-filters.component.html
- ui/main/src/app/modules/share/archives-logging-filters/archives-logging-filters.component.ts
- ui/main/src/app/services/processes.service.ts
- ui/main/src/app/services/user.service.ts
[OC-1639](https://opfab.atlassian.net/browse/OC-1639) : Use user perimeter to populate services/process/state list in archives/logging/monitoring/feedconfiguration
Tests performed : 
For notification configuration screen : 
- missing variable : no change for the screen : OK
- variable set to false : no change for the screen : OK
- variable set to true : 
- only the states are present for which a Receive right is granted : OK
- if I remove the userCardExamples3 perimeter from the Dispatcher group (to which operator1 belongs) then the process is not displayed at all : OK (if no more state present for a process then do not display the process)
- if I delete the gridCooperation and question perimeters from the Dispatcher group then the process group is …
> [OC-1639] Use user perimeter to populate services/process/state list in archives/logging/monitoring/feedconfiguration

- AUTHORS.txt
- src/docs/asciidoc/community/index.adoc
Changes to the TSC voting members have been validated by an online vote: https://lists.lfenergy.org/g/opfab-tsc/message/26
Nothing to mention on the release notes.
> [OC-1681] Updating TSC voting members and authors

- ui/main/src/app/modules/usercard/usercard.component.html
[OC-1684](https://opfab.atlassian.net/browse/OC-1684) : Bug in usercard preview when displaying a lot of recipients
To have a lot of entities, I set these entities in users-dev.yml : 
entities:
- id: ENTITY1
name: Control Room 1
description: Control Room 1
parents : ["ALLCONTROLROOMS"]
- id: ENTITY2
name: Control Room 2
description: Control Room 2
parents : ["ALLCONTROLROOMS"]
- id: ENTITY3
name: Control Room 3
description: Control Room 3
parents : ["ALLCONTROLROOMS"]
- id: ALLCONTROLROOMS
name: All Control Rooms 
description: All Control Rooms
entityAllowedToSendCard: false
- id: ENTITY4
name: IT Supervision Center 
description: IT Supervision Center
- id: ENTITY5
name: Control Room 5
description: Control Room 5
parents: ["ALLCONTROLROOMS"]
- id: …
> [OC-1684] Bug in usercard preview when displaying a lot of recipients

- config/docker/web-ui-cypress.json
- services/core/cards-publication/src/main/modeling/swagger.yaml
- src/test/api/karate/cards/cardsUserAcks.feature
- src/test/api/karate/cards/userAcknowledgmentUpdateCheck.feature
- ui/main/src/app/modules/cards/components/detail/detail.component.ts
- ui/main/src/app/services/acknowledge.service.ts
The issue is not a regression from this version (reproduced on version 2.4.0.RELEASE, but likely older than that).
It only happens on first acknowledgments, not unack or subsequent acks.
It happens with the acknowledge all feature as well.
The issue was due to a piece of code meant to trigger sound when reminders came up, which was targeted at update light card actions with hasBeenRead set to false.
The problem is that when a card is first acknowledged, a first update was sent with:
hasBeenAcknowledged: true
hasBeenRead: null 
(then the card was set to read by a second update triggered by the automatic closing of the card details).
The proposed solution is to set hasBeenRead to true in the lightcard update action for acknowledgement.
Tested:
- Acknowledging a single card doesn't trigger …
> [OC-1715] Acknowledging a card shouldn't trigger sound

- ui/main/src/app/model/user.model.ts
- ui/main/src/app/modules/admin/components/editmodal/users/edit-user-modal.component.html
- ui/main/src/app/modules/admin/components/editmodal/users/edit-user-modal.component.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
The ip addresses setting is handled as text input in modal form.  It is supposed to be a comma separated list of ip addresses and it is spitted into a string array before calling the api.
Release notes:
In Task section:
[OC-1695] Add authorized ip address settings in user administration screen
[OC-1695]: https://opfab.atlassian.net/browse/OC-1695
> [OC-1695] Add authorized ip address settings in user administration screen

- ui/main/src/app/modules/cards/components/detail/detail.component.ts
- ui/main/src/app/services/acknowledge.service.ts
- ui/main/src/app/services/reminder/reminder.service.ts
- ui/main/src/app/services/sound-notification.service.spec.ts
- ui/main/src/app/services/sound-notification.service.ts
- ui/main/src/app/store/actions/light-card.actions.ts
- ui/main/src/app/store/effects/card-operation.effects.ts
- ui/main/src/app/store/reducers/light-card.reducer.ts
I reverted the fix I made in OC-1715 so updates triggered by acknowledgement (either single card using the button or all card with the ack all feature) no longer set the card to hasBeenRead = true.
In the case of the single card ack, the ack button triggers a closing of the details which in turns triggers an update of the card with hasBeenRead = true, and which is also propagated to the back.
In the case of the ack all features however, no changes are made to the hasBeenRead property of the card, so the user can tell which card he/she has actually read.
Tests (on 4200 chrome, with cypress-flavoured docker):
- Incoming cards (with send6cards) trigger sounds
- Ack all or single card ack don't trigger sounds
- Ack all sets all cards to acknowledged but read cards stay read and unread stay …
> [OC-1728]  Acknowledging all cards shouldn't change their read status

- services/core/cards-consultation/src/main/java/org/opfab/cards/consultation/model/ArchivedCardConsultationData.java
- services/core/cards-consultation/src/main/java/org/opfab/cards/consultation/model/CardConsultationData.java
- services/core/cards-consultation/src/test/java/org/opfab/cards/consultation/TestUtilities.java
- services/core/cards-consultation/src/test/java/org/opfab/cards/consultation/controllers/CardOperationsControllerShould.java
- services/core/cards-consultation/src/test/java/org/opfab/cards/consultation/repositories/CardRepositoryShould.java
- services/core/cards-publication/src/main/java/org/opfab/cards/publication/model/ArchivedCardPublicationData.java
- services/core/cards-publication/src/main/java/org/opfab/cards/publication/model/CardPublicationData.java
- services/core/cards-publication/src/test/java/org/opfab/cards/publication/services/CardProcessServiceShould.java
- tools/spring/spring-mongo-utilities/src/main/java/org/opfab/springtools/configuration/mongo/MongoConfiguration.java
Indexes are set in two collections : cards and archivedCards
They are set on fields:
- used in requests made by the ui to search cards : startDate, endDate,...
- used to search for cards visibles for the current user (entityRecipients, userRecipients, groupRecipients and processStateKey)
They are defined in two classes using @Index annotation: CardPublicationData and ArchivesCardPublicationData
The automatic creation of the indexes has to be set to true (see tools/spring/spring-mongo-utilities/src/main/java/org/opfab/springtools/configuration/mongo/MongoConfiguration.java)
This was not the case in previous versions of mongoDB Java drive
Tasks : 
OC-1701 : Set indexes in mongoDB
> OC-1701 Set indexes in mongoDB

- services/core/cards-publication/src/main/java/org/opfab/cards/publication/kafka/card/CardCommandFactory.java
OC-1738: Bugfix: When sending a card via Kafka, the child card.data field was by mistake removed.
> [OC-1738] Restore the card data when it is removed before serializing

- src/test/cypress/cypress/integration/ResponseCard.spec.js
- src/test/resources/cards/defaultProcess/questionWithKeepChildCards.json
- ui/main/src/app/store/actions/light-card.actions.ts
- ui/main/src/app/store/effects/card-operation.effects.ts
BUG : When loading application, it can happen that a child card is received
from back before his parent card. In this case when the child card is
a response from an entity of the current user, the blue response arrow
is not seen in feed as it should.
Bugs : 
OC-1736 Correct bug when child card is receive before parent card
> [OC-1736] BUG when child card received before parent card

- services/core/users/src/main/java/org/opfab/users/services/UserServiceImp.java
Release notes:
[OC-1714] Invalid group from token shall not prevent to start application
[OC-1714]: https://opfab.atlassian.net/browse/OC-1714
> [OC-1714] Invalid group from token shall not prevent to start application

- src/test/resources/bundles/userCardExamples3/template/fr/task.handlebars
[OC-1756](https://opfab.atlassian.net/browse/OC-1756) : Typo error in french template of "Exemple de nouvelles cartes 3"
> [OC-1756] Typo error in french template of "Exemple de nouvelles cartes 3"

- build.gradle
- src/docs/asciidoc/deployment/configuration/security_configuration.adoc
- src/docs/asciidoc/dev_env/gradle.adoc
Nothing to mention in release notes.
I went back on the gradle asciidoctor plugin update that caused the issue with links, as there is no hurry to upgrade. I created OC-1770 to handle the change in behaviour in newer versions and do the update when we have the time.
> [OC-1769] Fixing issues with documentation noticed during release

- ui/main/src/app/model/light-card.model.ts
- ui/main/src/app/modules/cards/components/detail/detail.component.ts
- ui/main/src/app/services/acknowledge.service.ts
- ui/main/src/app/services/reminder/reminder.service.ts
- ui/main/src/app/services/sound-notification.service.ts
- ui/main/src/app/store/actions/light-card.actions.ts
- ui/main/src/app/store/effects/card-operation.effects.ts
- ui/main/src/app/store/reducers/light-card.reducer.ts
Refactoring of card read and acknowledge udpates on UI to avoid :
- having deleted card in ngrx store
- having card update from subscription erase by an update due to a read or un ack  (race condition)
BUGS : 
* OC-1750: BUG - Sometimes cards does not show on calendar
> [OC-1750] BUG - Sometimes cards does not show on calendar

- ui/main/src/app/modules/usercard/usercard.component.ts
Release notes
[OC-1752] : User card: changing process/state does not reset startDate, endDate and lttd
[OC-1752]: https://opfab.atlassian.net/browse/OC-1752
> [OC-1752] User card: changing process/state does not reset startDate, endDate and lttd

- src/test/resources/monitoringConfig/monitoringConfig.json
- ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.ts
To test use : 
Load config via  loadMonitoringConfig.sh monitoringConfig.json   in src/test/resources/monitoringConfig
Send card and respond to card 
make the monitoring export , you should see the entity name of the response in the excel file 
Features : 
OC-1691: Add publisherName in child card for custom export in monitoring
> [OC-1691] Add publisherName in child card for custom export in monitoring

- src/test/resources/bundles/defaultProcess_V1/config.json
- ui/main/src/app/modules/monitoring/monitoring.component.ts
Release notes:
[OC-1768] : Make possible the no displaying of a State in the Monitoring screen
NOTE: Cards with a process state without 'type' property are not displayed in monitoring screen 
[OC-1768]: https://opfab.atlassian.net/browse/OC-1768
> [OC-1768] Make possible the no displaying of a State in the Monitoring screen

- .travis.yml
- ui/main/package.json
Should solve at least 3 security issues (test to see if bot closes them or if it's broken).
No need to mention it in release notes as I don't think anyone was using it.
> [OC-1783] Removing Compodoc dependency

- ui/main/src/app/modules/usercard/usercard.component.ts
Release notes
[OC-1791] :Bug when a non existing entity is set in userCard.recipientList
[OC-1791]: https://opfab.atlassian.net/browse/OC-1791
> [OC-1791] Bug when a non existing entity is set in userCard.recipientList

- ui/main/src/app/modules/admin/components/editmodal/perimeters/edit-perimeter-modal.component.ts
The error message displayed is taken from backed response and is not translated
Release notes:
[OC-1761] : Admin interface - Deal with invalid perimeter
[OC-1761]: https://opfab.atlassian.net/browse/OC-1761
> [OC-1761] BUG - Admin interface - Deal with invalid perimeter

- ui/main/src/app/modules/archives/archives.component.html
- ui/main/src/app/modules/archives/archives.component.ts
- ui/main/src/app/modules/feed/components/card-list/filters/feed-filter/feed-filter.component.html
- ui/main/src/app/modules/feed/components/card-list/filters/feed-filter/feed-filter.component.ts
- ui/main/src/app/modules/logging/logging.component.html
- ui/main/src/app/modules/logging/logging.component.ts
- ui/main/src/app/modules/share/datetime-filter/datetime-filter.component.html
- ui/main/src/app/modules/share/datetime-filter/datetime-filter.component.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
Forbidden calendar dates are disabled. A warning message is shown when same date and end time is before start time, on logging and archives the message is shown when clicking on search button. 
Release notes
[1806] : Date filters : make impossible to enter a start date later than end date
> [1806] Date filters : make impossible to enter a start date later than end date

- ui/main/src/assets/styles/styles.scss
Release notes
[OC-1805] : In Archive page the values of service multifilter should not wrap
[OC-1805]: https://opfab.atlassian.net/browse/OC-1805
> [OC-1805] In Archive page the values of service multifilter should not wrap

- ui/main/package-lock.json
- ui/main/package.json
- ui/main/src/app/modules/feed/components/time-line/custom-timeline-chart/custom-timeline-chart.component.ts
#1282 : Update timeline dependency @swimlane/ngx-charts to v18
> Fix #1282 Update timeline dependency @swimlane/ngx-charts to v18

- services/core/users/src/main/java/org/opfab/users/controllers/CustomExceptionHandler.java
- services/core/users/src/test/java/org/opfab/users/controllers/PerimetersControllerShould.java
Release notes
#1272 : Posting a perimeter with blank string state cause 500 internal error
> #1272 Posting a perimeter with blank string state cause 500 internal error

- ui/main/angular.json
- ui/main/package.json
- ui/main/src/environments/environment.ts
- ui/main/src/polyfills.ts
- ui/main/src/test.ts
- ui/main/tsconfig.json
Linked to Angular migration so I don't think it's worth mentioning in the release notes.
> Fix #1393 Perform automatic angular migration to fix slow build

- .travis.yml
- src/docs/asciidoc/CICD/pipeline_conf.adoc
- src/docs/asciidoc/community/workflow.adoc
fix #1353 
This PR remove the doc-dry-run stage from the travis configuration and documentation. It as meant so we could test the documentation generation on the CI without actually publishing to the website, but there's little point (it's not that often that the documentation generation fails and we can test it locally).
No need to mention it in release notes I would say.
> #1353 Removing doc-dry-run stage in Travis

- services/core/users/src/main/java/org/opfab/users/configuration/oauth2/OAuth2UsersConfiguration.java
- tools/spring/spring-oauth2-utilities/src/main/java/org/opfab/springtools/configuration/oauth/OAuth2GenericConfiguration.java
[FE-1412] maps jwt login claims to lowercase.
> [FE-1412] Convert JWT claims to lowercase

- .travis.yml
Fixes #1312 
In release notes, under tasks:
#1312 : Caching cypress installation
Maybe bundle it with other issues under "Speeding up Gradle build"?
> Caching cypress installation (#1312)

- ui/main/build.gradle
Fixes #1413 
Now the ui build and tests are only run if either (or both) of the following statements is true :
1. Something has changed in their inputs:
- src (except for npm install)
- node_modules
- package.json
- package-lock.json
- angular.json
- tslint.json
2. Something has changed in their outputs (most likely, the output has been cleaned): build directory for the build task, reports directory for the test tasks.
I also took this opportunity to remove custom tasks that were neither used nor documented.
I tested changing the source, changing a dependency version in package.json, deleting the build altogether: in all these cases, the ui build is run.
I think it's worth a word in the release notes just in case someone notices the change in behaviour. Under tasks:
* 1413 : Only trigger …
> Only trigger UI build if task is not up to date (#1413)

- .travis.yml
- build.gradle
- ui/main/build.gradle
Fix #1359 
In release notes, under tasks:
#1359 : Remove dependency reporting plugins from Gradle build
+
Reports regarding dependency licences and security vulnerabilities are now provided by [LFX Security](https://security.lfx.linuxfoundation.org/#/a094100001Cb6HaAAJ/foundation-details)
> Removing dependency reporting plugins (#1359)

- src/test/cypress/cypress/integration/Acknowledgment.spec.js
- src/test/cypress/cypress/integration/Archives.spec.js
- src/test/cypress/cypress/integration/FeedConfigurationTests.spec.js
- src/test/cypress/cypress/integration/FeedTests.spec.js
- src/test/cypress/cypress/integration/ResponseCard.spec.js
- src/test/cypress/cypress/integration/StateTypeTests.spec.js
- src/test/cypress/cypress/support/commands.js
- src/test/resources/bundles/cypress/config.json
- src/test/resources/bundles/cypress/i18n/en.json
- src/test/resources/bundles/cypress/i18n/fr.json
- src/test/resources/bundles/defaultProcess_V1/template/fr/question.handlebars
- src/test/resources/cards/cypress/state_types/state_type1.json
- src/test/resources/cards/cypress/state_types/state_type2.json
- src/test/resources/cards/cypress/state_types/state_type3.json
- src/test/resources/cards/cypress/state_types/state_type4.json
- src/test/resources/cards/cypress/state_types/state_type5.json
- src/test/resources/cards/cypress/state_types/state_type6.json
- src/test/resources/cards/cypress/state_types/state_type7.json
- src/test/resources/deleteAllCards.sh
- src/test/resources/perimeters/cypress.json
- ui/main/src/app/app.component.scss
- ui/main/src/app/modules/cards/components/detail/detail.component.html
- ui/main/src/app/modules/cards/components/detail/detail.component.scss
- ui/main/src/app/modules/cards/components/detail/detail.component.ts
- ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.html
- ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.scss
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/scss/styles.scss
Fixes #1430 
In the release notes, under Features:
- #1430 : Card detail header for question cards now displays state type rather than state name
> Updating card detail header to use state type (#1430)

- .travis.yml
> Make travis build fail fast if docker images can't be generated

- src/docs/asciidoc/deployment/configuration/security_configuration.adoc
- ui/main/src/app/services/authentication/authentication.service.ts
Removed checking if user is already existing in OpFab with AuthFlow NONE. Now the user will be automatically created, just like the other AuthFlows. Changed documentation to reflect this change.
Signed-off-by: Gerben Danen <geppyz@gmail.com>
> Fix #1503 Automatic user creation with AuthFlow NONE

- ui/main/build.gradle
> Passing environment as a command line option is not necessary anymore (#1459)

- services/core/businessconfig/src/main/java/org/opfab/businessconfig/model/ProcessStatesData.java
- services/core/businessconfig/src/main/modeling/swagger.yaml
- src/docs/asciidoc/reference_doc/response_cards.adoc
- src/test/cypress/cypress/integration/Archives.spec.js
- src/test/cypress/cypress/integration/FeedNotificationConfiguration.spec.js
- src/test/resources/bundles/cypress/config.json
- src/test/resources/bundles/defaultProcess_V1/config.json
- ui/main/src/app/model/processes.model.ts
- ui/main/src/app/modules/archives/archives.component.html
- ui/main/src/app/modules/feedconfiguration/feedconfiguration.component.ts
- ui/main/src/app/modules/navbar/navbar.component.html
- ui/main/src/app/modules/share/archives-logging-filters/archives-logging-filters.component.ts
Add configuration to exclude some states from the notification configuration screen (#1263). For more information : https://opfab.github.io/documentation/current/reference_doc/#_configure_the_response_in_config_json
> Add configuration to exclude some states from the notification configuration screen (#1263)

- tools/spring/spring-oauth2-utilities/src/main/java/org/opfab/springtools/configuration/oauth/OAuth2GenericConfiguration.java
- tools/spring/spring-oauth2-utilities/src/main/java/org/opfab/springtools/configuration/oauth/jwt/groups/GroupsUtils.java
- tools/spring/spring-oauth2-utilities/src/main/java/org/opfab/springtools/configuration/oauth/jwt/groups/roles/RoleClaim.java
> Sonarcloud warnings : correct "Immediately return this expression instead of assigning it to the temporary variable" (Fix #1622)

- src/test/clientApp/clientApp.gradle
The build of the client application fails with the following message:
> Error: Could not find or load main class org.opfab.client.ClientApplication
> Caused by: java.lang.ClassNotFoundException: org.opfab.client.ClientApplication
Removing "'Main-Class': 'org.opfab.client.ClientApplication'" from the bootJar task in clientApp.gradle (to be consistent with the other bootjar tasks) makes this error go away. I think I remember it had something to do with the spring-boot update a few weeks ago.
> Fixing client app build

- tools/generic/utilities/src/main/java/org/opfab/utilities/AmqpUtils.java
Bugs : 
Persist rabbitMQ consumer queues to be resilient to rabbitMQ restarts (#1669)
> Persist rabbitMQ consumer queues to be resilient to rabbitMQ restarts (#1669)

- src/docs/asciidoc/reference_doc/template_description.adoc
- src/test/resources/bundles/userCardExamples2/template/en/question.handlebars
- src/test/resources/bundles/userCardExamples2/template/fr/question.handlebars
- ui/main/src/app/model/templateGateway.model.ts
- ui/main/src/app/modules/archives/archives.component.html
- ui/main/src/app/modules/archives/archives.component.ts
- ui/main/src/app/modules/calendar/calendar.component.html
- ui/main/src/app/modules/calendar/calendar.component.ts
- ui/main/src/app/modules/cards/components/card-details/card-details.component.ts
- ui/main/src/app/modules/cards/components/detail/detail.component.ts
- ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.html
- ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.ts
- ui/main/src/app/modules/share/card-detail/card-detail.component.ts
- ui/main/src/app/modules/usercard/usercard.component.html
- ui/main/src/app/modules/usercard/usercard.component.ts
- ui/main/src/assets/js/templateGateway.js
Fix #1647 
Release notes:
In Featues section:
#1647 Add getDisplayContext() method to the template to know in which context the rendering is done
> Add getDisplayContext() method to the template to know in which context the rendering is done (#1647)

- ui/main/src/app/modules/share/countdown/countdown.component.html
Fix #1677 
Release notes
#1677 Do not show popover when lttd expired icon is not visible 
> Do not show popover when lttd expired icon is not visible (#1677)

- ui/main/src/app/modules/monitoring/components/monitoring-filters/monitoring-filters.component.html
Fix #1678
Release notes
In bugs section
#1678 Process name not translated in monitoring screen when no process group defined
> Process name not translated in monitoring screen when no process group defined (#1678)

- src/docs/asciidoc/reference_doc/response_cards.adoc
- src/test/cypress/cypress/integration/CardDetail.spec.js
- src/test/resources/bundles/cypress/template/en/kitchenSink.handlebars
- src/test/resources/bundles/cypress/template/fr/kitchenSink.handlebars
- src/test/resources/bundles/userCardExamples2/template/en/question.handlebars
- src/test/resources/bundles/userCardExamples2/template/fr/question.handlebars
- ui/main/src/app/modules/cards/components/detail/detail.component.ts
- ui/main/src/assets/js/templateGateway.js
Fix #1645 
Release notes:
#1645 Add a method for template to get the entity used for response
> Add method getEntityUsedForUserResponse in templateGateway (#1645)

- ui/main/src/app/modules/monitoring/monitoring.component.html
- ui/main/src/app/modules/monitoring/monitoring.component.scss
- ui/main/src/app/modules/monitoring/monitoring.component.ts
Fix #1681 
Release notes
#1681 Add spinner when loading cards on monitoring screen 
> Add spinner when loading cards on monitoring screen (#1681)

- .travis.yml
- build.gradle
- client/cards/build.gradle
- client/client.gradle
- services/core/build.gradle
- services/services.gradle
- settings.gradle
- sonar-project.properties
- src/docs/asciidoc/dev_env/gradle.adoc
- src/test/clientApp/clientApp.gradle
- src/test/externalApp/externalApp.gradle
- tools/tools.gradle
- web-ui/web-ui.gradle
This PR fixes some (but not all, so the issue should remain open) deprecated features in the Gradle build that should allow the  optimizations to work properly on the back, hopefully speeding up the build.
It also removes compatibility properties that likely caused the client jars to still be generated with Java 8 rather than Java 11.
> Fix some deprecated features in Gradle build (#1545)

- src/test/cypress/README.adoc
- src/test/cypress/cypress/integration/Acknowledgment.spec.js
Fixes (#1751 )
See https://github.com/opfab/operatorfabric-core/issues/1751#issuecomment-923017715 for details on the cause of the problem.
I also fixed a test in CardDetails that was susceptible to the same problem (because of the `find` command).
This command is also used extensively in 5 other specs, but for the moment I left them as is and we'll see if they cause any trouble in the future we'll just apply the same solution.
Nothing in the release notes I think as it's only for tests ?
> Fixing flaky Cypress tests (#1751) and adding doc

- config/dev/cards-publication-dev.yml
- config/docker/cards-publication-docker.yml
- services/core/cards-publication/src/main/java/org/opfab/cards/publication/services/clients/impl/ExternalAppClientImpl.java
- src/test/api/karate/cardTests.txt
- src/test/api/karate/cards/externalRecipentErrors.feature
Fix  #1547
Release notes
#1547 : Error messages and status are mixed up in ExternalAppClientImpl 
> Error messages and status are mixed up in ExternalAppClientImpl (#1547)

- src/docs/asciidoc/community/workflow.adoc
- src/docs/asciidoc/deployment/configuration/configuration.adoc
- src/docs/asciidoc/dev_env/kafka.adoc
- src/docs/asciidoc/reference_doc/card_examples.adoc
- src/docs/asciidoc/reference_doc/users_management.adoc
Fixes #1283 
Two warnings remain:
> Sep 21, 2021 2:00:18 PM uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb content
> INFO: possible invalid reference: card_structure
=> I checked the link in the finished document and it works. I think the false positive is due to this reference being used as an example in the documentation guidelines.
> The JavaExecHandleBuilder.setMain(String) method has been deprecated. This is scheduled to be removed in Gradle 8.0. Please use the mainClass property instead. Consult the upgrading guide for further information: https://docs.gradle.org/7.2/userguide/upgrading_version_7.html#java_exec_properties
=> This has to be addressed by the Asciidoctor plugin, as tracked by https://github.com/asciidoctor/asciidoctor-gradle-plugin/issues/602.
No …
> Fixing doc references (#1283)

- src/docs/asciidoc/reference_doc/card_notification.adoc
#1777 Default value for acknowledgmentAllowed is not coherent with documentation
> Default value for acknowledgmentAllowed is not coherent with documentation (#1777)

- services/core/businessconfig/src/main/java/org/opfab/businessconfig/model/ResponseData.java
- services/core/businessconfig/src/main/modeling/swagger.yaml
- src/docs/asciidoc/reference_doc/response_cards.adoc
- src/test/api/karate/businessconfig/getResponseBusinessconfig.feature
- src/test/api/karate/businessconfig/resources/bundle_api_test/config.json
- src/test/resources/bundles/userCardExamples2/config.json
- ui/main/src/app/model/processes.model.ts
- ui/main/src/app/services/user-permissions-.service.ts
Fix #1873 
Release notes
#1873 : Authorize sending response from entity emitting user card. Use 'response.state.emittingEntityAllowedToRespond' field in bundle config.json to enable it.
> Authorize sending response from entity emitting user card (#1873)

- src/test/resources/processGroups/singleProcessGroup.json
- ui/main/src/app/modules/share/archives-logging-filters/archives-logging-filters.component.html
BUGS: 
When no process group define , double select field for process (in archive and logging screens) #2043
> Correct bug when no process group define (#2043)

- config/docker/custom-sounds/README.adoc
- config/docker/docker-compose.yml
- src/docs/asciidoc/reference_doc/card_notification.adoc
In release notes (under tasks?)
#2066 : Explain how sounds for browser notifications can be customized
Note : When testing, clear the cache / or open a new window. I first thought the volume overwrite wasn't working (the old sounds kept playing) but then I opened a new window and it worked (even though I had cache disabled from the start).
> Document sound customization (#2066)

- build.gradle
- services/services.gradle
- src/test/clientApp/clientApp.gradle
- src/test/externalApp/externalApp.gradle
- tools/tools.gradle
- web-ui/web-ui.gradle
Fixes #1350 
In tasks : 
* #1350 : Gradle - Removing legacy/duplicate plugin declaration
Some legacy / duplicate plugin declarations remain where we used subproject, they won't be needed anymore once we address https://github.com/opfab/operatorfabric-core/issues/1361
> Removing legacy plugin declaration when possible (#1350)

- ui/main/src/app/modules/admin/components/editmodal/entities/edit-entity-modal.component.html
- ui/main/src/app/modules/admin/components/editmodal/groups/edit-group-modal.component.html
- ui/main/src/app/modules/admin/components/editmodal/perimeters/edit-perimeter-modal.component.html
- ui/main/src/app/modules/admin/components/editmodal/users/edit-user-modal.component.html
For perimeters, the select dropdown list for the states is sorted but without using the prefix. To be discussed maybe ?
#2027 : Admin UI multiselect are not sorted
> Admin UI multiselect are not sorted (#2027)

- src/test/cypress/cypress/integration/UserCard.spec.js
- ui/main/src/app/modules/usercard/usercard.component.ts
Adding the "distinctUntilChanged" helped as the template was no longer re-rendered when the state value didn't actually change, but the test was still flaky, failing on the CI with a detached DOM error.
After investigating for quite a while, I wasn't able to pinpoint where the unwanted re-creations of the component were coming from, but as @freddidierRTE suggested adding a debounceTime step between state changes and template loading seems to fix the problem consistently (ran it several times on the CI, no failure).
So we're keeping this solution, as in any case it's better not to fire template requests until things have settled down.
> Fixing detached DOM error (#1891)

- src/test/cypress/cypress/integration/UserCard.spec.js
This morning's failure of the UserCard Cypress test on develop (https://app.travis-ci.com/github/opfab/operatorfabric-core/builds/242688841) was different from the previous ones.
In this case, judging by the logs, after filling out the usercard form, previewing it and clicking "send", Cypress doesn't find the card in the feed as expected.
Maybe the card sending (during which a "Sending card" spinner appears) took too long, or there was a problem with the sending. So to guard against that, I added a check that the green confirmation message at the top appeared. And in any case it's good to check that the confirmation message works as expected.
I also added it at the edition step.
Let's hope this fix is the last...
Signed-off-by: Alexandra Guironnet …
> Check on publication message in usercard test (#1891)

- gradle.properties
- services/core/cards-consultation/src/main/java/org/opfab/cards/consultation/configuration/webflux/GlobalErrorWebExceptionHandler.java
Several Spring dependencies updates that needed to be done together.
I had to change one deprecated class.
In the release notes, under Tasks:
* Dependency updates
* * Spring Cloud 2021.0.0
* * Spring OpenFeign 3.1.0
* * Spring Boot 2.6.1
* * Spring Kafka 2.8.0
Renovate Bot should auto-close its PRs once this is merged.
> Spring dependencies updates

- config/dev/nginx.conf.template
- config/docker/nginx.conf
- src/docs/asciidoc/resources/index.adoc
- src/docs/asciidoc/resources/migration_guide_to_3.2.adoc
in task : 
#2170 Do not cache i18n files to avoid the user having to clean his cache when upgrading opfab
> Do not cache i18n files (#2170)

- services/external-devices/src/main/java/org/opfab/externaldevices/drivers/ModbusDriver.java
- services/external-devices/src/main/java/org/opfab/externaldevices/drivers/ModbusDriverFactory.java
- services/external-devices/src/test/java/org/opfab/externaldevices/drivers/ModbusDriverFactoryShould.java
- services/external-devices/src/test/java/org/opfab/externaldevices/drivers/ModbusDriverShould.java
Fixes #2037 
In release notes, if it's not already there, under tasks:
* #2037 Add unit tests for the external devices feature
> Adding unit tests for Modbus driver (#2037)

- ui/main/src/app/modules/archives/archives.component.html
In release note, bugs section
#2137 : Improve visibility of spinner in archive screen when a research takes more than 1s
> Fix spinner in archive screen(#2137)

- ui/main/src/app/modules/admin/components/cell-renderers/state-rights-cell-renderer.component.html
- ui/main/src/app/modules/admin/components/cell-renderers/state-rights-cell-renderer.component.ts
- ui/main/src/app/modules/admin/components/editmodal/perimeters/edit-perimeter-modal.component.html
- ui/main/src/app/modules/admin/components/table/admin-table.directive.ts
#2126 : Admin screen : Use state names instead of state ids
> Admin screen : Use state names instead of state ids (#2126)

- sonar-project.properties
Tooling contains one-time migration tools, that are not meant to evolve or be tested for regressions, so it should be excluded from the coverage computation.
I didn't exclude it from Sonar altogether, as I think it's still useful to be warned of code smells.
> Exclude tooling from Sonar coverage

- ui/main/src/app/services/sound-notification.service.ts
Bugs : 
- #2243: Editing a received card "breaks" subsequent sound notifications
> Solve bug : Editing a received card "breaks" subsequent sound notifications (#2243)

- src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc
- src/test/cypress/cypress/integration/SoundNotification.spec.js
- ui/main/src/app/modules/settings/components/settings/checkbox-setting/checkbox-setting.component.ts
- ui/main/src/app/modules/settings/components/settings/settings.component.html
- ui/main/src/app/modules/settings/components/settings/settings.component.ts
- ui/main/src/app/modules/settings/components/settings/text-setting/text-setting.component.ts
The solution I propose in my pull request do not make a PATCH request. This way, we don't lose the information of whether a particular setting value was a choice from the user or just the default values in "web-ui.json" file.
#2029 : Instance-wide default values mechanism for settings properties can be confusing
> Instance-wide default values mechanism for settings properties can be confusing

- services/cards-consultation/src/test/java/org/opfab/cards/consultation/controllers/CardOperationsControllerShould.java
- services/cards-consultation/src/test/java/org/opfab/cards/consultation/services/CardSubscriptionServiceShould.java
I was sad that the quality gate was failed ;-) and these were easy fixes.
Regarding the removed "test", it wasn't actually a test but a helper function that got "stuck" with the @Test annotation when the test above it was removed, hence Sonar's warnings.
I removed it because the only test using it has been removed.
> Fix some Sonar bugs

- ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.ts
Bugs : 
#2271 : Monitoring screen: Missing '-' between startDate and endDate in column business period in export file
> Monitoring screen: Missing '-' between startDate and endDate in column business period in export file (#2271)

- services/external-devices/build.gradle
- services/services.gradle
- src/test/dummyModbusDevice/dummyModbusDevice.gradle
- src/test/externalApp/externalApp.gradle
- web-ui/web-ui.gradle
Currently, when the version is a release version, the docker task prepares an image with the following name:
`name "lfeoperatorfabric/of-${project.name.toLowerCase()}`
Which means that it has no tags, and as a result it's tagged latest (https://vsupalov.com/docker-latest-tag/).
Fixes #2290 
Nothing in release notes. The "Task XXX is existed" warning is just due to the fact that the docker configuration is repeated in several build files.
> Fix Gradle docker tasks (#2290)

- config/dev/stopOpfab.sh
- config/docker/stopOpfab.sh
#1946 : Docker recreates volumes every time a docker-compose up is triggered
>  Docker recreates volumes every time a docker-compose up is triggered (#1946)

- services/businessconfig/src/main/java/org/opfab/businessconfig/configuration/oauth2/WebSecurityConfiguration.java
- services/cards-consultation/src/main/java/org/opfab/cards/consultation/configuration/webflux/WebSecurityConfiguration.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/configuration/oauth2/WebSecurityConfiguration.java
- services/external-devices/src/main/java/org/opfab/externaldevices/configuration/oauth2/WebSecurityConfiguration.java
- services/users/src/main/java/org/opfab/users/configuration/oauth2/WebSecurityConfiguration.java
- src/docs/asciidoc/deployment/index.adoc
- src/test/api/karate/admin/loggersApi.feature
- src/test/api/karate/adminTests.txt
- src/test/api/karate/karate-config.js
Release notes
In Task section:
#2257 : Permit to access to log api only to members of admin group
> Permit to access to log api only to members of admin group (#2257)

- ui/main/src/app/modules/admin/components/table/admin-table.directive.html
- ui/main/src/app/modules/admin/components/table/admin-table.directive.ts
#2270 : Admin screen : Incoherence between pagination and displayed results after deleting a filter
> Admin screen : Incoherence between pagination and displayed results after deleting a filter (#2270)

- ui/main/src/app/modules/share/archives-logging-filters/archives-logging-filters.component.ts
#2388 : Take perimeter into account for search fields in archives and logging screen
> Take perimeter into account for search fields in archives and logging screen when no process groups (#2388)

- ui/main/src/app/modules/navbar/navbar.component.html
- ui/main/src/app/modules/navbar/navbar.component.scss
Fix #2449 
Release notes
#2449 : the right side of the menus is not visible when the screen size is about 1024 x 600
> With a screen size about 1024 x 600 the right side of the menus is not visible (#2449)

- ui/main/src/app/modules/usercard/selectStateForm/usercard-select-state-form.component.html
-#2482 : Bug when in usercard the first process has only one state
> Correct bug when in usercard the first process has only one state 

- src/test/resources/bundles/userCardExamples3/template/usercard_task.handlebars
Fix #2451 
Release notes:
#2451 : Task usercard : field "minutesForReminder" overwritten by default value when editing the card 
> Task usercard : field "minutesForReminder" overwritten by default value when editing the card (#2451)

- ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.html
- ui/main/src/app/modules/monitoring/monitoring.component.html
- ui/main/src/app/modules/monitoring/monitoring.component.scss
Fix  #2450 
Fix #2455 
Monitoring screen : 
- "Card with response form my entity" should be darker color in day mode (#2450)
-  Problem with padding below "Cards with response... (#2455)
Release notes
#2450 : Monitoring screen - "Card with response form my entity" should be darker color in day mode
#2450 : Monitoring screen - Problem with padding below "Cards with response... 
> Monitoring screen : fix style problems  (#2450  #2455)

- src/test/cypress/cypress/integration/Monitoring.spec.js
- src/test/cypress/cypress/integration/UserCard.spec.js
- src/test/resources/bundles/defaultProcess_V1/i18n.json
- src/test/resources/bundles/defaultProcess_V1/template/usercard_message.handlebars
- src/test/resources/cards/defaultProcess/message.json
- ui/main/src/app/modules/cards/components/detail/detail.component.html
I propose to replace {{xxx}} by {{{xxx}}} in the bundles (i18n.json files) where we don't want handlebars to escape characters.
> Bundles templates : problem of html encoding with handlebars (#2501)

- ui/main/src/app/modules/logging/logging.component.scss
Fix #2506
Release notes:
#2506 : Logging screen : set max with on table columns 
> Logging screen : set max with on table columns (#2506)

- web-ui/src/main/docker/start-webui.sh
Fix #2543 
To have log rotation woring it is necessary to change default access_log  and error_log filenames because nginx container by default redirects log to standard output. 
For example uncomment the following line in nginx.conf.template :
Release notes:
#2543 : Logrotate for nginx does not work.
> Activate crontab for nginx container (#2543)

- ui/main/src/app/modules/admin/components/editmodal/entities/edit-entity-modal.component.html
- ui/main/src/app/modules/admin/components/editmodal/entities/edit-entity-modal.component.ts
Fix #2459
Release notes
#2459 : Entity labels : Add label with no need for the user to click enter
> Entity labels : Add label with no need for the user to click enter (#2459)

- src/test/resources/bundles/userCardExamples2/template/confirmation.handlebars
- src/test/resources/bundles/userCardExamples2/template/question.handlebars
#2573 : Add entity name in templates example instead of entityId
> Add entity name in templates example instead of entityId (#2573)

- src/docs/asciidoc/reference_doc/user_cards.adoc
I propose to add nothing in release notes because this issue is related to issue #2493 which will be mentioned in the release notes.
> Add doc for getCurrentState() and getCurrentProcess() method (#2619)

- ui/main/src/app/modules/feed/components/time-line/custom-timeline-chart/custom-timeline-chart.component.html
- ui/main/src/app/modules/feed/components/time-line/custom-timeline-chart/custom-timeline-chart.component.ts
Fix #2582 
Release notes
#2582 : In day mode , number in timeline are not always fully visible 
> In day mode , number in timeline are not always fully visible (#2582)

- config/docker/nginx-cors-permissive.conf
Fix #2140 
Release notes
#2140 :  Fix card publishing path in nginx-cors-permissive.conf
> Fix card publishing path in nginx-cors-permissive.conf (#2140)

- ui/main/src/app/modules/usercard/datesForm/usercard-dates-form.component.html
- ui/main/src/app/modules/usercard/datesForm/usercard-dates-form.component.ts
In release notes, task section : 
#2584 : Enable to set temporarily startDate after endDate during userCard creation
> Enable to set temporarily startDate after endDate during userCard creation (#2584)

- ui/main/src/app/services/global-style.service.ts
- ui/main/src/scss/styles.scss
In release notes, tasks section : 
#2591 : Pagination links to previous/next pages are displayed in grey when there is no previous/next page
> Display disabled buttons in gray in pagination (#2591)

- src/test/cypress/cypress/integration/Timeline.spec.js
- ui/main/src/app/modules/feed/components/time-line/custom-timeline-chart/custom-timeline-chart.component.html
- ui/main/src/app/modules/feed/components/time-line/custom-timeline-chart/custom-timeline-chart.component.ts
> Add cypress tests on the timeline bubbles (#2574)

- bin/load_environment_light.sh
- src/docs/asciidoc/dev_env/launch_dev.adoc
- src/docs/asciidoc/dev_env/misc.adoc
- src/docs/asciidoc/dev_env/requirements.adoc
- src/docs/asciidoc/dev_env/scripts.adoc
- src/docs/asciidoc/dev_env/troubleshooting.adoc
- src/test/api/karate/README.adoc
Tasks : 
#1305 Ensure version consistence by relying entirely on Gradle wrapper for building
> Ensure version consistence by relying entirely on Gradle wrapper (#1305)

- src/docs/asciidoc/reference_doc/user_cards.adoc
- src/test/cypress/cypress/integration/UserCard.spec.js
- src/test/resources/bundles/defaultProcess_V1/template/usercard_message.handlebars
- ui/main/src/app/modules/usercard/selectCardEmitterForm/usercard-select-card-emitter-form.component.ts
- ui/main/src/app/modules/usercard/usercard.component.html
- ui/main/src/app/modules/usercard/usercard.component.ts
- ui/main/src/assets/js/usercardTemplateGateway.js
Fix #2675 
Release notes
In Features section
#2675 : Add a method to tell the usercard template the entity used to send card
> Add a method to tell the usercard template the entity used to send card (#2675)

- src/docs/asciidoc/reference_doc/user_cards.adoc
- src/docs/asciidoc/resources/migration_guide_to_3.6.adoc
- src/test/resources/bundles/defaultProcess_V1/template/usercard_message.handlebars
- src/test/resources/bundles/defaultProcess_V1/template/usercard_process.handlebars
- src/test/resources/bundles/userCardExamples/template/usercard_conference.handlebars
- src/test/resources/bundles/userCardExamples/template/usercard_incidentInProgress.handlebars
- src/test/resources/bundles/userCardExamples2/template/usercard_confirmation.handlebars
- src/test/resources/bundles/userCardExamples2/template/usercard_message.handlebars
- src/test/resources/bundles/userCardExamples2/template/usercard_question.handlebars
- src/test/resources/bundles/userCardExamples3/template/usercard_task.handlebars
- ui/main/src/app/modules/usercard/usercard.component.ts
Release note: 
In tasks : 
Transfert method getSpecificCardInformation from templateGateway to usercardTemplateGateway ( use of templateGateway.getSpecificCardInformation is now deprecated)
> Transfert method getSpecificCardInformation from templateGateway to usercardTemplateGateway

- ui/main/src/app/modules/share/datetime-filter/datetime-filter.component.ts
Fix #2710 
-  Text : #2710 : Archives/Logging screens: reset should disable timepicker arrows
> Archives/Logging screens : reset should disable timepicker arrows (#2710)

- src/docs/asciidoc/deployment/configuration/configuration.adoc
- In release note : nothing to add in release notes
> Correct mandatory column for checkIfUserIsAlreadyConnected in documentation (#2817)

- ui/main/src/app/modules/cards/components/detail/detail.component.scss
-  Text : #2808 Add box around the acknowledged footer of the card in day mode
> Add box around the acknowledged footer of the card in day mode (#2808)

- ui/main/src/app/modules/externaldevicesconfiguration/editModal/externaldevicesconfiguration-modal.component.html
-  Text : #2822 External devices configuration screen : single-filters are no longer aligned
> External devices configuration screen : single-filters are no longer aligned #2822

- src/test/externalApp/src/main/java/org/opfab/externalapp/service/ExternalAppServiceImpl.java
Nothing to add in release notes, the bug was already corrected
> Remove useless checks before setting card attributes in ExternalAppServiceImpl.java (#2845)

- ui/main/src/app/modules/admin/components/table/admin-table.directive.ts
- ui/main/src/app/modules/externaldevicesconfiguration/externaldevicesconfiguration.component.ts
- ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.ts
Fix #3054
-  Text : #3054 : Ag-grid: replace deprecated property localeTextFunc
> Ag-grid: replace deprecated property localeTextFunc (#3054)

- ui/main/src/app/modules/usercard/usercard.component.html
-  In chapter :  Bug
-  Text : #2995 Remove 'You are not allowed to send cards'  text when editing cards with slow network
> Remove 'You are not allowed to send cards'  text when editing cards with slow network (#2995)

- ui/main/src/app/modules/admin/admin.module.ts
- ui/main/src/app/modules/admin/components/cell-renderers/array-cell-renderer.component.ts
- ui/main/src/app/modules/admin/components/cell-renderers/perimeters-cell-renderer.component.ts
- ui/main/src/app/modules/admin/components/cell-renderers/state-rights-cell-renderer.component.ts
- ui/main/src/app/modules/admin/components/table/admin-table.directive.ts
- ui/main/src/app/modules/admin/components/table/groups-table.component.ts
I've also sorted alphabetically the columns "groups" and "entities" (in users management), and "perimeters" column (in groups management).
-  Text : #3105 : Sort alphabetically state rights in perimeter administration table
> Sort alphabetically state rights in perimeter administration table (#3105)

- services/users/src/main/java/org/opfab/users/configuration/DataInitComponent.java
I renamed the issue "Force logins to be stored with lowercase letters when it comes from an init file" because when a user is created via the admin interface, uppercase letters are already forbidden.
So the only way to have logins with uppercase letters in database is if the users come from an init file (or a properties file). 
-  Text : #2958 : Force logins to be stored with lowercase letters when it comes from an init file
> Force logins to be stored with lowercase letters when it comes from an init file (#2958)

- ui/main/src/scss/styles.scss
-  Text : #2588 : Logging screen : summary column extends without limit if the message contains no space character
> Logging screen : summary column extends without limit if the message contains no space character (#2588)

- ui/main/src/scss/styles.scss
-  Text : #3168 : Archives/logging screens : set color gray for the cards (like monitoring)
> Archives/logging screens : set color gray for the cards (like monitoring) (#3168)

- services/cards-consultation/src/main/java/org/opfab/cards/consultation/configuration/webflux/MessageToSubscriptionsRoutesConfig.java
- services/cards-consultation/src/main/java/org/opfab/cards/consultation/configuration/webflux/WebSecurityConfiguration.java
- services/cards-consultation/src/main/java/org/opfab/cards/consultation/configuration/webflux/WillNewSubscriptionDisconnectAnExistingSubscriptionRoutesConfig.java
- services/cards-consultation/src/main/java/org/opfab/cards/consultation/controllers/CardOperationsController.java
- services/cards-consultation/src/main/java/org/opfab/cards/consultation/services/CardSubscriptionService.java
- services/cards-consultation/src/test/java/org/opfab/cards/consultation/routes/MessageToSubscriptionsRoutesShould.java
Sonar complains about coverage, I've tried to add a test : 
```
@Test
void postMessageToSubscriptions() {
CardSubscription subscription = service.subscribe(currentUserWithPerimeters, "test");
subscription.getPublisher().subscribe(log::info);
webTestClient.post()
.uri("/messageToSubscriptions")
.body(Mono.just("RELOAD"), String.class)
.exchange()
.expectStatus().isOk()
.expectBody().isEmpty();      
}
```
But the test always fails telling return code is 404 instead of 200.
And when I test with postman, the return code is 200.
-  Text : #3128 : Add administration endpoint for sending messages on subscription
> Add administration endpoint for sending messages on subscription (#3128)

- config/dev/nginx.conf.template
- config/docker/nginx.conf
- ui/main/ngsw-config.json
-  Text : #3251 Do not cache index.html to ease application update in production
> Do not cache index.html to ease application update in production

- src/test/cypress/cypress/integration/UserCard.spec.js
- ui/main/src/app/modules/usercard/selectStateForm/usercard-select-state-form.component.ts
Cypress was right , there was really a pb in the code 
When editing the card the events of changing state in usercard was send twice leading to load template twice in a very  short time.
It does :
```
//First load 
Angular code : userCardTemplate.getSpecificCardInformation = null
Template  code : userCardTemplate.getSpecificCardInformation = templateCode
//Second Load 
Angular code : userCardTemplate.getSpecificCardInformation = null  
Template code : userCardTemplate.getSpecificCardInformation = templateCode 
```
But when we click on "prepare card" button in cypress code it may happen during the second load thus the getSpecificCardInformation() may be null
> Adjust usercard cypress test

- src/test/cypress/cypress/integration/ResponseCard.spec.js
- ui/main/src/app/modules/cards/components/detail/detail.component.ts
Fix #3279 
-  Text : #3279 : Card detail: show action buttons only after template is loaded
> Card detail: show action buttons only after template is loaded (#3279)

- ui/main/src/app/modules/share/datetime-filter/datetime-filter.component.ts
-  Text : 
#3356 : Archives/Logging screens : error for control in hours/minutes fields
#3365 : Usercard start/end dates : no error for wrong date
#3373 : https://github.com/opfab/operatorfabric-core/issues/3373
> Avoid null field in time input when user erases values (#3356,#3365,#3373)

- src/docs/asciidoc/dev_env/scripts.adoc
Fix #3364
I propose to add nothing in release notes
> Missing external devices on port 2105 in documentation (#3364)

- ui/main/src/app/modules/cards/components/detail/detail.component.ts
-  Text : #3169 : Redirection to the feed when editing a card from monitoring/agenda
> Redirection to the feed when editing a card from monitoring/agenda (#3169)

- src/docs/asciidoc/deployment/configuration/configuration.adoc
> Misplaced documentation menu External Devices service (#3360)

- ui/main/src/app/modules/admin/components/editmodal/perimeters/edit-perimeter-modal.component.ts
-  Text : #3435 : Unused fields in request when update/create a perimeter via admin UI
> Unused fields in request when update/create a perimeter via admin UI (#3435)

- services/cards-publication/src/main/java/org/opfab/cards/publication/services/clients/impl/ExternalAppClientImpl.java
- src/test/api/karate/cards/externalRecipentErrors.feature
Fix #3372 
-  Text : #3372 : Send HTTP error 500 when external application endpoint is not found
> Send HTTP error 500 when external application endpoint not found

- services/external-devices/src/main/java/org/opfab/externaldevices/services/ConfigService.java
- ui/main/src/app/services/card.service.ts
This PR corrects this for example : 
"Retrieved configuration for for user....
Retrieved configuration for for device ....
Retrieved configuration for for signal ....."
> Cleaning some log sentences

- src/test/cypress/cypress/integration/ResponseCard.spec.js
- ui/main/src/app/modules/cards/components/detail/detail.component.html
- ui/main/src/app/modules/cards/components/detail/detail.component.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
-  Text : #3383 : Permit to select more than one entity if possible when sending a response card
> Permit to select more than one entity if possible when sending a response card (#3383)

- ui/main/src/app/modules/core/application-loading/sound-activation/sound-activation.component.ts
Fix #2998 
-  Text : #2998 : No sound on Firefox after closing and reopening the browser
> No sound on Firefox after closing and reopening the browser (#2998)

- services/users/src/main/java/org/opfab/users/controllers/EntitiesController.java
- services/users/src/main/java/org/opfab/users/controllers/GroupsController.java
- services/users/src/main/java/org/opfab/users/controllers/PerimetersController.java
- services/users/src/main/java/org/opfab/users/controllers/UsersController.java
- services/users/src/main/java/org/opfab/users/services/UserService.java
- services/users/src/main/java/org/opfab/users/services/UserServiceImp.java
- services/users/src/main/modeling/swagger.yaml
- services/users/src/test/java/org/opfab/users/services/UserServiceShould.java
- src/test/api/karate/externaldevices/deleteUserConfig.feature
- src/test/api/karate/users/createUsers.feature
- src/test/api/karate/users/deleteUser.feature
- src/test/api/karate/users/entities/checkEntityGroupManagement.feature
- src/test/api/karate/users/entities/createEntities.feature
- src/test/api/karate/users/entities/deleteUserFromEntity.feature
- src/test/api/karate/users/entities/updateListOfEntityUsers.feature
- src/test/api/karate/users/fetchUserSettings.feature
- src/test/api/karate/users/groups/createGroups.feature
- src/test/api/karate/users/groups/deleteUserFromGroup.feature
- src/test/api/karate/users/groups/updateListOfGroupUsers.feature
- src/test/api/karate/users/ipControl.feature
- src/test/api/karate/users/patchUserSettings.feature
- src/test/api/karate/users/perimeters/createPerimeters.feature
- src/test/api/karate/users/perimeters/getPerimetersForAUser.feature
- src/test/api/karate/users/updateExistingUser.feature
I've chosen to forbid uppercase letters in login and so, to delete calls to toLowerCase() functions to convert login. 
To be discussed maybe ?
-  Text : #1318 : Resource identifiers should only contain letters, digits, dashes or underscores
> Resource identifiers should only contain letters, digits, dashes or underscores (#1318)

- config/dev/cards-publication-dev.yml
- services/cards-publication/src/main/java/org/opfab/cards/publication/services/CardProcessingService.java
- src/docs/asciidoc/deployment/configuration/configuration.adoc
- src/docs/asciidoc/resources/migration_guide_to_3.10.adoc
Fix #3543 
-  Text : #3543 : Add option to not refuse sending card if process or state does not exists
> Add option to not refuse sending card if process or state does not exists (#3543)

- ui/main/src/app/modules/feed/components/card-list/filters/feed-sort/feed-sort.component.html
- ui/main/src/app/services/lightcards/sort.service.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
Fix #3565
-  Text : #3565 Add option to sort cards by start and end date
> Add card sorting by start and end date (#3565)

- ui/main/.eslintrc.json
This will in particular avoid having error when using keyword const in js scripts
> Set eslint control to ecma script version 2017

- ui/main/src/app/modules/externaldevicesconfiguration/table/externaldevicesconfiguration-directive.ts
-  Text : #3664 : Chekboxes in external configuration screen lose state when changing page
> Chekboxes in external configuration screen lose state when changing page (#3664)

- ui/main/src/app/modules/feedconfiguration/feedconfiguration.component.html
-  Text : #3665 : When process name is long, it overlaps the following process name in notification configuration screen
> When process name is long, it overlaps the following process name in notification configuration screen (#3665)

- src/test/resources/bundles/messageOrQuestionExample/template/confirmation.handlebars
Fix #3613
-  Text : #3613 : In confirmation example , show response input only after user click on modify answer
> In confirmation example, show response input only after user clicks on modify answer (#3613)

- ui/main/src/app/modules/admin/components/table/admin-table.directive.ts
- ui/main/src/scss/styles.scss
-  Text : #3720 : Use less space for edit/delete columns in admin screens
> Use less space for edit/delete columns in admin screens (#3720)

- ui/main/src/app/modules/monitoring/components/monitoring-filters/monitoring-filters.component.ts
- ui/main/src/app/modules/monitoring/components/monitoring-filters/monitoring-process-list.ts
-  Text : #3829 : Monitoring : wrong label in multiselect for service when process groups not totally configured
> Monitoring : wrong label in multiselect for service when process groups not totally configured (#3829)

- ui/main/src/app/modules/monitoring/monitoring.component.html
-  Text : #3800 : Monitoring : message when no result should be like the one for archives and logging pages
> Monitoring : message when no result should be like the one for archives and logging pages (#3800)

- ui/main/src/app/modules/admin/components/cell-renderers/state-rights-cell-renderer.component.scss
- ui/main/src/app/modules/archives/archives.component.scss
- ui/main/src/app/modules/calendar/calendar.component.scss
- ui/main/src/app/modules/feed/components/card-list/filters/feed-filter/feed-filter.component.scss
- ui/main/src/app/modules/feed/components/pinned-cards/pinned-cards.component.scss
- ui/main/src/app/modules/logging/logging.component.scss
- ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.scss
- ui/main/src/app/modules/settings/components/settings/checkbox-setting/checkbox-setting.component.scss
- ui/main/src/app/modules/share/countdown/countdown.component.scss
- ui/main/src/app/modules/share/light-card/light-card.component.scss
- ui/main/src/app/modules/share/timeline-buttons/timeline-buttons.component.scss
- ui/main/src/app/modules/usercard/usercard.component.scss
I propose to add nothing in release notes or maybe in Tasks section ?
-  Text : #3855 : Solve deprecated usage of ~ in import
> Solve deprecated usage of ~ in import (#3855)

- ui/main/src/app/modules/share/light-card/light-card.component.ts
- ui/main/src/app/services/grouped-cards.service.ts
-  Text : The arrow from the grouped cards symbol would appear even though there are no grouped cards due to the filter settings.
> Fixed grouped card icon (#8325)

- ui/main/src/app/modules/share/archives-logging-filters/archives-logging-filters.component.html
Fix #3950 
-  Text : #3950 : Fix reset button does not clear tags filter in Archives page
> Fix reset button does not clear tags filter in Archives page (#3950)

- services/cards-publication/src/main/java/org/opfab/cards/publication/services/clients/impl/ExternalAppClientImpl.java
Fix #3915
-  Text : #3915 : External app : changing the type of the returned object
> External app : changing the type of the returned object (#3915)

- src/docs/asciidoc/resources/migration_guide_to_3.12.adoc
- src/test/resources/bundles/defaultProcess_V1/template/usercard_message.handlebars
- ui/main/src/app/modules/usercard/usercard.component.ts
Fix #2730
-  Text : #2730 : Remove deprecated method templateGateway.getSpecificCardInformation()
> Remove deprecated method templateGateway.getSpecificCardInformation() (#2730)

- ui/main/src/app/business/server/config.server.ts
- ui/main/src/app/business/server/process.server.ts
- ui/main/src/app/business/server/serverResponse.ts
- ui/main/src/app/business/services/config.service.spec.ts
- ui/main/src/app/business/services/config.service.ts
- ui/main/src/app/business/services/processes.service.spec.ts
- ui/main/src/app/business/services/processes.service.ts
- ui/main/src/app/modules/card/card.component.ts
- ui/main/src/app/modules/card/services/handlebars.service.spec.ts
- ui/main/src/app/server/angular.server.ts
- ui/main/src/app/server/angularConfig.server.ts
- ui/main/src/app/server/angularProcess.server.ts
- ui/main/src/tests/mocks/configServer.mock.ts
- ui/main/src/tests/mocks/processServer.mock.ts
Add a ServerResponse class to manage error in business services without having to be coupled with angular HttpClient 
> Refacto UI : modify http error management in server classes

- ui/main/src/app/modules/share/simplified-card-view/simplified-card-view.component.ts
Fix #4062 
-  Text : #4062 : Fix error when opening card with no childs from Archives screen
> Fix error when opening card with no childs from Archives screen (#4062)

- ui/main/src/app/app.component.ts
- ui/main/src/app/app.module.ts
- ui/main/src/app/business/server/opfabEventStream.server.ts
- ui/main/src/app/business/services/opfabEventStream.service.ts
- ui/main/src/app/modules/activityarea/activityarea.component.ts
- ui/main/src/app/modules/card/components/card-ack/card-ack.component.ts
- ui/main/src/app/modules/card/components/card-acks-footer/card-acks-footer.component.ts
- ui/main/src/app/modules/card/components/card-footer-text/card-footer-text.component.ts
- ui/main/src/app/modules/core/application-loading/app-loaded-in-another-tab/app-loaded-in-another-tab.component.ts
- ui/main/src/app/modules/core/application-loading/application-loading.component.ts
- ui/main/src/app/modules/core/session-end/session-end.component.ts
- ui/main/src/app/modules/feedconfiguration/feedconfiguration.component.ts
- ui/main/src/app/modules/share/light-card/light-card.component.spec.ts
- ui/main/src/app/server/angularOpfabEventStream.server.ts
- ui/main/src/app/services/acknowledge.service.spec.ts
- ui/main/src/app/services/card.service.ts
- ui/main/src/app/services/lightcards/lightcards-store.service.ts
- ui/main/src/app/services/sound-notification.service.ts
- ui/main/src/app/store/effects/authentication.effects.spec.ts
- ui/main/src/app/store/effects/authentication.effects.ts
- ui/main/src/app/store/effects/card-operation.effects.ts
- ui/main/src/app/store/effects/card.effects.ts
Isolate the code that manage the realtime connection to opfab using an interface ui/main/src/app/business/server/opfabEventStream.server.ts implemented in ui/main/src/app/server/angularOpfabEventStream.server.ts
This class manage technically the connection (heartbeat management, recovery ..) 
The business management of the events is shared between 
- A new  class ui/main/src/app/business/services/opfabEventStream.service.ts  for the general events 
- The existing class ui/main/src/app/services/lightcards/lightcards-store.service.ts for the events regarding cards 
The lightcards-store does not access directly to the event stream server but uses the event stream **service** (opfabEventStream.service.ts)
The resulting card.service.ts is now mainly a gateway to the back for cards operations , …
> Refacto event stream management

- ui/main/src/app/modules/usercard/usercard.component.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
> User card: missing translation for error message when expiration date before start date (#4094)

- config/docker/ui-config/ui-menu.json
Fix #4092
-  Text : #4092 : Fix Admin menu entry not translated in french
> Fix Admin menu entry not translated in french (#4092)

- ui/main/src/app/modules/useractionlogs/components/useractionlogs-table/useractionlogs-table.component.ts
Fix #4104
-  Text : #4104  : Add seconds in Date column in user action logs
> Add seconds in Date column in user action logs (#4104)

- ui/main/src/app/modules/usercard/selectStateForm/usercard-select-state-form.component.ts
-  Text : #4154 : Usercard template does not change when switching from same state id in a different process
> Usercard template does not change when switching from same state id in a different process (#4154)

- README.adoc
- src/docs/asciidoc/reference_doc/user_cards.adoc
- src/docs/asciidoc/resources/migration_guide_to_3.13.adoc
- src/test/resources/bundles/conferenceAndITIncidentExample/template/usercard_conference.handlebars
- src/test/resources/bundles/conferenceAndITIncidentExample/template/usercard_incidentInProgress.handlebars
- src/test/resources/bundles/messageOrQuestionExample/template/usercard_confirmation.handlebars
- src/test/resources/bundles/messageOrQuestionExample/template/usercard_question.handlebars
- ui/main/src/app/modules/usercard/usercard.component.ts
-  Text : #4170 Renamed the viewCardInAgenda parameter to viewCardInCalendar
> Renamed viewCardInAgenda to viewCardInCalendar #4170

- ui/main/src/app/modules/core/application-loading/login/login.component.ts
-  Text : #4216  Remove space in end of login to avoid user mistake
> Remove space in end of login to avoid user mistake (#4216)

- services/businessconfig/src/main/java/org/opfab/businessconfig/configuration/oauth2/WebSecurityConfiguration.java
- services/businessconfig/src/test/java/org/opfab/businessconfig/application/IntegrationTestApplication.java
- services/businessconfig/src/test/resources/security.xml
- services/cards-publication/src/main/java/org/opfab/cards/publication/configuration/oauth2/WebSecurityConfiguration.java
- services/cards-publication/src/test/java/org/opfab/cards/publication/application/UnitTestApplication.java
- services/cards-publication/src/test/resources/security.xml
- services/external-devices/src/main/java/org/opfab/externaldevices/configuration/oauth2/WebSecurityConfiguration.java
- services/users/src/main/java/org/opfab/users/configuration/oauth2/OpfabIpAuthorizationManager.java
- services/users/src/main/java/org/opfab/users/configuration/oauth2/OpfabLoginAuthorizationManager.java
- services/users/src/main/java/org/opfab/users/configuration/oauth2/OpfabLoginNotEqualAuthorizationManager.java
- services/users/src/main/java/org/opfab/users/configuration/oauth2/WebSecurityConfiguration.java
- tools/spring/spring-oauth2-utilities/src/main/java/org/opfab/springtools/configuration/oauth/OAuth2GenericConfiguration.java
- tools/spring/spring-oauth2-utilities/src/main/java/org/opfab/springtools/configuration/oauth/OpfabAuthorizationManager.java
- tools/spring/spring-oauth2-utilities/src/main/java/org/opfab/springtools/configuration/oauth/OpfabIpAuthorizationManager.java
-  Text : #4234 : Remove use of deprecated method authorizeRequests()
> Remove use of deprecated method authorizeRequests() (#4234)

- src/test/resources/bundles/taskAdvancedExample/template/usercard_taskAdvanced.handlebars
-  Text : #4243 : Reinforce form controls when sending a recurrent card in Task Advanced example
> Reinforce form controls when sending a recurrent card in Task Advanced example (#4243)

- src/test/resources/bundles/conferenceAndITIncidentExample/template/usercard_incidentInProgress.handlebars
- ui/main/src/app/business/services/businessdata.service.ts
Modify template to have  the select of the field in mutliselect  done after the init of the mutliselect component  : the addition of the keyword async done in this release implies that the method initMultiSelect() is not called right away.
Not related to the bug : Clone business  data object to avoid side effect (without cloning the template is able to modify the data in the cache) 
Nothing in release note as it was not present in previous release
> Fix bug in IT Incident example (#4426)

- ui/main/src/app/modules/archives/archives.component.ts
-  Text : #4480 : Do not limit the number of cards returned in archives export
> Do not limit the number of cards returned in archives export (#4480)

- ui/main/src/app/authentication/auth.service.ts
- ui/main/src/app/authentication/implicit-authentication-handler.ts
-  Text : #4514 Session close in implicit mode without warning
To test : 
- Set opfab in implicit mode ` 
- Config keyloak :  You need to set short  time value for testing :  
- Set access token lifespan for implicit flow to a short value  example : 1 min 
- Set SSO Session max to a short value to test that session is properly closed : example 4 minutes 
- Configure web-ui param `secondsToCloseSession` to a short value , example 5
> Solve issue Session close in implicit mode without warning (#4514)

- ui/main/src/app/modules/card/services/handlebars.service.ts
-  Text : Documentation part :
- **11.2.1.22.** 
_findObjectByProperty_
Searching directly an object in a list using the value of a property. Returns the object if it contains it, null otherwise.
```
{{#with (findObjectByProperty card.data.myObjectsList propertyName propertyValue)}}
<p>Property value of found object: {{this.propertyName}}</p>
{{/with}}
```
> Adding of the new helper 'findObjectByProperty'

- ui/main/src/app/modules/usercard/usercard.component.ts
-  Text : #4539 : Geomap disappears if we update a card (via edit button)
> Geomap disappears if we update a card (via edit button) (#4539)

- ui/main/src/app/modules/usercard/recipientForm/usercard-recipients-form.component.ts
- ui/main/src/app/modules/usercard/usercard.component.html
-  Text : #4540 : Default value set in "recipients in copy" field in edit mode
> Default value set in "recipients in copy" field in edit mode (#4540)

- ui/main/src/shared/css/opfab-application.css
> Removed the orange outline from the autofocus on the cancel button of a new card

- ui/main/src/app/modules/logging/components/logging-table/logging-table.component.ts
> Logging screen : display header names of columns on two lines if it needs (#4534)

- src/docs/asciidoc/reference_doc/ui_customization.adoc
- ui/main/src/app/business/services/config.service.ts
- ui/main/src/app/modules/navbar/navbar.component.html
- ui/main/src/app/modules/navbar/navbar.component.ts
-  Text : #4451 : If navigation bar menu has only one entry, show submenu anyway
> If navigation bar menu has only one entry, show submenu anyway (#4451)

- src/docs/asciidoc/reference_doc/template_description.adoc
- src/docs/asciidoc/reference_doc/ui_api.adoc
- src/docs/asciidoc/reference_doc/user_cards.adoc
- src/docs/asciidoc/resources/migration_guide_to_4.0.adoc
- src/test/resources/bundles/conferenceAndITIncidentExample/template/usercard_conference.handlebars
- src/test/resources/bundles/conferenceAndITIncidentExample/template/usercard_incidentInProgress.handlebars
- src/test/resources/bundles/defaultProcess_V1/template/usercard_message.handlebars
- src/test/resources/bundles/defaultProcess_V1/template/usercard_process.handlebars
- src/test/resources/bundles/messageOrQuestionExample/template/usercard_confirmation.handlebars
- src/test/resources/bundles/messageOrQuestionExample/template/usercard_message.handlebars
- src/test/resources/bundles/messageOrQuestionExample/template/usercard_question.handlebars
- src/test/resources/bundles/taskAdvancedExample/template/usercard_taskAdvanced.handlebars
- src/test/resources/bundles/taskExample/template/usercard_task.handlebars
- ui/main/src/app/business/services/opfabAPI.service.ts
- ui/main/src/app/modules/usercard/recipientForm/usercard-recipients-form.component.ts
- ui/main/src/app/modules/usercard/usercard.component.ts
- ui/main/src/assets/js/opfab.js
- ui/main/src/assets/js/usercardTemplateGateway.js
Nothing in release note as  #4438 is already in release note
> Move userCardTemplateGateway methods in opfab UI API

- src/docs/asciidoc/reference_doc/card_notification.adoc
- src/docs/asciidoc/resources/migration_guide_to_4.0.adoc
> Add reminder service in migration guide for 4.0 (#4664)

- config/docker/ui-config/web-ui.json
- src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc
- src/docs/asciidoc/resources/migration_guide_to_4.0.adoc
- ui/main/src/app/business/view/core/alert/alert.view.spec.ts
- ui/main/src/app/business/view/core/alert/alert.view.ts
-  Text : 
-  Added the option 'hideBusinessMessages' to web-ui.json to hide alert messages with level "BUSINESS'. 
- Renamed and moved alertMessageBusinessAutoClose and alertMessageOnBottomOfTheScreen to a new `alerts` section in the config
> Added hideBusinessAlertMessages to hide all message with level BUSINESS

- bin/load_environment_light.sh
- services/businessconfig/src/main/docker/Dockerfile
- services/cards-consultation/src/main/docker/Dockerfile
- services/cards-publication/src/main/docker/Dockerfile
- services/external-devices/src/main/docker/Dockerfile
- services/users/src/main/docker/Dockerfile
- src/test/dummyModbusDevice/src/main/docker/Dockerfile
- src/test/externalApp/src/main/docker/Dockerfile
Fix #4704
-  Text : #4704 : Migrate to java 17.0.7
> Migrate to java 17.0.7 (#4704)

- node-services/cards-reminder/src/cardsReminder.ts
- node-services/cards-reminder/src/domain/application/cardsReminderControl.ts
- node-services/cards-reminder/src/domain/application/reminderService.ts
- node-services/cards-reminder/src/domain/application/rruleReminderService.ts
- node-services/cards-reminder/src/domain/client-side/cardsRemiderService.ts
- node-services/cards-reminder/src/domain/server-side/remindDatabaseService.ts
- src/docs/asciidoc/resources/migration_guide_to_4.0.adoc
Fix #4732
-  Text : #4732 :Add an endpoint to card reminder to reset and reprocess reminder database
> Add an endpoint to card reminder to reset and reprocess reminder database (#4732)

- services/external-devices/src/main/java/org/opfab/externaldevices/services/DevicesService.java
> External-devices : Do not print stacktrace in logs when device is not available or exiting

- config/dev/common-dev.yml
- config/docker/common.yml
- config/docker/node-services.yml
- config/docker/ui-config/web-ui.json
- node-services/cards-external-diffusion/config/default-docker.yml
- node-services/cards-external-diffusion/config/default.yml
- node-services/cards-external-diffusion/src/cardsExternalDiffusion.ts
- node-services/cards-reminder/config/default-docker.yml
- node-services/cards-reminder/config/default.yml
- node-services/cards-reminder/src/cardsReminder.ts
- node-services/common/src/common/client-side/authenticationService.ts
- node-services/supervisor/config/default-docker.yml
- node-services/supervisor/config/default.yml
- node-services/supervisor/src/connectionSupervisor.ts
- services/businessconfig/src/main/resources/application.yml
- services/cards-consultation/src/main/resources/application.yml
- services/cards-publication/src/main/java/org/opfab/cards/publication/configuration/Services.java
- services/cards-publication/src/main/resources/application.yml
- services/external-devices/src/main/resources/application.yml
- services/users/src/main/resources/application.yml
- src/docs/asciidoc/deployment/configuration/configuration.adoc
- src/docs/asciidoc/deployment/configuration/security_configuration.adoc
- src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc
- src/docs/asciidoc/resources/migration_guide_to_4.0.adoc
- src/test/externalApp/src/main/resources/application.yml
- src/test/resources/uiConfig/security-CODE-flow.json
- src/test/resources/uiConfig/security-IMPLICIT-flow.json
- src/test/resources/uiConfig/security-PASSWORD-flow.json
- tools/generic/utilities/src/main/java/org/opfab/utilities/eventbus/rabbit/RabbitEventBus.java
- ui/main/src/app/authentication/auth-handler.ts
- To be consistent : prefix back configuration parameters with operatorfabric 
- Remove tokenExpiredClaim parameter as it has a standard value ( exp) 
- Remove some unused security parameters
-  Text : #4934  Simplify some configuration
> Simplify some configuration

- config/dev/cards-publication-dev.yml
- config/docker/cards-publication.yml
- services/cards-publication/src/main/java/org/opfab/cards/publication/configuration/ExternalRecipients.java
- services/cards-publication/src/test/resources/application-kafka.yml
- services/cards-publication/src/test/resources/application.yml
- src/docs/asciidoc/deployment/configuration/configuration.adoc
- src/docs/asciidoc/dev_env/kafka.adoc
- src/docs/asciidoc/reference_doc/response_cards.adoc
- src/docs/asciidoc/resources/migration_guide_to_4.0.adoc
Fix #4945
-  Text : #4945 : Rename external recipients config params
> Rename external recipients config params (#4945)

- ui/main/src/app/business/view/externalAppIframe/externalAppIFrame.view.spec.ts
- ui/main/src/app/business/view/externalAppIframe/externalAppIFrame.view.ts
-  Text : #5013 Mask params in navigation bar for external apps
> Mask params in navigation bar for external apps

- src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc
- src/docs/asciidoc/resources/migration_guide_to_4.0.adoc
- ui/main/src/app/authentication/auth-handler.ts
Nothing in release note (pb not present in previous release)
> Reduce secondsToCloseSession to 60s to avoid being logout before silent refresh in IMPLICIT auth mode

- ui/main/src/app/business/services/businessconfig/processes.service.ts
-  Text : #5118 : When loading an empty processgroup file the information is not updated on ui
> When loading an empty processgroup file the information is not updated on ui (#5118)

- ui/main/src/app/business/services/lightcards/search-service.ts
Fix #5169
-  Text : #5169 : Fix search in the Card Feed when the translatedSummary is missing
> Fix search in the Card Feed when the translatedSummary is missing (#5169)

- node-services/cards-external-diffusion/config/default-docker.yml
- node-services/cards-external-diffusion/docker/Dockerfile
- node-services/cards-reminder/config/default-docker.yml
- node-services/cards-reminder/docker/Dockerfile
- node-services/supervisor/config/default-docker.yml
- node-services/supervisor/docker/Dockerfile
- src/docs/asciidoc/deployment/index.adoc
- src/docs/asciidoc/resources/migration_guide_to_4.1.adoc
-  Text : #5206 Set /var/log/opfab as log directory in all node-service dockers
> Set /var/log/opfab as log directory in all node-service dockers

- src/test/cypress/cypress/integration/Resilience.spec.js
Fix #5059 
-  Text : #5059 : Add a test to check card reception after mongoDB restart
> Add a test to check card reception after mongoDB restart (#5059)

- ui/main/src/app/business/buildInTemplates/task/usercard/taskUserCardTemplate.ts
The bug : if you set a task description field containing several words, then if you edit the card, only the first word is taken into account.
> fix bug on buildin template task, for task description field

- ui/main/src/app/modules/dashboard/dashboard.component.ts
-  Text : #5110 Opening a card from dashboard now closes the tooltip
> Opening a card from dashboard closes the popover #5110

- node-services/cards-reminder/config/default.yml
- node-services/cards-reminder/package.json
- node-services/cards-reminder/src/cardsReminder.ts
- node-services/cards-reminder/src/domain/application/cardsReminderControl.ts
- node-services/cards-reminder/src/domain/application/reminderService.ts
- node-services/cards-reminder/src/domain/application/reminderUtils.ts
- node-services/cards-reminder/src/domain/application/rrule-reminderUtils.ts
- node-services/cards-reminder/src/domain/application/rruleReminderService.ts
- node-services/cards-reminder/src/domain/client-side/cardsReminderService.ts
- node-services/cards-reminder/src/domain/model/card.model.ts
- node-services/cards-reminder/src/domain/model/reminder.model.ts
- node-services/cards-reminder/src/domain/server-side/cardsReminderOpfabServicesInterface.ts
- node-services/cards-reminder/src/domain/server-side/remindDatabaseService.ts
- node-services/cards-reminder/tests/cardsReminderControl.test.ts
- node-services/cards-reminder/tests/cardsReminderService.test.ts
- node-services/cards-reminder/tests/opfabServicesInterfaceStub.ts
- node-services/cards-reminder/tests/remindDataBaseServiceStub.ts
- node-services/cards-reminder/tests/reminderUtils.test.ts
- services/cards-publication/src/main/java/org/opfab/cards/publication/model/RecurrencePublicationData.java
-  Text : #5368 Card reminder go in a loop under certain circumstances
**Content of the PR :** 
**Change the logic for processing the next date to remind the card :**
Previous solution was : Send remind --> Delete old remind --> Compute next remind date and store in db --> Receive a card update from eventBus and ignore the update as it is a consequence of the remind
This solution may end up, in certain circumstances, to processed two times or more the next remind date computing resulting in loosing one or more occurrence of reminds.
New solution : Send Remind --> Received a card update from eventBus --> Compute next remind and update remind in bd 
---> see node-services/cards-reminder/src/domain/application/reminderService.ts & …
> Solve issue : Card reminder go in a loop under certain circumstances

- services/cards-publication/src/main/java/org/opfab/cards/publication/model/ArchivedCardPublicationData.java
Fix #5440
-  Text : #5440 : Add an index on mongoDB archivedCards collection for field processInstanceId
> Add an index on mongoDB archivedCards collection for field processInstanceId (#5440)

- src/test/resources/bundles/defaultProcess_V1/css/style.css
> Fix rich text editor default color in base message example (#5472)

- gradle.properties
Fix #5456
-  Text : #5456 : Solve deprecated sonar gradle task dependency on compile task
> Solve deprecated sonar gradle task dependency on compile task (#5456)

- ui/main/src/assets/js/opfab.js
Fix #5489
-  Text : #5489 : Remove default value https://quiljs.com in link edition in rich text editor
> Remove default value https://quiljs.com in link edition in rich text editor (#5489)

- ui/main/src/scss/styles.scss
Fix #5485
-  Text : #5485 : Avoid empty line in ag-grid tables
> Avoid empty line in ag-grid tables (#5485)

- node-services/cards-reminder/src/domain/application/reminderService.ts
- node-services/cards-reminder/src/domain/application/rruleReminderService.ts
- node-services/cards-reminder/tests/cardsReminderControl.test.ts
-  Text : #5546  No reminder occurs when secondsBeforeTimeSpanForReminder is set to 0
> Solve issue : No reminder occurs when secondsBeforeTimeSpanForReminder is set to 0 (#5546) - Release 4.1.0

- src/docs/asciidoc/deployment/index.adoc
-  Text : #5487 : Not found error when clicking on links relatives to card limiter
> Not found error when clicking on links relatives to card limiter (#5487)

- src/test/cypress/cypress/integration/TaskAdvanced.spec.js
- ui/main/src/app/business/buildInTemplates/task/usercard/taskUserCardTemplate.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
-  Text : #5493 : Task advanced : missing translation on number/weekday and "nth day of the month"
> Task advanced : missing translation on number/weekday and "nth day of the month" (#5493)

- services/cards-publication/src/main/java/org/opfab/cards/publication/configuration/SecurityFilterConfiguration.java
- src/test/api/karate/cardTests.txt
- src/test/api/karate/cards/cardIdWithSpecialCharacters.feature
Permitted to delete a card with id contaianing a semicolon.
Still not possible to get/view the card in the UI due to spring webflux truncating path variables containing semicolon.
Fix #5295
-  Text : #5295 :  Allow to delete card with id containing special characters
> Allow to delete card with id containing special characters (#5295)

- ui/main/src/app/business/buildInTemplates/task/card/taskCardTemplateView.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
Fix #5482
-  Text : #5482 :  Task advanced : the text for a negative number in "nth day of the month" is not right
> Task advanced : the text for a negative number in "nth day of the month" is not right (#5482)

- ui/main/src/app/modules/share/archives-logging-filters/archives-logging-filters.component.ts
-  Text : #5652 : Archives/loggging screen : disable admin mode shall reset the search result if admin has no processes
> Archives/loggging screen : disable admin mode shall reset the search result if admin has no processes (#5652)

- node-services/cards-reminder/src/domain/application/rrule-reminderUtils.ts
- ui/main/src/app/business/buildInTemplates/task/usercard/taskUserCardTemplate.ts
I added a control to forbid numbers greater than 31. I also added a check to avoid doing valueOf() on an undefined object.
But I think this is normal to not have reminder if the user create a card with, for example, "30th day of month" and "february". 
The user must be careful when he creates his card.
-  Text : #5617 : Cards reminder error when Task advanced card has "nth day of month" field greater than month number of days
> Cards reminder error when Task advanced card has nth day of month greater than month number of days (#5617)

- config/docker/users.yml
- src/docs/asciidoc/reference_doc/users_management.adoc
- ui/main/src/app/modules/usercard/recipientForm/usercard-recipients-form.component.ts
- ui/main/src/app/modules/usercard/usercard.component.ts
-  Text : #5434 Entities need the CARD_SENDER role to send a card and the CARD_RECEIVER role to receive a card
> Use entity role in usercards #5434

- client/cards/src/main/java/org/opfab/cards/model/CardActionEnum.java
- client/cards/src/main/modeling/config.json
- services/cards-consultation/src/main/java/org/opfab/cards/consultation/configuration/mongo/LightCardReadConverter.java
- services/cards-consultation/src/main/java/org/opfab/cards/consultation/configuration/webflux/CardRoutesConfig.java
- services/cards-consultation/src/main/java/org/opfab/cards/consultation/model/ArchivedCardConsultationData.java
- services/cards-consultation/src/main/java/org/opfab/cards/consultation/model/CardConsultationData.java
- services/cards-consultation/src/main/java/org/opfab/cards/consultation/model/LightCardConsultationData.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/model/ArchivedCardPublicationData.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/model/CardPublicationData.java
- services/cards-publication/src/main/java/org/opfab/cards/publication/model/LightCardPublicationData.java
- services/cards-publication/src/main/modeling/swagger.yaml
- src/docs/asciidoc/reference_doc/card_structure.adoc
- src/docs/asciidoc/reference_doc/response_cards.adoc
- src/test/resources/bundles/messageOrQuestionExample/template/confirmation.handlebars
- ui/main/src/app/business/model/card.model.ts
- ui/main/src/app/business/model/light-card.model.ts
- ui/main/src/app/business/store/lightcards/lightcards-store.ts
- ui/main/src/app/modules/card/components/card-ack/card-ack.component.ts
- ui/main/src/app/modules/card/components/card-body/card-body.component.ts
- ui/main/src/app/modules/card/components/card-reponse/card-response.component.ts
- ui/main/src/app/modules/feed/components/card-list/card-list.component.ts
Fix #5461
-  Text : Add actions field to Card. Handle PROPAGATE_READ_ACK_TO_PARENT_CARD qction (#5461)
> Add actions field to Card. Handle PROPAGATE_READ_ACK_TO_PARENT_CARD action (#5461)

- src/test/resources/businessData/message-and-question-list
- ui/main/src/app/business/buildInTemplates/message-or-question-list/usercard/message-or-question-listUserCardTemplate.ts
- ui/main/src/app/business/buildInTemplates/message-or-question-list/usercard/message-or-question-listUserCardTemplateView.spec.ts
- ui/main/src/app/business/buildInTemplates/message-or-question-list/usercard/message-or-question-listUserCardTemplateView.ts
Fix #5738
-  Text : #5738 : Add the option to configure rich text in config file for message or question list build-in template
> Add the option to configure rich text in config file for message or question list build-in template (#5738)

- src/test/cypress/cypress/integration/Dashboard.spec.js
> Add cypress test for card detail opening after redirection from dashboard to feed  (#5914)

- config/docker/ui-config/ui-menu.json
Fix #5888 
-  Text : #5888: Fix linked navbar menus when logged as admin
> Fix ui-menu entries (#5888)

- ui/main/src/app/modules/realtimeusers/realtimeusers.component.html
in https://github.com/opfab/release-notes/blob/master/release_notes.4.2.0-RC.2
In chapter : Bug
Text : #5970 : issue with realtime user screen title
> Solve issue with realtime user screen title (#5970) - release 4.2.0

- ui/main/package-lock.json
- ui/main/package.json
Solve message during build :
npm WARN deprecated @types/moment@2.13.0: This is a stub types definition for Moment (https://github.com/moment/moment). Moment provides its own type definitions, so you don't need @types/moment installed!
> Remove unneeded types/moment deprecated dependency

- .github/workflows/scorecard.yml
> Add the possibility to launch manually the scorecard github workflow

- services/external-devices/src/main/java/org/opfab/externaldevices/services/ConfigService.java
- src/test/cypress/cypress/integration/ExternalDevicesConfiguration.spec.js
- ui/main/src/app/business/server/external-devices.server.ts
- ui/main/src/app/business/services/notifications/external-devices.service.ts
- ui/main/src/app/modules/externaldevicesconfiguration/table/devices.table.component.ts
- ui/main/src/app/modules/externaldevicesconfiguration/table/externaldevicesconfiguration-directive.ts
- ui/main/src/app/server/angularExternalDevices.server.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
Fix #5951 
-  Text : #5951 : Add a delete button to delete an external device configuration
> Delete external device from UI (#5951)

- node-services/cards-external-diffusion/config/default-docker.yml
- node-services/cards-external-diffusion/config/default.yml
- node-services/cards-external-diffusion/src/cardsExternalDiffusion.ts
- node-services/cards-external-diffusion/src/domain/application/cardsDiffusionControl.ts
- node-services/cards-external-diffusion/src/domain/application/dailyCardsDiffusionControl.ts
- node-services/cards-external-diffusion/src/domain/application/realTimeCardsDiffusionControl.ts
- node-services/cards-external-diffusion/src/domain/client-side/cardsExternalDiffusionService.ts
- node-services/cards-external-diffusion/src/domain/client-side/configDTO.ts
- node-services/cards-external-diffusion/src/domain/client-side/configService.ts
- node-services/cards-external-diffusion/src/domain/server-side/cardsExternaDiffusionDatabaseService.ts
- node-services/cards-external-diffusion/tests/dailyCardsDiffusionControl.test.ts
- node-services/cards-external-diffusion/tests/realTimeCardsDiffusionControl.test.ts
- node-services/cards-external-diffusion/tests/testHelpers.ts
- services/users/src/main/java/org/opfab/users/model/CurrentUserWithPerimeters.java
- services/users/src/main/java/org/opfab/users/model/UserSettings.java
- services/users/src/main/java/org/opfab/users/services/CurrentUserWithPerimetersService.java
- services/users/src/main/java/org/opfab/users/services/UserSettingsService.java
- services/users/src/main/modeling/swagger.yaml
- services/users/src/test/java/org/opfab/users/services/CurrentUserWithPerimetersServiceShould.java
- src/docs/asciidoc/deployment/configuration/configuration.adoc
- src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc
- src/test/api/karate/cards-external-diffusion/cardsExternalDiffusion.feature
- ui/main/src/app/business/model/userWithPerimeters.model.ts
- ui/main/src/app/modules/settings/components/settings/checkbox-setting/checkbox-setting.component.scss
- ui/main/src/app/modules/settings/components/settings/settings.component.html
- ui/main/src/app/modules/settings/components/settings/settings.component.ts
- ui/main/src/assets/i18n/en.json
- ui/main/src/assets/i18n/fr.json
- ui/main/src/assets/i18n/nl.json
-  Text : #5733 Added the option to send daily recap by email
> Added the option to send daily recap by email (#5733)

- ui/main/src/assets/js/opfab.js
This commit resolves an issue where the usercard error would only appear once due to the use of the global flag (/g) in a JavaScript regular expression.
The issue was that calling this.EMPTY_REGEXP.test(this.quill.root.innerHTML) on the same string would return true the first time and false subsequently.
The global flag causes the RegExp.test() method to alternate between matching and not matching the regex,
as explained in the official MDN documentation: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test#using_test_on_a_regex_with_the_global_flag
Norhing in release note for 4.3.0 , will be in release note 4.2.0
> Solve issue : usercard error appears only once (#6104)

- ui/main/src/assets/js/opfab.js
This commit resolves an issue where the usercard error would only appear once due to the use of the global flag (/g) in a JavaScript regular expression. The issue was that calling this.EMPTY_REGEXP.test(this.quill.root.innerHTML) on the same string would return true the first time and false subsequently.
The global flag causes the RegExp.test() method to alternate between matching and not matching the regex, as explained in the official MDN documentation: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test#using_test_on_a_regex_with_the_global_flag
**- In release note 4.2.0  :**
-  Text : #6104 : usercard error appears only once
> Solve issue : usercard error appears only once (#6104) - release 4.2.0 
