opfab/operatorfabric-core

ui/main/src/app/services/time.service.spec.ts, ui/main/src/app/services/time.service.ts
Kind of change does this PR introduce: Bug fix
=> [OC-44] Resolving the issue with the date filter

ui/main/src/app/modules/archives/components/archive-filters/archive-filters.component.html, ui/main/src/app/modules/cards/components/detail/detail.component.ts, ui/main/src/assets/i18n/fr.json
From the feed page, the cards details section still unchanged after changing the current selection
=> [OC-344] Card details are not chaged whichever card is selected

ui/main/src/app/modules/cards/components/detail/detail.component.ts
=> [OC-334]: Fixing the build break

ui/main/src/app/modules/cards/components/card-details/card-details.component.html, ui/main/src/app/modules/cards/components/card-details/card-details.component.spec.ts, ui/main/src/app/modules/cards/components/card-details/card-details.component.ts, ui/main/src/app/store/effects/card.effects.spec.ts, ui/main/src/app/store/effects/card.effects.ts
As a 3rd party, I want to optionally display a cross icon on the card details so operators can close them
=> [OC-357] Display a cross icon on the card details

services/infra/config/src/main/docker/volume/dev-configurations/web-ui.yml, services/web/web-ui/src/docs/asciidoc/configuration.adoc, ui/main/src/app/modules/settings/components/settings/settings.component.html, ui/main/src/app/modules/settings/components/settings/settings.component.ts
The visibility of this field must be configurable. The administator can enable or disable it
=> [OC-440] Visibility of the tags in settings page

services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/controllers/CardOperationsController.java, ui/main/src/app/modules/feed/components/card-list/filters/filters.component.html, ui/main/src/app/modules/feed/components/card-list/filters/filters.component.ts, ui/main/src/app/modules/settings/components/settings/settings.component.html
As a user, I don't want to see the tags displayed on the top of the feed
=> [OC-438] Visibility of the tags in tags page

services/web/web-ui/src/docs/asciidoc/configuration.adoc, ui/main/src/app/modules/feed/components/card-list/filters/filters.component.ts, ui/main/src/app/modules/settings/components/settings/email-setting/email-setting.component.html, ui/main/src/app/modules/settings/components/settings/email-setting/email-setting.component.ts, ui/main/src/app/modules/settings/components/settings/settings.component.html, ui/main/src/app/modules/settings/components/settings/settings.component.ts, ui/main/src/app/modules/settings/components/settings/text-setting/text-setting.component.html, ui/main/src/app/modules/settings/components/settings/text-setting/text-setting.component.ts
Disabling the email and description in the settings page
=> [OC-435]: Disabling the email and description in the settings page

ui/main/src/app/modules/cards/components/card-details/card-details.component.html, ui/main/src/app/modules/cards/components/detail/detail.component.ts
=> [OC-334]: Fixing the template issue

services/core/actions/src/main/java/org/lfenergy/operatorfabric/actions/services/ActionService.java, services/core/actions/src/test/java/org/lfenergy/operatorfabric/actions/services/ActionServiceShould.java
`[OC-470]`
[OC-470]: https://opfab.atlassian.net/browse/OC-470
=> [OC-470] accepts action url without any curly braces

ui/main/src/app/modules/cards/services/handlebars.service.ts
*Does this PR already have an issue describing the problem ?* _If so, link to this issue using `#XXX` or `[OC-XXX]` and skip the rest_
*What kind of change does this PR introduce?* _(Bug fix, feature, docs update, …)_
*What is the current behavior?* _(You can also link to an open issue here)_
*What is the new behavior (if this is a feature change)?*
*Does this PR introduce a breaking change?* _(What changes might users need to make in their application due to this PR?)_
*Other information*:
TIP: If any of the questions/checkboxes don't apply, please delete them.
=> Helper 'json' added to the Handlebars helpers

ui/main/src/app/modules/cards/components/card/card.component.html
=> [OC-474] Fixing the design actions

src/docs/asciidoc/user_guide/01_deployment.adoc
=> [OC-473] Adding information regarding the ADMIN role ci_documentation

services/infra/config/src/main/docker/volume/dev-configurations/web-ui.yml, services/infra/config/src/main/docker/volume/docker-configurations/web-ui.yml, services/web/web-ui/src/docs/asciidoc/configuration.adoc, ui/main/src/app/modules/cards/services/handlebars.service.spec.ts, ui/main/src/app/modules/cards/services/handlebars.service.ts, ui/main/src/app/services/i18n.service.ts
[]  The commit message follows our guidelines
[]  Tests for the changes have been added (for bug fixes / features)
[] Docs have been added / updated (for bug fixes / features)
This is a simple fix for urgent client project. See OC-480 for full handling of the language choice issue.
=> [OC-505] Replace browser lang by config lang + EN default

ui/main/src/app/modules/cards/components/card/card.component.html
=> [OC-511] desactive rounded left control

services/web/web-ui/src/docs/asciidoc/configuration.adoc, ui/main/src/app/app.module.ts, ui/main/src/app/components/navbar/menus/menu-link/menu-link.component.html, ui/main/src/app/components/navbar/menus/menu-link/menu-link.component.scss, ui/main/src/app/components/navbar/menus/menu-link/menu-link.component.spec.ts, ui/main/src/app/components/navbar/menus/menu-link/menu-link.component.ts, ui/main/src/app/components/navbar/navbar.component.html, ui/main/src/app/components/navbar/navbar.component.spec.ts, ui/main/src/app/store/effects/menu.effects.spec.ts, ui/main/src/app/store/reducers/menu.reducer.spec.ts, ui/main/src/tests/helpers.spec.ts, ui/main/src/tests/helpers.ts
=> OC-524 Make the opening of thirdparty menu link configurable

ui/main/src/app/components/navbar/custom-logo/custom-logo.component.spec.ts
Fix issues with fixture.detectChanges()
=> Oc 558 bis (custom-logo)

services/infra/config/src/main/docker/volume/dev-configurations/web-ui.yml, services/web/web-ui/src/docs/asciidoc/01_timeline.adoc, ui/main/src/app/modules/feed/components/time-line/time-line.component.ts
The domain names to display must be configured from web-ui.json
=> Adding domaines to web-ui.json

client/actions/src/main/java/org/lfenergy/operatorfabric/actions/model/ActionEnum.java, client/thirds/src/main/java/org/lfenergy/operatorfabric/thirds/model/ActionEnum.java, services/core/actions/src/main/modeling/swagger.yaml, services/core/cards-publication/src/main/modeling/swagger.yaml, services/core/thirds/src/main/modeling/swagger.yaml
=> [OC-527] Check that properties that are defined as optional in the documentation (in bundles and in cards) don't cause errors if absent

services/core/actions/src/docs/asciidoc/01_3rd_Party_Endpoint_Spec.adoc, services/core/actions/src/docs/asciidoc/configuration.adoc, services/core/actions/src/docs/asciidoc/index.adoc, services/core/cards-consultation/src/docs/asciidoc/configuration.adoc, services/core/cards-publication/src/docs/asciidoc/01_Card_Examples.adoc, services/core/cards-publication/src/docs/asciidoc/02_Card_Anatomy.adoc, services/core/cards-publication/src/docs/asciidoc/03_REST_API_Overview.adoc, services/core/cards-publication/src/docs/asciidoc/configuration.adoc, services/core/cards-publication/src/docs/asciidoc/index.adoc, services/core/thirds/src/docs/asciidoc/00_customization_example.adoc, services/core/thirds/src/docs/asciidoc/02_troubleshooting.adoc, services/core/thirds/src/docs/asciidoc/configuration.adoc, services/core/time/src/docs/asciidoc/configuration.adoc
=> [OC-591] [User guide] - [Thirds service] - Review and corrections in documentation (asciidoc)

services/core/actions/src/docs/asciidoc/01_3rd_Party_Endpoint_Spec.adoc, services/core/actions/src/docs/asciidoc/configuration.adoc, services/core/actions/src/docs/asciidoc/index.adoc, services/core/cards-consultation/src/docs/asciidoc/configuration.adoc, services/core/cards-publication/src/docs/asciidoc/01_Card_Examples.adoc, services/core/cards-publication/src/docs/asciidoc/02_Card_Anatomy.adoc, services/core/cards-publication/src/docs/asciidoc/03_REST_API_Overview.adoc, services/core/cards-publication/src/docs/asciidoc/configuration.adoc, services/core/cards-publication/src/docs/asciidoc/index.adoc, services/core/time/src/docs/asciidoc/configuration.adoc
=> [OC-590] [User guide] - [Time service] - Review and corrections in documentation (asciidoc)

services/core/actions/src/docs/asciidoc/01_3rd_Party_Endpoint_Spec.adoc, services/core/actions/src/docs/asciidoc/configuration.adoc, services/core/actions/src/docs/asciidoc/index.adoc, services/core/cards-consultation/src/docs/asciidoc/configuration.adoc, services/core/cards-publication/src/docs/asciidoc/01_Card_Examples.adoc, services/core/cards-publication/src/docs/asciidoc/02_Card_Anatomy.adoc, services/core/cards-publication/src/docs/asciidoc/03_REST_API_Overview.adoc, services/core/cards-publication/src/docs/asciidoc/configuration.adoc, services/core/cards-publication/src/docs/asciidoc/index.adoc
=> [OC-589] [User guide] - [Actions service] - Review and corrections in documentation (asciidoc)

services/core/cards-consultation/src/docs/asciidoc/configuration.adoc, services/core/cards-publication/src/docs/asciidoc/01_Card_Examples.adoc, services/core/cards-publication/src/docs/asciidoc/02_Card_Anatomy.adoc, services/core/cards-publication/src/docs/asciidoc/03_REST_API_Overview.adoc, services/core/cards-publication/src/docs/asciidoc/configuration.adoc, services/core/cards-publication/src/docs/asciidoc/index.adoc
Can you please review this pull resquest ?
Thank you
=> [OC-556] Card example §3.2.1 form user guide are not accepted by server AND error not explicit

services/core/cards-consultation/src/docs/asciidoc/configuration.adoc, services/core/cards-publication/src/docs/asciidoc/01_Card_Examples.adoc, services/core/cards-publication/src/docs/asciidoc/02_Card_Anatomy.adoc, services/core/cards-publication/src/docs/asciidoc/03_REST_API_Overview.adoc, services/core/cards-publication/src/docs/asciidoc/configuration.adoc, services/core/cards-publication/src/docs/asciidoc/index.adoc, services/core/users/src/docs/asciidoc/00_cookbook.adoc, services/core/users/src/docs/asciidoc/01_users_and_groups.adoc, services/core/users/src/docs/asciidoc/configuration.adoc, services/core/users/src/docs/asciidoc/index.adoc
=> [OC-587] [User guide] - [User service] - Review and corrections in documentation (asciidoc)

tools/generic/utilities/src/main/java/org/lfenergy/operatorfabric/utilities/PathUtils.java
=> [OC-583] Strengthen permissions on bundle files

ui/main/src/app/components/navbar/navbar.component.html
See https://opfab.atlassian.net/browse/OC-607
=> OC-607 fixed incorrect mouse cursor on navbar entries

ui/main/src/app/modules/thirdparty/iframedisplay.component.html, ui/main/src/app/modules/thirdparty/iframedisplay.component.scss
See https://opfab.atlassian.net/browse/OC-606
=> OC-606 better sizing of iframe for third party applications

services/infra/config/src/main/docker/volume/dev-configurations/web-ui.yml, ui/main/src/app/store/effects/authentication.effects.spec.ts, ui/main/src/app/store/effects/authentication.effects.ts
Clear application data/state properly on logout
=> [OC-463] Clear application data/state properly on logout

services/infra/config/src/main/docker/volume/dev-configurations/web-ui.yml, ui/main/src/app/modules/feed/feed.component.ts, ui/main/src/app/services/card.service.ts, ui/main/src/app/services/notify.service.spec.ts, ui/main/src/app/services/notify.service.ts, ui/main/src/app/services/services.module.ts
Display notification from the browser when the user receive new cards
=> [OC-18] Adding Notification through OS and/or Browser - web push

src/main/docker/demo/docker-compose.sh, src/main/docker/demo/docker-compose.yml, src/main/docker/deploy/docker-compose.sh, src/main/docker/deploy/docker-compose.yml
Please can you review this pull request ?
Thank you
=> [OC-599] Do not run docker images run as root - AUDIT ENTSOE 

ui/main/src/app/services/notify.service.spec.ts
*Does this PR already have an issue describing the problem ?* _If so, link to this issue using `#XXX` or `[OC-XXX]` and skip the rest_
*What kind of change does this PR introduce?* _(Bug fix, feature, docs update, …)_
*What is the current behavior?* _(You can also link to an open issue here)_
*What is the new behavior (if this is a feature change)?*
*Does this PR introduce a breaking change?* _(What changes might users need to make in their application due to this PR?)_
*Other information*:
TIP: If any of the questions/checkboxes don't apply, please delete them.
=> [OC-207] Remove fdescribe

ui/main/src/app/app-routing.module.ts, ui/main/src/app/store/effects/authentication.effects.ts
OC-615: Once logged if the user reload the UI the navbar alone is displayed
This is a correction only commit. The UT will be done within the resolution of OC-611: Create missing Unit Test for Implicit flow in the UI.
=> stays on the url at page refresh

ui/main/src/app/store/effects/translate.effects.spec.ts, ui/main/src/app/store/effects/translate.effects.ts
Title and summary in feed do not work
=> [OC-650] Title and summary in feed do not work

tools/spring/spring-mongo-utilities/src/main/java/org/lfenergy/operatorfabric/springtools/configuration/mongo/MongoConfiguration.java
Please can you review this pull request ?
Thank you
=> [OC-602] Deprecated MongoClient constructor - AUDIT ENTSOE

services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/model/TimeSpanConsultationData.java, services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/repositories/CardOperationRepositoryImpl.java
Please can you review this pull request ?
Thank you
=> [OC-641] Correct deprecated warning in build

ui/main/src/app/modules/settings/components/settings/settings.component.ts
=> [OC-581] Resolving build break

services/infra/config/src/main/docker/volume/dev-configurations/web-ui.yml, services/infra/config/src/main/docker/volume/docker-configurations/web-ui.yml, ui/main/src/app/modules/feed/components/time-line/time-line.component.ts
See https://opfab.atlassian.net/projects/OC/issues/OC-659
=> [OC-659] changes in timeline TR domain configuration

services/core/cards-consultation/src/docs/asciidoc/configuration.adoc, services/core/cards-publication/src/docs/asciidoc/configuration.adoc, services/web/web-ui/src/docs/asciidoc/01_timeline.adoc
=> [OC-560] Fixing SEVERE warnings in doc generation

src/main/docker/test-environment/docker-compose.yml, src/main/docker/test-environment/keycloak-configuration.md, src/main/docker/test-quality-environment/docker-compose.yml
Remove set container names in test-env / test-quality-env
Remove demo docker-compose
Remove dummy-card-daemon image from DockerHub and gradle
Update documentation accordingly
=> OC-458 - Remove set container names and demo docker-compose

services/infra/client-gateway/src/docs/asciidoc/filters-and-cors-configuration.adoc, services/infra/config/src/main/docker/volume/dev-configurations/application.yml, services/infra/config/src/main/docker/volume/dev-configurations/web-ui.yml, services/web/web-ui/src/docs/asciidoc/configuration.adoc, src/docs/asciidoc/user_guide/02_security.adoc, ui/main/src/app/store/effects/authentication.effects.spec.ts, ui/main/src/app/store/effects/authentication.effects.ts
Log out button doesn't work when Keycloak and OpFab are on different domains
=> [OC-653] Keycloak and OpFab are on different domains

services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/services/CardWriteService.java, services/core/cards-publication/src/main/modeling/swagger.yaml, services/core/cards-publication/src/test/java/org/lfenergy/operatorfabric/cards/publication/services/CardWriteServiceShould.java
Please can you review this pull request ?
Thank you
=> [OC-368] Cards with an end date that is before their start date should be refused

ui/main/src/app/modules/feed/components/time-line/time-line.component.ts
Changing the local depending on what in the store in _opfab_ initialisation
=> [OC-664] Timeline labels don't take user locale into account

versions.properties
*Does this PR already have an issue describing the problem ?* _If so, link to this issue using `#XXX` or `[OC-XXX]` and skip the rest_
*What kind of change does this PR introduce?* _(Bug fix, feature, docs update, …)_
*What is the current behavior?* _(You can also link to an open issue here)_
*What is the new behavior (if this is a feature change)?*
*Does this PR introduce a breaking change?* _(What changes might users need to make in their application due to this PR?)_
To help users integrate new releases easily, we try to include all the relevant information in release notes
(pointing to the documentation regarding this new feature is …
=> OC-725  versions upgrade

services/infra/config/src/main/docker/volume/dev-configurations/web-ui.yml, services/web/web-ui/src/docs/asciidoc/configuration.adoc, src/docs/asciidoc/release_notes/0.16.1.RELEASE.adoc, ui/main/src/app/store/effects/authentication.effects.ts
- Adding a new endpoint _logout_url_ to web-ui.yaml
- Using this parameter _authentification.effects.ts_
- Adding the corresponding doc
=> [OC-724] As admin I want to configure the path of my logout endpoint

src/docs/asciidoc/release_notes/0.16.1.RELEASE.adoc
Please can you review the release note ?
Thank you
=> Update of release note for 3 jira tickets

src/docs/asciidoc/release_notes/1.2.0.RELEASE.adoc, ui/main/src/app/modules/feed/components/card-list/filters/severity-sort/severity-sort.component.html, ui/main/src/app/modules/feed/components/card-list/filters/severity-sort/severity-sort.component.ts, ui/main/src/app/modules/feed/components/time-line/time-line.component.spec.ts, ui/main/src/app/modules/feed/feed.component.spec.ts, ui/main/src/app/store/reducers/light-card.reducer.spec.ts, ui/main/src/app/store/selectors/feed.selectors.spec.ts, ui/main/src/app/store/selectors/feed.selectors.ts, ui/main/src/app/store/states/feed.state.spec.ts, ui/main/src/app/store/states/feed.state.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json
=> [OC-835] Removing lttd from sorts, switching default

services/core/actions/src/main/docker/Dockerfile, services/core/cards-consultation/src/main/docker/Dockerfile, services/core/cards-publication/src/main/docker/Dockerfile, services/core/thirds/src/main/docker/Dockerfile, services/core/users/src/main/docker/Dockerfile, services/infra/client-gateway/src/main/docker/Dockerfile, services/infra/config/src/main/docker/Dockerfile, services/infra/registry/src/main/docker/Dockerfile, services/web/web-ui/src/main/docker/Dockerfile, src/docs/asciidoc/deployment/index.adoc
Tested image generation and running them using deploy docker-compose : OK
=> [OC-793] Changing docker base image

services/core/users/src/main/java/org/lfenergy/operatorfabric/users/configuration/DataInitComponent.java, services/core/users/src/main/java/org/lfenergy/operatorfabric/users/controllers/GroupsController.java, services/core/users/src/main/java/org/lfenergy/operatorfabric/users/model/GroupData.java, services/core/users/src/main/modeling/swagger.yaml, services/core/users/src/main/resources/application-dev.yml, services/core/users/src/test/java/org/lfenergy/operatorfabric/users/ApplicationShould.java, services/core/users/src/test/java/org/lfenergy/operatorfabric/users/controllers/GroupsControllerShould.java, services/core/users/src/test/resources/application-test-init.yml, services/infra/config/src/main/docker/volume/dev-configurations/users.yml, services/infra/config/src/main/docker/volume/docker-configurations/users.yml, src/docs/asciidoc/deployment/users_groups_admin.adoc, src/docs/asciidoc/docs/release_notes.adoc, src/test/api/karate/users/groups/addUsersToGroup.feature, src/test/api/karate/users/groups/createGroups.feature, src/test/api/karate/users/groups/deleteUserFromGroup.feature, src/test/api/karate/users/groups/getGroupDetails.feature, src/test/api/karate/users/groups/getGroups.feature, src/test/api/karate/users/groups/updateExistingGroup.feature, src/test/utils/karate/users/getGroupsAndUsers.feature
Please can you review this pull request ? 
Thank you.
=> [OC-736] Add a field "name" to the object group

src/docs/asciidoc/community/index.adoc
New list voted by email 12/05/20
=> [OC-886] Updating TSC members

src/docs/asciidoc/community/CODE_OF_CONDUCT.adoc
=> [OC-794] Updating Code of Conduct

ui/main/src/app/modules/archives/archive.component.spec.ts, ui/main/src/app/modules/archives/archives.component.html, ui/main/src/app/modules/archives/archives.component.scss, ui/main/src/app/modules/archives/archives.component.ts, ui/main/src/app/store/actions/archive.actions.ts, ui/main/src/app/store/reducers/archive.reducer.ts, ui/main/src/app/store/selectors/archive.selectors.ts, ui/main/src/app/store/states/archive.state.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json
This branch includes the request of the OC-402
=> [OC-772] Bug on archives filters and &  display an explicit message if no cards are found that match my filters ..

src/docs/asciidoc/getting_started/index.adoc
- Token script now needs to be sourced
- Removed token copy instruction
- Added json syntax highlighting
=> [OC-896] Updating getting started for 1.3.0.RELEASE and minor fixes

services/core/actions/src/main/java/org/lfenergy/operatorfabric/actions/services/ActionService.java, services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/configuration/json/PageImplSerializer.java, services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/configuration/webflux/GlobalErrorWebExceptionHandler.java, services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/model/LightCardConsultationData.java, services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/repositories/ArchivedCardCustomRepository.java, services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/repositories/ArchivedCardCustomRepositoryImpl.java, services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/repositories/CardOperationRepositoryImpl.java, services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/repositories/UserUtilitiesCommonToCardRepository.java, services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/services/CardSubscription.java, services/core/cards-consultation/src/test/java/org/lfenergy/operatorfabric/cards/consultation/TestUtilities.java, services/core/cards-consultation/src/test/java/org/lfenergy/operatorfabric/cards/consultation/controllers/CardOperationsControllerShould.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/configuration/mongo/LocalMongoConfiguration.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/model/CardPublicationData.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/model/LightCardPublicationData.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/services/CardRepositoryService.java, src/docs/asciidoc/docs/release_notes.adoc
Fixed small issues from Sonarcloud and made light refactoring about a couple of properties in LightCardConsultationData for json serialization concerns
=> [OC-692] Fix Sonar and refactoring LigthCard references

src/docs/asciidoc/docs/release_notes.adoc, ui/main/src/app/components/navbar/navbar.component.html, ui/main/src/app/modules/cards/components/details/details.component.ts, ui/main/src/app/modules/cards/services/handlebars.service.ts, ui/main/src/app/modules/feed/components/card-list/filters/time-filter/time-filter.component.ts, ui/main/src/app/modules/feed/components/time-line/custom-timeline-chart/custom-timeline-chart.component.scss, ui/main/src/app/store/reducers/light-card.reducer.ts
=> [OC-888] Sonarcloud frontend fixes

src/docs/asciidoc/docs/release_notes.adoc, ui/main/src/app/services/authentication/authentication.service.ts
=> [OC-898]  First and last name not displayed in implicit mode

CICD/prepare_release_version.sh, src/docs/asciidoc/docs/release_notes.adoc, src/main/docker/deploy/docker-compose.yml
=> [OC-899] Updating deploy and dev-env to rely on SNAPSHOT images

src/docs/asciidoc/CICD/release_process.adoc, src/docs/asciidoc/TODO_WIP.adoc, src/docs/asciidoc/community/workflow.adoc, src/docs/asciidoc/deployment/configuration/configuration.adoc, src/docs/asciidoc/deployment/configuration/registry_configuration.adoc, src/docs/asciidoc/dev_env/launch_dev.adoc, src/docs/asciidoc/dev_env/misc.adoc, src/docs/asciidoc/dev_env/project_structure.adoc, src/docs/asciidoc/dev_env/requirements.adoc, src/docs/asciidoc/dev_env/troubleshooting.adoc
=> OC-901 Fixing broken links in doc

services/core/thirds/src/main/java/org/lfenergy/operatorfabric/thirds/controllers/ThirdsController.java, services/core/thirds/src/main/java/org/lfenergy/operatorfabric/thirds/services/ThirdsService.java, services/core/thirds/src/main/modeling/swagger.yaml, services/core/thirds/src/test/java/org/lfenergy/operatorfabric/thirds/controllers/GivenAdminUserThirdControllerShould.java, services/core/thirds/src/test/java/org/lfenergy/operatorfabric/thirds/controllers/GivenNonAdminUserThirdControllerShould.java, services/core/thirds/src/test/java/org/lfenergy/operatorfabric/thirds/services/ThirdsServiceShould.java, src/docs/asciidoc/docs/release_notes.adoc, src/test/api/karate/launchAllThirds.sh, src/test/api/karate/thirds/deleteBundle.feature
Check out our link:src/docs/asciidoc/community/review_checklist.adoc[PR review checklist]
=> [OC-897] added operation delete for the resource thirds

services/core/cards-publication/build.gradle, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/CardPublicationApplication.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/controllers/CardController.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/security/configuration/WebSecurityConfiguration.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/services/CardProcessingService.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/services/processors/UserCardProcessor.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/services/processors/impl/UserCardProcessorImpl.java, services/core/cards-publication/src/main/resources/application-dev.yml, services/core/cards-publication/src/main/resources/application-docker.yml, services/core/cards-publication/src/test/java/org/lfenergy/operatorfabric/cards/publication/configuration/webflux/WebSecurityConfigurationTest.java, services/core/cards-publication/src/test/java/org/lfenergy/operatorfabric/cards/publication/services/CardProcessServiceShould.java, src/docs/asciidoc/docs/release_notes.adoc, src/test/api/karate/cards/userCards.feature, src/test/api/karate/launchAllCards.sh
Then, remove the text and replace it with your PR comment.
* Look through changed files to make sure everything is relevant to the PR (no mistakenly added changes,
no secret information, no malicious changes) and to see if you have remarks on the way things are implemented
* Check that the commit(s) message(s) is(are) relevant and follow conventions ([OC-XXX] ... )
* If there is more than one commit, is it meaningful or do we …
=> [OC-875] ==> New endpoint cards/userCard to receive users cards

ui/main/src/app/modules/feed/components/card-list/filters/filters.component.html, ui/main/src/app/modules/feed/components/card-list/filters/filters.component.ts, ui/main/src/app/services/card.service.ts, ui/main/src/app/store/actions/cards-subscription.actions.ts, ui/main/src/app/store/index.ts, ui/main/src/app/store/reducers/cards-subscription.reducer.ts, ui/main/src/app/store/selectors/cards-subscription.selectors.ts, ui/main/src/app/store/states/cards-subscription.state.ts, ui/main/src/tests/helpers.ts
RELEASE NOTE :  
[OC-945] Add a spining icon when connection with server is lost 
[OC-945]: https://opfab.atlassian.net/browse/OC-945
=> [OC-945] Add a spining icon when connection with server is lost

build.gradle
RELEASE NOTE : 
Tasks: 
[OC-943] : Add a gradle task to launch sonar analysis.
[OC-943]: https://opfab.atlassian.net/browse/OC-943
=> [OC-943] Add a gradle task to launch sonar analysis

README.adoc, src/docs/asciidoc/resources/mock_pipeline.adoc
I created this issue mostly to track the change in case something funny happens with the pipeline again, but I don't think it should appear on the release notes.
=> [OC-965] Updating default branch Sonar

services/core/thirds/src/main/java/org/lfenergy/operatorfabric/thirds/model/ThirdData.java, services/core/thirds/src/main/java/org/lfenergy/operatorfabric/thirds/model/ThirdStatesData.java, services/core/thirds/src/main/modeling/swagger.yaml
Then, remove the text and replace it with your PR comment.
* Look through changed files to make sure everything is relevant to the PR (no mistakenly added changes,
no secret information, no malicious changes) and to see if you have remarks on the way things are implemented
* Check that the commit(s) message(s) is(are) relevant and follow conventions ([OC-XXX] ... )
* If there is more than one commit, is it meaningful or do we …
=> [OC-977] Add acknowledgmentAllowed in bundle definition

services/core/thirds/src/main/java/org/lfenergy/operatorfabric/thirds/model/ThirdProcessesData.java, services/core/thirds/src/main/java/org/lfenergy/operatorfabric/thirds/model/ThirdStatesData.java, services/core/thirds/src/main/modeling/swagger.yaml
REALESE NOTES
link:++https://opfab.atlassian.net/browse/OC-954++[OC-954] Add name field for process/state and stateColor in third
[OC-954]: https://opfab.atlassian.net/browse/OC-954
=> [OC-954] names processes and states, colors states

services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/model/CardPublicationData.java, services/core/cards-publication/src/main/modeling/swagger.yaml, src/test/api/karate/cards/cards.feature
for release  notes:
[OC-957] : Field recipient in card shoud be optionnal
[OC-957]: https://opfab.atlassian.net/browse/OC-957
=> [OC-957] : Field recipient in card shoud be optionnal

ui/main/src/app/modules/cards/components/card-details/card-details.component.html, ui/main/src/app/modules/feed/components/time-line/custom-timeline-chart/custom-timeline-chart.component.html
Small ui correction related to ticket OC-947 
=> [OC-947] Align left text in message after bubble click

services/core/thirds/src/main/modeling/swagger.yaml
=> [OC-962] add code removed by error in OC-962

client/users/src/main/java/org/lfenergy/operatorfabric/users/model/RightsEnum.java, services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/services/CardSubscription.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/services/CardProcessingService.java, services/core/users/src/main/java/org/lfenergy/operatorfabric/users/model/CurrentUserWithPerimetersData.java, services/core/users/src/main/modeling/swagger.yaml, services/core/users/src/test/java/org/lfenergy/operatorfabric/users/controllers/GroupsControllerShould.java, services/core/users/src/test/java/org/lfenergy/operatorfabric/users/controllers/PerimetersControllerShould.java, services/core/users/src/test/java/org/lfenergy/operatorfabric/users/controllers/UsersControllerShould.java, services/core/users/src/test/java/org/lfenergy/operatorfabric/users/model/CurrentUserWithPerimetersDataShould.java, services/core/users/src/test/java/org/lfenergy/operatorfabric/users/services/UserServiceShould.java, src/test/api/karate/users/perimeters/addPerimetersForAGroup.feature, src/test/api/karate/users/perimeters/createPerimeters.feature, src/test/api/karate/users/perimeters/deleteGroupFromPerimeter.feature, src/test/api/karate/users/perimeters/getCurrentUserWithPerimeters.feature, src/test/api/karate/users/perimeters/getCurrentUserWithPerimeters_JWTMode.feature, src/test/api/karate/users/perimeters/getPerimeterDetails.feature, src/test/api/karate/users/perimeters/getPerimetersForAGroup.feature, src/test/api/karate/users/perimeters/getPerimetersForAUser.feature, src/test/api/karate/users/perimeters/postCardRoutingPerimeters.feature, src/test/api/karate/users/perimeters/updateExistingPerimeter.feature, src/test/api/karate/users/perimeters/updateListOfPerimeterGroups.feature, src/test/api/karate/users/perimeters/updatePerimetersForAGroup.feature, src/test/utils/karate/cards/post2CardsOnlyForEntitiesWithPerimeters.feature
Release note :
[OC-950](https://opfab.atlassian.net/browse/OC-950) Rename RightsEnum
=> [OC-950] Rename RightsEnum

src/docs/asciidoc/CICD/release_process.adoc
Should we put this type of (doc-only) issues on the release notes?
In any case, I see no additional information to provide, the title says it all.
=> [OC-999] Minor edits to doc after 1rst git flow release

services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/model/CardPublicationData.java, services/core/cards-publication/src/test/java/org/lfenergy/operatorfabric/cards/publication/controllers/AsyncCardControllerShould.java, services/core/cards-publication/src/test/java/org/lfenergy/operatorfabric/cards/publication/controllers/CardControllerShould.java, services/core/cards-publication/src/test/java/org/lfenergy/operatorfabric/cards/publication/services/CardProcessServiceShould.java, src/test/api/karate/cards/postCardWithNoProcess.feature, src/test/api/karate/cards/postCardWithNoState.feature, src/test/api/karate/launchAllCards.sh
Release note :
[OC-951](https://opfab.atlassian.net/browse/OC-951) Process and state fields of a card must be mandatory
=> [OC-951] Process and state fields of a card must be mandatory

config/dev/web-ui.json, config/docker/web-ui.json, src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc, ui/main/src/app/modules/archives/components/archive-filters/archive-filters.component.ts, ui/main/src/app/modules/archives/components/archive-list/archive-list-page/archive-list-page.component.html, ui/main/src/app/modules/archives/components/archive-list/archive-list-page/archive-list-page.component.ts
Resolve 2 bugs 
+ remove unuseful parameter operatorfabric.archive.filter.page.first 
+ remove unused parameter  operatorfabric.archive.filter.publisher 
RELEASE NOTE : 
[OC-1006] Archives - Bugs in pagination . 
Information :  Parameters  operatorfabric.archive.filter.page.first  &  operatorfabric.archive.filter.publisher  in web-ui.json has been removed
[OC-1006]: https://opfab.atlassian.net/browse/OC-1006
=> [OC-1006] Archives - Bugs in pagination

ui/main/src/app/modules/settings/components/settings/email-setting/email-setting.component.html, ui/main/src/app/modules/settings/components/settings/text-setting/text-setting.component.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json
Release Note : 
[OC-990 ] Automatic saving of the settings . User do not need anymore to press enter when modifying a text field in the settings view.
=> [OC-990] Automatic saving of the settings

ui/main/src/app/modules/cards/components/detail/detail.component.ts, ui/main/src/app/services/global-style.service.ts, ui/main/src/app/store/actions/global-style.actions.ts, ui/main/src/app/store/index.ts, ui/main/src/app/store/reducers/global-style.reducer.ts, ui/main/src/app/store/selectors/global-style.selectors.ts, ui/main/src/app/store/states/global-style.state.ts, ui/main/src/tests/helpers.ts
[OC-974] Redraw card when switching day/night mode
[OC-974]: https://opfab.atlassian.net/browse/OC-974
=> [OC-974] Redraw card when switching day/night mode

config/dev/web-ui.json, config/docker/web-ui.json, src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc, ui/main/src/app/modules/feed/components/card-list/filters/filters.component.html, ui/main/src/app/modules/feed/components/card-list/filters/filters.component.ts, ui/main/src/app/modules/feed/components/card-list/filters/time-filter/time-filter.component.html, ui/main/src/app/modules/feed/components/card-list/filters/time-filter/time-filter.component.spec.ts, ui/main/src/app/modules/feed/components/card-list/filters/time-filter/time-filter.component.ts, ui/main/src/app/modules/feed/components/time-line/init-chart/init-chart.component.ts, ui/main/src/app/services/filter.service.spec.ts, ui/main/src/app/services/filter.service.ts, ui/main/src/app/store/effects/card-operation.effects.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json
[OC-949] Filter by publish date in feed when clicking on the clock icon 
NB : If the timeline is not loaded (parameter operatorfabric.feed.timeline.hide set to true ) , the time filter on the feed is still filtering on business date 
[OC-949]: https://opfab.atlassian.net/browse/OC-949
=> [OC-949] Filter by publish date in feed

services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/controllers/CardController.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/security/configuration/WebSecurityConfiguration.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/services/CardProcessingService.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/services/processors/UserCardProcessor.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/services/processors/impl/UserCardProcessorImpl.java, services/core/cards-publication/src/test/java/org/lfenergy/operatorfabric/cards/publication/services/CardProcessServiceShould.java, src/test/api/karate/cards/userCards.feature, src/test/api/karate/launchAllCards.sh
for release notes:
tasks:
[OC-914] control authorizations for /userCard endpoint
[OC-914]: https://opfab.atlassian.net/browse/OC-914
=> [OC-914] control authorizations for /userCard endpoint

ui/main/src/app/modules/feed/components/time-line/init-chart/init-chart.component.html, ui/main/src/app/modules/feed/components/time-line/init-chart/init-chart.component.scss, ui/main/src/app/modules/feed/components/time-line/init-chart/init-chart.component.ts, ui/main/src/app/modules/feed/components/time-line/time-line.component.html, ui/main/src/app/modules/feed/feed.component.html, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json
[OC-948]  Button for hide or display timeline
[OC-948]: https://opfab.atlassian.net/browse/OC-948
=> [OC-948]  Button for hide or display timeline

config/docker/cards-publication-docker.yml, config/docker/docker-compose.yml
RELEASE NOTE :
[OC-1014] Load configuration files  from outside docker in the config/docker/docker-compose.yml
[OC-1014]: https://opfab.atlassian.net/browse/OC-1014
=>  [OC-1014] Load configuration from outside docker

src/docs/asciidoc/reference_doc/card_examples.adoc, src/docs/asciidoc/reference_doc/card_structure.adoc, src/docs/asciidoc/reference_doc/users_service.adoc
Release note:
[OC-830] Update documentation with routing mechanism
[OC-830]: https://opfab.atlassian.net/browse/OC-830
=> [OC-830] Update documentation with routing mechanism

config/dev/web-ui.json, config/docker/web-ui.json, src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc, ui/main/src/app/components/navbar/navbar.component.spec.ts, ui/main/src/app/components/navbar/navbar.component.ts, ui/main/src/app/store/states/menu.state.ts
[OC-1029] possibility to hide some application menus
[OC-1029]: https://opfab.atlassian.net/browse/OC-1029
=> [OC-1029] hides some application menus in the navbar

services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/services/CardProcessingService.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/services/CardRepositoryService.java, services/core/cards-publication/src/test/java/org/lfenergy/operatorfabric/cards/publication/services/CardProcessServiceShould.java, src/test/api/karate/cards/userCards.feature
for release notes:
[OC-966] : when delete/update card , delete child card
[OC-966]: https://opfab.atlassian.net/browse/OC-966
=> [OC-966] : when delete/update card , delete child card

services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/configuration/mongo/LightCardReadConverter.java, services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/configuration/webflux/CardRoutesConfig.java, services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/model/ArchivedCardConsultationData.java, services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/model/CardConsultationData.java, services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/model/LightCardConsultationData.java, services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/repositories/ArchivedCardCustomRepositoryImpl.java, services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/repositories/CardCustomRepositoryImpl.java, services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/repositories/UserUtilitiesCommonToCardRepository.java, services/core/cards-consultation/src/test/java/org/lfenergy/operatorfabric/cards/consultation/routes/CardRoutesShould.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/model/ArchivedCardPublicationData.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/model/CardPublicationData.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/model/LightCardPublicationData.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/services/CardProcessingService.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/services/CardRepositoryService.java, services/core/cards-publication/src/main/modeling/swagger.yaml, services/core/cards-publication/src/test/java/org/lfenergy/operatorfabric/cards/publication/services/CardProcessServiceShould.java, src/test/api/karate/cards/cards.feature, src/test/api/karate/cards/userCards.feature, ui/main/src/app/model/card.model.ts, ui/main/src/app/model/light-card.model.ts, ui/main/src/app/modules/cards/components/card-details/card-details.component.ts, ui/main/src/app/modules/cards/components/detail/detail.component.ts, ui/main/src/app/modules/feed/feed.component.ts
for releases notes:
[OC-1001] : rename parentCardId card field to parentCardUid
[OC-1001]: https://opfab.atlassian.net/browse/OC-1001
=> [OC-1001] : rename parentCardId card field to parentCardUid

bin/load_environment_light.sh, build.gradle, gradle/wrapper/gradle-wrapper.properties, services/core/cards-consultation/src/test/java/org/lfenergy/operatorfabric/cards/consultation/controllers/CardOperationsControllerShould.java, services/core/cards-consultation/src/test/java/org/lfenergy/operatorfabric/cards/consultation/repositories/CardRepositoryShould.java, services/core/cards-publication/src/test/java/org/lfenergy/operatorfabric/cards/publication/controllers/CardControllerProcessAcknowledgementShould.java, services/core/cards-publication/src/test/java/org/lfenergy/operatorfabric/cards/publication/services/CardProcessServiceShould.java, settings.gradle, src/test/externalApp/build.gradle, src/test/externalApp/settings.gradle, tools/spring/spring-mongo-utilities/build.gradle, tools/spring/spring-mongo-utilities/src/main/java/org/lfenergy/operatorfabric/springtools/configuration/mongo/MongoConfiguration.java, versions.properties
for release notes:
[OC-1030] : upgrade spring from 2.2.5 to 2.4.0-M1
[OC-1030]: https://opfab.atlassian.net/browse/OC-1030
=> [OC-1030] : upgrade spring from 2.2.5 to 2.4.0-M1

ui/main/src/app/modules/archives/components/archive-filters/archive-filters.component.ts
Then, remove the text and replace it with the information and comments that should go into the release notes.
* The PR comment contains a brief explanation of the impact of these developments, and a pointer
to the relevant documentation if need be. Otherwise, it should why this development doesn't need
to be on the release notes.
* Look through changed files to make sure everything is relevant to the PR (no mistakenly added …
=> [OC-938] : In archives, reset button doesn't really clear selected card

.travis.yml, bin/load_environment_light.sh
Release notes already updated.
=> [OC-1050] Bumping java version (minor) to one supported by sdkman

ui/main/src/app/modules/logging/components/logging-table/logging-table.component.html, ui/main/src/app/modules/logging/components/logging-table/logging-table.component.scss, ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.html, ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.scss, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json
Aligns code to be Sonar compliant and translates monitoring table headers.
=> [OC-936] corrects sonar alerts and translates logging table headers

bin/load_variables.sh, services/core/cards-publication/build.gradle, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/CardPublicationApplication.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/configuration/mongo/LocalMongoConfiguration.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/configuration/mongo/TraceReadConverter.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/controllers/CardController.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/services/CardProcessingService.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/services/CardRepositoryService.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/services/TraceReposiory.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/services/UserBasedOperationResult.java, services/core/cards-publication/src/test/java/org/lfenergy/operatorfabric/cards/publication/repositories/TraceReposioryForTest.java, services/core/cards-publication/src/test/java/org/lfenergy/operatorfabric/cards/publication/services/CardProcessServiceShould.java, settings.gradle, src/test/api/karate/cards/userAcknowledgmentUpdateCheck.feature, tools/spring/aop-process/build.gradle, tools/spring/aop-process/src/main/java/org/lfenergy/operatorfabric/aop/annotations/EnableAopTraceProcessing.java, tools/spring/aop-process/src/main/java/org/lfenergy/operatorfabric/aop/process/AbstractActionAspect.java, tools/spring/aop-process/src/main/java/org/lfenergy/operatorfabric/aop/process/AopTraceType.java, tools/spring/aop-process/src/main/java/org/lfenergy/operatorfabric/aop/process/MongoActionTraceAspect.java, tools/spring/aop-process/src/main/java/org/lfenergy/operatorfabric/aop/process/UserAcknowledgmentActionTraceAspect.java, tools/spring/aop-process/src/main/java/org/lfenergy/operatorfabric/aop/process/mongo/models/UserActionTraceData.java
not finished yet, this PR is for feedback
=> [OC-1041] : Log user ackKnowledgment

services/core/users/src/main/java/org/lfenergy/operatorfabric/users/configuration/oauth2/WebSecurityConfiguration.java, services/core/users/src/main/java/org/lfenergy/operatorfabric/users/controllers/UsersController.java, services/core/users/src/main/modeling/swagger.yaml, services/core/users/src/test/java/org/lfenergy/operatorfabric/users/controllers/UsersControllerShould.java, src/test/api/karate/launchAllUsers.sh, src/test/api/karate/users/deleteUser.feature
Release note:
[OC-1021](https://opfab.atlassian.net/browse/OC-1021) Endpoint do delete user
=> [OC-1021] Endpoint do delete user

services/core/users/src/main/java/org/lfenergy/operatorfabric/users/controllers/EntitiesController.java, services/core/users/src/main/modeling/swagger.yaml, services/core/users/src/test/java/org/lfenergy/operatorfabric/users/controllers/EntitiesControllerShould.java, services/core/users/src/test/java/org/lfenergy/operatorfabric/users/controllers/UsersControllerShould.java, src/test/api/karate/launchAllUsers.sh, src/test/api/karate/users/deleteEntity.feature, src/test/api/karate/users/deleteUser.feature
Release note:
[OC-1022](https://opfab.atlassian.net/browse/OC-1022) Endpoint to delete entity
=> [OC-1022] End point to delete entity

services/core/users/src/main/java/org/lfenergy/operatorfabric/users/controllers/EntitiesController.java, services/core/users/src/main/java/org/lfenergy/operatorfabric/users/controllers/GroupsController.java, services/core/users/src/main/modeling/swagger.yaml, services/core/users/src/test/java/org/lfenergy/operatorfabric/users/controllers/EntitiesControllerShould.java, services/core/users/src/test/java/org/lfenergy/operatorfabric/users/controllers/GroupsControllerShould.java, src/test/api/karate/launchAllUsers.sh, src/test/api/karate/users/entities/deleteEntity.feature, src/test/api/karate/users/groups/deleteGroup.feature
Release note:
[OC-1023](https://opfab.atlassian.net/browse/OC-1023) Endpoint to delete group
=> [OC-1023] Endpoint to delete group

.travis.yml, bin/load_environment_light.sh
Release note :
Replace line regarding [OC-1050] with this issue
[OC-1050]: https://opfab.atlassian.net/browse/OC-1050
=> [OC-1063] Update java to version 8.0.265-zulu

services/core/users/src/main/java/org/lfenergy/operatorfabric/users/controllers/EntitiesController.java, services/core/users/src/main/java/org/lfenergy/operatorfabric/users/controllers/PerimetersController.java, services/core/users/src/main/modeling/swagger.yaml, services/core/users/src/test/java/org/lfenergy/operatorfabric/users/controllers/PerimetersControllerShould.java, src/test/api/karate/launchAllUsers.sh, src/test/api/karate/users/perimeters/deletePerimeter.feature
Release note:
[OC-1024](https://opfab.atlassian.net/browse/OC-1024) Endpoint to delete perimeter
=> [OC-1024] Endpoint to delete perimeter

src/docs/asciidoc/getting_started/index.adoc
Release note:
[OC-831](https://opfab.atlassian.net/browse/OC-831) Update getting started with routing mechanism
=> [OC-831] Update getting started with routing mechanism

services/core/users/src/main/java/org/lfenergy/operatorfabric/users/configuration/oauth2/WebSecurityConfiguration.java, services/core/users/src/main/modeling/swagger.yaml, services/core/users/src/test/java/org/lfenergy/operatorfabric/users/controllers/EntitiesControllerShould.java, src/test/api/karate/users/entities/getEntities.feature
Release note:
[OC-1067](https://opfab.atlassian.net/browse/OC-1067) GET /entities : allow all users for this operation
=> [OC-1067] GET /entities : allow all users for this operation

ui/main/src/app/modules/feed/components/time-line/custom-timeline-chart/custom-timeline-chart.component.html, ui/main/src/app/modules/feed/components/time-line/custom-timeline-chart/custom-timeline-chart.component.scss, ui/main/src/app/modules/feed/components/time-line/custom-timeline-chart/custom-timeline-chart.component.ts
Limit the number of lines to show when clicking on a bubble in the timeline
The number of line is calculated regarding the window height
Relase Note :
[OC-1069] Limit the number of lines to show when clicking on bubbles in timeline
[OC-1069]: https://opfab.atlassian.net/browse/OC-1069
=> [OC-1069] Limit  line when clicking on timeline

src/test/utils/karate/businessconfig/resources/bundle_defaultProcess/config.json, src/test/utils/karate/businessconfig/resources/bundle_defaultProcess/css/contingencies.css, src/test/utils/karate/businessconfig/resources/bundle_defaultProcess/i18n/en.json, src/test/utils/karate/businessconfig/resources/bundle_defaultProcess/i18n/fr.json, src/test/utils/karate/businessconfig/resources/bundle_defaultProcess/template/en/contingencies.handlebars, src/test/utils/karate/businessconfig/resources/bundle_defaultProcess/template/fr/contingencies.handlebars, src/test/utils/karate/cards/post6CardsSeverity.feature
No information in release note
=> [OC-1070] Add new example in defaultBundle

src/docs/asciidoc/reference_doc/card_examples.adoc, src/docs/asciidoc/reference_doc/card_structure.adoc
[[OC-419](https://opfab.atlassian.net/browse/OC-419)] : Correcting Publication Service Documentation (Reference doc)
=> [OC-419] Correcting Publication Service Documentation (User Guide)

services/core/businessconfig/src/main/docker/volume/businessconfig-storage/TEST/1/config.json, services/core/businessconfig/src/main/docker/volume/businessconfig-storage/TEST/config.json, services/core/businessconfig/src/main/docker/volume/businessconfig-storage/first/0.1/config.json, services/core/businessconfig/src/main/docker/volume/businessconfig-storage/first/config.json, services/core/businessconfig/src/main/docker/volume/businessconfig-storage/first/v1/config.json, services/core/businessconfig/src/main/java/org/lfenergy/operatorfabric/businessconfig/configuration/json/BusinessconfigModule.java, services/core/businessconfig/src/main/java/org/lfenergy/operatorfabric/businessconfig/model/ProcessData.java, services/core/businessconfig/src/main/java/org/lfenergy/operatorfabric/businessconfig/model/ProcessUiVisibilityData.java, services/core/businessconfig/src/main/modeling/swagger.yaml, src/test/api/karate/businessconfig/getABusinessconfig.feature, src/test/api/karate/businessconfig/resources/bundle_api_test/config.json, src/test/api/karate/businessconfig/resources/bundle_api_test_v2/config.json, src/test/utils/karate/businessconfig/resources/bundle_defaultProcess/config.json, ui/main/src/app/model/processes.model.ts, ui/main/src/app/modules/logging/logging.component.ts, ui/main/src/app/modules/monitoring/monitoring.component.ts
[[OC-1076](https://opfab.atlassian.net/browse/OC-1076)] : Add a filter to see only revelant process
=> [OC-1076] Add a filter to see only revelant process

ui/main/src/app/modules/cards/components/card-details/card-details.component.ts, ui/main/src/app/modules/free-message/free-message.component.ts
Then, remove the text and replace it with the information and comments that should go into the release notes.
* The PR comment contains a brief explanation of the impact of these developments, and a pointer
to the relevant documentation if need be. Otherwise, it should why this development doesn't need
to be on the release notes.
* Look through changed files to make sure everything is relevant to the PR (no mistakenly added …
=> [OC-1082] UI - Remove use of  method askUserApplicationRegistered

services/core/businessconfig/src/main/docker/volume/businessconfig-storage/first/config.json, services/core/businessconfig/src/main/docker/volume/businessconfig-storage/first/v1/config.json, services/core/businessconfig/src/main/docker/volume/businessconfig-storage/first/v1/i18n/en.json, services/core/businessconfig/src/main/docker/volume/businessconfig-storage/first/v1/i18n/fr.json, src/test/utils/karate/businessconfig/resources/bundle_defaultProcess/config.json, src/test/utils/karate/businessconfig/resources/bundle_defaultProcess/i18n/en.json, src/test/utils/karate/businessconfig/resources/bundle_defaultProcess/i18n/fr.json, src/test/utils/karate/cards/post6CardsSeverity.feature, src/test/utils/karate/cards/setPerimeterFor6Cards.feature
Release note :
Tasks: 
[OC-1094] Add write access for "defaultprocess" with state "message" in standard config and bundle cleaning
[OC-1094]: https://opfab.atlassian.net/browse/OC-1094
=> [OC-1094] Add write access for defaultprocess with state message in standard config and bundle cleaning

config/dev/ngnix.conf, config/docker/nginx-cors-permissive.conf, config/docker/ngnix.conf, services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/services/CardSubscriptionService.java, ui/main/src/app/services/card.service.ts
Add an heardbeat mechanism to the SSE connection
to avoid setting long timeout in nginx
and to be compatible with the use of external proxies
Release note:
Task: 
[OC-1096] Add an heardbeat mechanism to the SSE connection to avoid setting long timeout in nginx and to be compatible with the use of external proxies
[OC-1096]: https://opfab.atlassian.net/browse/OC-1096
=> [OC-1096] Robustify connection for card notification

ui/main/src/app/modules/cards/components/detail/detail.component.html, ui/main/src/app/modules/cards/components/detail/detail.component.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json
Then, remove the text and replace it with the information and comments that should go into the release notes.
* The PR comment contains a brief explanation of the impact of these developments, and a pointer
to the relevant documentation if need be. Otherwise, it should why this development doesn't need
to be on the release notes.
* Look through changed files to make sure everything is relevant to the PR (no mistakenly added …
=> [OC-967] Front : view all user entity responses

ui/main/src/app/modules/feed/components/card-list/filters/time-filter/time-filter.component.ts, ui/main/tslint.json
Features: 
[OC-1116] Init hours and minutes to 00:00 in feed time filter instead of blank field 
[OC-1116]: https://opfab.atlassian.net/browse/OC-1116
=> Oc 1116 Init hours and minutes to 00:00 in feed time filter instead of blank field 

services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/configuration/webflux/CardSubscriptionRoutesConfig.java, services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/controllers/CardOperationsController.java, services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/controllers/CardOperationsGetParameters.java, services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/model/CardSubscriptionDto.java, services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/repositories/CardCustomRepository.java, services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/repositories/CardCustomRepositoryImpl.java, services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/services/CardSubscription.java, services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/services/CardSubscriptionService.java, services/core/cards-consultation/src/test/java/org/lfenergy/operatorfabric/cards/consultation/controllers/CardOperationsControllerShould.java, services/core/cards-consultation/src/test/java/org/lfenergy/operatorfabric/cards/consultation/repositories/CardRepositoryShould.java, services/core/cards-consultation/src/test/java/org/lfenergy/operatorfabric/cards/consultation/services/CardSubscriptionServiceShould.java, ui/main/src/app/services/card.service.ts
Tasks: 
[OC-1122]  Robustify permanent connection for card notification II
[OC-1122]: https://opfab.atlassian.net/browse/OC-1122
=> [OC-1122] Robustify permanent connection for card notification II

ui/main/src/app/modules/feed/components/card-list/filters/acknowledgement-filter/acknowledgement-filter.component.html, ui/main/src/app/modules/feed/components/card-list/filters/acknowledgement-filter/acknowledgement-filter.component.scss, ui/main/src/app/modules/feed/components/card-list/filters/severity-sort/severity-sort.component.html
release note 
Features : 
[OC-1121] Change icons for acknowledge filter in feed
[OC-1121]: https://opfab.atlassian.net/browse/OC-1121
=> [OC-1121] New ack icons in feed filter

src/docs/asciidoc/community/index.adoc, ui/main/src/app/modules/cards/components/detail/detail.component.ts
Do not use ngFor / ngIf  with methods computing "action
enable" or  the list of entities in detail component
As angular will call these methods very regulary
(around ten times per seconds), use instead variables and
compute them only when necessary.
Release note :
Task :  
[OC-1124] Refactor card detail component to avoid unnecessary processing
Bug:
[OC-1125]  Card are sometimes not mark as read 
[OC-1124]: https://opfab.atlassian.net/browse/OC-1124
[OC-1125]: https://opfab.atlassian.net/browse/OC-1125
=> [OC-1124] Refactor to avoid unnecessary processing

client/cards/build.gradle, client/cards/src/main/avro/I8n.avsc, client/cards/src/main/avro/card.avsc, client/cards/src/main/avro/cardCommand.avsc, client/cards/src/main/avro/detail.avsc, client/cards/src/main/avro/recipient.avsc, client/cards/src/main/avro/timespan.avsc, config/dev/cards-publication-dev.yml, services/core/cards-publication/build.gradle, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/configuration/json/GsonConfig.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/kafka/command/BaseCommandHandler.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/kafka/command/CommandHandler.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/kafka/command/CreateCardCommandHandler.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/kafka/command/DeleteCardCommandHandler.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/kafka/command/UpdateCardCommandHandler.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/kafka/consumer/CardCommandConsumerConfiguration.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/kafka/consumer/CardCommandConsumerDeserializer.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/kafka/consumer/CardCommandConsumerListener.java, services/core/cards-publication/src/test/java/org/lfenergy/operatorfabric/cards/publication/configuration/GsonConfigShould.java, services/core/cards-publication/src/test/java/org/lfenergy/operatorfabric/cards/publication/kafka/command/CreateCardCommandHandlerShould.java, services/core/cards-publication/src/test/java/org/lfenergy/operatorfabric/cards/publication/kafka/command/DeleteCardCommandHandlerShould.java, services/core/cards-publication/src/test/java/org/lfenergy/operatorfabric/cards/publication/kafka/command/UpdateCardCommandHandlerTest.java, services/core/cards-publication/src/test/java/org/lfenergy/operatorfabric/cards/publication/kafka/consumer/CardCommandConsumerConfigurationShould.java, services/core/cards-publication/src/test/java/org/lfenergy/operatorfabric/cards/publication/kafka/consumer/CardCommandConsumerListenerShould.java, services/core/cards-publication/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker, versions.properties
[OC-1073, smt429]
Added initial kafka support (consumer, AVRO schema, config)
=> Oc 1073 smt 429

.gitignore, config/docker/docker-compose.sh, config/docker/docker-compose.yml, src/test/utils/karate/businessconfig/resources/bundle_defaultProcess/config.json, src/test/utils/karate/businessconfig/resources/bundle_defaultProcess/i18n/en.json, src/test/utils/karate/businessconfig/resources/bundle_defaultProcess/i18n/fr.json
Release note :
Tasks:
[OC-1129] Modify storage directory for bundle in docker reference configuration (in config/docker) 
[OC-1129]: https://opfab.atlassian.net/browse/OC-1129
=>  Set volume for bundle storage in config/docker

ui/main/src/app/services/card.service.ts, ui/main/src/app/services/entities.service.ts
[[OC-1130](https://opfab.atlassian.net/browse/OC-1130)] : Add name of entity in logging screen
=> [OC-1130] Add name of entity in logging screen

services/core/businessconfig/build.gradle, services/core/businessconfig/src/main/java/org/lfenergy/operatorfabric/businessconfig/configuration/json/BusinessconfigModule.java, services/core/businessconfig/src/main/java/org/lfenergy/operatorfabric/businessconfig/controllers/BusinessconfigController.java, services/core/businessconfig/src/main/java/org/lfenergy/operatorfabric/businessconfig/model/ProcessGroupData.java, services/core/businessconfig/src/main/java/org/lfenergy/operatorfabric/businessconfig/model/ProcessGroupsData.java, services/core/businessconfig/src/main/java/org/lfenergy/operatorfabric/businessconfig/model/ProcessGroupsLocaleData.java, services/core/businessconfig/src/main/java/org/lfenergy/operatorfabric/businessconfig/services/ProcessesService.java, services/core/businessconfig/src/main/modeling/swagger.yaml, services/core/businessconfig/src/test/data/processgroups.json, services/core/businessconfig/src/test/java/org/lfenergy/operatorfabric/businessconfig/controllers/BusinessconfigControllerWithWrongConfigurationShould.java, services/core/businessconfig/src/test/java/org/lfenergy/operatorfabric/businessconfig/controllers/GivenAdminUserThirdControllerShould.java, services/core/businessconfig/src/test/java/org/lfenergy/operatorfabric/businessconfig/controllers/GivenNonAdminUserBusinessconfigControllerShould.java, services/core/businessconfig/src/test/java/org/lfenergy/operatorfabric/businessconfig/services/ProcessesServiceShould.java, src/test/api/karate/businessconfig/getProcessGroups.feature, src/test/api/karate/businessconfig/resources/processgroups1.json, src/test/api/karate/businessconfig/resources/processgroups2.json, src/test/api/karate/businessconfig/uploadProcessGroupsFile.feature, src/test/api/karate/launchAllBusinessconfig.sh, tools/generic/utilities/src/main/java/org/lfenergy/operatorfabric/utilities/PathUtils.java
[OC-1078](https://opfab.atlassian.net/browse/OC-1078) : Implement notion of processGroup (work still in progress)
=> [OC-1078] Implement notion of processGroup

ressources/logo/logo_lfe_operatorfabric.svg
Signed-off-by: Lucian Balea <lucian.balea@rte-france.com>
=> Correct license info for opfab logo

ui/main/src/assets/images/icons/operator-fabric.svg.license
Signed-off-by: Lucian Balea <lucian.balea@rte-france.com>
=> Add license info for opfab logo

ui/main/src/assets/fonts/LICENSE
Signed-off-by: Lucian Balea <lucian.balea@rte-france.com>
=> Correct LICENSE

ui/main/package.json, ui/main/src/app/modules/logging/components/logging-table/logging-table.component.html, ui/main/src/app/modules/logging/components/logging-table/logging-table.component.scss, ui/main/src/app/modules/logging/components/logging-table/logging-table.component.ts, ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.html, ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.scss, ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.spec.ts, ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.ts, ui/main/src/app/modules/monitoring/monitoring.module.ts, ui/main/src/app/services/export.service.spec.ts, ui/main/src/app/services/export.service.ts, ui/main/src/app/services/services.module.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json
Then, remove the text and replace it with the information and comments that should go into the release notes.
* The PR comment contains a brief explanation of the impact of these developments, and a pointer
to the relevant documentation if need be. Otherwise, it should why this development doesn't need
to be on the release notes.
* Look through changed files to make sure everything is relevant to the PR (no mistakenly added …
=> [ OC-1044 ]  Add export function

services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/kafka/command/BaseCommandHandler.java, services/core/cards-publication/src/test/java/org/lfenergy/operatorfabric/cards/publication/kafka/command/CreateCardCommandHandlerShould.java, services/core/cards-publication/src/test/java/org/lfenergy/operatorfabric/cards/publication/kafka/command/DeleteCardCommandHandlerShould.java, services/core/cards-publication/src/test/java/org/lfenergy/operatorfabric/cards/publication/kafka/command/UpdateCardCommandHandlerTest.java, services/core/cards-publication/src/test/java/org/lfenergy/operatorfabric/cards/publication/kafka/consumer/CardCommandConsumerListenerShould.java
Bugfix so card.data is properly deserialized into CardPublicationData.data
=> Fix for deserializing CardPublicationData.data

src/docs/asciidoc/reference_doc/template_description.adoc, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/config.json, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/i18n/en.json, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/i18n/fr.json, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/template/en/conference.handlebars, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/template/en/message.handlebars, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/template/en/usercard_conference.handlebars, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/template/en/usercard_message.handlebars, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/template/fr/conference.handlebars, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/template/fr/message.handlebars, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/template/fr/usercard_conference.handlebars, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/template/fr/usercard_message.handlebars, src/test/utils/karate/cards/setPerimeterForUserCardExamples.feature, ui/main/src/app/modules/cards/services/handlebars.service.spec.ts, ui/main/src/app/modules/cards/services/handlebars.service.ts, ui/main/src/app/modules/usercard/newcard-template.services.ts, ui/main/src/app/modules/usercard/usercard.component.html, ui/main/src/app/modules/usercard/usercard.component.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json
Feature 
[OC 1143] Improve new card feature
=> [OC 1143] Improve new card feature 

ui/main/src/app/modules/cards/components/detail/detail.component.ts
Avoid : ERROR TypeError: "cardTemplate is null"  in console
=> [OC-1149] remove error in card detail

src/docs/asciidoc/community/workflow.adoc
Release note
tasks
[OC-1156] How to check regression of a branch
[OC-1156]: https://opfab.atlassian.net/browse/OC-1156
=> [OC-1156] explains howto check branch regression

config/docker/ngnix.conf
=> [OC-1153] : fix bug conf docker

src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/template/en/usercard_conference.handlebars, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/template/fr/usercard_conference.handlebars, ui/main/src/app/model/card.model.ts, ui/main/src/app/modules/usercard/usercard.component.ts
Feature : 
[OC-1158] Add the option to view usercard in agenda
[OC-1158]: https://opfab.atlassian.net/browse/OC-1158
=> [OC-1158] Add the option to view usercard in agenda

services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/controllers/CardController.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/services/CardProcessingService.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/services/CardRepositoryService.java, services/core/cards-publication/src/main/modeling/swagger.yaml, services/core/cards-publication/src/test/java/org/lfenergy/operatorfabric/cards/publication/controllers/CardControllerProcessAcknowledgementShould.java, services/core/cards-publication/src/test/java/org/lfenergy/operatorfabric/cards/publication/controllers/CardControllerShould.java, services/core/cards-publication/src/test/java/org/lfenergy/operatorfabric/cards/publication/controllers/CardControllerUserCardShould.java, services/core/cards-publication/src/test/java/org/lfenergy/operatorfabric/cards/publication/repositories/CardRepositoryForTest.java, services/core/cards-publication/src/test/java/org/lfenergy/operatorfabric/cards/publication/services/CardProcessServiceShould.java, src/test/api/karate/cards/deleteUserCard.feature, src/test/api/karate/launchAllCards.sh, ui/main/src/app/model/card.model.ts, ui/main/src/app/modules/cards/components/detail/detail.component.html, ui/main/src/app/modules/cards/components/detail/detail.component.scss, ui/main/src/app/modules/cards/components/detail/detail.component.ts, ui/main/src/app/services/card.service.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json
Tasks section : 
[OC-1092](https://opfab.atlassian.net/browse/OC-1092) : Delete a card from the UI
=> [OC-1092] Delete a card from the UI

config/dev/common-dev.yml, config/docker/common-docker.yml, services/core/cards-publication/src/test/resources/application.yml, src/docs/asciidoc/deployment/configuration/configuration.adoc, tools/spring/aop-process/src/main/java/org/lfenergy/operatorfabric/aop/process/UserAcknowledgmentActionTraceAspect.java
[OC-1169](https://opfab.atlassian.net/browse/OC-1169) : Set business log as optional
=> [OC-1169] Set business log as optionnal

ui/main/src/app/components/share/multi-filter-2/multi-filter-2.component.ts, ui/main/src/app/modules/usercard/usercard.component.html, ui/main/src/app/modules/usercard/usercard.component.ts
Features : 
[OC 1178] Minor corrections in create card feature
=> OC 1178 Minor corrections in create card feature

ui/main/src/assets/i18n/fr.json
release notes:
==> [OC-1180] : label correction
[OC-1180]: https://opfab.atlassian.net/browse/OC-1180
=> [OC-1180] : label correction

ui/main/src/app/modules/admin/services/data.service.ts
release notes:
==> [OC-1167] : fix bug deletion for administration
[OC-1167]: https://opfab.atlassian.net/browse/OC-1167
=> [OC-1167] : fix bug deletion for administration

src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/config.json, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/i18n/en.json, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/i18n/fr.json, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/template/en/question.handlebars, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/template/en/usercard_question.handlebars, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/template/fr/question.handlebars, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/template/fr/usercard_question.handlebars, src/test/utils/karate/cards/setPerimeterForUserCardExamples.feature, ui/main/src/app/modules/usercard/usercard.component.html, ui/main/src/app/modules/usercard/usercard.component.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json
Features : 
[OC-1194] Add the possibility to send usercard with response card
[OC-1194]: https://opfab.atlassian.net/browse/OC-1194
=> OC-1194 Add the possibility to send usercard with response card

ui/main/src/app/modules/feed/components/time-line/custom-timeline-chart/custom-timeline-chart.component.ts
BUGS:
[OC-1205] BUG in timeline when switching to winter time
[OC-1205]: https://opfab.atlassian.net/browse/OC-1205
=> [OC-1205] BUG in timeline when switching to winter time

services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/configuration/mongo/LightCardReadConverter.java, services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/configuration/webflux/CardRoutesConfig.java, services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/model/ArchivedCardConsultationData.java, services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/model/CardConsultationData.java, services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/model/LightCardConsultationData.java, services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/repositories/ArchivedCardCustomRepositoryImpl.java, services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/repositories/CardCustomRepositoryImpl.java, services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/repositories/UserUtilitiesCommonToCardRepository.java, services/core/cards-consultation/src/test/java/org/lfenergy/operatorfabric/cards/consultation/routes/CardRoutesShould.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/model/ArchivedCardPublicationData.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/model/CardPublicationData.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/model/LightCardPublicationData.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/services/CardProcessingService.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/services/CardRepositoryService.java, services/core/cards-publication/src/main/modeling/swagger.yaml, services/core/cards-publication/src/test/java/org/lfenergy/operatorfabric/cards/publication/services/CardProcessServiceShould.java, src/test/api/karate/cards/cards.feature, src/test/api/karate/cards/userCards.feature, ui/main/src/app/model/card.model.ts, ui/main/src/app/model/light-card.model.ts, ui/main/src/app/modules/cards/components/detail/detail.component.ts, ui/main/src/app/modules/feed/components/time-line/custom-timeline-chart/custom-timeline-chart.component.ts, ui/main/src/app/modules/feed/feed.component.ts
[[OC-1189](https://opfab.atlassian.net/browse/OC-1189)] Attach child card to parent card id and not parent uid
=> [OC-1189] Attach child card to parent card id and not parent uid

services/core/businessconfig/src/main/docker/volume/businessconfig-storage/TEST/1/i18n/en.json, services/core/businessconfig/src/main/docker/volume/businessconfig-storage/TEST/1/i18n/fr.json, src/docs/asciidoc/dev_env/token.adoc, src/docs/asciidoc/dev_env/troubleshooting.adoc, src/docs/asciidoc/reference_doc/process_definition.adoc, src/docs/asciidoc/reference_doc/ui_customization.adoc
[OC-1213] Rewrites documentation, correcting `cURL` examples and some `json` ones.
[OC-1213]: https://opfab.atlassian.net/browse/OC-1213
=> [OC-1213] Rewrites and corrects documentation

src/docs/asciidoc/deployment/configuration/configuration.adoc, src/docs/asciidoc/dev_env/index.adoc, src/docs/asciidoc/dev_env/kafka.adoc
Some intial documentation on the Kafka integration.
Please let me know if you think I should include more info.
=> Oc 1073 esm 165 documentation

ui/main/src/app/modules/cards/components/detail/detail.component.ts, ui/main/src/app/modules/feed/components/time-line/custom-timeline-chart/custom-timeline-chart.component.ts, ui/main/src/app/modules/usercard/components/card-preview/card-preview.component.ts
Release note :
BUGS : 
OC-1215 Solve memory leaks
=> OC-1215 - Solve memory leaks 

ui/main/src/app/services/processes.service.ts
nothing in release note , it is an update of OC-1188
=> [OC-1188] Minor correction

config/docker/cards-publication-docker.yml, config/docker/common-docker.yml
Non regression api test were failing in docker mode
because of wrong configuration
Release note :
Task : 
[OC-1002] Minor corrections for karate testing in docker mode 
[OC-1002]: https://opfab.atlassian.net/browse/OC-1002
=> [OC-1002] Minor corrections for karate testing

bin/run_all.sh
Task : 
[OC-1222] Add an option to hard kill the processes in run_all.sh
[OC-1222]: https://opfab.atlassian.net/browse/OC-1222
=> [OC-1222] Add an option to hard kill the processes in run_all.sh

services/core/users/src/main/java/org/lfenergy/operatorfabric/users/controllers/EntitiesController.java, services/core/users/src/main/java/org/lfenergy/operatorfabric/users/controllers/EntityCycleDetector.java, services/core/users/src/main/java/org/lfenergy/operatorfabric/users/model/EntityData.java, services/core/users/src/main/java/org/lfenergy/operatorfabric/users/utils/EntityCycleDetector.java, services/core/users/src/main/modeling/swagger.yaml, services/core/users/src/test/java/org/lfenergy/operatorfabric/users/controllers/EntityCycleDetectorShould.java, src/docs/asciidoc/deployment/users_groups_admin.adoc, src/test/api/karate/launchAllUsers.sh, src/test/api/karate/users/entities/checkEntityGroupManagement.feature
Feature:
[OC-1144] adds parent reference declaration to entity+
A cycle detection is performed when post or patch of Entities
[OC-1144]: https://opfab.atlassian.net/browse/OC-1144
=> [OC-1144] Adds parents to entity and forbides cycle in transitive ref"

src/test/api/karate/buildAndLaunchAll.sh, src/test/api/karate/launchAllBusinessconfig.sh, src/test/api/karate/launchAllCards.sh, src/test/api/karate/launchAllUsers.sh, src/test/api/karate/launchAllUsers_JWTMode.sh
Release note 
Tasks:
[OC-1225] Add a script to automate api none-regression test
[OC-1225]: https://opfab.atlassian.net/browse/OC-1225
=> [OC-1225] Add a script to automate api none-regression test

ui/main/src/app/modules/archives/archives-routing.module.ts
Bugs: 
[OC-1224] Closing archive card was not possible anymore
[OC-1224]: https://opfab.atlassian.net/browse/OC-1224
=> [OC-1224] BUG - Closing archive card was not possible anymore

services/core/businessconfig/src/main/java/org/lfenergy/operatorfabric/businessconfig/model/ProcessStatesData.java, services/core/businessconfig/src/main/modeling/swagger.yaml, src/docs/asciidoc/reference_doc/card_notification.adoc, src/docs/asciidoc/reference_doc/index.adoc, src/test/api/karate/businessconfig/getABusinessconfig.feature, src/test/api/karate/businessconfig/resources/bundle_api_test/config.json, src/test/api/karate/businessconfig/resources/bundle_api_test_v2/config.json, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/config.json, ui/main/src/app/app.component.ts, ui/main/src/app/model/card.model.ts, ui/main/src/app/model/processes.model.ts, ui/main/src/app/modules/cards/components/detail/detail.component.ts, ui/main/src/app/services/card.service.ts, ui/main/src/app/services/reminder/reminder.service.ts, ui/main/src/app/services/reminder/reminderList.spec.ts, ui/main/src/app/services/reminder/reminderList.ts, ui/main/src/app/services/services.module.ts, ui/main/src/app/services/sound-notification.service.ts, ui/main/src/app/store/effects/card-operation.effects.ts
release note :
FEATURE : 
[OC-1093] Add a reminder feature (see documentation : https://opfab.github.io/documentation/current/reference_doc/#_card_reminder_experimental )
[OC-1093]: https://opfab.atlassian.net/browse/OC-1093
=> [OC-1093] Add a reminder feature

src/docs/asciidoc/dev_env/troubleshooting.adoc, src/docs/asciidoc/dev_env/ui.adoc
BUG
[OC-1232] documents workaround to resolve ng build failure
[OC-1232]: https://opfab.atlassian.net/browse/OC-1232
=> [OC-1232] documents workaround to resolve ng build failure

config/dev/users-dev.yml, config/docker/users-docker.yml, config/keycloak/export/dev-users-0.json, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/config.json, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/i18n/en.json, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/i18n/fr.json, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/template/en/incidentInProgress.handlebars, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/template/en/usercard_incidentInProgress.handlebars, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/template/fr/incidentInProgress.handlebars, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/template/fr/usercard_incidentInProgress.handlebars, src/test/utils/karate/cards/setPerimeterForUserCardExamples.feature
Release note:
Tasks: 
[OC-1236] Add a new example of usercard (incident management)
[OC-1236]: https://opfab.atlassian.net/browse/OC-1236
=> [OC-1236] Add a new example of usercard (incident management)

src/docs/asciidoc/reference_doc/response_cards.adoc, src/test/utils/karate/businessconfig/resources/bundle_defaultProcess/template/en/question.handlebars, src/test/utils/karate/businessconfig/resources/bundle_defaultProcess/template/fr/question.handlebars, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/template/en/incidentInProgress.handlebars, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/template/fr/incidentInProgress.handlebars, ui/main/src/app/services/entities.service.ts, ui/main/src/assets/js/templateGateway.js
Tasks :
[OC-1210] Add a method in templateGateway.js to get entity names
[OC-1210]: https://opfab.atlassian.net/browse/OC-1210
=> [OC-1210] Add a method in templateGateway.js to get entity names

services/core/businessconfig/src/main/java/org/lfenergy/operatorfabric/businessconfig/model/ProcessStatesData.java, services/core/businessconfig/src/main/modeling/swagger.yaml, services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/configuration/mongo/LightCardReadConverter.java, services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/model/ArchivedCardConsultationData.java, services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/model/CardConsultationData.java, services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/model/LightCardConsultationData.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/model/ArchivedCardPublicationData.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/model/CardPublicationData.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/model/LightCardPublicationData.java, services/core/cards-publication/src/main/modeling/swagger.yaml, services/core/cards-publication/src/test/java/org/lfenergy/operatorfabric/cards/publication/services/CardProcessServiceShould.java, src/docs/asciidoc/reference_doc/card_notification.adoc, src/test/api/karate/businessconfig/getABusinessconfig.feature, src/test/api/karate/businessconfig/resources/bundle_api_test/config.json, src/test/api/karate/businessconfig/resources/bundle_api_test_v2/config.json, src/test/api/karate/cards/cardsWithTimespans.feature, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/config.json, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/template/en/usercard_conference.handlebars, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/template/en/usercard_task.handlebars, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/template/fr/usercard_conference.handlebars, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/template/fr/usercard_task.handlebars, ui/main/src/app/model/card.model.ts, ui/main/src/app/model/light-card.model.ts, ui/main/src/app/model/processes.model.ts, ui/main/src/app/modules/usercard/usercard.component.ts, ui/main/src/app/services/reminder/reminder.service.ts, ui/main/src/app/services/reminder/reminderList.spec.ts, ui/main/src/app/services/reminder/reminderList.ts, ui/main/src/app/services/reminder/reminderUtils.spec.ts, ui/main/src/app/services/reminder/reminderUtils.ts
Group with OC-1093 and OC-1230 in features : 
[OC-1093][OC-1230][OC-1239] Add a reminder feature (see documentation : https://opfab.github.io/documentation/current/reference_doc/#_card_reminder_experimental ) , feature is experimental 
[OC-1093]: https://opfab.atlassian.net/browse/OC-1093
[OC-1230]: https://opfab.atlassian.net/browse/OC-1230
[OC-1239]: https://opfab.atlassian.net/browse/OC-1239
=> OC-1239 Finalize recurrent reminder

src/test/utils/karate/examples/gridCooperation/bundle_gridCooperation/config.json, src/test/utils/karate/examples/gridCooperation/bundle_gridCooperation/i18n/en.json, src/test/utils/karate/examples/gridCooperation/bundle_gridCooperation/i18n/fr.json, src/test/utils/karate/examples/gridCooperation/bundle_gridCooperation/template/en/action-FrEs-IGCC-export-0.handlebars, src/test/utils/karate/examples/gridCooperation/bundle_gridCooperation/template/en/action-FrEs-IGCC-export-300.handlebars, src/test/utils/karate/examples/gridCooperation/bundle_gridCooperation/template/en/action-FrEs-IGCC-import-0.handlebars, src/test/utils/karate/examples/gridCooperation/bundle_gridCooperation/template/en/action-FrEs-IGCC-import-300.handlebars, src/test/utils/karate/examples/gridCooperation/bundle_gridCooperation/template/en/compliant-FrEs-IGCC.handlebars, src/test/utils/karate/examples/gridCooperation/bundle_gridCooperation/template/en/template.handlebars, src/test/utils/karate/examples/gridCooperation/bundle_gridCooperation/template/en/timeout-FrEs-IGCC.handlebars, src/test/utils/karate/examples/gridCooperation/bundle_gridCooperation/template/fr/action-FrEs-IGCC-export-0.handlebars, src/test/utils/karate/examples/gridCooperation/bundle_gridCooperation/template/fr/action-FrEs-IGCC-export-300.handlebars, src/test/utils/karate/examples/gridCooperation/bundle_gridCooperation/template/fr/action-FrEs-IGCC-import-0.handlebars, src/test/utils/karate/examples/gridCooperation/bundle_gridCooperation/template/fr/action-FrEs-IGCC-import-300.handlebars, src/test/utils/karate/examples/gridCooperation/bundle_gridCooperation/template/fr/compliant-FrEs-IGCC.handlebars, src/test/utils/karate/examples/gridCooperation/bundle_gridCooperation/template/fr/template.handlebars, src/test/utils/karate/examples/gridCooperation/bundle_gridCooperation/template/fr/timeout-FrEs-IGCC.handlebars, src/test/utils/karate/examples/gridCooperation/packageBundle.sh, src/test/utils/karate/examples/gridCooperation/postBundleGridCooperation.feature, src/test/utils/karate/examples/gridCooperation/postCardForGridCooperation1.feature, src/test/utils/karate/examples/gridCooperation/postCardForGridCooperation2.feature, src/test/utils/karate/examples/gridCooperation/postCardForGridCooperation3.feature
release note : 
Tasks: 
[OC-1244] Add a new buisness example (IGCC)
[OC-1244]: https://opfab.atlassian.net/browse/OC-1244
=> [OC-1244] Add a new buisness example (IGCC)

ui/main/src/app/modules/calendar/calendar.component.html, ui/main/src/app/modules/cards/components/card-details/card-details.component.ts, ui/main/src/app/modules/cards/components/detail/detail.component.html, ui/main/src/app/modules/cards/components/detail/detail.component.ts
No buttons for archives & monitoring
No ack/unack buttons for agenda
All buttons for feed
Release note
Tasks:
[OC-1245] Set button visibility for card detail
[OC-1245]: https://opfab.atlassian.net/browse/OC-1245
=> [OC-1245] Set button visibility for detail card

services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/configuration/mongo/RecurrenceReadConverter.java, services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/model/RecurrenceConsultationData.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/configuration/mongo/RecurrenceReadConverter.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/configuration/mongo/RecurrenceWriterConverter.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/model/RecurrencePublicationData.java, services/core/cards-publication/src/main/modeling/swagger.yaml, services/core/cards-publication/src/test/java/org/lfenergy/operatorfabric/cards/publication/services/CardProcessServiceShould.java, src/docs/asciidoc/reference_doc/card_notification.adoc, src/docs/asciidoc/reference_doc/card_structure.adoc, src/test/api/karate/cards/cardsWithTimespans.feature, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/template/en/usercard_task.handlebars, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/template/fr/usercard_task.handlebars, ui/main/src/app/model/card.model.ts, ui/main/src/app/services/reminder/reminderUtils.spec.ts, ui/main/src/app/services/reminder/reminderUtils.ts
Replace line : 
[OC-1093] [OC-1230] [OC-1239] Add a reminder feature (see documentation : https://opfab.github.io/documentation/current/reference_doc/#_card_reminder_experimental ), feature is experimental
With 
[OC-1093] [OC-1230] [OC-1239][OC-1240]  Add a reminder feature (see documentation : https://opfab.github.io/documentation/current/reference_doc/#_card_reminder )
[OC-1093]: https://opfab.atlassian.net/browse/OC-1093
[OC-1230]: https://opfab.atlassian.net/browse/OC-1230
[OC-1239]: https://opfab.atlassian.net/browse/OC-1239
[OC-1093]: https://opfab.atlassian.net/browse/OC-1093
[OC-1230]: https://opfab.atlassian.net/browse/OC-1230
[OC-1239]: https://opfab.atlassian.net/browse/OC-1239
[OC-1240]: https://opfab.atlassian.net/browse/OC-1240
=> [OC-1240] Process multi-timespans in reminder feature

src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/template/en/incidentInProgress.handlebars
=> [OC-1249] Correct translation in template for incident in progress example 

src/docs/asciidoc/getting_started/index.adoc, src/docs/asciidoc/resources/migration_guide_to_1.8.adoc
Tasks:
Update getting started documentation for release 1.8.0
=> [OC-1204] Update getting started documentation for release 1.8.0

src/docs/asciidoc/reference_doc/process_definition.adoc, src/docs/asciidoc/resources/index.adoc, src/docs/asciidoc/resources/migration_guide_to_1.8.adoc
=> [OC-1251] Update migration doc for release 1.8.0

config/keycloak/export/dev-users-0.json, services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/services/CardSubscription.java, services/core/users/src/main/java/org/lfenergy/operatorfabric/users/controllers/CurrentUserWithPerimetersController.java, services/core/users/src/test/java/org/lfenergy/operatorfabric/users/controllers/CurrentUserWithPerimetersControllerShould.java, src/test/api/karate/launchAllUsers.sh, src/test/api/karate/users/entities/checkEntityGroupManagement.feature, src/test/api/karate/users/entities/transitive-entities-in-currentUser.feature
To use the api tests add the following users to keycloak:
- user-with-root-entity-only
- user-with-single-entity
- user-with-child-and-grand-child-entity
- user-without-child-entity
Features:
[OC-1229] send card to user using group entities
[OC-1229]: https://opfab.atlassian.net/browse/OC-1229
=> [OC-1229] send card to user using group entities

src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc
Release note :
Task : 
[OC-1206] Add config parameters for date and time rendering in documentation
[OC-1206]: https://opfab.atlassian.net/browse/OC-1206
=> [OC-1206] Add config parameters for date and time rendering in documentation

ui/main/src/app/modules/monitoring/monitoring.component.ts, ui/main/src/app/services/card.service.ts, ui/main/src/assets/i18n/en.json
In the ticket it is written : "Do not filter card via feed filter"
But as we have discussed, I suppose it will be done in another ticket ?
[OC-1223](https://opfab.atlassian.net/browse/OC-1223) : Small evolutions of monitoring and logging screen
=> [OC-1223] Small evolutions of monitoring and logging screen

ui/main/src/app/app-routing.module.ts, ui/main/src/app/modules/monitoring/components/monitoring-filters/monitoring-filters.component.ts
This PR concerns [OC-1252](https://opfab.atlassian.net/browse/OC-1252).
It seems that monitoring screen uses the feed filtering mechanism for its own filtering. So we have to think about another solution. It will be done in another jira ticket.
=> [OC-1152]  Correct bug in menu due to new filter notification screen

ui/main/src/app/modules/monitoring/components/monitoring-filters/monitoring-filters.component.ts, ui/main/src/app/services/filter.service.ts, ui/main/src/app/store/actions/feed.actions.ts, ui/main/src/app/store/effects/feed-filters.effects.ts
[OC-1273](https://opfab.atlassian.net/browse/OC-1273) : Do not filter ack card for monitoring screen
=> [OC-1273] Do not filter ack card for monitoring screen

src/docs/asciidoc/dev_env/kafka.adoc
[OC-1286]
Add more explanation on Kafka bootstrap server and provide an example how to integrate a Kafka broker (bitnami)
[OC-1286]: https://opfab.atlassian.net/browse/OC-1286
=> [OC-1286] Updated Kafka documentation

services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/repositories/ArchivedCardCustomRepositoryImpl.java, services/core/cards-publication/src/main/modeling/swagger.yaml, src/test/api/karate/buildAndLaunchAll.sh, src/test/api/karate/cards/fetchArchivedCardsWithParams.feature, src/test/api/karate/launchAllCards.sh, ui/main/src/app/services/card.service.ts
[OC-1289](https://opfab.atlassian.net/browse/OC-1289) : Do not show child cards on the UI archive panel
=> [OC-1289] - Do not show child cards on the UI archive panel

build.gradle, services/core/businessconfig/build.gradle, versions.properties
[[OC-1285](https://opfab.atlassian.net/browse/OC-1285)] Update dependency for security
=> [OC-1285] Update dependency for security

services/core/businessconfig/src/main/java/org/lfenergy/operatorfabric/businessconfig/model/ProcessData.java, src/docs/asciidoc/getting_started/index.adoc, src/test/api/karate/businessconfig/getABusinessconfig.feature, src/test/utils/karate/businessconfig/postBundleUserCardExamples.feature
[OC-1276](https://opfab.atlassian.net/browse/OC-1276) : Double state definition in process endpoint
=> [OC-1276] Double state definition in process endpoint

services/core/users/src/main/java/org/lfenergy/operatorfabric/users/controllers/UsersController.java, services/core/users/src/main/modeling/swagger.yaml, src/docs/asciidoc/reference_doc/users_management.adoc, src/test/api/karate/users/createUsers.feature, src/test/api/karate/users/deleteUser.feature, src/test/api/karate/users/entities/addUsersToEntity.feature, src/test/api/karate/users/entities/deleteUserFromEntity.feature, src/test/api/karate/users/entities/updateListOfEntityUsers.feature, src/test/api/karate/users/groups/addUsersToGroup.feature, src/test/api/karate/users/groups/deleteUserFromGroup.feature, src/test/api/karate/users/groups/updateListOfGroupUsers.feature, src/test/api/karate/users/perimeters/getPerimetersForAUser.feature, src/test/api/karate/users/updateExistingUser.feature, ui/main/src/app/modules/admin/components/editmodal/users/edit-user-modal.component.html, ui/main/src/assets/i18n/en.json
In Tasks section :   
[OC-1183](https://opfab.atlassian.net/browse/OC-1183) : Set login to lowercase
=> [OC-1183] Set login to lowercase

src/test/utils/karate/businessconfig/resources/bundle_defaultProcess/css/style.css, src/test/utils/karate/businessconfig/resources/bundle_defaultProcess/template/en/chart-line.handlebars, src/test/utils/karate/businessconfig/resources/bundle_defaultProcess/template/en/chart.handlebars, src/test/utils/karate/businessconfig/resources/bundle_defaultProcess/template/en/process.handlebars, src/test/utils/karate/businessconfig/resources/bundle_defaultProcess/template/en/question.handlebars, src/test/utils/karate/businessconfig/resources/bundle_defaultProcess/template/en/template.handlebars, src/test/utils/karate/businessconfig/resources/bundle_defaultProcess/template/fr/chart-line.handlebars, src/test/utils/karate/businessconfig/resources/bundle_defaultProcess/template/fr/chart.handlebars, src/test/utils/karate/businessconfig/resources/bundle_defaultProcess/template/fr/process.handlebars, src/test/utils/karate/businessconfig/resources/bundle_defaultProcess/template/fr/question.handlebars, src/test/utils/karate/businessconfig/resources/bundle_defaultProcess/template/fr/template.handlebars, ui/main/src/app/components/share/card-detail/card-detail.component.html, ui/main/src/app/components/share/card-detail/card-detail.component.scss, ui/main/src/app/components/share/card-detail/card-detail.component.ts, ui/main/src/app/modules/archives/archives.component.html, ui/main/src/app/modules/cards/components/detail/detail.component.html, ui/main/src/app/modules/cards/components/detail/detail.component.scss, ui/main/src/app/modules/feed/components/card-list/filters/feed-filter/feed-filter.component.html, ui/main/src/app/modules/feed/components/card-list/filters/filters.component.html, ui/main/src/app/modules/feed/feed.component.html, ui/main/src/app/modules/logging/components/logging-filters/logging-filters.component.html, ui/main/src/app/modules/monitoring/components/monitoring-filters/monitoring-filters.component.html, ui/main/src/app/modules/settings/components/settings/settings.component.html, ui/main/src/app/modules/usercard/usercard.component.html, ui/main/src/app/services/global-style.service.ts, ui/main/src/assets/styles/styles.scss
Nothing in release note , there will be an unique item for new UI
=> [OC-1300] Change detail card background color for night mode

ui/main/src/app/modules/usercard/usercard.component.ts
OC-1296 : Show recipients list in alphabetic order in the create card form
=> [OC-1296] Show recipients list in alphabetic order in the create card form

ui/main/src/app/modules/feed/components/time-line/custom-timeline-chart/custom-timeline-chart.component.ts
In features : 
[OC-1299] Remove the bubble related to the end of the business period
[OC-1299]: https://opfab.atlassian.net/browse/OC-1299
=> [OC-1299] Remove the bubble related to the end of the business period

src/test/utils/karate/businessconfig/resources/bundle_defaultProcess/template/en/question.handlebars, src/test/utils/karate/businessconfig/resources/bundle_defaultProcess/template/fr/question.handlebars, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/template/en/incidentInProgress.handlebars, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/template/en/usercard_incidentInProgress.handlebars, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/template/en/usercard_task.handlebars, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/template/fr/incidentInProgress.handlebars, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/template/fr/usercard_incidentInProgress.handlebars, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/template/fr/usercard_task.handlebars, ui/main/src/app/modules/feed/components/card-list/filters/feed-filter/feed-filter.component.html, ui/main/src/app/modules/feedconfiguration/feedconfiguration.component.html, ui/main/src/app/modules/settings/components/settings/checkbox-setting/checkbox-setting.component.html, ui/main/src/app/modules/settings/components/settings/checkbox-setting/checkbox-setting.component.scss, ui/main/src/assets/styles/styles.scss
=> [OC-1311] New checkbox style

ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.html, ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.scss, ui/main/src/assets/styles/styles.scss
nothing in release note because "New UI" ticket
=> [OC-1303] Remove eye icon in monitoring screen

ui/main/src/app/modules/feed/components/time-line/init-chart/init-chart.component.html, ui/main/src/app/modules/feed/components/time-line/init-chart/init-chart.component.scss, ui/main/src/app/modules/feed/components/time-line/init-chart/init-chart.component.spec.ts, ui/main/src/app/modules/feed/components/time-line/init-chart/init-chart.component.ts
Nothing in release note because "New UI" ticket.
=> [OC-1302] Remove home button in timeline

ui/main/src/app/modules/archives/archives.component.scss, ui/main/src/app/modules/logging/components/logging-table/logging-table.component.scss
[OC-1315](https://opfab.atlassian.net/browse/OC-1315) : Bug in archives and logging screen result in chrome
=> [OC-1315] Bug in archives and logging screen result in chrome

ui/main/src/app/modules/login/login.component.html, ui/main/src/index.html
=> [OC-1334] Correct bug in custom login page style

README.adoc, src/docs/asciidoc/CICD/release_process.adoc, src/docs/asciidoc/resources/mock_pipeline.adoc
Update release process documentation and readme badges to point to travis-ci.com
=> [OC-1110] Update doc to point to travis-ci.com

ui/main/src/assets/styles/styles.scss
Re-introduce specific style code supress by error in a previous commit
=> [OC-1355] Bug in creation/edit user with multiselect component

ui/main/src/app/modules/navbar/navbar.component.ts, ui/main/src/app/modules/share/card-detail/card-detail.component.ts, ui/main/src/app/modules/usercard/usercard.component.html
=> [OC-1353] Do not permit to have preview of card at the same time as view card in the feed

src/docs/asciidoc/reference_doc/response_cards.adoc, src/docs/asciidoc/resources/migration_guide_to_1.9.adoc, src/test/api/karate/businessconfig/resources/bundle_test_action/template/en/long-card.handlebars, src/test/api/karate/businessconfig/resources/bundle_test_action/template/en/template1.handlebars, src/test/api/karate/businessconfig/resources/bundle_test_action/template/fr/long-card.handlebars, src/test/utils/karate/businessconfig/resources/bundle_defaultProcess/template/en/question.handlebars, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/template/en/question.handlebars, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/template/fr/incidentInProgress.handlebars, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/template/fr/question.handlebars, ui/main/src/app/modules/cards/components/detail/detail.component.ts
Task : 
[OC-1309] Template communication improvement : for card with responses, it is not necessary anymore to call templateGateway.applyChildCards() in template on loading, OperatorFabric will do it. 
[OC-1309]: https://opfab.atlassian.net/browse/OC-1309
=> [OC-1309] Template communication improvement

ui/main/src/app/modules/logging/components/logging-filters/logging-filters.component.html, ui/main/src/app/modules/monitoring/components/monitoring-filters/monitoring-filters.component.html
=> [OC-1348] Bug - Error in console when clicking logging or monitoring in the navbar menu

ui/main/src/app/services/processes.service.ts
Task : 
[OC-1363] Start UI even if no processes defined (add a warning in the log)
[OC-1363]: https://opfab.atlassian.net/browse/OC-1363
=> [OC-1363] Start UI even if no processes defined

src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc, src/docs/asciidoc/reference_doc/card_notification.adoc
[[OC-1360](https://opfab.atlassian.net/browse/OC-1360)] : Add documentation for card notification filter feature
=> [OC-1360] Add documentation for card notification filter feature

ui/main/src/app/modules/cards/components/detail/detail.component.ts
Solution is to keep card as unread in the UI until we exit the detail of the card.
=> [OC-1376] When clicking on an unread card, it should not move down in the feed

ui/main/src/app/modules/usercard/usercard.component.html, ui/main/src/app/modules/usercard/usercard.component.ts
Release notes :  
[OC-1381](https://opfab.atlassian.net/browse/OC-1381) : Add Cancel button for create card
=> [OC-1381] Add Cancel button for create card

ui/main/src/app/modules/feed/components/card-list/filters/tags-filter/tags-filter.component.html
Note: addEntity and addGroup will disappear with OC-1191
For release notes:
- [OC-1274] Correcting UI HTML attributes
[OC-1274]: https://opfab.atlassian.net/browse/OC-1274
=> [OC-1274] Correcting UI HTML attributes

ui/main/src/app/modules/archives/archives.component.ts
=> [OC-1417] BUG - Archives- Exporting results feature doesn't take into account filters

ui/main/src/app/modules/cards/components/detail/detail.component.ts
=> [OC-1419] BUG Card detail show last seen card for few instants before showing the selected card

README.adoc
=> [OC-1387] New opfab description in documentation

services/core/businessconfig/src/main/docker/volume/businessconfig-storage/TEST/1/config.json, services/core/businessconfig/src/main/docker/volume/businessconfig-storage/TEST/config.json, services/core/businessconfig/src/main/docker/volume/businessconfig-storage/first/config.json, services/core/businessconfig/src/main/docker/volume/businessconfig-storage/first/v1/config.json, services/core/businessconfig/src/main/java/org/lfenergy/operatorfabric/businessconfig/model/ProcessStatesData.java, services/core/businessconfig/src/main/modeling/swagger.yaml, services/core/businessconfig/src/test/data/bundles/second/2.0/config.json, services/core/businessconfig/src/test/data/bundles/second/2.1/config.json, services/core/businessconfig/src/test/docker/volume/businessconfig-storage/first/config.json, src/docs/asciidoc/getting_started/index.adoc, src/docs/asciidoc/reference_doc/process_definition.adoc, src/docs/asciidoc/reference_doc/response_cards.adoc, src/docs/asciidoc/reference_doc/user_cards.adoc, src/test/api/karate/businessconfig/resources/bundle_api_test/config.json, src/test/api/karate/businessconfig/resources/bundle_api_test_v2/config.json, src/test/api/karate/businessconfig/resources/bundle_test_action/config.json, src/test/utils/karate/businessconfig/resources/bundle_defaultProcess/config.json, src/test/utils/karate/businessconfig/resources/bundle_defaultProcess_V0.1/config.json, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/config.json, src/test/utils/karate/examples/gridCooperation/bundle_gridCooperation/config.json, src/test/utils/karate/operatorfabric-getting-started/resources/bundles/bundle_message/config.json, src/test/utils/karate/operatorfabric-getting-started/resources/bundles/bundle_message_v2/config.json, ui/main/src/app/model/processes.model.ts, ui/main/src/app/modules/cards/components/detail/detail.component.html, ui/main/src/tests/helpers.ts
[OC-1407](https://opfab.atlassian.net/browse/OC-1407) : Remove detailTitle
=> [OC-1407] Remove detailTitle

src/docs/asciidoc/CICD/release_process.adoc, src/docs/asciidoc/resources/index.adoc
After going through the process for 2.0.0.RELEASE I found that a few things were no longer relevant.
=> [OC-1427] Minor updates to release process doc

services/core/businessconfig/build.gradle, services/core/businessconfig/src/main/java/org/lfenergy/operatorfabric/businessconfig/services/ProcessesService.java, services/core/businessconfig/src/test/data/processgroups_with_duplicate_in_different_groups.json, services/core/businessconfig/src/test/data/processgroups_with_duplicate_in_same_group.json, services/core/businessconfig/src/test/java/org/lfenergy/operatorfabric/businessconfig/controllers/GivenAdminUserThirdControllerShould.java, services/core/businessconfig/src/test/java/org/lfenergy/operatorfabric/businessconfig/services/ProcessesServiceShould.java, src/docs/asciidoc/reference_doc/process_definition.adoc, src/test/api/karate/businessconfig/resources/processgroups2_with_duplicate_in_different_groups.json, src/test/api/karate/businessconfig/resources/processgroups2_with_duplicate_in_same_group.json, src/test/api/karate/businessconfig/uploadProcessGroupsFile.feature
Release notes ?
[OC-1409](https://opfab.atlassian.net/browse/OC-1409) : When pushing the process group file check for duplicate process
=> [OC-1409] When pushing the process group file check for duplicate process

src/docs/asciidoc/community/workflow.adoc
Release note 
In tasks:
[OC-1429] Update documentation for reviewer
[OC-1429]: https://opfab.atlassian.net/browse/OC-1429
=> [OC-1429] Update documentation for reviewer

src/test/api/karate/buildAndLaunchAll.sh
=> [OC-1430] Adapt api testing script

ui/main/src/app/modules/feedconfiguration/feedconfiguration.component.html, ui/main/src/app/modules/feedconfiguration/feedconfiguration.component.ts, ui/main/src/app/services/processes.service.ts
[[OC-1399](https://opfab.atlassian.net/browse/OC-1399)] Notification Screen - Display the states in alphabetical order
=> [OC-1399] Notification Screen - Display the states in alphabetical order

config/dev/web-ui.json, config/docker/web-ui.json, src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc, ui/main/src/app/modules/navbar/navbar.component.html, ui/main/src/app/modules/navbar/navbar.component.ts
Features : 
OC-1438 Add the possibility to show environment name in the top right corner
=> [OC-1438] Add the possibility to show environment name in the top right corner

src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/template/en/usercard_message.handlebars, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/template/en/usercard_question.handlebars, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/template/fr/usercard_message.handlebars, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/template/fr/usercard_question.handlebars, ui/main/src/app/modules/usercard/usercard.component.ts
When the user makes an error in the usercard input form
the text of the error shall be display as define in the
input template.
OC-1436 Error message does not appear correctly in usercard
=> [OC-1436] BUG - Usercard - Error message

ui/main/src/app/modules/feed/components/card-list/filters/feed-filter/feed-filter.component.ts
[OC-1428] Fix bug on Feed Filter when setting only date and not time
[OC-1428]: https://opfab.atlassian.net/browse/OC-1428
=> [OC-1428] Fix bug on Feed Filter when setting only date and not time

src/docs/asciidoc/reference_doc/response_cards.adoc, src/test/utils/karate/businessconfig/resources/bundle_defaultProcess/template/en/question.handlebars, src/test/utils/karate/businessconfig/resources/bundle_defaultProcess/template/fr/question.handlebars, ui/main/src/app/modules/cards/components/detail/detail.component.ts, ui/main/src/assets/js/templateGateway.js
[OC-1201] Inform the template when lttd has expired
[OC-1201]: https://opfab.atlassian.net/browse/OC-1201
=> [OC-1201] Inform the template when lttd has expired

ui/main/src/assets/i18n/en.json
Bug : 
[OC-1452] Translation error : criticity --> criticality
[OC-1452]: https://opfab.atlassian.net/browse/OC-1452
=> [OC-1452] Translation error : criticity --> criticality

client/businessconfig/src/main/java/org/lfenergy/operatorfabric/businessconfig/model/TypeOfStateEnum.java, client/businessconfig/src/main/modeling/config.json, services/core/businessconfig/src/main/java/org/lfenergy/operatorfabric/businessconfig/model/ProcessStatesData.java, services/core/businessconfig/src/main/modeling/swagger.yaml, src/test/api/karate/businessconfig/getABusinessconfig.feature, src/test/api/karate/businessconfig/resources/bundle_api_test_v2/config.json
[OC-1447](https://opfab.atlassian.net/browse/OC-1447) : Introduce notion of type of state
=> [OC-1447] Introduce notion of type of state

ui/main/src/app/modules/feed/components/time-line/custom-timeline-chart/custom-timeline-chart.component.html, ui/main/src/app/modules/feed/components/time-line/custom-timeline-chart/custom-timeline-chart.component.spec.ts, ui/main/src/app/modules/feed/components/time-line/custom-timeline-chart/custom-timeline-chart.component.ts, ui/main/src/app/modules/feed/components/time-line/init-chart/init-chart.component.spec.ts
[OC-1270] Timeline circles to open popover on mouseover
[OC-1270]: https://opfab.atlassian.net/browse/OC-1270
=> [OC-1270] Timeline circles to open popover on mouseover

ui/main/src/app/modules/cards/components/detail/detail.component.ts
(issuer OC-1419 reopen)
Bug : 
[OC-1472] Card detail show last seen card for few instants before showing the selected card (rework of OC-1419)
[OC-1472]: https://opfab.atlassian.net/browse/OC-1472
=> [OC-1472] Card detail show last seen card for few instants before showing the selected card

services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/model/CardPublicationData.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/services/CardProcessingService.java, services/core/cards-publication/src/test/java/org/lfenergy/operatorfabric/cards/publication/services/CardProcessServiceShould.java, src/test/api/karate/cards/cards.feature
[OC-1347] Fix bug with keepChilCards default value
[OC-1347]: https://opfab.atlassian.net/browse/OC-1347
=> [OC-1347] Fix bug with keepChilCards default value

ui/main/src/app/modules/admin/components/editmodal/users/edit-user-modal.component.html
I don't think it's worth mentioning in the release notes, it's part of the rework of the admin modals.
=> [OC-1474] Fix style of administration edit/create modals

ui/main/src/app/modules/admin/components/editmodal/groups-entities/edit-entity-group-modal.component.ts, ui/main/src/app/modules/admin/components/table/admin-table.directive.ts, ui/main/src/app/modules/admin/components/table/entities-table.component.ts, ui/main/src/app/modules/admin/components/table/groups-table.component.ts, ui/main/src/app/modules/admin/components/table/users-table.component.ts
Not worth mentioning in release notes, as it was a bug after the refactoring of admin.
I also took into account some of tslints warnings.
=> [OC-1458] Fixing delete message for entities and groups in admin

ui/main/src/app/app.component.ts, ui/main/src/app/modules/admin/admin.component.ts
I don't think it's worth mentioning in the release notes, it's part of the rework of the admin modals.
=> [OC-1475] Fix Groups dropdown for users edit/create modal in admin

ui/main/src/app/modules/admin/admin.component.html, ui/main/src/app/modules/admin/admin.component.ts, ui/main/src/app/modules/admin/components/table/admin-table.directive.ts
Release notes:
Under bugs : [OC-1459] Admin - Propagate entity/group update to users
[OC-1459]: https://opfab.atlassian.net/browse/OC-1459
=> [OC-1459] Admin - Propagate entity/group update to users

services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/controllers/CardController.java, src/test/api/karate/cards/cards.feature, src/test/api/karate/cards/deleteUserCard.feature
Release notes:
[OC-1469] Fix Bug - publisherType not  set to external when receiving a card via card endPoint
[OC-1469]: https://opfab.atlassian.net/browse/OC-1469
=> [OC-1469] Fix Bug - publisherType not  set to external 

ui/main/src/app/modules/calendar/calendar.component.scss
Release notes: 
[OC-1478] Fix Bug in calendar day mode when event spans multiple days
[OC-1478]: https://opfab.atlassian.net/browse/OC-1478
=> [OC-1478] Fix Bug in calendar day mode when event spans multiple days

ui/main/src/app/modules/admin/components/editmodal/groups-entities/edit-entity-group-modal.component.html, ui/main/src/app/modules/admin/components/editmodal/groups-entities/edit-entity-group-modal.component.ts, ui/main/src/app/modules/admin/components/editmodal/users/edit-user-modal.component.html, ui/main/src/app/modules/admin/components/editmodal/users/edit-user-modal.component.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json
[OC-1457](https://opfab.atlassian.net/browse/OC-1457) : Admin : Do not limit size of input field
=> [OC-1457] Admin : Do not limit size of input field

ui/main/src/app/modules/archives/archives.component.html, ui/main/src/app/modules/archives/archives.component.ts, ui/main/src/app/modules/share/multi-filter/multi-filter.component.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json, ui/main/src/assets/styles/styles.scss
[OC-1439](https://opfab.atlassian.net/browse/OC-1439) : New archives screen filters
=> [OC-1439] New archives screen filters

ui/main/src/app/modules/cards/components/detail/detail.component.ts, ui/main/src/app/modules/share/countdown/countdown.component.ts
Release notes:
[OC-964] Deal with user in more than one entity
[OC-964]: https://opfab.atlassian.net/browse/OC-964
=> [OC-964] Deal with user in more than one entity

ui/main/src/app/modules/archives/archives.component.ts, ui/main/src/app/modules/logging/components/logging-table/logging-table.component.ts, ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json
In Bug section : 
OC-1425 : Export data : title of the columns are not translated
=> [OC-1425] : Export data : title of the columns are not translated

ui/main/src/app/modules/archives/archives.component.html, ui/main/src/app/modules/archives/archives.component.ts, ui/main/src/app/modules/archives/archives.module.ts, ui/main/src/app/modules/logging/components/logging-filters/logging-filters.component.html, ui/main/src/app/modules/logging/components/logging-filters/logging-filters.component.ts, ui/main/src/app/modules/logging/components/logging-table/logging-table.component.html, ui/main/src/app/modules/logging/components/logging-table/logging-table.component.ts, ui/main/src/app/modules/logging/logging.component.html, ui/main/src/app/modules/logging/logging.module.ts, ui/main/src/app/modules/share/archives-logging-filters/archives-logging-filters.component.html, ui/main/src/app/modules/share/archives-logging-filters/archives-logging-filters.component.ts, ui/main/src/app/modules/share/archives-logging-filters/archives-logging-filters.module.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json
[OC-1440](https://opfab.atlassian.net/browse/OC-1440) : New logging screen filters
=> [OC-1440] New logging screen

src/docs/asciidoc/reference_doc/template_description.adoc, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/template/en/incidentInProgress.handlebars, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/template/en/usercard_incidentInProgress.handlebars, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/template/fr/incidentInProgress.handlebars, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/template/fr/usercard_incidentInProgress.handlebars, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples3/template/en/usercard_task.handlebars, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples3/template/fr/usercard_task.handlebars, ui/main/src/assets/styles/styles.scss
Release note :
Features : 
OC-1503 Add an opfab style for border box with label in template
=> OC-1503 Add an opfab style for border box with label in template

src/docs/asciidoc/reference_doc/response_cards.adoc, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/template/en/incidentInProgress.handlebars, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/template/fr/incidentInProgress.handlebars, ui/main/src/app/modules/cards/components/detail/detail.component.ts, ui/main/src/assets/js/templateGateway.js
Release notes:
[OC-1508] Communicate to the template if the user can respond by calling templateGateway.setUserCanRespond(boolean) function
[OC-1508]: https://opfab.atlassian.net/browse/OC-1508
=> [OC-1508] Communicate to the template if the user can respond

ui/main/src/app/modules/cards/components/detail/detail.component.html, ui/main/src/app/modules/cards/components/detail/detail.component.ts, ui/main/src/app/modules/feed/feed.component.html, ui/main/src/app/modules/feed/feed.component.ts
Features : 
OC-1512 Adapt UI  for small screens (Feed)
=> [OC-1512] Adapt UI for small screens

ui/main/src/app/modules/usercard/usercard.component.ts
Release notes:
[OC-1499] Disable service and process fields when editing a user card
[OC-1499]: https://opfab.atlassian.net/browse/OC-1499
=> [OC-1499] Disable service and process fields when editing a user card

src/docs/asciidoc/reference_doc/template_description.adoc
Task : 
[OC-1514] Add documentation for json handlebars helper 
[OC-1514]: https://opfab.atlassian.net/browse/OC-1514
=> OC-1514 Add documentation for json handlebars helper

src/docs/asciidoc/reference_doc/archives.adoc, src/docs/asciidoc/reference_doc/response_cards.adoc, src/test/utils/karate/businessconfig/resources/bundle_defaultProcess/config.json, src/test/utils/karate/businessconfig/resources/bundle_defaultProcess/i18n/en.json, src/test/utils/karate/businessconfig/resources/bundle_defaultProcess/template/en/multipleOptionsResponse.handlebars, src/test/utils/karate/businessconfig/resources/bundle_defaultProcess/template/en/question.handlebars, src/test/utils/karate/businessconfig/resources/bundle_defaultProcess/template/en/response.handlebars, src/test/utils/karate/businessconfig/resources/bundle_defaultProcess/template/fr/multipleOptionsResponse.handlebars, src/test/utils/karate/businessconfig/resources/bundle_defaultProcess/template/fr/question.handlebars, src/test/utils/karate/cards/setPerimeterFor6Cards.feature, ui/main/src/app/modules/cards/components/detail/detail.component.ts
Release notes:
Under features
[OC-1498] Add the possibility to set the response state from the template
+
See the [documentation](https://opfab.github.io/documentation/archives/2.2.0.RELEASE/docs/single_page_doc.html#response_cards) for details.
[OC-1498]: https://opfab.atlassian.net/browse/OC-1498
=> [OC-1498] Add the possibility to set the response state from the template

ui/main/src/app/modules/feed/feed.component.html, ui/main/src/app/modules/feed/feed.component.scss, ui/main/src/app/modules/feed/feed.component.ts, ui/main/src/app/modules/navbar/navbar.component.html, ui/main/src/assets/styles/styles.scss
=> [OC-1512] Adapt UI for small screens - Adjustements

config/dev/docker-compose.yml, config/docker/docker-compose.yml, src/main/docker/mongodb/docker-compose.yml, src/main/docker/test-environment/docker-compose.yml, src/main/docker/test-quality-environment/docker-compose.yml
Remove old mongo docker container before starting (docker rm container_id ) 
Release note :
Task : 
OC-1521 Upgrade to MongoDB 4.4.4
=> [OC-1521] Upgrade to MongoDB 4.4.4

ui/main/src/app/modules/admin/components/table/admin-table.directive.ts, ui/main/src/app/modules/admin/components/table/perimeters-table.component.ts
In release notes under tasks: 
[OC-1524] Admin UI - Avoid dismissal of modals on outside click
[OC-1524]: https://opfab.atlassian.net/browse/OC-1524
=> [OC-1524] Admin UI - Avoid dismissal of modals on outside click

build.gradle, services/services.gradle, versions.properties
I don't think it's worth mentioning in the release notes.
=> [OC-1520] Setting version for Prometheus/Micrometer dependency

services/core/businessconfig/src/main/java/org/lfenergy/operatorfabric/businessconfig/services/ProcessesService.java, services/core/businessconfig/src/test/java/org/lfenergy/operatorfabric/businessconfig/controllers/GivenAdminUserBusinessconfigControllerShould.java, services/core/businessconfig/src/test/java/org/lfenergy/operatorfabric/businessconfig/controllers/GivenNonAdminUserBusinessconfigControllerShould.java, services/core/businessconfig/src/test/java/org/lfenergy/operatorfabric/businessconfig/services/ProcessesServiceShould.java
For release notes, under "Bugs":
[OC-1464] Fix bug when deleting all bundles
[OC-1464]: https://opfab.atlassian.net/browse/OC-1464
=> [OC-1464] Fix bug when deleting all bundles

ui/main/src/app/modules/feed/components/time-line/init-chart/init-chart.component.ts
Release notes
[OC-1515] Memorize choosen domain for timeline
[OC-1515]: https://opfab.atlassian.net/browse/OC-1515
=> [OC-1515] Memorize choosen domain for timeline

config/docker/docker-compose.yml
in Release note : 
Task : 
OC-1519 : Start users, card-consultation and card-publication after mongo and rabbit (in docker-compose)
=> [OC-1519] Start users,card-consultation and card-publication after mongo and rabbit

src/docs/asciidoc/reference_doc/user_cards.adoc, ui/main/src/app/modules/usercard/usercard.component.html, ui/main/src/app/modules/usercard/usercard.component.ts
Feature : 
OC-1530 :  usercard: when sending the card send it as well to the current user
=> [OC-1530] usercard: when sending the card send it as well to the current user

ui/main/src/assets/i18n/fr.json
OC-1535 : correct a typo on the timeline (French version)
=> [OC-1535] correct a typo on the timeline (French version)

bin/load_environment_light.sh, src/docs/asciidoc/dev_env/launch_dev.adoc, src/docs/asciidoc/dev_env/requirements.adoc, src/docs/asciidoc/dev_env/ui.adoc, src/test/utils/karate/README.adoc
A few changes to the documentation after setting up my environment from scratch on Ubuntu.
No need to mention it in the release notes I think.
=> [OC-1534] Update dev environment documentation

ui/main/src/app/modules/archives/archives.component.html, ui/main/src/app/modules/archives/archives.component.ts, ui/main/src/app/modules/cards/components/detail/detail.component.html, ui/main/src/app/modules/cards/components/detail/detail.component.ts, ui/main/src/app/modules/share/light-card/light-card.component.html, ui/main/src/app/modules/share/light-card/light-card.component.ts, ui/main/src/app/modules/usercard/usercard.component.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json
release note :
Feature : 
OC-1529 Show card entity publisher on feed and card detail
=> [OC-1529] Show card entity publisher on feed and card detail

services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/repositories/ArchivedCardCustomRepositoryImpl.java, services/core/cards-consultation/src/main/java/org/lfenergy/operatorfabric/cards/consultation/repositories/CardCustomRepositoryImpl.java, services/core/cards-consultation/src/test/java/org/lfenergy/operatorfabric/cards/consultation/TestUtilities.java, services/core/cards-consultation/src/test/java/org/lfenergy/operatorfabric/cards/consultation/controllers/CardOperationsControllerShould.java, services/core/cards-consultation/src/test/java/org/lfenergy/operatorfabric/cards/consultation/repositories/ArchivedCardRepositoryShould.java, services/core/cards-consultation/src/test/java/org/lfenergy/operatorfabric/cards/consultation/repositories/CardRepositoryShould.java, src/docs/asciidoc/reference_doc/card_structure.adoc, src/test/utils/karate/cards/postAChartCard.feature, src/test/utils/karate/cards/postAContingenciesCard.feature, src/test/utils/karate/cards/postAMessageCard.feature, src/test/utils/karate/cards/postAProcessCard.feature, src/test/utils/karate/cards/postCardWithOldBundleVersion.feature, ui/main/src/app/services/filter.service.ts
In Release notes:
[OC-1531] Change rule of visiblity for cards with no endDate to be visible when startDate is between start and end of chosen period.
[OC-1531]: https://opfab.atlassian.net/browse/OC-1531
=> [OC-1531] Change rule of visiblity for cards with no endDate

ui/main/src/assets/i18n/fr.json
=> [OC-1561] Usercard preview : mistake in french translation "PREVISUALISATION FEED"

config/dev/web-ui-test.json, config/dev/web-ui.json, config/docker/web-ui.json, src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc, ui/main/src/app/modules/feed/components/card-list/filters/feed-filter/feed-filter.component.html, ui/main/src/app/modules/feed/components/card-list/filters/feed-filter/feed-filter.component.ts, ui/main/src/app/modules/feed/components/card-list/filters/filters.component.html, ui/main/src/app/modules/feed/components/card-list/filters/filters.component.ts, ui/main/src/app/modules/feed/feed.component.html, ui/main/src/app/modules/feed/feed.component.ts
[OC-1562](https://opfab.atlassian.net/browse/OC-1562) : Remove web-ui option to hidetime line
=> [OC-1562] Remove web-ui option to hidetime line

src/test/api/karate/cards/fetchArchivedCardsWithParams.feature
Release notes
In Tasks:
[OC-1556] Modify Karate API test to add test card with no end date
[OC-1556]: https://opfab.atlassian.net/browse/OC-1556
=> [OC-1556] Modify Karate API test to add test card with no end date

ui/main/src/app/modules/feedconfiguration/feedconfiguration.component.html, ui/main/src/app/modules/feedconfiguration/feedconfiguration.component.ts, ui/main/src/app/services/processes.service.ts
In bug section : 
[OC-1538](https://opfab.atlassian.net/browse/OC-1538) : BUG - FeedNotification configuration - processes not sorted by their label
=> [OC-1538] BUG - FeedNotification configuration

src/test/utils/karate/businessconfig/resources/bundle_defaultProcess/i18n/fr.json, src/test/utils/karate/businessconfig/resources/bundle_defaultProcess/template/en/usercard_process.handlebars, src/test/utils/karate/businessconfig/resources/bundle_defaultProcess/template/fr/usercard_process.handlebars
Release notes
[OC-1560] User card : fix title when using "process example" template
[OC-1560]: https://opfab.atlassian.net/browse/OC-1560
=> [OC-1560] User card : fix title when using "process example" template

ui/main/src/app/modules/cards/components/detail/detail.component.ts, ui/main/src/app/modules/usercard/usercard.component.ts
Release notes
In Task section:
[OC-1552] Entity emitting the card shall not be able to respond
[OC-1552]: https://opfab.atlassian.net/browse/OC-1552
=> [OC-1552] Entity emitting the card shall not be able to respond

ui/main/src/assets/styles/styles.scss
[OC-1462](https://opfab.atlassian.net/browse/OC-1462) : Admin UI - Adapt column fiter to night mode
=> [OC-1462] Admin UI - Adapt column fiter to night mode

ui/main/src/app/modules/usercard/usercard.component.ts
[OC-1509](https://opfab.atlassian.net/browse/OC-1509) : Recurrent error message when posting user cards
=> [OC-1509] Recurrent error message when posting user cards

config/dev/nginx.conf.template, config/docker/nginx.conf
[OC-1567] Activate nginx gzip compression
[OC-1567]: https://opfab.atlassian.net/browse/OC-1567
=> [OC-1567] Activate nginx gzip compression

services/core/businessconfig/src/main/java/org/lfenergy/operatorfabric/businessconfig/model/UserCardData.java, services/core/businessconfig/src/main/modeling/swagger.yaml, src/docs/asciidoc/reference_doc/user_cards.adoc, src/test/api/karate/businessconfig/getABusinessconfig.feature, src/test/api/karate/businessconfig/resources/bundle_api_test/config.json, src/test/api/karate/businessconfig/resources/bundle_api_test_v2/config.json, src/test/utils/karate/businessconfig/postBundleUserCardExamples2.feature, src/test/utils/karate/businessconfig/resources/bundle_defaultProcess/config.json, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples/config.json, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples2/config.json, src/test/utils/karate/businessconfig/resources/bundle_userCardExamples3/config.json, ui/main/src/app/model/processes.model.ts, ui/main/src/app/modules/usercard/usercard.component.html, ui/main/src/app/modules/usercard/usercard.component.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json
Release notes
[OC-1227] Add lttd field as an option in user card
[OC-1227]: https://opfab.atlassian.net/browse/OC-1227
=> [OC-1227] Add lttd field as an option in user card

ui/main/src/app/modules/share/countdown/countdown.component.ts
Release note :
Features : 
[OC-1572] Do not use entiyAllowedToRespond to show/hide the clock for  last time to decide
[OC-1572]: https://opfab.atlassian.net/browse/OC-1572
=> [OC-1572] Do not use entiyAllowedToRespond to show/hide the clock for  last time to decide

src/test/api/karate/businessconfig/deleteBundle.feature, src/test/api/karate/businessconfig/deleteBundleVersion.feature, src/test/api/karate/businessconfig/getBusinessconfig.feature, src/test/api/karate/businessconfig/uploadBundle.feature, src/test/api/karate/launchAllBusinessconfig.sh, src/test/utils/karate/Action/uploadBundleAction.feature, src/test/utils/karate/README.adoc, src/test/utils/karate/businessconfig/postBundleDefaultProcess.feature, src/test/utils/karate/businessconfig/postBundleTestAction.feature, src/test/utils/karate/businessconfig/postBundleUserCardExamples.feature, src/test/utils/karate/businessconfig/postBundleUserCardExamples2.feature, src/test/utils/karate/businessconfig/postBundleUserCardExamples3.feature, src/test/utils/karate/examples/gridCooperation/postBundleGridCooperation.feature, src/test/utils/karate/operatorfabric-getting-started/message1.feature, src/test/utils/karate/operatorfabric-getting-started/message2.feature
Release notes
[OC-1537] Fix karate tests to work with Karate 1.0.0
[OC-1537]: https://opfab.atlassian.net/browse/OC-1537
=> [OC-1537] Fix karate tests to work with Karate 1.0.0

services/core/cards-consultation/src/test/java/org/lfenergy/operatorfabric/cards/consultation/services/CardSubscriptionServiceShould.java
Added in Jira issue the steps to reproduce the problem.
Not worth mentioning in release notes.
=> [OC-1284] cards-consultation : Tests - receiveCards() - HEARTBEAT should be ignored

ui/main/src/app/modules/admin/components/editmodal/entities/edit-entity-modal.component.html, ui/main/src/app/modules/admin/components/editmodal/entities/edit-entity-modal.component.scss, ui/main/src/app/modules/admin/components/editmodal/entities/edit-entity-modal.component.ts
Release notes
[OC-1505] Add parent entities to edition modal in Admin
[OC-1505]: https://opfab.atlassian.net/browse/OC-1505
=> [OC-1505] Add parent entities to edition modal in Admin

ui/main/src/app/modules/cards/services/handlebars.service.ts
I propose to add nothing in release notes ?
[OC-1510](https://opfab.atlassian.net/browse/OC-1510) : Many custom handlebars helpers have unused options parameters
=> [OC-1510] Many custom handlebars helpers have unused options parameters

ui/main/src/app/store/effects/authentication.effects.ts, ui/main/src/app/store/effects/card-operation.effects.ts, ui/main/src/app/store/effects/card.effects.ts, ui/main/src/app/store/effects/custom-router.effects.ts, ui/main/src/app/store/effects/feed-filters.effects.ts, ui/main/src/app/store/effects/logging.effects.ts, ui/main/src/app/store/effects/menu.effects.ts, ui/main/src/app/store/effects/monitoring.effects.ts, ui/main/src/app/store/effects/settings.effects.ts, ui/main/src/app/store/effects/user.effects.ts
In release notes, add it to the ngrx v11 update item.
=> [OC-1579] ngrx - replace deprecated Effect decorator

ui/main/src/app/modules/logging/components/logging-table/logging-table.component.ts
Release notes 
[OC-1582] Fix bug when exporting to excel in logging screen
[OC-1582]: https://opfab.atlassian.net/browse/OC-1582
=> [OC-1582] Fix bug when exporting to excel in logging screen

ui/main/src/app/modules/usercard/usercard.component.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json
Release notes
[OC-1491] UserCard: check that end date is after start date, show a clear error message otherwise
[OC-1491]: https://opfab.atlassian.net/browse/OC-1491
=> [OC-1491] UserCard: check that end date is after start date

ui/main/package.json, ui/main/src/app/app.module.ts, ui/main/src/app/modules/cards/components/detail/detail.component.html, ui/main/src/app/modules/cards/components/detail/detail.component.ts, ui/main/src/app/modules/share/countdown/countdown.component.html, ui/main/src/app/modules/share/countdown/countdown.component.ts, ui/main/src/app/modules/share/countdown/countdown.module.ts, ui/main/src/app/modules/share/countdown/countdown.spec.ts, ui/main/src/app/modules/share/countdown/countdown.ts, ui/main/src/app/modules/share/light-card/light-card.component.html, ui/main/src/app/modules/share/light-card/light-card.component.spec.ts, ui/main/src/app/modules/share/timeline-buttons/timeline-buttons.module.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json
Release note 
Task : 
OC-1573 : Re-factorize countdown module
=> [OC-1573] Refacto countdown module

src/docs/asciidoc/deployment/configuration/configuration.adoc, src/docs/asciidoc/dev_env/kafka.adoc
[OC-1588] Minor Kafka documentation update. Now mentions the card response topic setting.
[OC-1588]: https://opfab.atlassian.net/browse/OC-1588
=> [OC-1588] Kafka doc updates

ui/main/angular.json
Tasks : 
OC-1569 :  Remove unused ui-home-e2e project configuration in angular.json
=> [OC-1569] Remove unused ui-home-e2e project configuration in angular.json

ui/main/src/app/model/entity.model.ts, ui/main/src/app/model/user.model.ts, ui/main/src/app/services/user.service.ts, ui/main/src/app/store/actions/user.actions.ts, ui/main/src/app/store/effects/user.effects.ts, ui/main/src/app/store/states/user.state.ts
[OC-1487](https://opfab.atlassian.net/browse/OC-1487) : UI - User model exports (duplicate) Entity class
=> [OC-1487] UI - User model exports (duplicate) Entity class

src/test/cypress/README.adoc, src/test/cypress/cypress.json, src/test/cypress/cypress/integration/BasicCheck.spec.js, src/test/cypress/cypress/integration/BasicTestWithProgrammaticLogin.spec.js, src/test/cypress/cypress/integration/CheckTimeline.spec.js, src/test/cypress/cypress/integration/CheckTranslationsEN.spec.js, src/test/cypress/cypress/integration/CheckTranslationsFR.spec.js, src/test/cypress/cypress/integration/LoginPage.spec.js, src/test/cypress/cypress/integration/NavigationHiddenTimelineEN.spec.js, src/test/cypress/cypress/integration/NavigationHiddenTimelineFR.spec.js, src/test/cypress/cypress/integration/NotificationManagement.spec.js, src/test/cypress/cypress/integration/SendSeveralCards.spec.js, src/test/cypress/cypress/integration/UnauthenticatedShouldBeRedirected.spec.js, src/test/cypress/cypress/integration/UserCardResponses.spec.js, src/test/cypress/cypress/integration/UsercardCreation.spec.js, src/test/cypress/cypress/support/commands.js, src/test/cypress/package.json
No need to mention it in the release notes
=> [OC-1574] Reworking Cypress Tests - WIP1

services/core/users/src/main/java/org/lfenergy/operatorfabric/users/controllers/EntitiesController.java, services/core/users/src/main/java/org/lfenergy/operatorfabric/users/repositories/EntityRepository.java, services/core/users/src/test/java/org/lfenergy/operatorfabric/users/controllers/EntitiesControllerShould.java, services/core/users/src/test/java/org/lfenergy/operatorfabric/users/repositories/EntityRepositoryShould.java, src/test/api/karate/users/entities/checkEntityGroupManagement.feature
Release notes
[OC-1581] Deleting an entity that is listed as parent entity in some children entities should cause it to be removed from said children
[OC-1581]: https://opfab.atlassian.net/browse/OC-1581
=> [OC-1581] Deleting parent entity should remove the reference in child entities

ui/main/src/app/modules/usercard/usercard.component.html
[OC-1536](https://opfab.atlassian.net/browse/OC-1536) : Usercard - Do not show Process or State if only one choice
=> [OC-1536] Usercard - Do not show Process or State if only one choice

ui/main/src/app/modules/feedconfiguration/feedconfiguration.component.html
[OC-1591](https://opfab.atlassian.net/browse/OC-1591) : Notification configuration screen : bug in display near the "save" button
=> [OC-1591] Notification configuration screen : bug in display near the "save" button

src/test/api/karate/launchAll.sh
=> [OC-1596] Package the bundle when launching all api regression test (Bug correction)

ui/main/src/app/modules/cards/components/detail/detail.component.html
nothing in release note as bug was not present in previous version
=> [OC-1600] Correct bug introduced with new version of ngx-translate

src/test/api/karate/cards/getCardSubscription.feature
Release notes
In Tasks:
[OC-1282] Test with karate endpoint cardSubscription
[OC-1282]: https://opfab.atlassian.net/browse/OC-1282
=> [OC-1282] Test with karate endpoint cardSubscription

src/docs/asciidoc/reference_doc/response_cards.adoc, src/docs/asciidoc/resources/index.adoc, src/docs/asciidoc/resources/migration_guide_to_2.3.adoc, src/test/api/karate/businessconfig/resources/bundle_test_action/template/en/long-card.handlebars, src/test/api/karate/businessconfig/resources/bundle_test_action/template/en/template1.handlebars, src/test/api/karate/businessconfig/resources/bundle_test_action/template/fr/long-card.handlebars, src/test/api/karate/businessconfig/resources/bundle_test_action/template/fr/template1.handlebars, src/test/resources/bundles/defaultProcess_V1/template/en/question.handlebars, src/test/resources/bundles/defaultProcess_V1/template/fr/question.handlebars, src/test/resources/bundles/userCardExamples/template/en/incidentInProgress.handlebars, src/test/resources/bundles/userCardExamples/template/fr/incidentInProgress.handlebars, src/test/resources/bundles/userCardExamples2/template/en/question.handlebars, src/test/resources/bundles/userCardExamples2/template/fr/question.handlebars, ui/main/src/app/modules/cards/components/detail/detail.component.ts, ui/main/src/assets/js/templateGateway.js
Tasks : 
OC-1597: Improve communication between template and opfab 
+
IMPORTANT: This change the way of exchanging between opfab and template when using response cards . If you are using response cards, you must modify your templates . To migrate your templates, see https://opfab.github.io/documentation/current/docs/single_page_doc.html#_migration_guide_from_release_2_2_0_to_release_2_3_0
+
=> [OC-1597] Improve communication between template and opfab

ui/main/src/app/modules/cards/components/detail/detail.component.html
Nothing in release note as bug was not present in last release
=> [OC-1603] Finalize correction of bug introduced with new version of ngx-translate

client/cards/src/main/modeling/config.json, services/core/cards-consultation/src/main/modeling/config.json, services/core/cards-publication/src/main/modeling/config.json, services/core/cards-publication/src/main/modeling/swagger.yaml, ui/main/src/app/model/card.model.ts
[[OC-1586](https://opfab.atlassian.net/browse/OC-1586)] Remove TitlePositionEnum
=> [OC-1586] Remove TitlePositionEnum

src/docs/asciidoc/reference_doc/response_cards.adoc, src/test/resources/bundles/defaultProcess_V1/template/en/question.handlebars, src/test/resources/bundles/defaultProcess_V1/template/fr/question.handlebars, ui/main/src/app/modules/cards/components/detail/detail.component.ts, ui/main/src/assets/js/templateGateway.js
Release notes:
In Tasks:
[OC-1606] Add method isUserMemberOfAnEntityRequiredToRespond() for card template
[OC-1606]: https://opfab.atlassian.net/browse/OC-1606
=> [OC-1606] Add method isUserMemberOfAnEntityRequiredToRespond for template

ui/main/src/app/modules/admin/components/confirmation-dialog/confirmation-dialog.component.html, ui/main/src/app/modules/admin/components/editmodal/entities/edit-entity-modal.component.html, ui/main/src/app/modules/admin/components/editmodal/groups/edit-group-modal.component.html, ui/main/src/app/modules/admin/components/editmodal/perimeters/edit-perimeter-modal.component.html, ui/main/src/app/modules/admin/components/editmodal/users/edit-user-modal.component.html, ui/main/src/app/modules/cards/components/detail/detail.component.html, ui/main/src/app/modules/feedconfiguration/feedconfiguration.component.html
[OC-1610](https://opfab.atlassian.net/browse/OC-1610) : Confirmation popups : harmonize the closing cross
=> [OC-1610] Confirmation popups : harmonize the closing cross

config/dev/web-ui.json, config/docker/web-ui.json, src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc, ui/main/src/app/model/processes.model.ts, ui/main/src/app/modules/feed/components/card-list/card-list.component.html, ui/main/src/app/modules/feed/components/card-list/card-list.component.scss, ui/main/src/app/modules/feed/components/card-list/card-list.component.ts, ui/main/src/app/modules/feed/components/card-list/filters/filters.component.ts, ui/main/src/app/services/processes.service.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json
In features section : 
[OC-1288](https://opfab.atlassian.net/browse/OC-1288) : As an operator, I want to be able to acknowledge all notification in 1 click
=> [OC-1288] As an operator, I want to be able to acknowledge all notification in 1 click

ui/main/src/app/modules/admin/components/table/admin-table.directive.ts, ui/main/src/app/modules/admin/components/table/entities-table.component.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json
Release notes
[OC-1594] Translate true/false values in the Entity admin table
[OC-1594]: https://opfab.atlassian.net/browse/OC-1594
=> [OC-1594] Translate true/false values in the Entity admin table

ui/main/src/app/modules/usercard/usercard.component.ts
Nothing in release note (bug not present in previous version)
=> [OC-1626] BUG - After edition of a user card, the new version contains always a lttd

services/core/users/src/main/java/org/lfenergy/operatorfabric/users/controllers/UsersController.java
[OC-1628] BUG - Feed - receiving cards : changing a user setting stops cards reception
[OC-1628]: https://opfab.atlassian.net/browse/OC-1628
=> [OC-1628] BUG - Feed - receiving cards : changing a user setting stops cards reception

services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/controllers/CardController.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/services/CardProcessingService.java, services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/cards/publication/services/CardRepositoryService.java, services/core/cards-publication/src/main/modeling/swagger.yaml, services/core/cards-publication/src/test/java/org/lfenergy/operatorfabric/cards/publication/services/CardProcessServiceShould.java, src/test/api/karate/cardTests.txt, src/test/api/karate/cards/deleteCardsByEndDate.feature
[OC-1602] Delete cards endpoint to delete multiple cards by date criteria
[OC-1602]: https://opfab.atlassian.net/browse/OC-1602
=> [OC-1602] Delete cards endpoint to delete multiple cards by date criteria

ui/main/src/app/modules/share/timeline-buttons/timeline-buttons.component.ts
Release notes
[OC-1623] Fix bug when removing a timeline domain from web-ui configration
[OC-1623]: https://opfab.atlassian.net/browse/OC-1623
=> [OC-1623] Fix bug when removing a timeline domain from web-ui configration

ui/main/package-lock.json, ui/main/src/app/modules/archives/archives.component.html, ui/main/src/app/modules/share/card-detail/card-detail.component.ts, ui/main/src/app/modules/usercard/usercard.component.html
Updated also package-lock.json file.
Release notes
[OC-1624] Card preview in user card shall not set the template in full screen mode
[OC-1624]: https://opfab.atlassian.net/browse/OC-1624
=> [OC-1624] Card preview in user card shall not set the template in full screen mode

src/test/api/karate/karate-config.js
=> [OC-1638] Increase karate test timeout

src/test/resources/bundles/userCardExamples3/template/en/task.handlebars, src/test/resources/bundles/userCardExamples3/template/en/usercard_task.handlebars, src/test/resources/bundles/userCardExamples3/template/fr/task.handlebars, src/test/resources/bundles/userCardExamples3/template/fr/usercard_task.handlebars, ui/main/src/app/modules/cards/services/handlebars.service.ts
Release notes
[OC-1627] Tasks card does not fill the repetition date, duration and hour/min when editing the card
[OC-1627]: https://opfab.atlassian.net/browse/OC-1627
=> [OC-1627] Tasks card does not fill the repetition date, duration and hour/min when editing the card

src/test/resources/bundles/defaultProcess_V1/template/en/usercard_process.handlebars, src/test/resources/bundles/defaultProcess_V1/template/fr/usercard_process.handlebars
Release notes
[OC-1625] Usercard process template store in the card data the status value
[OC-1625]: https://opfab.atlassian.net/browse/OC-1625
=> [OC-1625] Usercard process template store in the card data the status value

src/test/api/karate/businessconfig/resources/bundle_api_test/config.json, src/test/api/karate/businessconfig/resources/bundle_api_test/i18n/en.json, src/test/api/karate/businessconfig/resources/bundle_api_test/i18n/fr.json, src/test/api/karate/businessconfig/resources/bundle_api_test_apogee/config.json, src/test/api/karate/businessconfig/resources/bundle_api_test_apogee/i18n/en.json, src/test/api/karate/businessconfig/resources/bundle_api_test_apogee/i18n/fr.json, src/test/resources/bundles/gridCooperation/config.json, src/test/resources/bundles/userCardExamples/config.json, src/test/resources/bundles/userCardExamples2/config.json, src/test/resources/bundles/userCardExamples3/config.json
A propose to add nothing in release notes
=> [OC-1622] Set a value for state.description fields in all card examples

src/test/resources/processGroups/singleProcessGroup.json, ui/main/src/app/modules/usercard/usercard.component.ts
Release notes:
[OC-1636] UserCard : Choose the first service in the list by default
[OC-1636]: https://opfab.atlassian.net/browse/OC-1636
=> [OC-1636] UserCard : Choose the first service in the list by default

ui/main/src/app/modules/admin/components/confirmation-dialog/confirmation-dialog.component.html, ui/main/src/app/modules/cards/components/detail/detail.component.html, ui/main/src/app/modules/feedconfiguration/feedconfiguration.component.html, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json, ui/main/src/assets/styles/styles.scss
Release notes
[OC-1609] Confirmation popups : harmonize size for text and title
[OC-1609]: https://opfab.atlassian.net/browse/OC-1609
=> [OC-1609] Confirmation popups : harmonize size for text and title

ui/main/src/app/modules/admin/components/editmodal/users/edit-user-modal.component.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json
Feature : 
[OC-1652] Admin screen : permit to create logins of 3 characters
[OC-1652]: https://opfab.atlassian.net/browse/OC-1652
=>  [OC-1652] Admin screen : permit to create logins of 3 characters

ui/main/src/app/modules/cards/components/detail/detail.component.ts
Release note: 
Feature : 
[OC-1641] When card is updated and selected in the feed, it shall be seen as unread
[OC-1641]: https://opfab.atlassian.net/browse/OC-1641
=> [OC-1641] When card is updated and selected in the feed, it shall be seen as unread

ui/main/src/app/modules/admin/services/confirmation-dialog.service.ts, ui/main/src/app/modules/cards/components/detail/detail.component.html, ui/main/src/app/modules/cards/components/detail/detail.component.scss, ui/main/src/app/modules/cards/components/detail/detail.component.ts, ui/main/src/app/modules/feed/components/card-list/card-list.component.ts, ui/main/src/app/modules/feedconfiguration/feedconfiguration.component.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json
Release notes:
[OC-1613] Confirmation popup shall be on the middle of the screen
[OC-1613]: https://opfab.atlassian.net/browse/OC-1613
=> [OC-1613] Confirmation popup shall be on the middle of the screen

ui/main/src/app/services/user.service.ts
[OC-1656](https://opfab.atlassian.net/browse/OC-1656) : user.service.ts : rework isCurrentUserAdmin() and isCurrentUserInAnyGroup()
=> [OC-1656] user.service.ts : rework isCurrentUserAdmin() and isCurrentUserInAnyGroup() 

ui/main/src/app/modules/cards/components/detail/detail.component.html, ui/main/src/app/modules/cards/components/detail/detail.component.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json
Release notes
[OC-1657] Card deletion result should be displayed with an alert messageage instead of popover
[OC-1657]: https://opfab.atlassian.net/browse/OC-1657
=> [OC-1657] Card deletion result should be displayed with an alert message

ui/main/src/app/modules/usercard/usercard.component.ts
Release notes:
[OC-1674]  Editing a usercard : multi-select component for state field is not set with the right value
[OC-1674]: https://opfab.atlassian.net/browse/OC-1674
=> [OC-1674] Editing a usercard : multi-select component for state field is not set with the right value

services/core/businessconfig/src/main/java/org/opfab/businessconfig/configuration/json/BusinessconfigModule.java, services/core/businessconfig/src/main/java/org/opfab/businessconfig/model/RecipientData.java, services/core/businessconfig/src/main/modeling/swagger.yaml, src/docs/asciidoc/reference_doc/user_cards.adoc, src/test/api/karate/businessconfig/getABusinessconfig.feature, src/test/api/karate/businessconfig/resources/bundle_api_test_v2/config.json, src/test/resources/bundles/userCardExamples/config.json, ui/main/src/app/model/processes.model.ts, ui/main/src/app/modules/usercard/usercard.component.ts, ui/main/src/app/services/entities.service.spec.ts, ui/main/src/app/services/entities.service.ts
Release notes
[OC-1584] Usercard : permit to have a restricted list of recipients  depending on the state and process
Note: in bundle config.json added in state definition  a "recipientList" field to configure a list of entities and optionally the levels of connection of related childs to be included in recipient list. Level 0 meaning the entity itself, level 1 for first level childs, level 2 for 2nd level connections, etc.
[OC-1584]: https://opfab.atlassian.net/browse/OC-1584
=> [OC-1584] Usercard : permit to have a restricted list of recipient

src/test/cypress/README.adoc, src/test/cypress/cypress/integration/FeedTests.spec.js, src/test/cypress/cypress/support/commands.js
Changes discussed during the presentation.
No need to mention it in the release notes.
=> [OC-1681] Changes to Cypress tests following discussion

ui/main/src/app/modules/usercard/usercard.component.html, ui/main/src/app/modules/usercard/usercard.component.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json
[OC-1682](https://opfab.atlassian.net/browse/OC-1682) : Usercard : Let the possibility to have no recipient
=> [OC-1682] Usercard : Let the possibility to have no recipient

ui/main/src/app/modules/cards/components/card-details/card-details.component.ts, ui/main/src/app/modules/cards/components/detail/detail.component.ts, ui/main/src/app/services/acknowledge.service.spec.ts, ui/main/src/app/services/acknowledge.service.ts, ui/main/src/app/services/action.service.ts
This solve as well OC-1675
Task : 
[OC-1690] Improve card detail view when state or process do not exist
[OC-1690]: https://opfab.atlassian.net/browse/OC-1690
=> [OC-1690] Improve card detail view when state or process do not exist

ui/main/src/app/modules/usercard/usercard.component.html, ui/main/src/app/modules/usercard/usercard.component.ts
Release notes
[OC-1673] Editing a usercard a wrong template is loaded at the beginning of display
[OC-1673]: https://opfab.atlassian.net/browse/OC-1673
=> [OC-1673] Editing a usercard a wrong template is loaded at the beginning of display

ui/main/src/app/model/line-of-monitoring-result.model.ts, ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.html, ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.scss
[OC-1692](https://opfab.atlassian.net/browse/OC-1692) : Monitoring screen - set text color for Process Status value
=> [OC-1692] Monitoring screen - set text color for Process Status value

services/core/cards-consultation/src/main/java/org/opfab/cards/consultation/configuration/mongo/LightCardReadConverter.java, services/core/cards-consultation/src/main/java/org/opfab/cards/consultation/model/ArchivedCardConsultationData.java, services/core/cards-consultation/src/main/java/org/opfab/cards/consultation/model/CardConsultationData.java, services/core/cards-consultation/src/main/java/org/opfab/cards/consultation/model/LightCardConsultationData.java, services/core/cards-publication/src/main/java/org/opfab/cards/publication/model/ArchivedCardPublicationData.java, services/core/cards-publication/src/main/java/org/opfab/cards/publication/model/CardPublicationData.java, services/core/cards-publication/src/main/java/org/opfab/cards/publication/model/LightCardPublicationData.java, services/core/cards-publication/src/main/java/org/opfab/cards/publication/services/CardProcessingService.java, services/core/cards-publication/src/main/modeling/swagger.yaml, services/core/cards-publication/src/test/java/org/opfab/cards/publication/services/CardProcessServiceShould.java, src/docs/asciidoc/reference_doc/card_structure.adoc, src/test/api/karate/cardTests.txt, src/test/api/karate/cards/cardsWithRepresentative.feature, src/test/resources/cards/defaultProcess/message.json, ui/main/src/app/model/card.model.ts, ui/main/src/app/model/light-card.model.ts, ui/main/src/app/model/line-of-logging-result.model.ts, ui/main/src/app/modules/archives/archives.component.html, ui/main/src/app/modules/archives/archives.component.ts, ui/main/src/app/modules/cards/components/detail/detail.component.html, ui/main/src/app/modules/cards/components/detail/detail.component.ts, ui/main/src/app/modules/logging/components/logging-table/logging-table.component.html, ui/main/src/app/modules/logging/components/logging-table/logging-table.component.ts, ui/main/src/app/services/card.service.ts
[OC-1655](https://opfab.atlassian.net/browse/OC-1655) : Add representative concept when sending card
=> [OC-1655] : Add representative concept when sending card

src/docs/asciidoc/reference_doc/card_examples.adoc
[OC-1577](https://opfab.atlassian.net/browse/OC-1577) : Documentation : add an example for routing card with perimeter
=> [OC-1577] Documentation : add an example for routing card with perimeter

ui/main/src/app/modules/admin/components/editmodal/users/edit-user-modal.component.ts
Release notes
[OC-1696] Name and surname shall not be mandatoy in admin screen
[OC-1696]: https://opfab.atlassian.net/browse/OC-1696
=> [OC-1696] Name and surname shall not be mandatoy in admin screen

services/core/users/src/main/java/org/opfab/users/controllers/GroupsController.java, services/core/users/src/test/java/org/opfab/users/controllers/GroupsControllerShould.java
Release notes
[OC-1670] Deletion of ADMIN group should not be possible
[OC-1670]: https://opfab.atlassian.net/browse/OC-1670
=> [OC-1670] Deletion of ADMIN group should not be possible

ui/main/src/app/modules/navbar/navbar.component.html
Bug :
[OC-1704] Correct bug when displaying feed on mobile phone
[OC-1704]: https://opfab.atlassian.net/browse/OC-1704
=> [OC-1704] Correct bug when displaying feed on mobile phone

bin/load_environment_light.sh
No need to mention it in the release notes.
=> [OC-1709] Updating Gradle to v6.9 in load env script

config/docker/ui-menu.json, src/docs/asciidoc/community/workflow.adoc, src/test/resources/bundles/defaultProcess_V1/i18n/fr.json, src/test/resources/bundles/defaultProcess_V1/template/en/usercard_process.handlebars, src/test/resources/bundles/defaultProcess_V1/template/fr/process.handlebars, src/test/resources/bundles/defaultProcess_V1/template/fr/usercard_process.handlebars, src/test/resources/processGroups/processGroups.json, src/test/resources/processGroups/singleProcessGroup.json
=> [OC-1718] Fixing typos, translations errors and broken links

src/docs/asciidoc/community/index.adoc
=> [OC-1720] Adding DCO sign-off check

ui/main/src/app/modules/archives/archives.component.ts, ui/main/src/app/modules/calendar/calendar.component.ts, ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.ts
Release notes
[OC-1711] Clicking on a link to a third application from a card in modal shall close the modal
[OC-1711]: https://opfab.atlassian.net/browse/OC-1711
=> [OC-1711] Clicking on a link to a third application from a card in modal shall close the modal

ui/main/src/app/modules/archives/archives.component.html, ui/main/src/app/modules/archives/archives.component.scss
Bug: 
[OC-1712] Screen adjustement for archives screen when resolution smaller than 1920*1080
[OC-1712]: https://opfab.atlassian.net/browse/OC-1712
=> [OC-1712] Screen adjustement for archives screen when resolution smaller than 1920*1080

services/core/cards-consultation/src/main/java/org/opfab/cards/consultation/configuration/webflux/ConnectionRoutesConfig.java, services/core/cards-consultation/src/main/java/org/opfab/cards/consultation/configuration/webflux/WebSecurityConfiguration.java, services/core/cards-consultation/src/main/java/org/opfab/cards/consultation/model/ConnectionData.java, services/core/cards-consultation/src/main/java/org/opfab/cards/consultation/services/CardSubscription.java, services/core/cards-consultation/src/main/java/org/opfab/cards/consultation/services/CardSubscriptionService.java, services/core/cards-consultation/src/test/java/org/opfab/cards/consultation/routes/ConnectionRoutesShould.java, services/core/cards-publication/src/main/modeling/swagger.yaml, src/docs/asciidoc/reference_doc/users_management.adoc, src/test/resources/getConnectedUsers.sh
- First implementation , UI in another issue 
- script src/test/resources/getConnectedUsers.sh provided for testing 
Feature : 
[OC-1697] Provide an endpoint to get access to open subscriptions
[OC-1697]: https://opfab.atlassian.net/browse/OC-1697
=> [OC-1697] Provide an endpoint to get access to open subscriptions

ui/main/src/app/modules/archives/archives.component.scss, ui/main/src/app/modules/logging/components/logging-filters/logging-filters.component.html, ui/main/src/app/modules/logging/components/logging-filters/logging-filters.component.scss, ui/main/src/app/modules/logging/components/logging-table/logging-table.component.html
Bugs :
* OC-1713 : Screen adjustement for logging screen when resolution smaller than 1920*1080
=> [OC-1713] Screen adjustement for logging screen when resolution smaller than 1920*1080

ui/main/src/app/modules/cards/components/detail/detail.component.ts, ui/main/src/app/modules/share/card-detail/card-detail.component.ts, ui/main/src/assets/js/templateGateway.js
Bug : 
* OC-1722 : Response to card example IT incident is not confirmed
=> [OC-1722] BUG - Response to card example IT incident is not confirmed

services/core/businessconfig/src/main/modeling/swagger.yaml, services/core/cards-publication/src/main/modeling/swagger.yaml, services/core/users/src/main/modeling/swagger.yaml
In release notes, under tasks :
OC-1730 : Fixing baseUrls in swagger for documentation
=> [OC-1730] Fixing baseUrls in swagger for documentation

ui/main/src/app/modules/navbar/navbar.component.html, ui/main/src/app/modules/navbar/navbar.component.scss
Release notes 
[OC-1716]  Adjustement to view for mobile phone when language is set to french
[OC-1716]: https://opfab.atlassian.net/browse/OC-1716
=> [OC-1716] Adjustement to view for mobile phone when language is set to french

config/dev/web-ui-cypress.json, config/dev/web-ui.json, config/docker/web-ui-cypress.json, config/docker/web-ui.json, src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc, ui/main/src/app/modules/feed/components/card-list/filters/feed-filter/feed-filter.component.html, ui/main/src/app/modules/feed/components/card-list/filters/feed-filter/feed-filter.component.ts, ui/main/src/app/modules/feed/components/card-list/filters/filters.component.html, ui/main/src/app/modules/feed/components/card-list/filters/filters.component.ts, ui/main/src/app/services/filter.service.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json
Release notes
[OC-1633] Add the option to filter notifications that has already been answered by user own entity
[OC-1633]: https://opfab.atlassian.net/browse/OC-1633
=> [OC-1633] Filter notification that has already been answered

CICD/prepare_release_version.sh
=> [OC-1558] Display correct OpFab version in about menu

services/core/businessconfig/src/main/java/org/opfab/businessconfig/BusinessconfigApplication.java, services/core/businessconfig/src/main/java/org/opfab/businessconfig/services/ProcessesService.java, services/core/businessconfig/src/main/resources/amqp.xml, services/core/cards-consultation/src/main/java/org/opfab/cards/consultation/services/CardSubscription.java, services/core/cards-consultation/src/main/java/org/opfab/cards/consultation/services/CardSubscriptionService.java, services/core/cards-consultation/src/test/java/org/opfab/cards/consultation/services/CardSubscriptionServiceShould.java, ui/main/src/app/modules/cards/cards.module.ts, ui/main/src/app/modules/cards/services/handlebars.service.ts, ui/main/src/app/services/card.service.ts, ui/main/src/app/store/actions/processes.actions.ts, ui/main/src/app/store/effects/processes.effects.ts, ui/main/src/app/store/index.ts
Release notes
[OC-1672] Reload the UI configuration when bundles has changed
[OC-1672]: https://opfab.atlassian.net/browse/OC-1672
=> [OC-1672] Reload the UI configuration when bundles has changed

src/test/cypress/cypress/integration/Acknowledgment.spec.js, src/test/cypress/cypress/support/commands.js, src/test/resources/bundles/cypress/config.json, src/test/resources/bundles/cypress/i18n/en.json, src/test/resources/bundles/cypress/i18n/fr.json, src/test/resources/bundles/cypress/template/en/template.handlebars, src/test/resources/bundles/cypress/template/fr/template.handlebars, src/test/resources/bundles/defaultProcess_V1/i18n/en.json, src/test/resources/cards/cypress/ack/message1.json, src/test/resources/cards/cypress/ack/message2.json, src/test/resources/cards/cypress/ack/message3.json, src/test/resources/cards/cypress/ack/message4.json, src/test/resources/perimeters/createAllPerimeter.sh, src/test/resources/perimeters/cypress.json, ui/main/src/app/modules/feed/components/card-list/card-list.component.html
Tasks : 
OC-1743: Add cypress tests for acknowledgment feature
=> [OC-1743] Add cypress tests for acknowledgment feature

config/dev/users-dev.yml, config/dev/web-ui.json, config/docker/users-docker.yml, config/docker/web-ui.json, src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc, src/docs/asciidoc/reference_doc/users_management.adoc, ui/main/src/app/app-routing.module.ts, ui/main/src/app/modules/feedconfiguration/feedconfiguration.component.html, ui/main/src/app/modules/navbar/navbar.component.html, ui/main/src/app/modules/navbar/navbar.component.ts, ui/main/src/app/modules/navbar/navbar.module.ts, ui/main/src/app/modules/realtimeusers/realtimeusers-routing.module.ts, ui/main/src/app/modules/realtimeusers/realtimeusers.component.html, ui/main/src/app/modules/realtimeusers/realtimeusers.component.scss, ui/main/src/app/modules/realtimeusers/realtimeusers.component.ts, ui/main/src/app/modules/realtimeusers/realtimeusers.module.ts, ui/main/src/app/services/user.service.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json
[OC-1699](https://opfab.atlassian.net/browse/OC-1699) : Add an admin screen to see open subscriptions
=> [OC-1699] Add an admin screen to see open subscriptions

config/dev/web-ui.json, src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc, ui/main/src/app/modules/usercard/usercard.component.ts
Release notes
[OC-1740] Use entity description attribute for recipient list in user card as an option
[OC-1740]: https://opfab.atlassian.net/browse/OC-1740
=> [OC-1740] Use entity description attribute for recipient list in user card as an option

ui/main/src/app/modules/cards/components/detail/detail.component.ts, ui/main/src/app/modules/feed/components/card-list/card-list.component.ts, ui/main/src/app/modules/navbar/navbar.component.ts, ui/main/src/app/services/app.service.ts, ui/main/src/app/store/effects/card-operation.effects.ts
[OC-1741](https://opfab.atlassian.net/browse/OC-1741) : Remove detail card view when card is deleted
=> [OC-1741] Remove detail card view when card is deleted

ui/main/src/app/modules/admin/components/editmodal/users/edit-user-modal.component.ts
=> [OC-1763] Fix bug in Admin UI when creating new user leaving ip address list empty

config/dev/web-ui-cypress.json, config/dev/web-ui-test.json, config/dev/web-ui.json, config/docker/web-ui-cypress.json, config/docker/web-ui.json
Nothing to mention in release notes.
=> [OC-1751] Remove deprecated property from web-ui examples

src/docs/asciidoc/reference_doc/template_description.adoc, src/test/cypress/cypress/integration/FeedTests.spec.js, src/test/cypress/cypress/support/commands.js, ui/main/src/app/app.component.html, ui/main/src/app/modules/admin/admin.component.html, ui/main/src/app/modules/admin/admin.component.ts, ui/main/src/app/modules/admin/components/editmodal/entities/edit-entity-modal.component.html, ui/main/src/app/modules/admin/components/editmodal/groups/edit-group-modal.component.html, ui/main/src/app/modules/admin/components/editmodal/perimeters/edit-perimeter-modal.component.html, ui/main/src/app/modules/admin/components/editmodal/users/edit-user-modal.component.html, ui/main/src/app/modules/cards/components/detail/detail.component.html, ui/main/src/app/modules/cards/components/detail/detail.component.ts, ui/main/src/app/modules/feed/components/card-list/filters/feed-filter/feed-filter.component.html, ui/main/src/app/modules/feed/components/card-list/filters/feed-sort/feed-sort.component.html, ui/main/src/app/modules/feed/components/card-list/filters/tags-filter/tags-filter.component.html, ui/main/src/app/modules/feed/feed.component.html, ui/main/src/app/modules/monitoring/components/monitoring-filters/monitoring-filters.component.html, ui/main/src/app/modules/navbar/navbar.component.html, ui/main/src/app/modules/settings/components/settings/checkbox-setting/checkbox-setting.component.html, ui/main/src/app/modules/settings/components/settings/list-setting/list-setting.component.html, ui/main/src/app/modules/settings/components/settings/text-setting/text-setting.component.html, ui/main/src/app/modules/settings/components/settings/type-ahead-settings/type-ahead-settings.component.html, ui/main/src/app/modules/share/archives-logging-filters/archives-logging-filters.component.html, ui/main/src/app/modules/share/datetime-filter/datetime-filter.component.html, ui/main/src/app/modules/usercard/usercard.component.html
[OC-1717](https://opfab.atlassian.net/browse/OC-1717) : Issue with usercard process template
=> [OC-1717] Issue with usercard process template

gradle.properties
=> [OC-1779] Reverting breaking swagger-codegen-cli version update

src/docs/asciidoc/community/index.adoc, ui/main/src/app/model/line-of-logging-result.model.ts, ui/main/src/app/services/card.service.ts
Storing moment object in ngrx store send an exception when use moment library later.
(Observed only with ng serve)
BUGS : 
* OC-1776 Bug in dev mode when using moment object in ngrx store
=> [OC-1776] Bug in dev mode when using moment object in ngrx store

src/docs/asciidoc/community/index.adoc, ui/main/src/app/modules/usercard/usercard.component.ts, ui/main/src/app/services/reminder/reminderList.spec.ts, ui/main/src/app/services/reminder/reminderList.ts
BUG : 
* OC-1775 Reminder isn't triggered when "Minutes to remind before task" is 0
=> [OC-1775] Reminder isn't triggered when "Minutes to remind before task" is 0

.travis.yml, src/test/cypress/cypress/fixtures/example.json
To see if it fixes issues with OC-1744.
https://docs.travis-ci.com/user/chrome#selecting-a-chrome-version
=> [OC-1778] Have Travis rely on latest stable chrome version

client/client.gradle, gradle.properties, services/core/build.gradle, services/core/businessconfig/src/main/java/org/opfab/businessconfig/model/MonitoringExportData.java, services/core/businessconfig/src/main/java/org/opfab/businessconfig/model/MonitoringExportFieldData.java, services/core/businessconfig/src/main/java/org/opfab/businessconfig/model/ProcessData.java, services/core/businessconfig/src/main/java/org/opfab/businessconfig/model/ProcessGroupsData.java, services/core/businessconfig/src/main/java/org/opfab/businessconfig/model/UserCardData.java, services/core/cards-consultation/src/main/java/org/opfab/cards/consultation/configuration/json/CardsModule.java, services/core/cards-consultation/src/main/java/org/opfab/cards/consultation/model/ArchivedCardConsultationData.java, services/core/cards-consultation/src/main/java/org/opfab/cards/consultation/model/CardConsultationData.java, services/core/cards-consultation/src/main/java/org/opfab/cards/consultation/model/LightCardConsultationData.java, services/core/cards-publication/src/main/java/org/opfab/cards/publication/model/ArchivedCardPublicationData.java, services/core/cards-publication/src/main/java/org/opfab/cards/publication/model/CardPublicationData.java, services/core/cards-publication/src/main/java/org/opfab/cards/publication/model/LightCardPublicationData.java, services/core/cards-publication/src/test/java/org/opfab/cards/publication/services/CardProcessServiceShould.java, services/core/users/src/main/java/org/opfab/users/controllers/CurrentUserWithPerimetersController.java, services/core/users/src/main/java/org/opfab/users/controllers/EntitiesController.java, services/core/users/src/main/java/org/opfab/users/controllers/GroupsController.java, services/core/users/src/main/java/org/opfab/users/controllers/PerimetersController.java, services/core/users/src/main/java/org/opfab/users/controllers/UsersController.java, services/core/users/src/main/java/org/opfab/users/model/CurrentUserWithPerimetersData.java, services/core/users/src/main/java/org/opfab/users/model/PerimeterData.java, services/core/users/src/main/java/org/opfab/users/utils/EntityCycleDetector.java, services/core/users/src/test/java/org/opfab/users/controllers/EntityCycleDetectorShould.java, src/test/api/karate/buildAndLaunchAll.sh, tools/swagger-spring-generators/src/main/java/org/opfab/generators/OpfabClientGenerator.java, tools/swagger-spring-generators/src/main/java/org/opfab/generators/OpfabSpringGenerator.java
Task : 
OC-1779 Updating swagger-codegen-cli to 2.4.20
=> [OC-1779] Updating swagger-codegen-cli to 2.4.20

ui/main/src/app/modules/monitoring/monitoring.component.html, ui/main/src/app/modules/monitoring/monitoring.component.ts
Fixes also issue OC-1759
Release notes
* OC-1760 : BUG - Monitoring - need to click again on search sometimes
* OC-1759 : Monitoring screen : cards no longer displayed unless you click on search
=> [OC-1760] BUG - Monitoring - need to click again on search sometimes

src/docs/asciidoc/reference_doc/process_definition.adoc, ui/main/src/app/model/processes.model.ts, ui/main/src/app/modules/calendar/calendar.component.ts, ui/main/src/app/modules/monitoring/monitoring.component.ts, ui/main/src/app/services/card.service.ts
OC-1765 : UI does not take into account uiVisibility configuration 
=> [OC-1765] BUG - UI does not take into account uiVisibility configuration

ui/main/src/app/modules/usercard/usercard.component.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json
OC-1762 : When all user entities are not allowed to send card do not show user card form
=> [OC-1762] When all user entities are not allowed to send card do not show user card form

ui/main/src/app/modules/archives/archives.component.html, ui/main/src/app/modules/archives/archives.component.ts, ui/main/src/app/modules/logging/components/logging-filters/logging-filters.component.html, ui/main/src/app/modules/logging/components/logging-filters/logging-filters.component.ts, ui/main/src/app/modules/logging/logging.component.html, ui/main/src/app/modules/monitoring/components/monitoring-filters/monitoring-filters.component.ts, ui/main/src/app/modules/monitoring/monitoring.component.html, ui/main/src/app/modules/share/archives-logging-filters/archives-logging-filters.component.ts, ui/main/src/app/services/processes.service.ts
The sonarcloud review is failed because of duplication code, but this code was already duplicated in develop.
OC-1785 : uiVisibility : do not show not visible processes in filters (monitoring and logging) 
=> [OC-1785] uiVisibility : do not show not visible processes in filters (monitoring and logging) 

services/core/businessconfig/src/main/modeling/swagger.yaml, src/test/resources/bundles/defaultProcess_V1/config.json, ui/main/src/app/model/line-of-logging-result.model.ts, ui/main/src/app/modules/logging/components/logging-table/logging-table.component.html, ui/main/src/app/modules/logging/logging.component.ts, ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.html, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json
Release note :  
Feature : 
* OC-1772: Monitoring and logging screen adjustment
=> [OC-1772] Monitoring  and logging screen adjustement

src/docs/asciidoc/reference_doc/response_cards.adoc
Task : 
OC-1788: Doc adjustment regarding response card
=> [OC-1788] Doc adjustement regarding response card

build.gradle, gradle.properties, services/core/cards-publication/src/test/java/org/opfab/cards/publication/configuration/kafka/ConsumerFactoryAutoConfigurationShould.java
[OC-1792] Fixed the failing Kafka Autoconfiguration Unit test by adding a default for the value deserializer.
[OC-1792]: https://opfab.atlassian.net/browse/OC-1792
=> [OC-1792] kafka unit test fix

ui/main/src/app/services/entities.service.ts
Release notes
In Bugs:
[OC-1790] : Bug - Card not seen when removing sender entity
[OC-1790]: https://opfab.atlassian.net/browse/OC-1790
=> [OC-1790] Bug - Card not seen when removing entity

build.gradle, gradle.properties, services/core/cards-publication/src/main/java/org/opfab/cards/publication/controllers/CustomExceptionHandler.java, services/core/cards-publication/src/test/java/org/opfab/cards/publication/configuration/kafka/ConsumerFactoryAutoConfigurationShould.java, services/services.gradle, src/docs/asciidoc/deployment/configuration/configuration.adoc, src/test/externalApp/externalApp.gradle
Release note :+1: 
Task : 
[OC-1746] Migrate to springboot v2.5.0
[OC-1746]: https://opfab.atlassian.net/browse/OC-1746
=> [OC-1746] Upgrade spring libraries to last version

ui/main/src/app/common/jsontoarray/json-to-array.spec.ts, ui/main/src/app/common/jsontoarray/json-to-array.ts, ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.ts
Release note :
Features : 
OC-1794: Monitoring export: authorize to export more that one array form json
=> [OC-1794] Monitoring export: allow exporting more that one array from json

ui/main/src/app/modules/admin/components/editmodal/entities/edit-entity-modal.component.html, ui/main/src/app/modules/admin/components/editmodal/groups/edit-group-modal.component.html, ui/main/src/app/modules/admin/components/editmodal/users/edit-user-modal.component.html, ui/main/src/app/modules/monitoring/components/monitoring-filters/monitoring-filters.component.html, ui/main/src/app/modules/share/archives-logging-filters/archives-logging-filters.component.html, ui/main/src/app/modules/share/multi-filter/multi-filter.component.ts, ui/main/src/app/modules/usercard/usercard.component.html
The error occurs with every Entity name matching an i18n prefix ('admin', ‘feed’, ‘menu', ..)
Release notes:
[OC-1786]  : Bug when using entity with name matching an i18n prefix
[OC-1786]: https://opfab.atlassian.net/browse/OC-1786
=> [OC-1786] Bug when using entity with name admin

services/core/cards-publication/src/main/java/org/opfab/cards/publication/controllers/CardController.java, services/core/cards-publication/src/main/java/org/opfab/cards/publication/services/CardProcessingService.java, services/core/cards-publication/src/test/java/org/opfab/cards/publication/services/CardProcessServiceShould.java
Nothing in release note (add-on for OC-1734)
=> [OC-1734] Bug when sending/deleting card with checkAuthenticationForCardSending=false

ui/main/src/app/modules/feed/components/card-list/filters/filters.component.html, ui/main/src/app/modules/feed/components/card-list/filters/filters.component.scss, ui/main/src/app/modules/feed/components/card-list/filters/filters.component.ts, ui/main/src/app/services/lightcards.service.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json
Release note: 
Features : 
[OC-1742] Add a spinner in feed when opfab is loading cards in background
[OC-1742]: https://opfab.atlassian.net/browse/OC-1742
=> [OC-1742] Add a spinner in feed when opfab is loading cards in background

services/core/cards-publication/src/main/java/org/opfab/cards/publication/services/CardProcessingService.java
Release note  : 
Bug : 
OC-1804: Do not round publish date to the second
=> [OC-1804] Do not round publish date to the second

src/test/cypress/cypress/integration/Acknowledgment.spec.js, src/test/resources/cards/cypress/ack/message5.json, src/test/resources/cards/cypress/ack/message6.json, ui/main/src/app/modules/cards/components/detail/detail.component.ts
Release notes
[OC-1749] : Take into account lttd when ack set to OnlyWhenResponseDisabledForUser
[OC-1749]: https://opfab.atlassian.net/browse/OC-1749
=> [OC-1749] Take into account lttd when ack set to OnlyWhenResponseDisabledForUser

ui/main/src/app/modules/settings/components/settings/text-setting/text-setting.component.html
OC-1800 : Error in style when showing field description in settings tab
=> [OC-1800] Error in style when showing field description in settings tab

services/core/cards-publication/src/main/java/org/opfab/cards/publication/services/CardRepositoryService.java
Release notes
[OC-1757] : Deleting cards by endDateBefore  using api does not removes cards from the feed
[OC-1757]: https://opfab.atlassian.net/browse/OC-1757
=> [OC-1757] Deleting cards by endDateBefore  using api does not removes cards from the feed

src/docs/asciidoc/reference_doc/process_definition.adoc, src/docs/asciidoc/reference_doc/response_cards.adoc
Tasks : 
OC-1813 Move documentation for "showDetailCardHeader" config value
[OC-1813]: https://opfab.atlassian.net/browse/OC-1813
=> [OC-1813] Move documentation for "showDetailCardHeader" config value

src/docs/asciidoc/community/index.adoc
=> #1276 Adding new slack to communication channels

src/test/cypress/cypress/integration/Archives.spec.js, src/test/cypress/cypress/support/commands.js, src/test/resources/deleteAllArchivedCards.sh, ui/main/src/app/modules/archives/archives.component.html
OC-1808 : Add cypress tests for archives screen
=> [OC-1808] Add cypress for archive screen

services/core/businessconfig/src/main/docker/Dockerfile, services/core/cards-consultation/src/main/docker/Dockerfile, services/core/cards-publication/src/main/docker/Dockerfile, services/core/users/src/main/docker/Dockerfile
Signed-off-by: Gerben Danen <gerben.danen@alliander.com>
resolves #1303
=> Fix #1303 create external-config folder in Dockerfile.

CONTRIBUTING.adoc
=> Fix #1300 Adding contributing file linking back to doc

src/test/cypress/cypress/integration/1-RealTimeUsers.spec.js, ui/main/src/app/modules/realtimeusers/realtimeusers.component.html
=> [OC-1744] Real time users screen : Adding a cypress test

ui/main/src/app/modules/admin/components/table/admin-table.directive.html, ui/main/src/app/modules/admin/components/table/admin-table.directive.ts, ui/main/src/app/modules/archives/archives.component.html, ui/main/src/app/modules/archives/archives.component.scss, ui/main/src/app/modules/logging/logging.component.html, ui/main/src/app/modules/logging/logging.component.scss, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json, ui/main/src/scss/styles.scss
Release notes
#1265 : Admin table styling
=> #1265 Admin table styling

ui/main/src/assets/js/templateGateway.js
Release note :
Bug: 
#1384 Clean templateGateway when loading card from archives or usercard
=> Fix #1384 Clean templateGateway when loading card from archives or usercard

sonar-project.properties
Task : 
#1396 Add common library (/tools) analysis in SonarCloud
=> Fix #1396 Add common library (/tools) analysis in SonarCloud

src/docs/asciidoc/reference_doc/template_description.adoc
=> Fix #1404 Broken link in doc relative to charts

src/docs/asciidoc/resources/index.adoc, src/docs/asciidoc/resources/jar_publication.adoc
No need to mention it in release notes
=> Fix #1315 Adding doc on initial publication setup

src/docs/asciidoc/reference_doc/response_cards.adoc, src/docs/asciidoc/reference_doc/user_cards.adoc, src/test/resources/bundles/userCardExamples2/template/en/usercard_message.handlebars, src/test/resources/bundles/userCardExamples2/template/fr/usercard_message.handlebars, ui/main/src/app/modules/usercard/usercard.component.ts
#1275 : Set externalRecipients in user card
=> Fix #1275 Set externalRecipients in user card

services/core/cards-consultation/src/main/java/org/opfab/cards/consultation/services/CardSubscription.java, services/core/cards-consultation/src/main/java/org/opfab/cards/consultation/services/CardSubscriptionService.java, tools/generic/utilities/build.gradle, tools/generic/utilities/src/main/java/org/opfab/utilities/AmqpUtils.java, tools/spring/spring-oauth2-utilities/src/main/java/org/opfab/springtools/configuration/oauth/UpdateUserListener.java, tools/spring/spring-oauth2-utilities/src/main/java/org/opfab/springtools/configuration/oauth/UpdateUserListenerConfiguration.java
Fix #1387
Release notes:
#1387 : Card publication service does not start if rabbit goes up too late 
=> #1387 Card publication service does not start if rabbit goes up too late 

ui/main/src/app/modules/monitoring/components/monitoring-filters/monitoring-filters.component.html, ui/main/src/app/modules/monitoring/components/monitoring-filters/monitoring-filters.component.ts, ui/main/src/app/modules/monitoring/monitoring.component.html, ui/main/src/app/modules/monitoring/monitoring.component.ts, ui/main/src/app/modules/share/timeline-buttons/timeline-buttons.component.ts, ui/main/src/app/services/filter.service.ts, ui/main/src/app/services/lightcards.service.ts, ui/main/src/app/store/actions/feed.actions.ts, ui/main/src/app/store/effects/feed-filters.effects.ts
Fix #1256 
Release notes
#1256 : Clarify sound when switching from feed to monitoring
=> #1256 Clarify sound when switching from feed to monitoring

ADOPTERS.adoc
=> Initializing ADOPTERS file (#1411)

src/docs/asciidoc/reference_doc/template_description.adoc, ui/main/src/app/modules/cards/services/handlebars.service.spec.ts, ui/main/src/app/modules/cards/services/handlebars.service.ts
[#1454] dateFormat helper doesn't work with strings (returns undefined) + new helper objectContainsKey
=> [#1454] dateFormat helper doesn't work with strings (returns undefined) + new helper objectContainsKey

ui/main/src/app/modules/cards/services/handlebars.service.spec.ts
=> Fix "compile dateFormat now" test (failing at night on CI) (#1427)

ui/main/src/app/modules/admin/components/editmodal/perimeters/edit-perimeter-modal.component.ts, ui/main/src/app/modules/admin/components/table/admin-table.directive.ts, ui/main/src/app/modules/businessconfigparty/iframedisplay.component.ts, ui/main/src/app/modules/cards/components/card-details/card-details.component.ts, ui/main/src/app/modules/feedconfiguration/feedconfiguration.component.ts, ui/main/src/app/modules/usercard/usercard.component.ts, ui/main/src/app/services/authentication/authentication.service.ts, ui/main/src/app/services/card.service.ts, ui/main/src/app/services/config.service.ts, ui/main/src/app/services/entities.service.ts, ui/main/src/app/services/error-service.ts, ui/main/src/app/services/groups.service.ts, ui/main/src/app/services/i18n.service.ts, ui/main/src/app/services/perimeters.service.ts, ui/main/src/app/services/user.service.ts, ui/main/src/app/store/effects/authentication.effects.spec.ts
Fixes #1466 
I had to fix this type of code smells in recent PRs so I figured I'd fix them all while it was still fresh in my mind.
=> Fixing code smells about deprecated TS methods (#1466)

src/docs/asciidoc/community/index.adoc, src/docs/asciidoc/community/workflow.adoc
=> Updating workflow doc to reflect move to GitHub issues (#1281)

COMMITTERS.adoc
Fixes #1478 
Nothing in release notes. I'm cancelling the build as it is documentation only.
=> Adding committers file with current reviewers (#1478)

src/test/resources/bundles/defaultProcess_V1/template/en/chart-line.handlebars, src/test/resources/bundles/defaultProcess_V1/template/en/chart.handlebars, src/test/resources/bundles/defaultProcess_V1/template/fr/chart-line.handlebars, src/test/resources/bundles/defaultProcess_V1/template/fr/chart.handlebars
Release note 
Bug 
Correct responsive problem with cards examples containing charts (#1479)
=> Correct responsive problem with cards examples containing charts (#1479)

src/docs/asciidoc/reference_doc/response_cards.adoc, src/test/resources/bundles/userCardExamples2/template/en/question.handlebars, src/test/resources/bundles/userCardExamples2/template/fr/question.handlebars, ui/main/src/app/modules/cards/components/detail/detail.component.ts, ui/main/src/assets/js/templateGateway.js
Features : 
Add a method for template to get the list of entities allowed to respond (#1274)
=> Add a method for template to get the list of entities allowed to respond (#1274)

services/core/users/src/main/java/org/opfab/users/configuration/oauth2/OAuth2UsersConfiguration.java
Fixes #1420 
In my opinion, not worth mentioning in the release notes.
=> Fixing Sonar Bug about possible NPE (#1420)

services/core/businessconfig/src/main/java/org/opfab/businessconfig/model/ResponseData.java, services/core/businessconfig/src/main/modeling/swagger.yaml, services/core/businessconfig/src/test/data/bundles/second/2.0/config.json, services/core/businessconfig/src/test/data/bundles/second/2.1/config.json, src/docs/asciidoc/reference_doc/response_cards.adoc, src/test/api/karate/businessconfig/getResponseBusinessconfig.feature, src/test/api/karate/businessconfig/resources/bundle_test_action/config.json, src/test/resources/bundles/defaultProcess_V1/config.json, ui/main/src/app/model/processes.model.ts, ui/main/src/app/modules/cards/components/detail/detail.component.html, ui/main/src/app/modules/cards/components/detail/detail.component.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json
in release note :  
Tasks:
Remove unused btnText field (#1501)
=> Remove unused btnText field (#1501)

ui/main/src/app/modules/usercard/usercard.component.html, ui/main/src/app/modules/usercard/usercard.component.ts
Prevent setting end date before start date in user card (#1453)
=> Fix #1453 Prevent setting end date before start date in user card

config/dev/common-dev.yml, config/docker/common-docker.yml, src/docs/asciidoc/deployment/configuration/security_configuration.adoc
In release not in task : 
#1348 Remove unused operatorfabric.security.* config in common.yml
=> Remove unused operatorfabric.security.* config in common.yml #1348

ui/main/src/app/modules/admin/admin.component.scss, ui/main/src/app/modules/admin/components/table/admin-table.directive.html, ui/main/src/scss/styles.scss
Release note in bugs : 
#1519 Add margin for table in admin screens
=> Add margin for table in admin screens (#1519)

ui/main/src/app/services/acknowledge.service.spec.ts, ui/main/src/app/services/acknowledge.service.ts, ui/main/src/app/services/action.service.ts, ui/main/src/tests/helpers.ts
Bug : 
#1504 Correct conditions for allowing acknowledgment
=> Correct conditions for allowing acknowledgment (#1504)

services/core/cards-consultation/src/main/java/org/opfab/cards/consultation/configuration/mongo/LightCardReadConverter.java, services/core/cards-consultation/src/main/java/org/opfab/cards/consultation/repositories/ArchivedCardCustomRepositoryImpl.java, src/test/cypress/cypress/integration/Archives.spec.js, ui/main/src/app/modules/archives/archives.component.html, ui/main/src/app/modules/archives/archives.component.scss, ui/main/src/app/modules/archives/archives.component.ts, ui/main/src/assets/images/icons/minus.svg, ui/main/src/assets/images/icons/plus.svg
Archives UI: see history of a card when clicking on + (#1266)
=> Fix #1266 : Archives UI: see history of a card when clicking on +

ui/main/src/app/modules/cards/components/detail/detail.component.html, ui/main/src/app/modules/cards/components/detail/detail.component.ts, ui/main/src/app/services/action.service.ts
=> Small refactoring for card detail 

ui/main/package-lock.json, ui/main/package.json, ui/main/src/app/modules/cards/services/handlebars.service.spec.ts
Release note , add to dependency update
=> upgrade to angular-oauth2-oidc 12.0.0

build.gradle, client/businessconfig/build.gradle, client/businessconfig/gradle.properties, client/cards/build.gradle, client/cards/gradle.properties, client/client.gradle, client/users/build.gradle, client/users/gradle.properties
Fix #1530
Nothing in release notes as it is only for readability purposes.
=> Fixing name in client jars poms (#1530)

ui/main/src/app/modules/cards/cards.module.ts, ui/main/src/app/modules/cards/components/card-details/card-details.component.ts, ui/main/src/app/modules/cards/components/detail/detail.component.html, ui/main/src/app/modules/cards/components/detail/detail.component.scss, ui/main/src/app/modules/cards/components/detail/detail.component.ts, ui/main/src/app/services/acknowledge.service.ts, ui/main/src/app/services/user-permissions-.service.ts, ui/main/src/app/store/effects/custom-router.effects.ts, ui/main/src/assets/js/templateGateway.js
=> Code cleaning and refactoring

.travis.yml, client/client.gradle, services/core/build.gradle, services/services.gradle, src/docs/asciidoc/dev_env/gradle.adoc, src/docs/asciidoc/dev_env/requirements.adoc
=> Restore copyDependency to fix Sonar code smells (#1556)

client/client.gradle
=> Fixing client:cards-client-data:sourcesJar duplicate error (#1561)

tools/spring/aop-process/build.gradle
=> Fix compilation warnings in :tools:spring:aop-process (#1554)

build.gradle, src/docs/asciidoc/resources/jar_publication.adoc
=> Fix doc generation (#1573) ci_documentation

.travis.yml
=> Cancel doc upload if generation failed (#1575)

src/test/cypress/cypress/integration/StateTypeTests.spec.js, src/test/resources/cards/cypress/state_types/state_type8.json, src/test/resources/cards/cypress/state_types/state_type9.json, ui/main/src/app/modules/cards/components/detail/detail.component.html, ui/main/src/app/modules/cards/components/detail/detail.component.ts, ui/main/src/app/modules/share/countdown/countdown.component.html, ui/main/src/app/modules/share/countdown/countdown.component.scss, ui/main/src/app/modules/share/countdown/countdown.component.ts, ui/main/src/app/modules/share/light-card/light-card.component.html, ui/main/src/app/modules/share/light-card/light-card.component.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json
Fixes #1431
Release notes:
In features section:
Modify current UI behavior when lttd is reached (#1431)
=> #1431 Modify current UI behavior when lttd is reached

src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc, ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.html, ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.ts, ui/main/src/app/modules/monitoring/monitoring.component.html, ui/main/src/app/modules/monitoring/monitoring.component.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json
Fix #1407
Release notes
Limit the number of lines visible on Monitoring (#1407)
=> Limit the number of lines visible on Monitoring (#1407)

ui/main/src/app/modules/admin/components/editmodal/entities/edit-entity-modal.component.ts, ui/main/src/app/modules/admin/components/editmodal/groups/edit-group-modal.component.ts, ui/main/src/app/modules/admin/components/editmodal/perimeters/edit-perimeter-modal.component.html, ui/main/src/app/modules/admin/components/editmodal/users/edit-user-modal.component.ts, ui/main/src/app/modules/share/single-filter/single-filter.component.html, ui/main/src/app/modules/share/single-filter/single-filter.component.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json
Fix #1456 
Release notes:
Admin UI: translate placeholder for multi-select component . Add placeholder  for single-filter component (#1456)
=> Admin UI: translate placeholder for multi-select (#1456)

ui/main/src/app/modules/admin/components/editmodal/entities/edit-entity-modal.component.ts, ui/main/src/app/modules/admin/components/editmodal/groups/edit-group-modal.component.ts, ui/main/src/app/modules/admin/components/editmodal/users/edit-user-modal.component.ts, ui/main/src/app/modules/admin/components/table/admin-table.directive.ts
Fix #1518
Release notes
Double the width of popups for admin interface (#1518)
=> Double the width of popups for admin interface (#1518)

ui/main/src/app/modules/share/timeline-buttons/timeline-buttons.component.ts, ui/main/src/app/store/reducers/light-card.reducer.spec.ts, ui/main/src/app/store/reducers/light-card.reducer.ts, ui/main/src/app/store/states/feed.state.ts
Fix #1441 
Release notes
Business Period selection for realtime screens - synchronization is incoherent (#1441)
=> Business Period synchronization for realtime screens (#1441)

services/core/businessconfig/src/main/java/org/opfab/businessconfig/model/ProcessData.java, services/core/cards-consultation/src/main/java/org/opfab/cards/consultation/configuration/mongo/LightCardReadConverter.java, services/core/cards-publication/src/main/java/org/opfab/cards/publication/configuration/mongo/RecurrenceWriterConverter.java, services/core/users/src/main/java/org/opfab/users/controllers/GroupsController.java, services/core/users/src/main/java/org/opfab/users/model/CurrentUserWithPerimetersData.java
=> Sonarcloud warnings : correct "Remove this unnecessary cast" (Fix #1624)

services/core/cards-consultation/src/main/java/org/opfab/cards/consultation/repositories/ArchivedCardCustomRepositoryImpl.java, services/core/cards-publication/src/main/java/org/opfab/cards/publication/services/CardNotificationService.java, services/core/cards-publication/src/main/java/org/opfab/cards/publication/services/clients/impl/ExternalAppClientImpl.java
=> Sonarcloud warnings : correct "Replace this lambda with a method reference" (Fix #1620)

services/core/cards-consultation/src/main/java/org/opfab/cards/consultation/configuration/webflux/ConnectionRoutesConfig.java, services/core/cards-publication/src/main/java/org/opfab/cards/publication/configuration/json/CardsModule.java, services/core/cards-publication/src/main/java/org/opfab/cards/publication/controllers/CardController.java, services/core/users/src/main/java/org/opfab/users/configuration/DataInitComponent.java, services/core/users/src/main/java/org/opfab/users/configuration/json/UsersModule.java, services/core/users/src/main/java/org/opfab/users/configuration/users/UsersProperties.java, services/core/users/src/main/java/org/opfab/users/controllers/GroupsController.java
=> Sonarcloud warnings : correct "remove this unused import" (Fix #1618)

services/core/cards-publication/src/main/java/org/opfab/cards/publication/controllers/CardController.java, services/core/cards-publication/src/main/java/org/opfab/cards/publication/services/CardProcessingService.java
=> Sonarcloud warnings : correct "use primitive boolean expression" (Fix #1616)

config/cypress/generateUIConfigForCypress.sh, config/docker/ui-config/web-ui.json, src/test/cypress/cypress/integration/Logout.spec.js, src/test/resources/uiConfig/security-PASSWORD-flow.json
Fixes #1529 
In bug section: Fixing logout and adding test (#1529)
=> Fixing logout and adding test (#1529)

ui/main/src/app/modules/cards/components/detail/detail.component.html, ui/main/src/app/modules/cards/components/detail/detail.component.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json
Fix #1444 
Release notes:
In Featues section:
Card detail: add last response received information (#1444)
=> Card detail: add last response received information (#1444)

ui/main/package-lock.json, ui/main/package.json, ui/main/src/app/modules/admin/admin.module.ts
=> Remove unused dependency ngx-bootstrap (#1629)

ui/main/src/app/services/lightcards.service.ts
in release note : 
Bug:
On startup of the application, sometimes loading in progress appears when no cards are available for user (#1605)
=> Improve "loading in progress" detection and solve bug #1605

ui/main/src/app/modules/archives/archives.component.ts
No release note as it is an optimization for #1266
=>  Archives screen optimization (#1613)

ui/main/src/app/modules/cards/components/card-details/card-details.component.ts, ui/main/src/app/modules/cards/components/detail/detail.component.ts, ui/main/src/app/modules/share/card-detail/card-detail.component.ts
Bugs : 
Archive card detail not shown when using userContext.entities in template (#1630)
=> Bug : Archive card detail not shown when using userContext.entities in template (#1630)

src/test/cypress/cypress/integration/FeedNotificationConfiguration.spec.js, ui/main/src/app/modules/feedconfiguration/feedconfiguration.component.html, ui/main/src/app/modules/feedconfiguration/feedconfiguration.component.scss
release note : 
Task : 
Improve configuration notification screen display with lot of processes (#1628)
=> Improve configuration notification screen display with lot of processes (#1628)

src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc, ui/main/src/app/modules/archives/archives.component.html, ui/main/src/app/modules/archives/archives.component.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json
Fix #1615 
Release notes
Archive screen : limit the number of update visible per card (#1615)
=> Archive screen : limit the number of update visible per card (#1615)

ui/main/src/app/modules/monitoring/monitoring.component.ts
Feature:
Sort monitoring results by publish date (#1661)
=> Sort monitoring results by publish date (#1661)

services/core/cards-publication/src/main/java/org/opfab/cards/publication/controllers/CardController.java, services/core/cards-publication/src/main/java/org/opfab/cards/publication/model/CardCreationReportData.java, services/core/cards-publication/src/main/modeling/swagger.yaml, src/test/api/karate/cards/cards.feature, src/test/clientApp/src/main/java/org/opfab/client/ClientApplication.java, src/test/clientApp/src/main/java/org/opfab/client/cards/CardClient.java
Fix #1639 
Release notes
In Featues section:
Add a response when creating card with API (#1639)
=> Add a response when creating card with API (#1639)

config/keycloak/export/dev-users-0.json, services/core/users/src/main/java/org/opfab/users/configuration/oauth2/WebSecurityConfiguration.java, services/core/users/src/main/java/org/opfab/users/controllers/UsersController.java, services/core/users/src/main/modeling/swagger.yaml, src/test/api/karate/userTests.txt, src/test/api/karate/users/synchronizeWithToken.feature, ui/main/src/app/services/user.service.ts, ui/main/src/app/store/actions/user.actions.ts, ui/main/src/app/store/effects/user.effects.ts, ui/main/src/app/store/reducers/user.reducer.ts
Fix #1270 
Release notes
#1270 Synchronize JWT token data with database
=> #1270 Synchronize JWT data with database

config/dev/users-dev.yml, config/docker/users-docker.yml, src/test/cypress/cypress/integration/CardDetail.spec.js, src/test/cypress/cypress/integration/FeedNotificationConfiguration.spec.js, src/test/resources/bundles/cypress/config.json, src/test/resources/bundles/cypress/i18n/en.json, src/test/resources/bundles/cypress/i18n/fr.json, src/test/resources/bundles/cypress/template/en/kitchenSink.handlebars, src/test/resources/bundles/cypress/template/fr/kitchenSink.handlebars, src/test/resources/cards/cypress/cardDetail/cardDetail.json, src/test/resources/cards/cypress/cardDetail/cardDetailResponseNotPossible.json, src/test/resources/cards/cypress/cardDetail/cardDetailResponseNotRequired.json, src/test/resources/perimeters/cypress.json, ui/main/src/app/modules/cards/components/detail/detail.component.html
Tasks : 
#1686 Add cypress tests for card detail rendering
=> Add cypress tests for card detail rendering (#1686)

ui/main/src/app/modules/cards/components/detail/detail.component.ts
Fix #1700 
Release notes
#1700 Fix lttd expired message in card detail
=> Fix lttd expired message in card detail (#1700)

src/docs/asciidoc/reference_doc/template_description.adoc, src/test/cypress/cypress/integration/StateTypeTests.spec.js, src/test/resources/bundles/defaultProcess_V1/template/en/question.handlebars, src/test/resources/bundles/defaultProcess_V1/template/fr/question.handlebars, ui/main/src/app/modules/usercard/usercard.component.html, ui/main/src/app/services/global-style.service.ts, ui/main/src/scss/styles.scss
Add opfab style for color warning, alert and success (#1445)
=> Add opfab style for color warning, alert and success (#1445)

ui/main/src/app/services/lightcards.service.ts
In release note
Task :
Optimize light cards loading when browser is slow
=> Optimize light cards loading when browser is slow

src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc, ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.html, ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.scss, ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.ts, ui/main/src/app/modules/monitoring/monitoring.component.html, ui/main/src/app/modules/monitoring/monitoring.component.ts, ui/main/src/app/modules/monitoring/monitoring.module.ts, ui/main/src/scss/styles.scss
Add advance table for monitoring screen (#1267)
=>  Add advance table for monitoring screen (Fix #1267) 

src/test/resources/bundles/defaultProcess_V1/template/en/chart-line.handlebars, src/test/resources/bundles/defaultProcess_V1/template/en/chart.handlebars, src/test/resources/bundles/defaultProcess_V1/template/fr/chart-line.handlebars, src/test/resources/bundles/defaultProcess_V1/template/fr/chart.handlebars
#1680 Charts not well display in archives screen
=> Charts not well display in archives screen (Fix #1680)

src/test/cypress/cypress/integration/FeedNotificationConfiguration.spec.js
=> Add cypress test for feature 'Allow feed notifications to be configured for a whole process' (Fix #1611)

services/core/users/src/main/java/org/opfab/users/controllers/GroupsController.java, src/test/api/karate/users/groups/createGroups.feature, ui/main/src/app/modules/admin/components/editmodal/groups/edit-group-modal.component.ts
Fix #1715 
Release notes
On Bugs section:
#1715 : Check perimeters existence on group creation or update 
=> Check perimeters existence on group creation or update (#1715)

ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.html, ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json
Fix #1682 
Release notes
#1682: Add an "export in progress" popup when export data from monitoring screen 
=> Add an "export in progress" popup when export data from monitoring screen (#1682)

build.gradle, client/client.gradle, services/core/build.gradle, services/services.gradle, src/test/api/karate/karateTests.gradle, src/test/externalApp/externalApp.gradle, tools/tools.gradle, ui/main/build.gradle, ui/ui.gradle
Fixes #1545 
See https://scans.gradle.com/s/theai67uuymdo/deprecations?expanded=WyI0Il0&expanded-stacktrace=WyI2Il0
Only remaining issue is inside the Swagger plugin code so we will wait for them to fix it.
=> Fix deprecations and optimize build (#1545)

src/test/resources/cards/defaultProcess/contingenciesBig.json, ui/main/src/app/app.component.html, ui/main/src/app/app.component.scss, ui/main/src/app/modules/cards/components/card-details/card-details.component.html, ui/main/src/app/modules/cards/components/card-details/card-details.component.scss, ui/main/src/app/modules/cards/components/card-details/card-details.component.ts, ui/main/src/app/modules/feed/components/card-list/filters/filters.component.html, ui/main/src/app/modules/feed/components/card-list/filters/filters.component.scss, ui/main/src/app/modules/monitoring/monitoring.component.html, ui/main/src/app/modules/monitoring/monitoring.component.scss, ui/main/src/app/modules/usercard/usercard.component.html, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json, ui/main/src/scss/styles.scss
Release note :
Feature : 
#1737 : Add spinner when card loading take more than one second
=> Add spinner when card loading take more than one second (#1737)

ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.ts
#1743 Monitoring screen : apply the sort to the export file
=> Monitoring screen : apply the sort to the export file (#1743)

services/core/cards-consultation/src/main/java/org/opfab/cards/consultation/model/ArchivedCardConsultationData.java, services/core/cards-consultation/src/main/java/org/opfab/cards/consultation/model/CardConsultationData.java, services/core/cards-publication/src/main/java/org/opfab/cards/publication/model/ArchivedCardPublicationData.java, services/core/cards-publication/src/main/java/org/opfab/cards/publication/model/CardPublicationData.java, services/core/cards-publication/src/main/java/org/opfab/cards/publication/services/CardProcessingService.java, services/core/cards-publication/src/main/modeling/swagger.yaml, services/core/cards-publication/src/test/java/org/opfab/cards/publication/services/CardProcessServiceShould.java, src/docs/asciidoc/reference_doc/card_structure.adoc, src/test/api/karate/cardTests.txt, src/test/api/karate/cards/postCardWithToNotify.feature
#1774 Add option to store card only in archives DB
=> Add option to store card only in archives DB (#1774)

src/docs/asciidoc/getting_started/index.adoc
=> Update Getting Started for version 2.9.0.RELEASE (#1560)

ui/main/src/app/services/processes.service.ts
Fix #1758 
Release notes
#1758 Load and cache all processes at startup (#1758)
=> Load and cache all processes at startup (#1758)

ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.ts
Nothing in release note as the bug was not present in previous release
=> Monitoring screen : fix row height to avoid display flickering (#1802)

config/docker/ui-config/web-ui.json, src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc, ui/main/src/app/modules/navbar/info/info.component.html, ui/main/src/app/modules/navbar/info/info.component.scss, ui/main/src/app/modules/navbar/info/info.component.ts
in release note : 
Feature : 
#1807  Add entity name in top-right of the screen #1807
=>  Add entity name in top-right of the screen (#1807)

services/core/cards-consultation/src/main/java/org/opfab/cards/consultation/repositories/ArchivedCardCustomRepositoryImpl.java, services/core/cards-publication/src/main/modeling/swagger.yaml, src/test/resources/cards/defaultProcess/contingenciesBig.json
Bug : 
#1813 Optimization to avoid OutOfMemory or mongoDB exception using archive screen
=> Optimization to avoid OutOfMemory or mongoDB exception using archive screen (#1813) 

services/core/businessconfig/src/main/docker/volume/businessconfig-storage/TEST/1/i18n.json, services/core/businessconfig/src/main/docker/volume/businessconfig-storage/first/v1/i18n.json, services/core/businessconfig/src/main/java/org/opfab/businessconfig/controllers/BusinessconfigController.java, services/core/businessconfig/src/main/java/org/opfab/businessconfig/model/ResourceTypeEnum.java, services/core/businessconfig/src/main/modeling/swagger.yaml, services/core/businessconfig/src/test/data/bundles/second/2.0/i18n.json, services/core/businessconfig/src/test/data/bundles/second/2.1/i18n.json, services/core/businessconfig/src/test/docker/volume/businessconfig-storage/deletetest/2.1/i18n.json, services/core/businessconfig/src/test/docker/volume/businessconfig-storage/first/0.1/i18n.json, services/core/businessconfig/src/test/docker/volume/businessconfig-storage/first/0.5/i18n.json, services/core/businessconfig/src/test/docker/volume/businessconfig-storage/first/v1/i18n.json, services/core/businessconfig/src/test/java/org/opfab/businessconfig/controllers/GivenAdminUserBusinessconfigControllerShould.java, services/core/businessconfig/src/test/java/org/opfab/businessconfig/controllers/GivenNonAdminUserBusinessconfigControllerShould.java, services/core/businessconfig/src/test/java/org/opfab/businessconfig/services/ProcessesServiceShould.java, src/docs/asciidoc/reference_doc/process_definition.adoc, src/docs/asciidoc/resources/migration_guide_to_3.0.adoc, src/test/api/karate/businessconfig/getI18n.feature, src/test/api/karate/businessconfig/resources/bundle_api_test/i18n.json, src/test/api/karate/businessconfig/resources/bundle_api_test_apogee/i18n.json, src/test/api/karate/businessconfig/resources/bundle_api_test_v2/i18n.json, src/test/api/karate/businessconfig/resources/bundle_test_action/i18n.json, src/test/api/karate/businessconfig/resources/packageBundles.sh, src/test/resources/bundles/cypress/i18n.json, src/test/resources/bundles/defaultProcess_V0.1/i18n.json, src/test/resources/bundles/defaultProcess_V1/i18n.json, src/test/resources/bundles/gridCooperation/i18n.json, src/test/resources/bundles/userCardExamples/i18n.json, src/test/resources/bundles/userCardExamples2/i18n.json, src/test/resources/bundles/userCardExamples3/i18n.json
Fix #1787 
Release notes
In Feaures ection:
#1787 Add translation for summary and title cards in i18n.json
=> Add translation for summary and title cards in i18n.json (#1787)

config/docker/ui-config/web-ui.json, services/core/users/src/main/java/org/opfab/users/model/UserSettingsData.java, services/core/users/src/main/modeling/swagger.yaml, services/core/users/src/test/java/org/opfab/users/model/UserSettingsDataShould.java, src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc, src/docs/asciidoc/dev_env/requirements.adoc, ui/main/src/app/app.component.ts, ui/main/src/app/modules/settings/components/settings/checkbox-setting/checkbox-setting.component.html, ui/main/src/app/modules/settings/components/settings/checkbox-setting/checkbox-setting.component.scss, ui/main/src/app/modules/settings/components/settings/list-setting/list-setting.component.html, ui/main/src/app/modules/settings/components/settings/settings.component.html, ui/main/src/app/modules/settings/components/settings/settings.component.scss, ui/main/src/app/services/sound-notification.service.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json
Fixes #1808 
In release notes:
#1808: Replay sound notifications until user interacts with app
+
See documentation (//TODO Add link) for the relevant configuration properties.
=> Replay sound notifications until user interacts with app (#1808)

config/docker/ui-config/web-ui.json, services/core/users/src/main/java/org/opfab/users/model/UserSettingsData.java, services/core/users/src/main/modeling/swagger.yaml, services/core/users/src/test/java/org/opfab/users/model/UserSettingsDataShould.java, src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc, src/docs/asciidoc/dev_env/requirements.adoc, ui/main/src/app/app.component.ts, ui/main/src/app/modules/settings/components/settings/checkbox-setting/checkbox-setting.component.html, ui/main/src/app/modules/settings/components/settings/checkbox-setting/checkbox-setting.component.scss, ui/main/src/app/modules/settings/components/settings/list-setting/list-setting.component.html, ui/main/src/app/modules/settings/components/settings/settings.component.html, ui/main/src/app/modules/settings/components/settings/settings.component.scss, ui/main/src/app/services/sound-notification.service.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json
Fixes #1808
In release notes:
#1808: Replay sound notifications until user interacts with app
+
See documentation (//TODO Add link) for the relevant configuration properties.
(making things right after #1815 was reverted)
=> Replay sounds until user interacts with app (#1808)

config/docker/ui-config/web-ui.json, src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc, src/docs/asciidoc/resources/migration_guide_to_3.0.adoc, ui/main/src/app/modules/settings/components/settings/settings.component.ts
#1286 : web-ui.json : rename parameters settings.infos.* in settings.infos.hide.*
=> web-ui.json : rename parameters settings.infos.* in settings.infos.hide.* (#1286)

services/core/cards-consultation/src/main/java/org/opfab/cards/consultation/model/LightCardConsultationData.java, ui/main/src/app/model/line-of-monitoring-result.model.ts, ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.ts, ui/main/src/app/modules/monitoring/monitoring.component.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json
Fix #1915 
Release notes
#1915 : Add "Emitter" column in the monitoring screen 
=> Add "Emitter" column in the monitoring screen (#1915)

src/docs/asciidoc/resources/index.adoc, src/docs/asciidoc/resources/migration_guide_to_3.0.adoc
=> New version of migration documentation for release 3.0.0 (#1999)

ui/main/src/app/modules/usercard/usercard.component.ts
Fix #2004
Release notes 
#2004 : Usercard restrict recipient list persist when changing process/state
=> Usercard restrict recipient list persist when changing process/state

src/docs/asciidoc/CICD/release_process.adoc
=> Adding info about version list in release process doc

config/docker/ui-config/web-ui.json, src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc, ui/main/src/app/modules/archives/archives.component.html, ui/main/src/app/modules/archives/archives.component.ts, ui/main/src/app/modules/feedconfiguration/feedconfiguration.component.ts, ui/main/src/app/modules/logging/logging.component.html, ui/main/src/app/modules/logging/logging.component.ts, ui/main/src/app/modules/monitoring/components/monitoring-filters/monitoring-filters.component.ts, ui/main/src/app/modules/monitoring/monitoring.component.html, ui/main/src/app/modules/monitoring/monitoring.component.ts, ui/main/src/app/modules/share/archives-logging-filters/archives-logging-filters.component.html, ui/main/src/app/modules/share/archives-logging-filters/archives-logging-filters.component.ts, ui/main/src/app/services/process-states-dropdown-list.service.ts, ui/main/src/app/services/processes.service.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json
#1908 : Use user perimeter to present process/state list in UI
=> Use user perimeter to present process/state list in UI (#1908)

ui/main/src/app/modules/usercard/usercard.component.ts
#2005 : Recipients list not well positioned in conference user card
=> Recipients list not well positioned in conference user card (#2005)

src/docs/asciidoc/resources/migration_guide_to_3.0.adoc
Task : 
Adjust migration documentation for release 3.0.0 (#2045)
=> Adjust migration documentation for release 3.0 (#2045)

build.gradle, client/cards/build.gradle, client/client.gradle, gradle.properties, services/core/build.gradle, services/core/cards-publication/build.gradle, services/services.gradle, settings.gradle, src/test/api/karate/karateTests.gradle, src/test/clientApp/clientApp.gradle, src/test/externalApp/externalApp.gradle, tools/tools.gradle, web-ui/web-ui.gradle
=> Centralize repository declarations in Gradle builds

build.gradle, client/cards/src/main/avro/card.avsc, client/cards/src/main/avro/timespan.avsc, services/core/cards-publication/src/test/java/org/opfab/cards/publication/kafka/integration/SendKafkaCardShould.java, services/core/cards-publication/src/test/java/org/opfab/cards/publication/kafka/producer/KafkaAvroWithoutRegistrySerializerShould.java
Updated AVRO files to better reflect CardPublicationData. 
Fixed AVRO compiler warnings  (fixes Issue #1532)
Updated to avro plugin v 1.2.1
=> Updated AVRO files to better reflect CardPublicationData.

bin/load_variables.sh, src/docs/asciidoc/dev_env/env_variables.adoc
=> Removing unused env variables (#1905)

ui/main/src/app/modules/share/card-detail/card-detail.component.ts, ui/main/src/app/modules/usercard/usercard.component.html
#2002 : add vertical scroll bar for usercard preview
=> add vertical scroll bar for usercard preview (#2002)

ui/main/src/app/modules/usercard/usercard.component.ts
#2056 : Recipients list is partially visible when usercard screen is too small
=> Recipients list is partially visible when usercard screen is too small (#2056)

services/core/cards-publication/src/main/java/org/opfab/cards/publication/kafka/command/DeleteCardCommandHandler.java, services/core/cards-publication/src/main/java/org/opfab/cards/publication/services/CardProcessingService.java, services/core/cards-publication/src/main/java/org/opfab/cards/publication/services/clients/ExternalAppClient.java, services/core/cards-publication/src/main/java/org/opfab/cards/publication/services/clients/impl/ExternalAppClientImpl.java, services/core/cards-publication/src/test/java/org/opfab/cards/publication/kafka/command/DeleteCardCommandHandlerShould.java, services/core/cards-publication/src/test/java/org/opfab/cards/publication/services/CardProcessServiceShould.java, src/docs/asciidoc/reference_doc/user_cards.adoc, src/test/api/karate/cards/cards.feature, src/test/api/karate/cards/externalRecipentErrors.feature, src/test/externalApp/src/main/java/org/opfab/externalApp/controller/ExternalAppController.java, src/test/externalApp/src/main/java/org/opfab/externalApp/service/ExternalAppService.java, src/test/externalApp/src/main/java/org/opfab/externalApp/service/ExternalAppServiceImpl.java
Release Note, Feature section:
#1849 : notify external recipients when one of their cards is deleted
=> send notification to externalRecipient when deleting card (#1849)

ui/main/src/app/modules/admin/components/table/admin-table.directive.html, ui/main/src/app/modules/archives/archives.component.html, ui/main/src/app/modules/archives/archives.component.ts, ui/main/src/app/modules/cards/components/detail/detail.component.html, ui/main/src/app/modules/feed/components/card-list/filters/feed-filter/feed-filter.component.html, ui/main/src/app/modules/feed/components/card-list/filters/feed-filter/feed-filter.component.ts, ui/main/src/app/modules/feedconfiguration/feedconfiguration.component.html, ui/main/src/app/modules/logging/logging.component.html, ui/main/src/app/modules/logging/logging.component.ts, ui/main/src/app/modules/monitoring/components/monitoring-filters/monitoring-filters.component.html, ui/main/src/app/modules/monitoring/components/monitoring-filters/monitoring-filters.component.ts, ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.html, ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.ts, ui/main/src/app/modules/monitoring/monitoring.component.html, ui/main/src/app/modules/share/archives-logging-filters/archives-logging-filters.component.html, ui/main/src/app/modules/share/archives-logging-filters/archives-logging-filters.component.ts, ui/main/src/app/modules/usercard/usercard.component.html, ui/main/src/app/modules/usercard/usercard.component.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json
#1294 : Organize i18n assets (particularly filters)
=> Organize i18n assets (particularly filters) (#1294)

ui/main/src/app/modules/usercard/usercard.component.ts
Bugs : 
#2090 The LTTD value does not change when a User Card is modified
=> Correct bug  #2090 : The LTTD value does not change when a User Card is modified

config/docker/nginx-cors-permissive.conf, src/test/cypress/cypress/integration/UserCard.spec.js, ui/main/src/app/modules/cards/components/detail/detail.component.html, ui/main/src/app/modules/navbar/navbar.component.html, ui/main/src/app/modules/usercard/usercard.component.html, ui/main/src/app/modules/usercard/usercard.component.ts
Fix #1891
Release notes
#1891 : Add cypress test for usercard 
=> Add cypress test for usercard (#1891)

services/core/cards-consultation/src/main/java/org/opfab/cards/consultation/model/LightCardConsultationData.java, services/core/cards-publication/src/main/java/org/opfab/cards/publication/model/CardPublicationData.java, ui/main/src/app/model/line-of-monitoring-result.model.ts, ui/main/src/app/modules/monitoring/components/cell-renderers/responses-cell-renderer.component.html, ui/main/src/app/modules/monitoring/components/cell-renderers/responses-cell-renderer.component.scss, ui/main/src/app/modules/monitoring/components/cell-renderers/responses-cell-renderer.component.ts, ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.ts, ui/main/src/app/modules/monitoring/monitoring.component.ts, ui/main/src/app/modules/monitoring/monitoring.module.ts, ui/main/src/app/services/lightcards-store.service.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json, ui/main/src/scss/styles.scss
Fix #1906 
Release notes
#1906 : Add "Answers" column in the monitoring screen
=> Add Answers column in the monitoring screen (#1906)

services/core/businessconfig/build.gradle, services/services.gradle, src/docs/asciidoc/dev_env/gradle.adoc
Fixes #2110 
Nothing to mention in release notes I think.
=> Removing unused Gradle task (#2110)

src/test/cypress/package-lock.json, src/test/cypress/package.json
=> Applying workaround for Cypress using deprecated lib (#2124)

src/docs/asciidoc/reference_doc/response_cards.adoc, ui/main/src/app/services/user-permissions-.service.ts, ui/main/src/tests/helpers.ts
=> Correct failing UI tests (#2131)

ui/main/build.gradle, ui/ui.gradle
Fixes #2128 
Nothing in release notes ?
=> Fixing UI unit tests configuration (#2128)

services/core/cards-publication/src/test/java/org/opfab/cards/publication/kafka/integration/SendKafkaCardShould.java
Fix for a race condition in a Kafka integration test
=> Fixed listener race condition in Kafka test

ui/main/src/app/modules/cards/components/detail/detail.component.ts, ui/main/src/app/modules/monitoring/components/cell-renderers/responses-cell-renderer.component.ts
Bugs : 
- Monitoring & Feed - Answers not visible after card update (#2135)
=> Bug - Monitoring & Feed - Answers not visible after card update (#2135)

src/docs/asciidoc/reference_doc/card_notification.adoc
As discussed during pre-3.1.0.RELEASE testing.
=> Clarify notification configuration documentation

src/test/cypress/cypress/integration/ResponseCard.spec.js, ui/main/src/app/modules/cards/components/detail/detail.component.html
=> Add cypress non-regression test to avoid #2135 (#2149)

src/test/cypress/cypress/integration/StateTypeTests.spec.js, ui/main/src/app/modules/logging/logging.component.html, ui/main/src/app/modules/logging/logging.component.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json, ui/main/src/scss/styles.scss
In Release notes, Tasks section :
"#1990 : Add a spinner when loading logging cards"
=> Add a spinner when loading logging cards (#1991)

src/docs/asciidoc/dev_env/gradle.adoc
=> Fix gpg documentation

ui/main/src/app/modules/monitoring/components/cell-renderers/responses-cell-renderer.component.ts, ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.ts
#2136 : Monitoring screen : Answers filtering based on id instead of name
=> Monitoring screen : Answers filtering based on id instead of name (#2136)

src/test/cypress/cypress/integration/SoundNotification.spec.js, src/test/cypress/cypress/support/commands.js, src/test/resources/deleteAllSettings.sh, ui/main/src/app/modules/settings/components/settings/checkbox-setting/checkbox-setting.component.html, ui/main/src/app/modules/settings/components/settings/checkbox-setting/checkbox-setting.component.ts, ui/main/src/app/modules/settings/components/settings/settings.component.html, ui/main/src/app/services/sound-notification.service.ts
=> Add cypress tests for sound notifications (#2150)

src/test/cypress/cypress/integration/SoundNotification.spec.js
=> Adjust cypress test to avoid false positive

src/test/cypress/cypress/integration/Monitoring.spec.js, ui/main/src/app/modules/cards/components/detail/detail.component.html, ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.html, ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.ts, ui/main/src/app/modules/monitoring/monitoring.component.html
=> Add cypress tests on monitoring screen (#1889)

config/docker/ui-config/web-ui.json
=> Remove unused "feed.notify" parameter in web-ui.json (#2138)

ui/main/src/app/modules/archives/archives.component.scss, ui/main/src/app/modules/cards/components/card-details/card-details.component.scss, ui/main/src/app/modules/logging/logging.component.html, ui/main/src/scss/styles.scss
Nothing in release note as bug is not present in previous release
=> Loading spinner in feed and monitoring take too much place (#2189)

ui/main/src/app/modules/admin/components/editmodal/entities/edit-entity-modal.component.html, ui/main/src/app/modules/admin/components/editmodal/entities/edit-entity-modal.component.scss, ui/main/src/app/modules/admin/components/editmodal/groups/edit-group-modal.component.html, ui/main/src/app/modules/admin/components/editmodal/groups/edit-group-modal.component.scss, ui/main/src/app/modules/admin/components/editmodal/perimeters/edit-perimeter-modal.component.html, ui/main/src/app/modules/admin/components/editmodal/perimeters/edit-perimeter-modal.component.scss, ui/main/src/app/modules/admin/components/editmodal/users/edit-user-modal.component.html, ui/main/src/app/modules/admin/components/editmodal/users/edit-user-modal.component.scss
In release notes, bug section, :
#2145 : Put scrollbar of administration modals directly in modals
=> Put scrollbar of administration modals directly in modals (#2145)

ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.ts, ui/main/src/scss/styles.scss
Release note 
Bugs 
#2171 Monitoring : The sort by severity doesn't work anymore
=> Correct bug in monitoring : The sort by severity doesn't work anymore (#2171)

ui/main/src/scss/styles.scss
in release notes, bug section : 
#2144 : Admin screen : remove empty space  in array of users/groups/entities/perimeters
=> Remove empty space in ag-grids (#2144)

src/test/clientApp/src/main/java/org/opfab/client/cards/CardClient.java
=> Solve sonar issuer java:S2259 on cardClient

.github/workflows/main.yml, CICD/github/upload_doc.sh
=> Add docker and doc tasks in github CI

ui/main/src/app/common/utilities.ts, ui/main/src/app/modules/archives/archives.component.ts, ui/main/src/app/modules/logging/logging.component.ts, ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.ts
=> Translate severity column in export files (#2142)

ui/main/src/app/modules/usercard/usercard.component.html, ui/main/src/app/modules/usercard/usercard.component.ts
#2133 : In usercard sometimes lttd is after enddate
=> In usercard sometimes lttd is after enddate (#2133)

ui/main/src/app/modules/usercard/usercard.component.ts
Bugs : 
- #2240 Correct bug in usercard when using same stateId in different processes
=> Correct bug in usercard when using same stateId in different processes 

src/docs/asciidoc/deployment/configuration/configuration.adoc, src/docs/asciidoc/dev_env/project_structure.adoc, src/docs/asciidoc/reference_doc/external_devices_service.adoc, src/docs/asciidoc/reference_doc/index.adoc, src/test/dummyModbusDevice/README.adoc
As discussed on Slack, it's not up to date and no one uses it.
=> Removing obsolete and unused tree structure

src/test/resources/bundles/defaultProcess_V1/template/question.handlebars, src/test/resources/bundles/userCardExamples/template/incidentInProgress.handlebars, src/test/resources/bundles/userCardExamples2/template/question.handlebars, ui/main/src/app/modules/cards/components/detail/detail.component.ts, ui/main/src/app/services/lightcards/lightcards-store.service.ts
Fix #2104 
Release notes
In tasks section:
#2104 : UI: Deal with delete child card
=> UI: Deal with delete child card (#2104)

services/businessconfig/src/main/java/org/opfab/businessconfig/model/UserCardData.java, services/businessconfig/src/main/modeling/swagger.yaml, src/docs/asciidoc/reference_doc/user_cards.adoc, src/test/api/karate/businessconfig/getABusinessconfig.feature, src/test/api/karate/businessconfig/resources/bundle_api_test/config.json, src/test/api/karate/businessconfig/resources/bundle_api_test_v2/config.json, src/test/cypress/cypress/integration/UserCard.spec.js, src/test/resources/bundles/userCardExamples/config.json, src/test/resources/bundles/userCardExamples3/config.json, ui/main/src/app/model/processes.model.ts, ui/main/src/app/modules/usercard/usercard.component.html, ui/main/src/app/modules/usercard/usercard.component.ts
In release notes, features section :
#2209 : Offer the possiblity to hide the recipient list in usercard
=> Offer the possiblity to hide the recipient list in usercard (#2209)

src/test/externalApp/externalApp.gradle
=> Remove unused dependency h2

ui/main/src/app/modules/usercard/usercard.component.ts
Release note :
Bugs : 
#2226 Sending a message user card with start and end date in the future gives an error on lttd that should be after start date
=> Sending a message user card with start and end date in the future gives an error on lttd that should be after start date (#2266)

ui/main/src/app/app.component.html, ui/main/src/app/app.component.ts, ui/main/src/app/services/card.service.ts, ui/main/src/app/services/sound-notification.service.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json
Bugs : 
#2289 : Sound activation improvements . Using chromium based browser, when reloading  the application (via F5 for example) the sound is only activated if user interact with the application (due to autoplay policy ). This correction force the user to click on  the page to activate the sound if the case arise
=> Sound activation improvements

ui/main/src/app/modules/logging/logging.component.ts
#2277 : Logging export file : bad name of the file
=> Logging export file : bad name of the file (#2277)

ui/main/package-lock.json, ui/main/package.json, ui/main/src/karma.conf.js
=> Removing karma-istanbul-coverage (#2198)

services/cards-consultation/src/main/java/org/opfab/cards/consultation/repositories/CardCustomRepositoryImpl.java, services/cards-consultation/src/test/java/org/opfab/cards/consultation/controllers/CardOperationsControllerShould.java, services/cards-consultation/src/test/java/org/opfab/cards/consultation/repositories/CardRepositoryShould.java, services/cards-publication/src/main/java/org/opfab/cards/publication/model/CardPublicationData.java, src/test/cypress/cypress/integration/FeedTests.spec.js, src/test/resources/cards/cypress/feed/futureEvent.json, ui/main/src/app/services/lightcards/filter.service.spec.ts, ui/main/src/app/services/lightcards/filter.service.ts
Fix #2205
Release notes
#2205 : Use publish date to show card on the feed
=> Use publish date to show card on the feed (#2205)

ui/main/src/app/modules/admin/components/cell-renderers/entity-cell-renderer.component.ts, ui/main/src/app/modules/admin/components/cell-renderers/group-cell-renderer.component.ts, ui/main/src/app/modules/admin/components/table/admin-table.directive.ts, ui/main/src/app/modules/admin/components/table/entities-table.component.ts
#2269 : Admin screen : filtering on several columns doesn't work
=> Admin screen : filtering on several columns doesn't work (#2269)

ui/main/src/app/modules/feed/components/time-line/custom-timeline-chart/custom-timeline-chart.component.spec.ts, ui/main/src/app/modules/feed/components/time-line/custom-timeline-chart/custom-timeline-chart.component.ts, ui/main/src/app/modules/share/timeline-buttons/timeline-buttons.component.ts
Bugs  
Timeline automatic shifting does not work properly (#2309)
=> Timeline automatic shifting does not work properly (#2309)

ui/main/src/app/modules/admin/components/table/admin-table.directive.ts, ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.ts, ui/main/src/scss/styles.scss
For the reviewer : I've added a comment in the issue to indicate there is the same problem in monitoring screen. So please check monitoring screen too. Thank you.
#2235 : Admin screen : the popup for the filters is sometimes half hidden
=> Admin screen : the popup for the filters is sometimes half hidden (#2235)

src/docs/asciidoc/reference_doc/users_management.adoc
=> Impossible to save settings for technical reasons - Issue when the user account ID contains a special character (#2310)

ui/main/src/app/modules/cards/components/card-details/card-details.component.ts
Release notes
#2282 : Wrong behaviour trying to load a not existent card 
=> Wrong behaviour trying to load a not existent card (#2282)

ui/main/src/app/modules/monitoring/monitoring.component.ts, ui/main/src/app/services/lightcards/lightcards-feed-filter.service.ts
=> Avoid ExpressionChangedAfterItHasBeenCheckedError

src/test/cypress/cypress/integration/SessionEnded.spec.js, src/test/cypress/cypress/integration/SoundNotification.spec.js, src/test/cypress/cypress/support/commands.js, ui/main/src/app/app.component.html, ui/main/src/app/app.component.ts, ui/main/src/app/services/authentication/authentication.service.ts, ui/main/src/app/services/sound-notification.service.ts, ui/main/src/app/store/actions/authentication.actions.ts, ui/main/src/app/store/effects/authentication.effects.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json
Feature : 
#2237 : Add sound when user session end
=> Add sound when user session end (#2337)

ui/main/src/assets/i18n/fr.json
=> Remove s in french translation for notification configuration screen (#2348)

src/docs/asciidoc/deployment/configuration/configuration.adoc
Signed-off-by: Gerben D <geppyz@gmail.com>
The issue #1324 was asking for a SASL implementation. This is already possible, so i've added example configurations to the documentation instead.
=> Added Kafka example configurations to documentation (#1324)

src/docs/asciidoc/reference_doc/user_cards.adoc, src/test/resources/bundles/userCardExamples/template/usercard_incidentInProgress.handlebars, ui/main/src/app/modules/usercard/usercard.component.ts
In Release note, feature section : 
#2092 : Add entityAllowedToRespond and entitiesRequiredToRespond to card template
=> add entityAllowedToRespond and entitiesRequiredToRespond to card template (#2092)

config/docker/nginx.conf, src/docs/asciidoc/deployment/configuration/configuration.adoc
Task: 
#2370 Provide secure nginx conf when checkAuthenticationForCardSending is set to false
=> Provide secure nginx conf when checkAuthenticationForCardSending is set to false

src/docs/asciidoc/reference_doc/user_cards.adoc
=> Fix documentation problem

services/businessconfig/build.gradle, services/businessconfig/src/main/java/org/opfab/businessconfig/configuration/json/BusinessconfigModule.java, services/businessconfig/src/main/java/org/opfab/businessconfig/controllers/BusinessconfigController.java, services/businessconfig/src/main/java/org/opfab/businessconfig/model/EntitiesGroupsData.java, services/businessconfig/src/main/java/org/opfab/businessconfig/model/RealTimeScreenData.java, services/businessconfig/src/main/java/org/opfab/businessconfig/model/RealTimeScreensData.java, services/businessconfig/src/main/java/org/opfab/businessconfig/model/ScreenColumnData.java, services/businessconfig/src/main/java/org/opfab/businessconfig/services/ProcessesService.java, services/businessconfig/src/main/modeling/swagger.yaml, services/businessconfig/src/test/data/realtimescreens.json, services/businessconfig/src/test/java/org/opfab/businessconfig/controllers/GivenAdminUserBusinessconfigControllerShould.java, services/businessconfig/src/test/java/org/opfab/businessconfig/controllers/GivenNonAdminUserBusinessconfigControllerShould.java, src/test/api/karate/businessConfigTests.txt, src/test/api/karate/businessconfig/resources/realtimescreens1.json, src/test/api/karate/businessconfig/resources/realtimescreens2.json, src/test/api/karate/businessconfig/uploadAndGetRealTimeScreensFile.feature
I propose to add nothing in release notes for the moment and to update it after the second issue about this new feature (#2356). Same thing for the documentation.
=> Create a configuration file for realtime screen (#2355)

src/test/resources/bundles/loadBundle.sh, src/test/resources/cards/deleteCard.sh, src/test/resources/cards/sendCard.sh, src/test/resources/cardsForStressTests/send6xN_TestCards.sh, src/test/resources/cardsForStressTests/sendCard.sh, src/test/resources/loadTestConf.sh, src/test/resources/monitoringConfig/loadMonitoringConfig.sh, src/test/resources/perimeters/createPerimeter.sh, src/test/resources/perimeters/deletePerimeter.sh, src/test/resources/processGroups/loadProcessGroups.sh, src/test/resources/realTimeScreens/loadRealTimeScreens.sh, src/test/resources/realTimeScreens/realTimeScreens.json, src/test/resources/uiConfig/deleteCoreMenu.sh, src/test/resources/uiConfig/removePropertyInJson.sh, src/test/resources/uiConfig/setSecurityAuthFlow.sh, src/test/resources/uiConfig/updateCoreMenu.sh, src/test/resources/uiConfig/updatePropertyInJson.sh, src/test/resources/uiConfig/updatePropertyInJsonWithSnippet.sh, src/test/resources/uiConfig/updatePropertyInJsonWithString.sh
I propose to add something in release notes when the issue #2356 is done, under the same feature.
=> Add a script to load a RealTimeScreen config (#2387)

src/test/resources/bundles/userCardExamples3/template/usercard_task.handlebars, ui/main/src/scss/styles.scss
Add in release notes, bug section : 
#2238 : Add controls on tasks times when creating a user card
=> Add controls on tasks times when creating a user card

config/docker/ui-config/ui-menu.json, services/external-devices/src/main/java/org/opfab/externaldevices/controllers/ConfigurationsController.java, services/external-devices/src/main/java/org/opfab/externaldevices/services/ConfigService.java, services/external-devices/src/test/java/org/opfab/externaldevices/services/ConfigServiceShould.java, src/test/api/karate/externaldevices/createUserConfig.feature, src/test/api/karate/externaldevices/resources/userConfigurations/update_operator5.json, src/test/cypress/cypress/integration/ExternalDevicesConfiguration.spec.js, ui/main/src/app/app-routing.module.ts, ui/main/src/app/model/external-devices.model.ts, ui/main/src/app/modules/externaldevicesconfiguration/editModal/externaldevicesconfiguration-modal.component.html, ui/main/src/app/modules/externaldevicesconfiguration/editModal/externaldevicesconfiguration-modal.component.scss, ui/main/src/app/modules/externaldevicesconfiguration/editModal/externaldevicesconfiguration-modal.component.ts, ui/main/src/app/modules/externaldevicesconfiguration/externaldevicesconfiguration-routing.module.ts, ui/main/src/app/modules/externaldevicesconfiguration/externaldevicesconfiguration.component.html, ui/main/src/app/modules/externaldevicesconfiguration/externaldevicesconfiguration.component.scss, ui/main/src/app/modules/externaldevicesconfiguration/externaldevicesconfiguration.component.ts, ui/main/src/app/modules/externaldevicesconfiguration/externaldevicesconfiguration.module.ts, ui/main/src/app/modules/navbar/navbar.component.html, ui/main/src/app/modules/navbar/navbar.component.ts, ui/main/src/app/modules/share/single-filter/single-filter.component.ts, ui/main/src/app/services/external-devices.service.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json
Fix #2357 
Release notes:
#2357 : Add an admin screen to configure external devices for users
=> Add an admin screen to set external device to user (#2357)

src/docs/asciidoc/reference_doc/template_description.adoc, src/test/cypress/cypress/integration/CardDetail.spec.js, src/test/resources/bundles/cypress/template/kitchenSink.handlebars, ui/main/src/app/modules/cards/components/detail/detail.component.ts, ui/main/src/app/modules/share/card-detail/card-detail.component.ts, ui/main/src/assets/js/templateGateway.js
In feature 
#2360 Inform template when rendering is done (via method templateGateway.onTemplateRenderingComplete())
=> Inform template when rendering is done (#2360)

.github/workflows/main.yml
=> correct bug in github action build script

src/test/cypress/cypress/integration/UserCard.spec.js, src/test/resources/cards/cypress/userCard/processSendByExternal.json, ui/main/src/app/services/user-permissions.service.ts
Bugs : 
- If user is in entitiesAllowedToEdit but publisher is external ,editing card is not allowed
=> If user is in entitiesAllowedToEdit but publisher is external, editing a card shall be allowed (#2407)

services/users/src/main/java/org/opfab/users/model/EntityData.java, services/users/src/main/modeling/swagger.yaml, services/users/src/test/java/org/opfab/users/configuration/ObjectMapperShould.java, src/docs/asciidoc/deployment/users_groups_admin.adoc, src/docs/asciidoc/reference_doc/template_description.adoc, src/docs/asciidoc/reference_doc/users_management.adoc, src/test/api/karate/users/entities/createEntities.feature, src/test/cypress/cypress/integration/ExternalDevicesConfiguration.spec.js, src/test/cypress/cypress/support/commands.js, ui/main/package-lock.json, ui/main/package.json, ui/main/src/app/app.module.ts, ui/main/src/app/model/entity.model.ts, ui/main/src/app/modules/admin/admin.module.ts, ui/main/src/app/modules/admin/components/editmodal/entities/edit-entity-modal.component.html, ui/main/src/app/modules/admin/components/editmodal/entities/edit-entity-modal.component.scss, ui/main/src/app/modules/admin/components/editmodal/entities/edit-entity-modal.component.ts, ui/main/src/app/services/entities.service.spec.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json, ui/main/src/scss/_variables.scss, ui/main/src/scss/styles.scss, ui/main/src/tests/mocks/entities.service.mock.ts
Fix #2386 
Release notes:
#2386 : Add 'labels' field to Entity model to allow associate labels  to an entity
=> Add a field labels to entity (#2386)

config/docker/ui-config/ui-menu.json, services/cards-consultation/src/main/java/org/opfab/cards/consultation/configuration/webflux/WebSecurityConfiguration.java, services/cards-consultation/src/test/java/org/opfab/cards/consultation/routes/ConnectionRoutesShould.java, services/users/src/main/java/org/opfab/users/configuration/oauth2/WebSecurityConfiguration.java, services/users/src/test/java/org/opfab/users/controllers/GroupsControllerShould.java, services/users/src/test/java/org/opfab/users/controllers/UsersControllerShould.java, src/test/api/karate/users/getUsers.feature, src/test/api/karate/users/groups/getGroups.feature, src/test/cypress/cypress/integration/1-RealTimeUsers.spec.js, ui/main/src/app/app.component.ts, ui/main/src/app/modules/admin/services/sharing.service.ts, ui/main/src/app/modules/realtimeusers/realtimeusers.component.ts
To merge after the PR for issue #2356 please.
I propose to add #2417 to the list of issues (about real time screens) already mentioned in the release notes ?
=> New real time users screen : allow the feature to all users (#2417)

ui/main/src/app/app.component.ts, ui/main/src/app/services/card.service.ts, ui/main/src/app/store/effects/authentication.effects.spec.ts, ui/main/src/app/store/effects/authentication.effects.ts
in release note : 
Bugs : 
#2421 : Close subscription when token expired
=> Close subscription when token expired (#2421)

src/test/cypress/cypress/integration/UserCard.spec.js
=> Adjust usercard cypress test

services/businessconfig/src/main/java/org/opfab/businessconfig/controllers/BusinessconfigController.java, services/businessconfig/src/main/java/org/opfab/businessconfig/services/ProcessesService.java, services/businessconfig/src/main/modeling/swagger.yaml, services/businessconfig/src/test/java/org/opfab/businessconfig/services/ProcessesServiceShould.java, src/test/api/karate/businessConfigTests.txt, src/test/api/karate/businessconfig/getBusinessconfigHistory.feature
Fix #2401 
Release notes
#2401 : Add endpoint to list all versions of a business process
=> Add endpoint to list all versions of a business process (#2401)

src/test/cypress/cypress/integration/Monitoring.spec.js, ui/main/src/app/model/line-of-monitoring-result.model.ts, ui/main/src/app/modules/monitoring/components/cell-renderers/responses-cell-renderer.component.ts, ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.ts, ui/main/src/app/modules/monitoring/monitoring.component.ts
#2428 : Monitoring column answers : showing only EntitiesRequiredToRespond
=> Monitoring column answers : showing only EntitiesRequiredToRespond (#2428)

services/cards-publication/src/main/java/org/opfab/cards/publication/controllers/CustomExceptionHandler.java, services/cards-publication/src/main/java/org/opfab/cards/publication/services/CardProcessingService.java, src/test/api/karate/cards/postCardWithNoProcess.feature, src/test/api/karate/cards/postCardWithNoState.feature
#2423 : Add message in api response when error arise when posting card
=> Add message in api response when error arise when posting card (#2423)

tools/generic/test-utilities/src/main/java/org/opfab/test/EmptyListComparator.java, ui/main/src/app/services/reminder/reminderList.spec.ts
=> Correct some sonar warnings

src/docs/asciidoc/getting_started/index.adoc
Release notes
#2358 : Update getting started to release 3.4.0 
=> Update getting started to release 3.4.0 (#2358)

ui/main/src/app/app-routing.module.ts
=> Calendar menu not hidden in navbar (#2452)

ui/main/src/app/modules/externaldevicesconfiguration/externaldevicesconfiguration.component.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json
=> External devices configuration : little translation errors (#2457)

ui/main/src/app/modules/cards/components/card-details/card-details.component.ts
#2460 : Loading in progress not visible anymore when loading a card
=> Loading in progress not visible anymore when loading a card (#2460)

ui/main/src/app/store/effects/authentication.effects.spec.ts, ui/main/src/app/store/effects/authentication.effects.ts
Release note 
Bugs :
#2464 : Connection not closed when user logout on chrome
=> Solve bug : Connection not closed when user logout on chrome (#2464)

src/test/cypress/cypress.json, src/test/cypress/cypress/integration/Acknowledgment.spec.js, src/test/cypress/cypress/integration/ResponseCard.spec.js, src/test/cypress/cypress/integration/UserCard.spec.js, ui/main/src/app/store/effects/authentication.effects.spec.ts
=> Correct falky cypress tests on github CI

src/docs/asciidoc/CICD/release_process.adoc
=> Update release process documentation

src/docs/asciidoc/reference_doc/user_cards.adoc, src/test/cypress/cypress/integration/UserCard.spec.js, src/test/resources/bundles/userCardExamples2/template/usercard_question.handlebars, ui/main/angular.json, ui/main/src/app/modules/usercard/usercard.component.ts, ui/main/src/assets/js/usercardTemplateGateway.js
Fix #1386 
Release notes
#1386 : Permit to access edition mode (CREATE or EDITION) from user card template 
=> Permit to access edition mode (CREATE or EDITION) from user card template  (#1386)

ui/main/src/app/modules/share/datetime-filter/datetime-filter.component.html, ui/main/src/app/modules/share/datetime-filter/datetime-filter.component.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json
Fix #2427 
Release notes
#2427 : Add translation for date picker 
=> Add translation for date picker (#2427)

src/test/cypress/cypress/integration/ResponseCard.spec.js
=> Correct falky cypress test

ui/main/src/app/modules/admin/components/cell-renderers/state-rights-cell-renderer.component.ts
Fix #2462 
Release notes
#2462 :  Admin perimeter management is not working well when using a non-exising process in perimeter
=> Admin perimeter management is not working well when using a non-exising process in perimeter (#2462)

config/docker/ui-config/web-ui.json, services/users/src/main/java/org/opfab/users/model/UserSettingsData.java, services/users/src/main/modeling/swagger.yaml, services/users/src/test/java/org/opfab/users/model/UserSettingsDataShould.java, src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc, src/docs/asciidoc/resources/index.adoc, src/docs/asciidoc/resources/migration_guide_to_3.5.adoc, src/test/api/karate/users/patchUserSettings.feature, ui/main/src/app/model/datetime-ngb.model.ts, ui/main/src/app/model/line-of-monitoring-result.model.ts, ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.ts, ui/main/src/app/modules/settings/components/settings/settings.component.html, ui/main/src/app/modules/settings/components/settings/settings.component.ts, ui/main/src/app/modules/share/light-card/light-card.component.spec.ts, ui/main/src/app/modules/usercard/datesForm/usercard-dates-form.component.ts, ui/main/src/app/services/i18n.service.ts, ui/main/src/app/services/reminder/reminderUtils.spec.ts, ui/main/src/app/services/reminder/reminderUtils.ts, ui/main/src/app/services/time.service.spec.ts, ui/main/src/app/services/time.service.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json
Release  note : 
Features : 
- Remove timezone management feature (#2467)
=> Remove timezone management feature (#2467)

src/docs/asciidoc/reference_doc/user_cards.adoc, src/test/cypress/cypress/integration/UserCard.spec.js, src/test/resources/bundles/userCardExamples2/template/usercard_confirmation.handlebars, ui/main/src/app/modules/usercard/usercard.component.ts, ui/main/src/assets/js/usercardTemplateGateway.js
Fix #2485
Release notes
#2485 : Usercard : in edition mode, give the template access to the child card of the current user 
=> Usercard : in edition mode, give to the template the child card of the current user (#2485)

src/test/cypress/cypress/integration/Acknowledgment.spec.js
=> Improve acknowledgment cypress test for avoid falky tests

ui/main/src/app/modules/share/light-card/light-card.component.html
#2454 : Feed : mix between french and english in summary of light card
=> Feed : mix between french and english in summary of light card (#2454)

services/cards-consultation/src/main/java/org/opfab/cards/consultation/repositories/ArchivedCardCustomRepositoryImpl.java
Release note :
Tasks : 
- #2505 Mongo requests for archived cards optimization
=> Mongo requests for archived cards optimization

src/test/cypress/cypress/integration/UserCard.spec.js, src/test/resources/bundles/defaultProcess_V1/i18n.json, src/test/resources/bundles/defaultProcess_V1/template/usercard_message.handlebars
=> Message usercard template : correct confusion between title and summary and truncate message setted by user for not having summary field too long

src/docs/asciidoc/dev_env/requirements.adoc, src/docs/asciidoc/getting_started/index.adoc, src/docs/asciidoc/reference_doc/user_cards.adoc
=> Documentation corrections

src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc, src/test/cypress/cypress/integration/Archives.spec.js, src/test/cypress/cypress/integration/CardDetail.spec.js, ui/main/src/app/modules/archives/archives.component.html, ui/main/src/app/modules/archives/archives.component.scss, ui/main/src/app/modules/archives/archives.component.ts, ui/main/src/app/modules/logging/logging.component.html, ui/main/src/app/modules/logging/logging.component.scss, ui/main/src/app/modules/logging/logging.component.ts, ui/main/src/app/modules/share/archives-logging-filters/archives-logging-filters.component.html, ui/main/src/app/modules/share/archives-logging-filters/archives-logging-filters.component.scss, ui/main/src/app/modules/share/archives-logging-filters/archives-logging-filters.component.ts, ui/main/src/app/modules/share/archives-logging-filters/archives-logging-filters.module.ts, ui/main/src/app/modules/share/datetime-filter/datetime-filter.component.ts
Fix #2491
Release notes:
#2491 : Set default publishDate search period in Archives and Logging screens  
=> Set default publishDate search period in Archives and Logging screens  (#2491)

config/docker/ui-config/ui-menu.json, config/docker/ui-config/web-ui.json, ui/main/src/assets/i18n/nl.json
Signed-off-by: Gerben D <geppyz@gmail.com>
=> Added Dutch translation (#2535)

services/users/src/main/java/org/opfab/users/model/CurrentUserWithPerimetersData.java, src/test/api/karate/users/perimeters/getCurrentUserWithPerimeters.feature, src/test/cypress/cypress/integration/1-RealTimeUsers.spec.js, src/test/cypress/cypress/integration/ActivityArea.spec.js, src/test/cypress/cypress/integration/Archives.spec.js, src/test/resources/cards/defaultProcess/chartLine.json, ui/main/src/app/modules/activityarea/activityarea.component.ts
I propose to add #2480 to the list of issues related to the new feature "restricted entities"
=> Restricted list of user entities : add cypress and karate tests (#2480)

build.gradle, gradle.properties, src/test/resources/bundles/defaultProcess_V1/i18n.json, tools/generic/utilities/build.gradle, tools/generic/utilities/src/main/java/org/opfab/utilities/I18nTranslation.java
I think it solves also https://github.com/opfab/operatorfabric-core/issues/2509. Please check. Thank you.
#2472 : Card summary and card title showing Hex code instead of special characters
=> Card summary and card title showing Hex code instead of special characters (#2472)

ui/main/src/app/modules/cards/components/detail/detail.component.html
#2529 : Acknowledge button on new line with screen size 1680*1050
=> Acknowledge button on new line with screen size 1680*1050 (#2529)

ui/main/src/app/modules/activityarea/activityarea.component.ts, ui/main/src/app/modules/feedconfiguration/feedconfiguration.component.ts, ui/main/src/app/store/effects/user.effects.ts
I propose to add nothing in release notes because the new feature "restricted list of entities" is not delivered yet.
=> Restricted list of entities : bug on activity area screen (#2550)

src/test/cypress/cypress/integration/UserCard.spec.js, ui/main/src/app/modules/usercard/usercard.component.ts
Fix #2494 
Release notes:
#2494  : When editing a user card view childcard in preview
=> When editing a user card view childcard in preview (#2494)

src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc, ui/main/src/app/services/authentication/authentication.service.ts
#2558 : No sound on external device when session ended
=> No sound on external device when session ended (#2558)

.gitignore, services/cards-consultation/src/main/java/org/opfab/cards/consultation/configuration/webflux/RemoteLogRoutesConfig.java, services/users/src/main/java/org/opfab/users/model/UserSettingsData.java, services/users/src/main/modeling/swagger.yaml, src/docs/asciidoc/community/index.adoc, src/test/api/karate/users/patchUserSettings.feature, ui/main/src/app/app.component.ts, ui/main/src/app/modules/settings/components/settings/checkbox-setting/checkbox-setting.component.scss, ui/main/src/app/modules/settings/components/settings/settings.component.html, ui/main/src/app/modules/settings/components/settings/settings.component.ts, ui/main/src/app/services/card.service.ts, ui/main/src/app/services/logs/opfab-logger.service.ts, ui/main/src/app/services/logs/remote-logger.service.ts, ui/main/src/app/services/services.module.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json, ui/main/src/assets/i18n/nl.json, ui/main/src/environments/environment.prod.ts, ui/main/src/environments/environment.ts
Feature : 
- #2567 Add remote logging feature
=> Add remote logging feature (#2567)

ui/main/src/app/modules/businessconfigparty/iframedisplay.component.ts
Nothing in release note as bug was introduce on the current release
=> Solve bug -  Business menu: clicking on different menus always displays the first page loaded in iframe

ui/main/src/app/modules/usercard/usercard.component.ts
=> Usercard : initialization of field publisherForCreatingUsercard before its use

ui/main/src/assets/i18n/nl.json
Added Dutch translation for date picker
=> Added Dutch translation for date picker

src/docs/asciidoc/business_description.adoc, src/docs/asciidoc/community/workflow.adoc
Tasks : 
#2586 : Add information about minimum resolution to use OperatorFabric
=> Add information about minimum resolution to use OperatorFabric (#2586)

src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc
release notes 
Tasks : 
- #2587 Add remoteLoggingEnabled UI parameters in documentation
=> Missing settings.remoteLoggingEnabled parameter in ui doc (#2587)

src/test/cypress/cypress/integration/Timeline.spec.js
=> Correct falky cypress test on timeline

README.adoc
=> Documentation adjustment

src/test/cypress/cypress/integration/UserCard.spec.js, ui/main/src/app/modules/usercard/selectCardEmitterForm/usercard-select-card-emitter-form.component.html, ui/main/src/app/modules/usercard/selectCardEmitterForm/usercard-select-card-emitter-form.component.ts, ui/main/src/app/modules/usercard/usercard.component.html, ui/main/src/app/modules/usercard/usercard.component.ts, ui/main/src/app/modules/usercard/usercard.module.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json, ui/main/src/assets/i18n/nl.json
#2526 : Usercard : permit to choose the entity that publish
=> Usercard : permit to choose the entity that publish (#2526)

src/test/cypress/cypress/integration/UserCard.spec.js, src/test/resources/bundles/defaultProcess_V1/template/usercard_message.handlebars, src/test/resources/bundles/userCardExamples/template/usercard_conference.handlebars, src/test/resources/bundles/userCardExamples/template/usercard_incidentInProgress.handlebars, ui/main/src/app/modules/usercard/usercard.component.ts, ui/main/src/assets/js/usercardTemplateGateway.js
In release notes, feature section :
#2493 : Add the access to the current process and state in user card templates
=> add getState() and getProcess() in usercardTemplateGateway (#2493)

ui/main/src/app/modules/externaldevicesconfiguration/externaldevicesconfiguration.component.ts
#2596 : External devices screen : filter popup sometimes hidden
=> External devices screen : filter popup sometimes hidden (#2596)

ui/main/src/app/modules/calendar/calendar.component.ts, ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.ts
Fix #2583 
Release notes:
#2583  :  Feed : card indented whereas it should not 
=> Feed : card indented whereas it should not  (#2583)

ui/main/src/app/modules/settings/components/settings/settings.component.html, ui/main/src/app/modules/settings/components/settings/settings.component.ts, ui/main/src/app/modules/settings/components/settings/text-setting/text-setting.component.html, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json, ui/main/src/assets/i18n/nl.json
#2581 : In settings, control the value "Interval between sound replays"
=> In settings, control the value "Interval between sound replays" (#2581)

ui/main/src/app/app.component.ts, ui/main/src/app/modules/settings/components/settings/settings.component.ts, ui/main/src/app/services/card.service.ts
#2557 : Start even if translation file is not present for a declare language
=> Start even if translation file is not present for a declared language #2557

ui/main/src/app/modules/admin/components/editmodal/entities/edit-entity-modal.component.html, ui/main/src/app/modules/admin/components/editmodal/entities/edit-entity-modal.component.ts, ui/main/src/app/modules/admin/components/editmodal/groups/edit-group-modal.component.html, ui/main/src/app/modules/admin/components/editmodal/groups/edit-group-modal.component.ts, ui/main/src/app/modules/admin/components/editmodal/users/edit-user-modal.component.html, ui/main/src/app/modules/admin/components/editmodal/users/edit-user-modal.component.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json, ui/main/src/assets/i18n/nl.json
#2592 : Administration screen : create new user/entity/group with existing id is permitted whereas it should not
=> Administration screen : create new user/entity/group with existing id is permitted whereas it should not (#2592)

build.gradle
=> Solve sonar warning regarding exclusion configuration (#2575)

build.gradle
=> Solve sonar warning regarding exclusion configuration - update (#2575)

build.gradle, src/test/cypress/cypress/integration/ActivityArea.spec.js, src/test/cypress/cypress/integration/ResponseCard.spec.js, src/test/resources/cards/defaultProcess/question.json, ui/main/src/app/modules/cards/cards.module.ts, ui/main/src/app/modules/cards/components/detail/detail.component.html, ui/main/src/app/modules/cards/components/detail/detail.component.ts, ui/main/src/app/services/user-permissions.service.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json, ui/main/src/assets/i18n/nl.json
#2527 : Card response : permit the user to choose entity when responding to a card #2527
=> Card response : permit the user to choose entity when responding to a card (#2527)

.github/workflows/main.yml, CICD/github/build.sh, CICD/github/install.sh, CICD/github/launch_cypress_tests.sh, CICD/github/launch_karate_tests.sh
=> Avoid duplicate code in CI/CD

client/businessconfig/build.gradle, client/cards/build.gradle, client/client.gradle, client/external-devices/build.gradle, client/users/build.gradle, src/test/externalApp/src/main/java/org/opfab/externalapp/ExternalAppApplication.java, src/test/externalApp/src/main/java/org/opfab/externalapp/config/JacksonConfig.java
This reverts commit b64e7997f577a7587f1ba3a6e372691139b41a59.
=> Revert "Make JacksonConfig available to clients (#1317)"

src/test/cypress/cypress/integration/ExternalDevicesConfiguration.spec.js, src/test/cypress/cypress/integration/Monitoring.spec.js, src/test/cypress/cypress/plugins/index.js, src/test/cypress/cypress/plugins/read-xlsx.js, src/test/cypress/cypress/support/commands.js, src/test/cypress/package-lock.json, src/test/cypress/package.json, ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.ts
Fix #2609
Release notes
#2609 :  Add cypress test for export
=> Add cypress test for export (#2609)

CICD/github/launch_cypress_tests.sh, src/test/cypress/cypress.json
=> Adapt timeout for cypress launch via CI/CD

src/test/resources/deleteAllArchivedCards.sh, src/test/resources/deleteAllCards.sh, src/test/resources/deleteAllSettings.sh
=> Adapt scripts for old version of mongo (v 4.0)

src/docs/asciidoc/dev_env/ui.adoc
=> Rework UI dev documentation (#1352)

src/docs/asciidoc/reference_doc/user_cards.adoc, src/test/cypress/cypress/integration/UserCard.spec.js, src/test/resources/bundles/userCardExamples2/template/usercard_question.handlebars, ui/main/src/app/modules/usercard/datesForm/usercard-dates-form.component.ts, ui/main/src/app/modules/usercard/usercard.component.ts, ui/main/src/assets/js/usercardTemplateGateway.js
Fix #2495
Release notes
#2495 : Add method in userTemplateGateway to set/get startDate,endDate, lttd 
=> Add method in userTemplateGateway to set/get startDate,endDate, lttd (#2495)

src/test/cypress/cypress/integration/UserCard.spec.js, ui/main/src/app/modules/usercard/selectStateForm/usercard-select-state-form.component.html
#2673 : In usercard screen, show process select even if there is only one process
=> In usercard screen, show process select even if there is only one process (#2673)

src/test/cypress/cypress/integration/ActivityArea.spec.js, src/test/cypress/cypress/integration/Archives.spec.js, src/test/cypress/cypress/integration/FeedNotificationConfiguration.spec.js, src/test/cypress/cypress/integration/ResponseCard.spec.js, src/test/cypress/cypress/integration/SoundNotification.spec.js, src/test/cypress/cypress/integration/UserCard.spec.js, src/test/cypress/cypress/support/commands.js, ui/main/src/app/modules/archives/archives.component.html, ui/main/src/app/modules/navbar/navbar.component.html
=> Remove force click in cypress tests

src/test/cypress/cypress/integration/Archives.spec.js, src/test/cypress/cypress/integration/Logging.spec.js, src/test/cypress/cypress/integration/Monitoring.spec.js, ui/main/src/app/modules/logging/logging.component.html
#2659 : Adding cypress tests for export file in archives and logging screens
=> Adding cypress tests for export file in archives and logging screens (#2659)

src/test/cypress/cypress/integration/ActivityArea.spec.js
=> Adujst cypress test for CI/CD

services/cards-consultation/src/main/java/org/opfab/cards/consultation/repositories/ArchivedCardCustomRepositoryImpl.java, ui/main/src/app/modules/archives/archives.component.html, ui/main/src/app/modules/archives/archives.component.ts, ui/main/src/app/modules/logging/logging.component.html, ui/main/src/app/modules/logging/logging.component.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json, ui/main/src/assets/i18n/nl.json
Bugs : 
#2705 Add error message instead of spinner when error in logging/archives screen
=> Add error message instead of spinner when error in logging/archives screen (#2705)

services/cards-publication/src/main/java/org/opfab/cards/publication/controllers/CardController.java, services/cards-publication/src/main/java/org/opfab/cards/publication/model/CardPublicationData.java, services/cards-publication/src/main/java/org/opfab/cards/publication/services/CardProcessingService.java, services/cards-publication/src/main/java/org/opfab/cards/publication/services/CardRepositoryService.java, services/cards-publication/src/main/modeling/swagger.yaml, services/cards-publication/src/test/java/org/opfab/cards/publication/controllers/CardControllerProcessAcknowledgementShould.java, services/cards-publication/src/test/java/org/opfab/cards/publication/services/CardProcessServiceShould.java, src/test/api/karate/cards/cardsUserAcks.feature, src/test/api/karate/cards/userAcknowledgmentUpdateCheck.feature, ui/main/src/app/modules/cards/components/detail/detail.component.ts, ui/main/src/app/modules/feed/components/card-list/card-list.component.ts, ui/main/src/app/services/acknowledge.service.ts
#2670 : Add acknowledgement at the entity level. Now when a user acknowledges a card, he also acknowledges it for his(its) entity(ies).
=> Add acknowledgement at the entity level (#2670)

services/cards-consultation/src/main/java/org/opfab/cards/consultation/configuration/webflux/ArchivedCardRoutesConfig.java, services/cards-consultation/src/main/java/org/opfab/cards/consultation/model/ArchivedCardConsultationData.java, services/cards-consultation/src/main/java/org/opfab/cards/consultation/model/ArchivedCardData.java, services/cards-consultation/src/main/java/org/opfab/cards/consultation/repositories/ArchivedCard.java, services/cards-consultation/src/main/java/org/opfab/cards/consultation/repositories/ArchivedCardCustomRepository.java, services/cards-consultation/src/main/java/org/opfab/cards/consultation/repositories/ArchivedCardCustomRepositoryImpl.java, services/cards-consultation/src/test/java/org/opfab/cards/consultation/routes/ArchivedCardRoutesShould.java, services/cards-publication/src/main/java/org/opfab/cards/publication/model/ArchivedCardPublicationData.java, services/cards-publication/src/main/java/org/opfab/cards/publication/services/CardProcessingService.java, services/cards-publication/src/main/java/org/opfab/cards/publication/services/CardRepositoryService.java, services/cards-publication/src/test/java/org/opfab/cards/publication/services/CardProcessServiceShould.java, src/docs/asciidoc/resources/migration_guide_to_3.6.adoc, src/test/api/karate/cards/cardsWithRepresentative.feature, src/test/api/karate/cards/fetchArchivedCard.feature, src/test/api/karate/cards/post1CardThenUpdateThenDelete.feature, src/test/api/karate/cards/post2CardsGroupRouting.feature, src/test/api/karate/cards/postCardFor3Users.feature, src/test/api/karate/cards/postCardWithToNotify.feature, src/test/cypress/cypress/integration/ResponseCard.spec.js, ui/main/src/app/modules/archives/archives.component.html, ui/main/src/app/modules/archives/archives.component.ts, ui/main/src/app/services/card.service.ts
Fix #2560 
Release notes
#2560 : Add child cards in archive detail cards 
=> Add child cards in archive detail cards (#2560)

src/test/cypress/cypress/integration/1-RealTimeUsers.spec.js, src/test/cypress/cypress/integration/ResponseCard.spec.js, src/test/cypress/cypress/integration/UserCard.spec.js
=> Improve cypress test to avoid failing when launch locally

ui/main/src/app/services/logs/opfab-logger.service.ts
Release note 
In task 
#2715 : improve ui log library
=> Improve ui log library (#2715)

client/cards/src/main/java/org/opfab/cards/model/CardOperationTypeEnum.java, services/cards-consultation/src/main/java/org/opfab/cards/consultation/model/ArchivedCardConsultationData.java, services/cards-consultation/src/main/java/org/opfab/cards/consultation/model/CardConsultationData.java, services/cards-consultation/src/main/java/org/opfab/cards/consultation/services/CardSubscription.java, services/cards-consultation/src/main/java/org/opfab/cards/consultation/services/CardSubscriptionService.java, services/cards-consultation/src/main/java/org/opfab/cards/consultation/services/RabbitMQEntryPoint.java, services/cards-consultation/src/main/resources/amqp.xml, services/cards-consultation/src/test/java/org/opfab/cards/consultation/TestUtilities.java, services/cards-consultation/src/test/java/org/opfab/cards/consultation/controllers/CardOperationsControllerShould.java, services/cards-consultation/src/test/java/org/opfab/cards/consultation/repositories/CardRepositoryShould.java, services/cards-publication/src/main/java/org/opfab/cards/publication/model/ArchivedCardPublicationData.java, services/cards-publication/src/main/java/org/opfab/cards/publication/model/CardOperationData.java, services/cards-publication/src/main/java/org/opfab/cards/publication/services/CardNotificationService.java, services/cards-publication/src/main/java/org/opfab/cards/publication/services/CardProcessingService.java, services/cards-publication/src/main/modeling/swagger.yaml, services/cards-publication/src/main/resources/amqp.xml, services/cards-publication/src/test/java/org/opfab/cards/publication/services/CardProcessServiceShould.java, ui/main/src/app/model/card-operation.model.ts, ui/main/src/app/model/card.model.ts, ui/main/src/app/modules/cards/components/detail/detail.component.html, ui/main/src/app/modules/cards/components/detail/detail.component.ts, ui/main/src/app/services/card.service.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json, ui/main/src/assets/i18n/nl.json
In Features section, I propose to add #2671 at the existing issue #2670
=> Show entity acknowledgement for the card emitter (#2671)

src/test/cypress/cypress/integration/Admin.spec.js
Fix  #2620
Release notes
#2620 : Test admin user screen via cypress
=> Test admin user screen via cypress (#2620)

src/test/cypress/cypress/integration/Acknowledgment.spec.js, src/test/cypress/cypress/integration/UserCard.spec.js, src/test/cypress/cypress/support/commands.js, src/test/resources/bundles/cypress/template/kitchenSink.handlebars, src/test/resources/cards/cypress/entitiesAcks/message1.json, src/test/resources/cards/sendAckForCard.sh, ui/main/src/app/modules/cards/components/detail/detail.component.html
For release notes, I propose to add #2735 to the list of issues about entities acknowledgements (#2670 and #2671)
=> Entity acknowledgement : adding cypress tests (#2735)

ui/main/src/app/modules/cards/components/detail/detail.component.html, ui/main/src/app/modules/cards/components/detail/detail.component.ts
I propose to add nothing in release notes because the feature for entities acks is not yet delivered.
=> When ack config is "Never" do not show ack list in card view (#2741)

src/docs/asciidoc/deployment/index.adoc
=> Add in documentation the edge configuration to avoid sleeping tab 

web-ui/src/main/docker/Dockerfile, web-ui/src/main/docker/nginx-logrotate-conf, web-ui/web-ui.gradle
-  Text : #2756 Adjust log permission for nginx logs files
=> Adjust log permission for nginx logs files (#2756)

services/businessconfig/src/main/java/org/opfab/businessconfig/model/ProcessStatesData.java, services/businessconfig/src/main/modeling/swagger.yaml, src/docs/asciidoc/reference_doc/card_notification.adoc, src/test/api/karate/businessconfig/getABusinessconfig.feature, src/test/api/karate/businessconfig/resources/bundle_api_test_v2/config.json, src/test/cypress/cypress/integration/Acknowledgment.spec.js, src/test/resources/bundles/cypress/config.json, src/test/resources/bundles/defaultProcess_V1/config.json, ui/main/src/app/model/processes.model.ts, ui/main/src/app/modules/cards/components/detail/detail.component.ts, ui/main/src/app/modules/feed/components/pinned-cards/pinned-cards.component.html, ui/main/src/app/modules/feed/components/pinned-cards/pinned-cards.component.scss, ui/main/src/app/modules/feed/components/pinned-cards/pinned-cards.component.ts, ui/main/src/app/modules/feed/components/time-line/init-chart/init-chart.component.html, ui/main/src/app/modules/feed/components/time-line/init-chart/init-chart.component.scss, ui/main/src/app/modules/feed/feed.module.ts
Fix #2692
Release notes
#2692 : Add the possiblity to automatically pin card 
=> Add the possiblity to automatically pin card (#2692)

src/test/cypress/cypress/integration/ActivityArea.spec.js, src/test/cypress/cypress/integration/Archives.spec.js, src/test/cypress/cypress/integration/Logging.spec.js, src/test/resources/bundles/defaultProcess_V1/config.json, src/test/resources/bundles/defaultProcess_V1/i18n.json, src/test/resources/bundles/defaultProcess_V1/template/chart.handlebars, src/test/resources/cards/defaultProcess/chart.json, src/test/resources/cardsForStressTests/defaultProcess/chart.json, src/test/resources/perimeters/defaultProcess.json
-  Text : #2760 New chart example
=> New chart example (#2760)

services/external-devices/src/main/java/org/opfab/externaldevices/services/DevicesService.java
=> External devices adaptation (#2728)

.github/workflows/main.yml, CICD/github/launch_cypress_tests.sh, src/docs/asciidoc/dev_env/cypress.adoc, src/test/cypress/cypressTests.gradle
=> Permit to launch a subset of cypress tests on CI

services/cards-consultation/src/test/java/org/opfab/cards/consultation/routes/ArchivedCardRoutesShould.java, services/cards-consultation/src/test/java/org/opfab/cards/consultation/routes/CardRoutesShould.java, services/cards-consultation/src/test/java/org/opfab/cards/consultation/routes/ConnectionRoutesShould.java, services/cards-publication/src/test/java/org/opfab/cards/publication/kafka/integration/SendKafkaCardShould.java, services/users/src/main/java/org/opfab/users/utils/EntityCycleDetector.java, services/users/src/test/java/org/opfab/users/controllers/EntityCycleDetectorShould.java
=> Solver sonar issues : Remove this 'public' modifier.

ui/main/src/tests/helpers.ts
=> Solve sonar issue: default values should be last

tools/spring/spring-oauth2-utilities/src/test/java/org/opfab/springtools/configuration/oauth/I18nProcessesCacheShould.java, tools/spring/spring-oauth2-utilities/src/test/java/org/opfab/springtools/configuration/oauth/UserServiceCacheShould.java
=> Solve sonar issue : Consecutive AssertJ "assertThat" statements should be chained

ui/main/src/scss/styles.scss
=> Solve sonar issue : duplicate css

ui/main/src/app/app-routing.module.ts, ui/main/src/tests/helpers.ts
=> Correct sonar warning regarding deprecated substr method

ui/main/src/app/modules/cards/services/handlebars.service.spec.ts, ui/main/src/app/modules/cards/services/handlebars.service.ts
=> Remove old handlebars helper not used

config/dev/cards-publication-dev.yml, config/docker/cards-publication-docker.yml, config/docker/ui-config/web-ui.json, services/cards-publication/src/main/java/org/opfab/cards/publication/services/processors/impl/UserCardProcessorImpl.java, services/cards-publication/src/test/resources/application.yml, src/docs/asciidoc/deployment/configuration/configuration.adoc, src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc, src/docs/asciidoc/reference_doc/response_cards.adoc, ui/main/src/app/services/user-permissions.service.ts
=> Remove checkPerimeterForResponseCard parameter (#2752)

src/docs/asciidoc/reference_doc/template_description.adoc, ui/main/src/app/modules/cards/services/handlebars.service.spec.ts, ui/main/src/app/modules/cards/services/handlebars.service.ts
Add the possibility to have the index of the key in the result
-  Text : #2789 Adapt keyValue handlebars helper (Add the possibility to have the index of the key in the result)
=> Adapt keyValue handlebars helper (#2789)

ui/main/src/app/modules/share/light-card/light-card.component.spec.ts, ui/main/src/app/services/time.service.spec.ts
=> UI tests about date format fail on 31st of every month (#2793)

ui/main/src/app/modules/feed/components/time-line/directives/mouse-wheel.directive.ts
=> Solve sonar issue : 'event' is deprecated

src/test/cypress/cypress/integration/BusinessMenu.spec.js
Fix #2618 
-  Text : #2618 : Add cypress test for business menu
=> Add cypress test for business menu (#2618)

config/dev/cards-consultation-dev.yml, config/docker/cards-consultation-docker.yml, services/cards-consultation/src/main/java/org/opfab/cards/consultation/configuration/webflux/ConnectionRoutesConfig.java, services/cards-consultation/src/main/java/org/opfab/cards/consultation/configuration/webflux/WillNewSubscriptionDisconnectAnExistingSubscription.java, services/cards-consultation/src/main/java/org/opfab/cards/consultation/services/CardSubscriptionService.java, services/cards-consultation/src/test/java/org/opfab/cards/consultation/routes/ConnectionRoutesShould.java, src/docs/asciidoc/deployment/configuration/configuration.adoc, src/docs/asciidoc/reference_doc/users_management.adoc, ui/main/src/app/app.component.html, ui/main/src/app/app.component.scss, ui/main/src/app/app.component.ts, ui/main/src/app/services/card.service.ts, ui/main/src/app/services/user.service.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json, ui/main/src/assets/i18n/nl.json
-  Text : #2668  Do not allow the same user to be connected twice at the same time
=> Disable a user to have several sessions at the same time

ui/main/src/app/modules/usercard/selectStateForm/usercard-select-state-form.component.ts
=> Order by alphabetical order process and services in usercard screen (#2767)

ui/main/src/app/modules/cards/components/detail/detail.component.html, ui/main/src/app/modules/usercard/selectCardEmitterForm/usercard-select-card-emitter-form.component.html
Nothing in release note as these bugs where not present on previous release
=> Correct style for entity emitter choices (#2809 & #2810)

ui/main/src/app/app.component.html, ui/main/src/app/app.component.ts
Nothing in release note as feature was not present on previous release
=> Bug when user already connected in implicit/code auth mode (#2818)

src/docs/asciidoc/resources/migration_guide_to_3.6.adoc
=> Add in migration documentation the removal of opfab version in web-ui.json

CICD/prepare_release_version.sh
=> update prepare_release_version.sh to set opfabVersion in package.json

services/cards-consultation/src/main/java/org/opfab/cards/consultation/configuration/webflux/RemoteLogRoutesConfig.java, ui/main/src/app/services/logs/remote-logger.service.ts
-  Text : #2816 Exception in remoteLog back service when too much log
=> Correct bug: Exception in remoteLog back service when too much log  #2816

src/test/api/karate/admin/getPrometheusMonitoring.feature, src/test/api/karate/admin/loggersApi.feature, src/test/api/karate/karate-config.js, src/test/api/karate/users/ipControl.feature
=> Duplicate variable for same data in karate-config.js (#2837)

ui/main/src/assets/i18n/fr.json
=> Admin screen : typo error in french version (#2803)

services/cards-publication/src/main/java/org/opfab/cards/publication/model/ArchivedCardPublicationData.java, services/users/src/main/java/org/opfab/users/model/UserSettingsData.java, tools/generic/utilities/src/main/java/org/opfab/utilities/ObjectUtils.java, tools/generic/utilities/src/test/java/org/opfab/utilities/ObjectUtilsShould.java
=> Refactoring patch methods (#2143)

src/docs/asciidoc/resources/migration_guide_to_3.6.adoc
=> Correct error in migration doc

ui/main/src/app/modules/share/light-card/light-card.component.ts, ui/main/src/app/modules/usercard/usercard.component.html
=> User card: in card preview lightcard should not be clickable (#2805)

src/test/cypress/cypress/integration/Acknowledgment.spec.js
=> Correct cypress test to avoid falky test in CI

src/test/cypress/cypress/integration/Monitoring.spec.js
=> Adjust cypress monitoring test to avoid CI falky test

services/cards-publication/src/main/java/org/opfab/cards/publication/services/clients/impl/ExternalAppClientImpl.java
=> Avoid to import lib org.apache.commons.lang3 in opfab just to define an empty string

src/docs/asciidoc/getting_started/troubleshooting.adoc
=> Correct error in documentation regarding template syntax #2823

src/docs/asciidoc/reference_doc/template_description.adoc
=> Add more documentation for template mechanism

ui/main/src/app/modules/feed/components/pinned-cards/pinned-cards.component.scss
=> Change the mouse cursor when going over the pin card (#2858)

src/test/cypress/cypress/integration/Acknowledgment.spec.js
=> Improve cypress test for pin cards to avoid falky test

src/test/cypress/cypress/integration/BusinessMenu.spec.js
=> Avoid falky test in cypress business menu tests

ui/main/src/app/modules/admin/components/editmodal/entities/edit-entity-modal.component.html, ui/main/src/app/modules/admin/components/table/entities-table.component.ts, ui/main/src/app/modules/settings/components/settings/settings.component.scss, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json, ui/main/src/assets/i18n/nl.json
=> Settings screen/Admin screens : Description for fields not in uppercase (#2811)

ui/main/src/scss/styles.scss
=> Correct bug: Too much margin in popup (#2865)

ui/main/package-lock.json, ui/main/package.json, ui/main/src/app/modules/cards/services/handlebars.service.spec.ts
=> Update dependency karma-jasmine to v5.0.0

ui/main/src/app/modules/feed/components/time-line/custom-timeline-chart/custom-timeline-chart.component.ts
=> Correct bug : Exception when clicking on timeline and card not present in feed (#2850)

ui/main/src/app/modules/admin/components/table/admin-table.directive.ts, ui/main/src/app/modules/externaldevicesconfiguration/externaldevicesconfiguration.component.ts, ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.ts
=> Solve aggrid deprecated feature (#2855)

services/cards-publication/src/main/java/org/opfab/cards/publication/services/CardProcessingService.java, services/cards-publication/src/test/java/org/opfab/cards/publication/services/CardProcessServiceShould.java
Fix #2813
-  Text : #2813 :Usercard edition : deal with the possibility to modify the emitter entity
=> Usercard edition : deal with the possibility to modify the emitter entity (#2813)

ui/main/src/app/app.component.ts, ui/main/src/app/modules/feed/components/time-line/init-chart/init-chart.component.spec.ts, ui/main/src/app/modules/share/timeline-buttons/timeline-buttons.component.ts, ui/main/src/app/store/effects/custom-router.effects.ts, ui/main/src/tests/mocks/remote-logger.service.mock.ts
=> Add more remote logs (#2890)

src/docs/asciidoc/reference_doc/template_description.adoc
=> Add some examples for opfab css styles in documentation (#2892)

ui/main/src/app/modules/cards/components/detail/detail.component.ts
Fix #2815
-  Text : #2815 : Modify answer button should appear in real time
=> Modify answer button should appear in real time (#2815)

ui/main/src/app/app.component.html, ui/main/src/app/app.component.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json, ui/main/src/assets/i18n/nl.json
-  Text : #2807  Add the user name to the userAlreadyConnected pop up
=> Add the user name to the userAlreadyConnected pop up (#2807)

ui/main/src/app/modules/feed/components/card-list/filters/feed-filter/feed-filter.component.scss, ui/main/src/scss/styles.scss
-  Text : #2821 : Fix text and background colors in time pickers
=> Fix text and background colors in time pickers (#2821)

src/test/resources/cards/sendCard.sh
Signed-off-by: Gerben D <geppyz@gmail.com>
-  Text : #2921 Fix issue with sendCard.sh script in MacOS
=> FE-2921 Fix bug in sendCard.sh

src/docs/asciidoc/reference_doc/user_cards.adoc, src/docs/asciidoc/resources/migration_guide_to_3.7.adoc, src/test/cypress/cypress/integration/UserCard.spec.js, src/test/resources/bundles/taskExample/template/usercard_task.handlebars, ui/main/src/app/modules/usercard/usercard.component.ts
Fix #2786 
-  Text : #2786 : User cards: add the possibility to set timespans from the template
=> User cards: add the possibility to set timespans (#2786)

ui/main/src/app/app.component.ts
-  Text : #2916 : Stop active repetitive sound alarm when user is disconnected by new user
=> Stop active repetitive sound alarm when user is disconnected by new user (#2916)

src/test/cypress/cypress/integration/Acknowledgment.spec.js, ui/main/src/app/modules/cards/components/detail/detail.component.ts, ui/main/src/app/services/entities.service.spec.ts, ui/main/src/app/services/entities.service.ts
Fix #2848
-  Text : #2848 : Deal with groups of entities in acknowledged footer
=> Deal with groups of entities in acknowledged footer (#2848)

ui/main/src/app/app.component.ts, ui/main/src/app/services/sound-notification.service.ts
-  Text : #2899 Disable sound activation pop up if sounds are played on an external device
=> Disable sound activation pop up if sounds are played on an external device (#2899)

ui/main/src/app/modules/externaldevicesconfiguration/externaldevicesconfiguration.component.html, ui/main/src/app/modules/externaldevicesconfiguration/externaldevicesconfiguration.component.ts, ui/main/src/assets/i18n/en.json
-  Text : #2866 : External devices configuration page : show error message when the service is not available
=> External devices configuration page : show error message when the service is not available (#2866)

config/dev/cards-publication-dev.yml, config/dev/docker-compose.yml, config/docker/cards-publication-docker.yml, config/docker/docker-compose.yml, config/docker/external-app-docker.yml, services/cards-publication/src/main/java/org/opfab/cards/publication/configuration/ExternalRecipients.java, services/cards-publication/src/main/java/org/opfab/cards/publication/controllers/CardController.java, services/cards-publication/src/main/java/org/opfab/cards/publication/services/CardProcessingService.java, services/cards-publication/src/main/java/org/opfab/cards/publication/services/clients/ExternalAppClient.java, services/cards-publication/src/main/java/org/opfab/cards/publication/services/clients/impl/ExternalAppClientImpl.java, services/cards-publication/src/test/java/org/opfab/cards/publication/application/UnitTestApplication.java, services/cards-publication/src/test/java/org/opfab/cards/publication/kafka/integration/SendKafkaCardShould.java, services/cards-publication/src/test/java/org/opfab/cards/publication/services/CardProcessServiceShould.java, services/cards-publication/src/test/java/org/opfab/cards/publication/services/clients/impl/ExternalAppClientImplShould.java, services/cards-publication/src/test/resources/application-kafka.yml, services/cards-publication/src/test/resources/application.yml, src/docs/asciidoc/deployment/configuration/configuration.adoc, src/docs/asciidoc/dev_env/kafka.adoc, src/docs/asciidoc/reference_doc/response_cards.adoc, src/docs/asciidoc/resources/migration_guide_to_3.7.adoc, src/test/api/karate/cards/cards.feature, src/test/externalApp/externalApp.gradle, src/test/externalApp/src/main/docker/Dockerfile, src/test/externalApp/src/main/java/org/opfab/externalapp/config/WebSecurityConfiguration.java, src/test/externalApp/src/main/resources/application-dev.yml, src/test/externalApp/src/main/resources/application.yml
=> Propagate user token to external recipient (#2905)

src/test/cypress/cypress/integration/Calendar.spec.js, ui/main/src/app/modules/calendar/calendar.component.ts, ui/main/src/app/modules/navbar/navbar.component.html
=> Add cypress tests for calendar feature (#2917)

src/test/cypress/cypress/integration/1-RealTimeUsers.spec.js, src/test/cypress/cypress/integration/AboutPopUpTests.spec.js, src/test/cypress/cypress/integration/Acknowledgment.spec.js, src/test/cypress/cypress/integration/ActivityArea.spec.js, src/test/cypress/cypress/integration/Admin.spec.js, src/test/cypress/cypress/integration/BusinessMenu.spec.js, src/test/cypress/cypress/integration/CoreMenuConfigurationTests.spec.js, src/test/cypress/cypress/integration/ExternalDevicesConfiguration.spec.js, src/test/cypress/cypress/integration/FeedNotificationConfiguration.spec.js, src/test/cypress/cypress/integration/ResponseCard.spec.js, src/test/cypress/cypress/integration/Timeline.spec.js, src/test/cypress/cypress/integration/Translation.spec.js, src/test/cypress/cypress/integration/UserCard.spec.js, src/test/cypress/cypress/support/commands.js, ui/main/src/app/modules/feed/components/card-list/filters/feed-filter/feed-filter.component.html, ui/main/src/app/modules/monitoring/components/monitoring-filters/monitoring-filters.component.html, ui/main/src/app/modules/monitoring/monitoring.component.html, ui/main/src/app/modules/navbar/navbar.component.html, ui/main/src/app/modules/share/archives-logging-filters/archives-logging-filters.component.html, ui/main/src/app/modules/share/timeline-buttons/timeline-buttons.component.html, ui/main/src/assets/i18n/en.json
-  Text : #2775 Add cypress tests for translations
=> Add cypress tests for translations (#2775)

src/test/cypress/cypress/integration/Translation.spec.js
- In release note : nothing to add in release notes
=> Update translation cypress tests (#2775)

config/dev/external-devices-dev.yml, config/docker/external-devices-docker.yml, services/external-devices/src/main/java/org/opfab/externaldevices/controllers/NotificationsController.java, services/external-devices/src/main/java/org/opfab/externaldevices/model/UserConfigurationData.java, services/external-devices/src/main/java/org/opfab/externaldevices/repositories/UserConfigurationRepository.java, services/external-devices/src/main/java/org/opfab/externaldevices/services/ConfigService.java, services/external-devices/src/main/java/org/opfab/externaldevices/services/DevicesService.java, services/external-devices/src/main/modeling/swagger.yaml, services/external-devices/src/test/java/org/opfab/externaldevices/configuration/json/ObjectMapperShould.java, services/external-devices/src/test/java/org/opfab/externaldevices/services/ConfigServiceShould.java, services/external-devices/src/test/java/org/opfab/externaldevices/services/DevicesServiceShould.java, src/docs/asciidoc/reference_doc/external_devices_service.adoc, src/docs/asciidoc/resources/migration_guide_to_3.7.adoc, src/test/api/karate/externaldevices/fetchUserConfig.feature, src/test/api/karate/externaldevices/resources/userConfigurations/broken_config.json, src/test/api/karate/externaldevices/resources/userConfigurations/operator5.json, src/test/api/karate/externaldevices/resources/userConfigurations/update_operator5.json, src/test/cypress/cypress/integration/ExternalDevicesConfiguration.spec.js, ui/main/src/app/model/external-devices.model.ts, ui/main/src/app/modules/externaldevicesconfiguration/editModal/externaldevicesconfiguration-modal.component.html, ui/main/src/app/modules/externaldevicesconfiguration/editModal/externaldevicesconfiguration-modal.component.scss, ui/main/src/app/modules/externaldevicesconfiguration/editModal/externaldevicesconfiguration-modal.component.ts, ui/main/src/app/modules/externaldevicesconfiguration/externaldevicesconfiguration.component.ts, ui/main/src/app/modules/externaldevicesconfiguration/externaldevicesconfiguration.module.ts, ui/main/src/app/modules/settings/components/settings/settings.component.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json, ui/main/src/assets/i18n/nl.json
-  Text : #2918 : Enable to have several sound devices connected at the same time for each user
=> Enable to have several sound devices connected at the same time for each user (#2918)

config/dev/users-dev.yml, config/docker/users-docker.yml, services/users/src/main/java/org/opfab/users/model/GroupData.java, services/users/src/main/modeling/swagger.yaml, src/test/api/karate/users/groups/createGroups.feature, src/test/api/karate/users/groups/getGroupDetails.feature, src/test/api/karate/users/groups/getGroups.feature, src/test/cypress/cypress/integration/ActivityArea.spec.js, ui/main/src/app/model/group.model.ts, ui/main/src/app/modules/activityarea/activityarea.component.html, ui/main/src/app/modules/activityarea/activityarea.component.scss, ui/main/src/app/modules/activityarea/activityarea.component.ts, ui/main/src/app/services/entities.service.ts, ui/main/src/app/services/groups.service.ts
Sonar tells there are 4 code smells but if I'm not wrong, this is not on new parts of code.
-  Text : #2849 : Add already connected users in activity area screen
=> Add already connected users in activity area screen (#2849)

ui/main/src/app/modules/cards/components/card-details/card-details.component.ts, ui/main/src/app/store/selectors/card.selectors.ts
-  Text : #2820 : Feed screen : No spinner when it takes time to load a card
=> Feed screen : No spinner when it takes time to load a card (#2820)

config/dev/users-dev.yml, config/docker/users-docker.yml
=> update of users config file for realtime parameter (#2849)

services/cards-consultation/src/main/java/org/opfab/cards/consultation/configuration/webflux/RemoteLogRoutesConfig.java
=> Remote log - only first lines of logs are written

src/docs/asciidoc/resources/index.adoc
- In release note : nothing to write
=> Add migration guide to 3.7.0

src/test/cypress/cypress/integration/1-RealTimeUsers.spec.js, src/test/cypress/cypress/integration/Acknowledgment.spec.js, src/test/cypress/cypress/integration/ActivityArea.spec.js, src/test/cypress/cypress/integration/ResponseCard.spec.js, src/test/cypress/cypress/integration/UserCard.spec.js
=> Correct falky cypress tests

ui/main/src/app/modules/externaldevicesconfiguration/externaldevicesconfiguration.component.ts
-  Text : #3008 :  External devices configuration screen : user login column not well aligned
=> External devices configuration screen : user login column not well aligned

ui/main/src/app/modules/login/login.component.html
-  Text : #3006 :  Log in screen : "Sign in" button not well centered
=> Log in screen : "Sign in" button not well centered (#3006)

ui/main/src/app/modules/feed/components/pinned-cards/pinned-cards.component.html
Fix #2844 
-  Text : #2844 : Pinned cards: add pinned icon
=> Pinned cards: add pinned icon (#2844)

.prettierrc.json, src/docs/asciidoc/community/index.adoc
-  Text : Add prettier configuration
=> Add prettier configuration

src/test/cypress/cypress/integration/GroupCards.spec.js, src/test/resources/cards/cypress/group/message1.json, src/test/resources/cards/cypress/group/message2.json, src/test/resources/cards/cypress/group/message3.json
Added cypress tests for the grouped card feature
=> Added cypress tests for grouped card feature

ui/main/src/app/modules/share/archives-logging-filters/archives-logging-filters.component.ts
2 code smells but not on new code.
-  Text : #3013 :  Bug in archives and logging screens when searching by state
=> Bug in archives and logging screens when searching by state (#3013)

.prettierrc.json, src/test/cypress/cypress/integration/Calendar.spec.js, src/test/cypress/cypress/integration/SoundNotification.spec.js, src/test/resources/cards/cypress/calendar/chart_customDates.json
-  Text : #2983 : Calendar cypress tests sometimes fail depending on the current date/time
=> Calendar cypress tests sometimes fail depending on the current date/time (#2983)

services/users/src/main/java/org/opfab/users/controllers/EntitiesController.java, services/users/src/main/java/org/opfab/users/controllers/GroupsController.java, services/users/src/main/java/org/opfab/users/controllers/UsersController.java
In Release note :
Bugs : 
Changing activity area does not always propagate to cards-consultation service (#3052)
=> Changing activity area does not always propagate to cards-consultation service (#3052)

services/users/src/main/java/org/opfab/users/model/GroupData.java, src/test/api/karate/users/groups/createGroups.feature, src/test/api/karate/users/groups/getGroupDetails.feature, ui/main/src/app/modules/admin/components/editmodal/groups/edit-group-modal.component.html, ui/main/src/app/modules/admin/components/editmodal/groups/edit-group-modal.component.ts, ui/main/src/app/modules/admin/components/table/admin-table.directive.ts, ui/main/src/app/modules/admin/components/table/entities-table.component.ts, ui/main/src/app/modules/admin/components/table/groups-table.component.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json, ui/main/src/assets/i18n/nl.json
2 code smells but not on new code.
-  Text : #3009 : Admin screen : deal with the realtime parameter for groups
=> Admin screen : deal with the realtime parameter for groups (#3009)

.github/workflows/main.yml, CICD/github/launch_cypress_tests.sh
=> Add back logs in github CI when cypress test fails

src/docs/asciidoc/reference_doc/user_cards.adoc
=> Add a warning in documentation regarding usercard templates

config/docker/ui-config/web-ui.json, src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc, src/test/cypress/cypress/integration/ActivityArea.spec.js, ui/main/src/app/app.component.html, ui/main/src/app/app.component.ts, ui/main/src/app/app.module.ts, ui/main/src/app/modules/activityarea/activityarea.component.html, ui/main/src/app/modules/activityarea/activityarea.component.ts, ui/main/src/app/modules/activityarea/activityarea.module.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json, ui/main/src/assets/i18n/nl.json
Fix #2861
-  Text : #2861: Choose your entities on login
=> Choose your entities on login (#2861)

ui/main/src/app/modules/feed/components/time-line/init-chart/init-chart.component.scss, ui/main/src/app/modules/navbar/navbar.component.scss, ui/main/src/app/modules/share/light-card/light-card.component.scss, ui/main/src/app/modules/share/timeline-buttons/timeline-buttons.component.html, ui/main/src/app/modules/share/timeline-buttons/timeline-buttons.component.scss
-  Text : #2997 : Mouse cursor is not the good one in different places
=> Mouse cursor is not the good one in different places (#2997)

src/test/cypress/cypress/integration/UserCard.spec.js, src/test/resources/bundles/messageOrQuestionExample/template/usercard_message.handlebars, ui/main/src/app/modules/usercard/recipientForm/usercard-recipients-form.component.ts, ui/main/src/app/modules/usercard/usercard.component.ts
Fix #2986
-  Text : #2986 : Usercard : add a method to set initial selected recipient list
=> Usercard : add a method to set initial selected recipient list (#2986)

ui/main/src/app/modules/feed/components/time-line/init-chart/init-chart.component.html
-  Text : #3029 : set 'Hide timeline' text in French on one single line
=> set 'Hide timeline' text in French on one single line (#3029)

src/docs/asciidoc/reference_doc/user_cards.adoc
=> Add documentation for usercardTemplateGateway.setInitialSelectedRecipients (#3069)

services/businessconfig/src/main/java/org/opfab/businessconfig/model/ProcessStatesData.java, services/businessconfig/src/main/modeling/swagger.yaml, src/docs/asciidoc/reference_doc/card_notification.adoc, src/test/api/karate/businessconfig/getABusinessconfig.feature, src/test/api/karate/businessconfig/resources/bundle_api_test_v2/config.json, src/test/cypress/cypress/integration/Acknowledgment.spec.js, src/test/cypress/package-lock.json, src/test/resources/bundles/cypress/config.json, src/test/resources/bundles/defaultProcess_V1/config.json, ui/main/src/app/model/processes.model.ts, ui/main/src/app/modules/cards/components/detail/detail.component.ts
Fix #3025
-  Text : #3025 : Add an option to hide unacknowledge button
=> Add an option to hide unacknowledge button (#3025)

ui/main/src/app/modules/cards/components/card-details/card-details.component.ts
Fix #2993
-  Text : #2993 : Fix bug when getting not existing card with slow network
=> Fix bug when getting not existing card with slow network (#2993)

ui/main/src/app/modules/archives/archives.component.html, ui/main/src/app/modules/archives/archives.component.scss, ui/main/src/app/modules/archives/archives.component.ts, ui/main/src/app/modules/logging/logging.component.html, ui/main/src/app/modules/logging/logging.component.ts, ui/main/src/app/modules/monitoring/components/monitoring-table/monitoring-table.component.html, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json, ui/main/src/assets/i18n/nl.json
Fix #3010
-  Text : #3010 : Archives and Logging: spinners or loading messages missing
=> Archives and Logging: spinners or loading messages missing (#3010)

services/cards-consultation/src/main/java/org/opfab/cards/consultation/services/CardSubscription.java, src/test/cypress/cypress/integration/ActivityArea.spec.js, src/test/cypress/cypress/support/commands.js, ui/main/src/app/app.component.html, ui/main/src/app/app.component.scss, ui/main/src/app/app.component.ts, ui/main/src/app/services/url-checker.service.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json, ui/main/src/assets/i18n/nl.json
-  Text : #2804 : Prevent to have several tabs connected at the same time in the same browser
=> Prevent to have several tabs connected at the same time in the same browser (#2804)

src/test/cypress/cypress/integration/FeedTests.spec.js, src/test/cypress/cypress/integration/Translation.spec.js, ui/main/src/app/modules/cards/components/card-details/card-details.component.html, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json, ui/main/src/assets/i18n/nl.json
-  Text : #3005 :  Add text when trying to open a card that is not found in the feed
=> Add text when the card is not found (#3005)

ui/main/.eslintrc.json, ui/main/src/app/common/utilities.ts, ui/main/src/app/modules/archives/archives.component.html, ui/main/src/app/modules/archives/archives.component.ts
-  Text : #2999 : Archives screen : no spinner when we are in mode "collapsible updates"
=> Archives screen : no spinner when we are in mode "collapsible updates" (#2999)

src/test/cypress/cypress/integration/Admin.spec.js, ui/main/src/app/modules/admin/admin.component.html, ui/main/src/app/modules/admin/components/editmodal/perimeters/edit-perimeter-modal.component.html, ui/main/src/app/modules/admin/components/editmodal/perimeters/edit-perimeter-modal.component.ts
=> Add cypress tests for perimeter administration (#2936)

ui/main/package-lock.json, ui/main/package.json
=> Remove codelyser (originally used by tslint)

ui/main/src/app/app.component.html, ui/main/src/app/app.component.ts, ui/main/src/app/app.module.ts, ui/main/src/app/modules/core/reload-required/reload-required.component.html, ui/main/src/app/modules/core/reload-required/reload-required.component.scss, ui/main/src/app/modules/core/reload-required/reload-required.component.ts, ui/main/src/app/services/card.service.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json, ui/main/src/assets/i18n/nl.json
Fix #3104 
-  In chapter :  Task
-  Text : #3104 :  When reload is requested, ask the user to reload via an alert
=> When reload is requested, ask the user to reload via an alert (#3104)

services/cards-consultation/src/main/java/org/opfab/cards/consultation/configuration/webflux/CardSubscriptionRoutesConfig.java, services/cards-consultation/src/main/java/org/opfab/cards/consultation/controllers/CardOperationsController.java, services/cards-consultation/src/main/java/org/opfab/cards/consultation/services/CardSubscriptionService.java, services/cards-consultation/src/test/java/org/opfab/cards/consultation/routes/ConnectionRoutesShould.java, ui/main/src/app/services/card.service.ts
-  Text : #3106 : Account already used message when reloading page
=> Account already used message when reloading page (#3106)

src/docs/asciidoc/reference_doc/template_description.adoc, src/test/cypress/cypress/integration/UserCard.spec.js, src/test/resources/bundles/conferenceAndITIncidentExample/template/usercard_incidentInProgress.handlebars, src/test/resources/bundles/defaultProcess_V1/template/usercard_process.handlebars, ui/main/src/app/modules/core/application-loading/application-loading.component.ts, ui/main/src/assets/js/opfab.js
Fix #3126 Fix #3143
-  Text : #3126 : Add possibility to use multiselect as simple select
-  Text : #3143 Missing translations for opfab.multiSelect on startup
=> Add possibility to use multiselect as simple select (#3126)

src/test/resources/uiConfig/setSecurityAuthFlow.sh
-  Text : #3101 : Remove environment choice in setSecurityAuthFlow.sh
=> Remove environment choice in setSecurityAuthFlow.sh (#3101)

services/cards-consultation/src/main/java/org/opfab/cards/consultation/model/CardConsultationData.java, services/cards-consultation/src/main/java/org/opfab/cards/consultation/repositories/CardCustomRepositoryImpl.java, services/cards-publication/src/main/java/org/opfab/cards/publication/model/CardPublicationData.java, services/cards-publication/src/main/java/org/opfab/cards/publication/services/CardRepositoryService.java, services/cards-publication/src/test/java/org/opfab/cards/publication/services/CardProcessServiceShould.java
Fix #3083
-  Text : #3083 : Avoid loosing acknowlegments when connection lost
=> Avoid loosing acknowlegments when connection lost (#3083)

src/test/cypress/cypress/integration/CheckIfOpfabUrlIsAlreadyTaken.spec.js, src/test/cypress/cypress/support/commands.js, ui/main/src/app/modules/core/application-loading/app-loaded-in-another-tab/app-loaded-in-another-tab.component.html, ui/main/src/app/modules/core/application-loading/application-loading.component.html
=> Add cypress tests for OpFab started in another tab (#3103)

ui/main/src/app/modules/archives/archives.component.ts
-  Text : #3155 : Archives screen : spinner endlessly if no result and "collapsible updates" checked
=> Archives screen : spinner endlessly if no result and "collapsible updates" checked (#3155)

src/test/api/karate/cards/getCardSubscription.feature
Fix #3151
-  Text : #3151 : Add karate test for card acknowledgment recovery when connection lost
=> Add karate test for card acknowledgment recovery when connection lost (#3151)

services/cards-consultation/src/main/java/org/opfab/cards/consultation/controllers/CardOperationsController.java, ui/main/src/app/services/card.service.ts
Nothing in release note as if was not present in previous release
=> Correct bug with susbcription not well closed (#3174)

ui/main/src/app/modules/usercard/usercard.component.ts
Nothing in release note  as bug was not in previous release
=> Correct bug : EndDate or Lttd empty in usercard input (#3182)

ui/main/src/app/modules/share/archives-logging-filters/archives-logging-filters.component.html
-  Text : #3184 : Archives/logging screens : multi-filters not well aligned
=> Archives/logging screens : multi-filters not well aligned (#3184)

ui/main/src/app/modules/cards/components/detail/detail.component.ts
-  Text : #3181 : Acknowledgments footer : sort entities alphabetically
=> Acknowledgments footer : sort entities alphabetically (#3181)

ui/main/src/app/modules/archives/archives.component.ts, ui/main/src/app/modules/logging/logging.component.ts, ui/main/src/app/modules/share/archives-logging-filters/archives-logging-filters.component.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json, ui/main/src/assets/i18n/nl.json
-  Text : #1330 :  Do not show search result when there is an invalid date in archives/logging screens
=> Do not show search result when there is an invalid date in archives/logging screens (#1330)

ui/main/src/app/modules/admin/components/table/admin-table.directive.ts
Fix #3171
-  Text : #3171 : Entities management screen : filter on parent entities is not working
=> Entities management screen : filter on parent entities is not working (#3171)

src/docs/asciidoc/community/index.adoc
=> Add new ts code guidelines

ui/main/src/app/modules/share/archives-logging-filters/archives-logging-filters.component.ts
- In release note : Nothing to add
=> Refactor archives-logging-filter

src/test/cypress/cypress/integration/UserCard.spec.js, src/test/cypress/cypress/support/commands.js, ui/main/src/app/model/multiselect.model.ts, ui/main/src/app/modules/share/multi-select/multi-select.component.ts, ui/main/src/app/modules/usercard/selectStateForm/usercard-select-state-form.component.html, ui/main/src/app/modules/usercard/selectStateForm/usercard-select-state-form.component.ts, ui/main/src/assets/js/opfab.js
-  Text : #3146  : Usercard : Replace single filter component
=> Usercard : Replace single filter component (#3146)

src/test/cypress/cypress/integration/Monitoring.spec.js, src/test/cypress/cypress/plugins/read-xlsx.js, src/test/cypress/cypress/support/commands.js, src/test/resources/monitoringConfig/monitoringConfig.json
Fix #3166
-  Text : #3166  : Add cypress test for monitoring export with custom configuration
=> Add cypress test for monitoring export with custom configuration (#3166)

src/test/cypress/cypress/integration/Translation.spec.js, ui/main/src/assets/i18n/fr.json
=> Feed filters : set "Réinitialiser" instead of "Reinitialiser" (#3170)

ui/main/src/app/modules/share/light-card/light-card.component.html
=> Do not open grouped cards in the geomap popup (#3200)

ui/main/src/app/modules/archives/archives.component.html, ui/main/src/app/modules/archives/archives.component.ts, ui/main/src/app/modules/logging/logging.component.html, ui/main/src/app/modules/logging/logging.component.ts, ui/main/src/app/modules/share/archives-logging-filters/archives-logging-filters.component.html, ui/main/src/app/modules/share/archives-logging-filters/archives-logging-filters.component.ts
fix #3173 
-  In chapter : Bugs 
-  Text : #3173 : Archives and logging: datepicker forbidden dates are not disabled
=> Archives and logging: datepicker forbidden dates are not disabled (#3173)

ui/main/src/app/app.module.ts, ui/main/src/app/common/utilities.ts, ui/main/src/app/modules/core/application-loading/sound-activation/sound-activation.component.ts
In release note :  
Authorize PWA conditionally and only for chrome based browsers
=> Authorize PWA only for chrome based browsers to solve #3248

src/test/cypress/cypress/integration/UserCard.spec.js
=> Clean usercard cypress test

src/test/cypress/cypress/integration/UIReload.spec.js, src/test/cypress/cypress/support/commands.js, src/test/resources/sendMessageToSubscriptions.sh
Fix #3235
-  Text : #3235 : Add a cypress test for reload request feature (
=> Add a cypress test for reload request feature (#3235)

src/test/cypress/cypress/integration/1-RealTimeUsers.spec.js, src/test/cypress/cypress/integration/ActivityArea.spec.js, src/test/cypress/cypress/integration/Archives.spec.js, src/test/cypress/cypress/integration/Logging.spec.js, src/test/cypress/cypress/support/commands.js, ui/main/src/app/app.module.ts, ui/main/src/app/modules/activityarea/activityarea.component.html, ui/main/src/app/modules/activityarea/activityarea.component.ts, ui/main/src/app/modules/activityarea/activityarea.module.ts, ui/main/src/app/modules/archives/archives.component.html, ui/main/src/app/modules/archives/archives.component.ts, ui/main/src/app/modules/archives/archives.module.ts, ui/main/src/app/modules/logging/logging.component.html, ui/main/src/app/modules/logging/logging.component.ts, ui/main/src/app/modules/logging/logging.module.ts, ui/main/src/app/modules/realtimeusers/realtimeusers.component.html, ui/main/src/app/modules/realtimeusers/realtimeusers.component.ts, ui/main/src/app/modules/realtimeusers/realtimeusers.module.ts, ui/main/src/app/modules/share/spinner/spinner.component.html, ui/main/src/app/modules/share/spinner/spinner.component.scss, ui/main/src/app/modules/share/spinner/spinner.component.ts, ui/main/src/app/modules/share/spinner/spinner.module.ts, ui/main/src/assets/i18n/en.json, ui/main/src/assets/i18n/fr.json, ui/main/src/assets/i18n/nl.json
-  Text : #3163 : Creation of a spinner component and spinners added in real time users screen and in activity area screen
=> Creation of a spinner component (#3163)

src/test/cypress/cypress/integration/Monitoring.spec.js
=> Avoid falky test on monitoring export

config/dev/users-dev.yml, config/docker/users-docker.yml, src/test/cypress/cypress/integration/CardDetail.spec.js, src/test/resources/bundles/cypress/template/kitchenSink.handlebars, ui/main/src/app/services/entities.service.ts
Fix #3240 
-  Text : #3240 : TemplateGateway.getEntity should return entity labels
=> TemplateGateway.getEntity should return entity labels (#3240)

src/test/cypress/cypress/integration/UserCard.spec.js, ui/main/src/app/modules/share/card-detail/card-detail.component.html, ui/main/src/app/modules/share/card-detail/card-detail.component.ts, ui/main/src/app/modules/share/card-detail/card-detail.module.ts, ui/main/src/app/modules/usercard/usercard.component.html, ui/main/src/app/modules/usercard/usercard.component.ts, ui/main/src/app/modules/usercard/usercard.module.ts
-  Text : #3167 Add spinner in user card creation screen
=> Add spinners in user card creation screen (#3167)

config/docker/ui-config/web-ui.json, src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc, ui/main/src/app/modules/core/application-loading/application-loading.component.ts
-  Text : #3238 : Add the possibility to enable/disable the possibility to have the same OpFab url used several times at the same time (#3238)
=> Add the possibility to enable/disable the check if the url is already locked (#3238)
